### ISSUE TITLE
unable to import ngc file

### ISSUE THREAD

**Issue by princyparsana** [ncbi/sra-tools#103]
Hi, 

I am trying to decrypt data downloaded from dbgap. I am using the latest binary CentOS version of sra toolkit. When I import the project key (file.ngc), it fails to give the dialogue that confirms successful import. And hence, eventually it fails to decrypt the files. I get the following error:
`2017-12-04T17:03:34 vdb-decrypt.2.8.2 err: path not found while opening directory within file system module - unable to obtain a password
2017-12-04T17:03:34 vdb-decrypt.2.8.2: exiting: RC(rcFS,rcDirectory,rcOpening,rcPath,rcNotFound) (834996504)`

Can someone please help with how can I address this?

**Comment by klymenko** [comment]
> it fails to give the dialogue that confirms successful import

Could you give more details?

Are you able to run "vdb-config -i" and [start the dialog to import ngc file](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use#s-3)?

**Comment by princyparsana** [comment]
yes I am. However, after I select the ngc file; it does not give the dialogue for successful import.

When I try to import the file using command line by `vdb-config --import ~/***/***.ngc`; it gives the following error:
`2017-12-04T17:27:06 vdb-config.2.8.2 int: file wrong type while reading file within configuration module - cannot import ngc file: ***/***.ngc`

Thanks

**Comment by klymenko** [comment]
The message states that the file you are trying to import is not a valid ngc file.

**Comment by princyparsana** [comment]
Yep, I got that. However, this is the same file that I use to decrypt files using sra toolkit v 2.4 on another cluster. However, I installed the latest version on a different cluster and the same file gives an error. Would you suggest downloading a fresh copy of the ngc file?

Also, I am curious what is the difference between vdb-passwd (file where I saved the key in v2.4) and .ngc file?

Thank you

**Comment by klymenko** [comment]
Yes, download dbGaP repository key (ngc file) from dbGaP Authorized Access page.

vdb-passwd is obsolete and does not work anymore.

To access dbgap data you should import ngc file by running "vdb-config".

Instructions how to access Protected Data are on https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use

**Comment by princyparsana** [comment]
re-downloading the repo key (ngc file) solved the issue. Thanks!
