### ISSUE TITLE
make install installs non-executable files in bin

### ISSUE THREAD

**Issue by sjackman** [ncbi/sra-tools#106]
Non-executable files ought not be installed in `bin`. They should instead by installed in `/usr/local/share/sra-tools`, or perhaps not installed at all.
```
/usr/local/bin/magic
/usr/local/bin/ncbi/certs.kfg
/usr/local/bin/ncbi/default.kfg
/usr/local/bin/ncbi/vdb-copy.kfg
```

**Comment by kwrodarmer** [comment]
Yes, this is thanks to the wonders of Windows, sorry. We have to store some configuration files nearby the executables so that they can be located by Windows code. Most of our users do not have admin rights and are using configuration that is auto-located.

It appears this is your first encounter with the SRA Toolkit, which is older than brew, and we have our legacy.

**Comment by sjackman** [comment]
> It appears this is your first encounter with the SRA Toolkit, which is older than brew, and we have our legacy.

I've been using SRA and the SRA Toolkit since it was first released. I'm trying to create a formula for SRA Toolkit Homebrew/core for the benefit of myself and your users.

> Yes, this is thanks to the wonders of Windows, sorry. We have to store some configuration files nearby the executables so that they can be located by Windows code. Most of our users do not have admin rights and are using configuration that is auto-located.

On macOS and Linux, could these config files be installed somewhere else, such as `$prefix/share/sra-tools`? What purpose do they serve, or could they be deleted?

**Comment by klymenko** [comment]
On Unix they are installed to /etc/ncbi
These are system-wide configuration files.
If they are not installed, there are big chances that the toolkit will not work properly, e.g., will not be able to resolve accessions or find NCBI storage.

**Comment by sjackman** [comment]
`sratoolkit fastq-dump` works for me without these configuration files on a Linux system without these config files. Is it expected to work?

> On Unix they are installed to /etc/ncbi

On macOS and Linux where I don't have root access, I'm seeing them installed in `bin/ncbi`. I'd like to install these files to either `$prefix/etc/ncbi` how do I specify the installation location of the config files to `./configure`? With `autoconf` the option is `./configure --sysconfdir=…`.

**Comment by klymenko** [comment]
> fastq-dump works for me without these configuration files
sratoolkit is looking for configuration files in several locations, starting from /etc/ncbi, next place - ncbi directory next to the binary.
If no configuration was found, it uses embedded configuration.
From experience, some old or incorrect configuration is found, e.g., old system install to /etc/ncbi or something else. Then it is picked up and embedded configuration is not used and usually toolkit fails.

Whan you installing toolkit - install configuration files to /etc/ncbi. If you cannot update /etc/ncbi - they should be copied to ncbi directory next to the binaries.

**Comment by sjackman** [comment]
May I make a request then of installing to and searching `../etc/ncbi/` relative to the binaries (that is `$prefix/etc/ncbi`) in addition to `/etc/ncbi/` and `$prefix/bin/ncbi/`?

> If no configuration was found, it uses embedded configuration.

Good to know. Thanks.

**Comment by kwrodarmer** [comment]
For those who are repackaging the SRA Toolkit with their distros, and you would qualify, you should take steps to install configuration files into /etc/ncbi and then we can drop the ncbi directory under bin. If you're installing into traditional places, that's the way to go, I think.

**Comment by kwrodarmer** [comment]
That said, we can consider other options. The idea of `$prefix/etc/ncbi` is reasonable, I think.

**Comment by sjackman** [comment]
The primary use case of Linuxbrew is on institutional HPC systems where users do not have administrative access, so they're not able to write to `/etc`. Thanks for considering my request of installing the config files to `$prefix/etc/ncbi`.

**Comment by ilovezfs** [comment]
If it doesn't respect sysconfdir then the etc files will not persist across upgrades since they'll be stuck in a particular Cellar location instead of HOMEBREW_PREFIX/etc.

**Comment by sjackman** [comment]
I don't think these config files are used very often. (@kwrodarmer @klymenko Correct me if I'm wrong.)  I've always deleted these files, so that it uses the default embedded configuration is used instead.

> If no configuration was found, it uses embedded configuration.

**Comment by kwrodarmer** [comment]
The embedded configuration is a last ditch effort to avoid failure, and should never be relied upon. It is bare bones, i.e. incomplete. The tools read configuration every time they run. Whether or not they end up needing particular configuration entries depends upon the circumstances. Consider them quite important.

**Comment by sjackman** [comment]
Good to know. Thanks @kwrodarmer. In that case, it would very helpful for `./configure` to respect `--sysconfdir`.
See https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
and https://www.gnu.org/software/automake/manual/html_node/Data.html

**Comment by sjackman** [comment]
Can you confirm that it's not typical for users to edit this file? That is to say, it's more a static data file than it is a user-editable configuration file.

**Comment by kwrodarmer** [comment]
We are looking at this and I'm creating an internal ticket right now. I'm not sure if we'll jump all the way to embedding awful full paths into the binary which tends to make them non-portable, or if we'll start with a relative search for an "etc" directory at the same level as the "bin" directory, but we'll make some change for this release.

**Comment by kwrodarmer** [comment]
It is discouraged for users to edit these files, as they have their own configuration in their home directories that can override it. Our tools only support editing of the user's file.

That said, it is expected that site admins *will* edit these files as needed.

**Comment by sjackman** [comment]
These sound more like data files than config files to me, in which case the original unmodified files ought to be installed in `pkgdatadir` (`$prefix/share/sra-tools/`) rather than `sysconfdir`. `sra-tools` can still search the home directory and `sysconfdir` (`/etc/ncbi`) for modified versions of these files.

**Comment by sjackman** [comment]
> I'm not sure if we'll jump all the way to embedding awful full paths into the binary which tends to make them non-portable, or if we'll start with a relative search for an "etc" directory at the same level as the "bin" directory,

I also dislike searching absolute paths for this same reason. I'd suggest discovering `bindir` as the location of the executable, and then finding the data dir relatively from there, `$bindir/../share/sra-tools`.

**Comment by stineaj** [comment]
Closing this issue. Updates were made for this specific user question for releases since 2017. The toolkit has switched to CMake in version 3.0.0
