### ISSUE TITLE
vdb-config

### ISSUE THREAD

**Issue by linsalrob** [ncbi/sra-tools#109]
If I uncheck "Enable Remote Access (1)" _and_ "Enable Local File Caching (2)" then fastq-dump still downloads a fastq file that I do not have locally. 

Presumably, the option to Enable Remote Access is just ignored?

How do I ensure fastq-dump is actually using the locally cached version versus retrieving the file remotely?

**Comment by klymenko** [comment]
Send the output of "vdb-config -on" to sra-tools@ncbi.nlm.nih.gov

**Comment by kwrodarmer** [comment]
How do you know that you don't have the file locally? Sorry if that sounds like a silly question, but your report implies that our behavior is broken and I cannot reproduce the error.

Even with everything turned off, it will still access anything that is in cache, i.e. turning off caching does not disable the files that exist in cache.

**Comment by linsalrob** [comment]
Yes, you are correct. In a clean install, it has the expected behavior: 

item not found while constructing within virtual database module - the path 'SRA_ID' cannot be opened as database or table

(where SRA_ID is my ID). 

Apologies, there must be another issue I must track down.
