### ISSUE TITLE
impossible to build against existing ncbi-vdb

### ISSUE THREAD

**Issue by rekado** [ncbi/sra-tools#11]
`setup/package.prl` declares a dependency on at least one file in the `ilib` directory of `ncbi-vdb`.  When `ncbi-vdb` is built and installed, the `ilib` directory is not installed, so building sra-tools against an existing installation of `ncbi-vdb` is not possible.

(I'm attempting to package sra-tools and its dependencies for GNU Guix.)

**Comment by rekado** [comment]
@kwrodarmer Has this been fixed or is there another approach to building with an existing ncbi-vdb package?

**Comment by kwrodarmer** [comment]
No - it has not been fixed. The issue was closed inadvertently.

**Comment by klymenko** [comment]
To be built, sra-tools package requires source files and build files of ncbi-vdb.
