### ISSUE TITLE
sam-dump.2.8.2 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )

### ISSUE THREAD

**Issue by huangziyan11111** [ncbi/sra-tools#110]
use sam-dump to transform sra file to sam:
sam-dump.2.8.2 SRR5358553.sra >SRR5358553.sam while it failed with note: sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )
I don't know how to solve it, please help me. Thank you.

**Comment by kwrodarmer** [comment]
How did you download SRR5358553.sra? If you had used the `prefetch` tool, it would download all dependencies as well, and you would not have to go out over the network.

The error you are having comes from the lower levels of networking, and says that it could not establish a secure handshake. There are many many reasons why this might be so. Please write to sra-tools@ncbi.nlm.nih.gov and explain the situation. If possible, run the command

`test-sra SRR5358553.sra > test-sra.out 2>&1`

and send the output to the email address (_do not post it here_).
