### ISSUE TITLE
re-opened: "Strange Perl error #80"

### ISSUE THREAD

**Issue by brobr** [ncbi/sra-tools#111]
Hi,

I would like to readdress [https://github.com/ncbi/sra-tools/issues/80](https://github.com/ncbi/sra-tools/issues/80)

I also run in the same error as . is no longer included in @inc in perl of newer versions of my distribution.

Further, what scripts could be manually edited that you are referring to with this statement?

>  we can guard against this by putting BEGIN { push @inc, '.' unless $INC[-1] eq '.' } at the top of our scripts.

Otherwise, how do I add . to @inc when I want to compile a package with ncbi-programs (ncbi/ncbi-vdb, ngs, sra-tools) that can be used by slackware's package tools (i.e. placing it in the /usr directory)? 

Sorry, I am not familiar whatsoever with perl

Regards,

Rob

See below for tail-ends of my perl -V outputs:

on Slackware-current with Perl-26.1:
Compiled at Oct 8 2017 14:35:44
@inc:
/usr/local/lib64/perl5
/usr/local/share/perl5
/usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl
/usr/lib64/perl5
/usr/share/perl5

on Slackware-14.2 with Perl-22.2
Compiled at Apr 29 2016 23:26:30
@inc:
/usr/local/lib64/perl5
/usr/local/share/perl5
/usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl
/usr/lib64/perl5
/usr/share/perl5
.

**Comment by darnassiano** [comment]
set an environment variable as:

`LIB5PERL=path_where_you_cloned_sratoolkit_master/sra-tools/setup`

**Comment by klymenko** [comment]
@brobr , do you still have this issue?

**Comment by brobr** [comment]
Hi klymenko, sorry about the lack of updates. No, no issue anymore (and I've used sra-toolkit quite a few times lately).
