### ISSUE TITLE
download data from .krt file using prefetch

### ISSUE THREAD

**Issue by komalsrathi** [ncbi/sra-tools#117]
Hi,

I am trying to download the data from a dbGaP study. I am using the `.krt` and `.ngc` files as below:

```
vdb-config --import RNA_16973.ngc ./

prefetch --max-size 100000000 -t ascp -a "$ASPERA/connect/bin/ascp|$ASPERA/connect/etc/asperaweb_id_dsa.openssh" cart_DAR64359_201802160946.krt
```

I am getting several errors - please see the attached logs file.

[prefetch_logs.txt](https://github.com/ncbi/sra-tools/files/1749414/prefetch_logs.txt)

**Comment by klymenko** [comment]
Please look over the information about firewalls at https://github.com/ncbi/sra-tools/wiki/Firewall-and-Routing-Information and make sure that your IT people are aware of the requirements for accessing SRA data at NCBI.

**Comment by komalsrathi** [comment]
Ok thank you - I will check with them.
