### ISSUE TITLE
Support Compiling on FreeBSD

### ISSUE THREAD

**Issue by reedacartwright** [ncbi/sra-tools#12]
SRA-tools compiles on Apple and Linux, but does not compile on FreeBSD.  Due to the complex nature of the build system it is difficult to port without knowing the intricacies of the software.

**Comment by kwrodarmer** [comment]
At this time, we are only supporting Linux, OS X, and Windows. We left this issue open with the hopes of finding cycles to add FreeBSD, but this has not materialized. If we do add support in the future, we will try to make an announcement about it.

The port should not be terrible. Basically all of the platform specific code is under sub-directories named for the flavor, and we don't have large amounts of code that are platform specific. Essentially most/all is under the `ncbi-vdb` library, and most of it is universal to *Unix*. There are a few areas of divergence, and these are separated between linux and mac, and sometimes bsd.

**Comment by reedacartwright** [comment]
I worked on a FreeBSD port several months ago.  I got it to build, but did not run as expected.  If you could provide documentation for the platform specific code areas and testing procedures, I might be able to fix my port.

**Comment by outpaddling** [comment]
Just stumbled on this and wanted to leave a note to posterity: There is a functional 2.8.2 port here, though it was never committed to the official ports tree:
[https://github.com/outpaddling/freebsd-ports-wip/tree/master/sra-tools](https://github.com/outpaddling/freebsd-ports-wip/tree/master/sra-tools)
Work is ongoing on newer versions, though it was stalled for a while.

**Comment by outpaddling** [comment]
FYI, sra-tools 2.11.0 was just committed to the ports tree.
