### ISSUE TITLE
fastq-dump --split-files generate two FASTQ with different number of reads

### ISSUE THREAD

**Issue by smshuai** [ncbi/sra-tools#127]
Hi,

I'm using `sratoolkit.2.9.0-ubuntu64` to `prefetch` and `fastq-dump` data from SRA. Some FASTQ files generated by `fastq-dump --split-files` have a very different number of reads, which is not valid for downstream analysis.

Here are some of these runs:
- SRR3681114 (the first FASTQ file has 296747632 lines and the second one has 188376340 lines)
- SRR3681155 (first 370798776 lines; second 226769644 lines)

Do you have any idea why this happens? Thanks in advance!

**Comment by kwrodarmer** [comment]
Try using `--skip-technical` and `--split-3` rather than `--split-files`.

**Comment by smshuai** [comment]
The problem is solved. Thanks very much.

**Comment by twohrdrive** [comment]
hey guys, I'm still having this issue. I get only two fastq files, and they each have different number of reads. I first used the "prefetch SRR#####" command to obtain the .sra file.

Then I invoked fastq-dump like so:

`fastq-dump --skip-technical --read-filter pass --readids --clip SRR##### --split-3 -v -v -v  SRR#####`

Any ideas?

**Comment by twohrdrive** [comment]
I should mention, I'm using an SRX#####.sra database, not an SRR database
