### ISSUE TITLE
prefetch aspera error

### ISSUE THREAD

**Issue by psddia** [ncbi/sra-tools#129]
Hi,

I'm running the command -
prefetch -t ascp -a "\aspera directory\bin\ascp|\asperadirectory\etc\asperaweb_id_dsa.openssh" -o kart cart#.krt
and I get this error -
"user@host:" in all sources must match

What does this mean?
![onpaste 20180508-154435](https://user-images.githubusercontent.com/29783841/39779366-fa577f2a-52d6-11e8-8b5e-70499a781ac2.png)

**Comment by klymenko** [comment]
Send your question to sra-tools@ncbi.nlm.nih.gov

**Comment by kwrodarmer** [comment]
The SRA Toolkit Team can help you at the email address given above - it's best for any questions regarding sensitive information to be kept out of GitHub.
