### ISSUE TITLE
clarify configure options

### ISSUE THREAD

**Issue by agarwal** [ncbi/sra-tools#13]
The `configure` script takes the argument `--with-ncbi-vdb-sources`, but I'm not sure what it should be set to. I've tried pointing it to the ncbi-vdb root directory, every sub-directory of it, the install directory of ncbi-vdb, but none work. The configuration always ends with an error like:

```
checking for ncbi-vdb package source files and build results...
    includes... /home/aa1/tmp/ncbi-vdb-2.5.0
    libraries... /home/aa1/tmp/ncbi-vdb-2.5.0/_install/lib64
no
configure: error: required ncbi-vdb package not found.
```

I think I'm using `--with-ngs-sdk-prefix` and `--with-ncbi-vdb-build` correctly, but more clarification on those would be helpful too. Thank you.

**Comment by dgpinheiro** [comment]
I installed ncbi-vdb and ncbi-sdk using a custom prefix "/usr/local/".
I'm having the same error:

checking for ngs-sdk package...
        includes... /usr/local
        libraries... /usr/local/lib64
includes: /usr/local/include
libraries: /usr/local/lib64
checking for ncbi-vdb package source files and build results...
        includes... /usr/local/bioinfo/ncbi/ncbi-vdb
        libraries... /usr/local/lib64
no
configure: error: required ncbi-vdb package not found.

**Comment by aboshkin** [comment]
After installation to /usr/local/, I would expect the ncbi-vdb include files to be located in /usr/local/include/ndbi-vdb. In your output, the script is looking for them elsewhere ( /usr/local/bioinfo/ncbi/ncbi-vdb )

Can you post all 3 of the ./configure commands that you are using?

Thank you,
Anatoly

**Comment by nyetsche** [comment]
I'm seeing a similar issue.

From a clean download of `ngs`, ncbi-vdb` and `sra-tools`, I get:

```
ubuntu@ip-172-16-120-93:~/sra-tools$ ./configure --with-ngs-sdk-prefix=$HOME/ngs/ngs-sdk --with-ncbi-vdb-sources=$HOME/ncbi-vdb --with-ncbi-vdb-build=$HOME/ncbi-vdb/libs
Configuring SRA-TOOLS package
checking system type... Linux
checking machine architecture... x86_64
checking SRA-TOOLS version... 2.5.7
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking for fuse library... no
checking for hdf5 library... no
checking for magic library... no
checking for xml2 library... yes
checking for ngs-sdk package...
        includes... /home/ubuntu/ngs/ngs-sdk
        libraries... no
        libraries... /home/ubuntu/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
includes: /home/ubuntu/ngs/ngs-sdk
libraries: /home/ubuntu/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
checking for ncbi-vdb package source files and build results...
        includes... /home/ubuntu/ncbi-vdb
        libraries... no
        libraries... no
```
And have tried a wide variety of `--with-ncbi-vdb-sources=` / `--with-ncbi-vdb-build=` subdirectories of `$HOME/ncbi-vdb`.

Stepping through the code makes me think that `ncbi-vdb` is setting `pkgpath` permanently to `/usr/local/ncbi/ncbi-vdb`, but I can't quite make out why `ncbi-ngs` doesn't have that problem.

**Comment by nyetsche** [comment]
I have perhaps found the trick, though I'd think the better answer is check the `--with-ncbi-vdb-*` options, and/or clarify why it works for `--with-ngs-sdk`.

`--with-ngs-sdk` "naturally" finds the output directories, even though I never specified it:

`        libraries... /home/ubuntu/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib`

`--with-ncbi-vdb-build` does not. _Unless_ I specify it myself:

```./configure --with-ngs-sdk-prefix=$HOME/ngs/ngs-sdk --with-ncbi-vdb-sources=$HOME/ncbi-vdb --with-ncbi-vdb-build=$HOME/ncbi-outdir/ncbi-vdb
[...]
checking for ncbi-vdb package source files and build results...
        includes... /home/ubuntu/ncbi-vdb
        libraries... /home/ubuntu/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib
[...]
configured with: "'--with-ngs-sdk-prefix=/home/ubuntu/ngs/ngs-sdk' '--with-ncbi-vdb-sources=/home/ubuntu/ncbi-vdb' '--with-ncbi-vdb-build=/home/ubuntu/ncbi-outdir/ncbi-vdb'"```

A `make` is then successful.

So there's an inconsistency - the `--with` flag needs to be set for `ncbi-vdb`, but not `ngs`, but in both cases it still picks up on the `$HOME/ncbi-out` directory, which is vaguely hardcoded? I can't find any documentation on that directory, except for a single line (ish) in the `ncbi-vdb/Makefile`:

```
ubuntu@ip-172-16-120-93:~/sra-tools$ grep -i outdir ~/sra-tools/* ~/ngs/* ~/ncbi-vdb/*
/home/ubuntu/ncbi-vdb/Makefile: @ echo "Before initial build, run 'make OUTDIR=<dir> out' from"```

**Comment by klymenko** [comment]
See https://github.com/ncbi/sra-tools/wiki/Building-from-source-:--configure-options-explained
