### ISSUE TITLE
Unable to install sra-tools

### ISSUE THREAD

**Issue by UltraSpecialException** [ncbi/sra-tools#131]
Hi,

I was following the instructions from https://github.com/ncbi/sra-tools/wiki/Building-and-Installing-from-Source to install sra-tools onto my Mac. Everything was working perfectly fine until I got to the make step in the sra-tools folder (I have finished with the ncbi-vgs and ncbi-vdb installations). I got the following error when running make: 

clang -Wl,-arch,x86_64 -o /Users/tonynguyen/ncbi-outdir/sra-tools/mac/clang/x86_64/rel/bin/copycat.2.9.0 -DNDEBUG -m64 -mmacosx-version-min=10.6 copycat.o ccfileformat.o cccat.o cctree.o cctree-dump.o cctar.o ccsra.o ccsubchunk.o ccfile.o -L/Users/tonynguyen/ncbi-outdir/sra-tools/mac/clang/x86_64/rel/lib -L/Users/tonynguyen/ncbi-outdir/sra-tools/mac/clang/x86_64/rel/ilib -L/usr/local/ngs/ngs-sdk/lib64 -L/Users/tonynguyen/ncbi-outdir/ncbi-vdb/mac/clang/x86_64/rel/lib -L/Users/tonynguyen/ncbi-outdir/ncbi-vdb/mac/clang/x86_64/rel/ilib -lkapp -ltk-version -lncbi-vdb-static -lkff -lmagic-static -ldl -lpthread -lxml2 -liconv -lm
ld: library not found for -lmagic-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/tonynguyen/ncbi-outdir/sra-tools/mac/clang/x86_64/rel/bin/copycat] Error 1
make[2]: *** [std] Error 2
make[1]: *** [copycat] Error 2
make: *** [tools] Error 2

I have looked on Google but I can't seem to find a solution. I'd appreciate some help. Thanks in advance!

**Comment by kwrodarmer** [comment]
Did you run the configuration script beforehand?
What were your make commands?

As an aside, copycat is essentially an internal tool. It's unlikely that you would have a need for it, so skipping it in the build is fine. The configuration script should have detected the lack of libmagic and not attempted to build copycat.

**Comment by UltraSpecialException** [comment]
By configuration script do you mean running ./configure, if so then yes I did run it.

I simply went into the sra-tools folder and executed make.

**Comment by kwrodarmer** [comment]
While waiting for your response, I'll say that I suspect this is a bug in our configuration system that detects libmagic on your system and does not build our internal version of it but then generates a reference to it (the internal version).

There would be a few ways around this:
1. within `sra-tools/tools/copycat/` edit the `Makefile` to change the line 95 from
```

**Comment by UltraSpecialException** [comment]
the report under ./configure for libmagic is yes.

I tried your work around (1) and it worked. Thank you very much!

**Comment by kwrodarmer** [comment]
We will correct this for the next release. Glad you could use this workaround.
