### ISSUE TITLE
Unsuccessful instillation

### ISSUE THREAD

**Issue by morganclayman** [ncbi/sra-tools#135]
I've installed the sra toolkit following the wiki instructions (and making the proper adjustments for the transition to https and the change in version), but there is no output to the command which fastq-dump. The command ls lists the binaries, so I know that I'm in the proper directory, so I'm not sure what I'm doing incorrectly.

**Comment by morganclayman** [comment]
I’m using macOS and have never installed the toolkit on this computer.

**Comment by kwrodarmer** [comment]
Okay, that is a good starting point.

Is there a reason you are building from source and not just using the pre-built binaries?

https://github.com/ncbi/sra-tools/wiki/Downloads

**Comment by kwrodarmer** [comment]
In any event, please provide the exact command line you are executing.

**Comment by morganclayman** [comment]
I have executed the following commands:

1. curl --output sratoolkit.tar.gz https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-mac64.tar.gz
2. tar -xvzf sratoolkit.tar.gz
3. cd sratoolkit.2.9.0-mac64/bin
4. which fastq-dump

**Comment by klymenko** [comment]
Change your sequence to:

3. cd sratoolkit.2.9.0-mac64/bin
4. export PATH=$PATH:`pwd`
5. which fastq-dump

**Comment by morganclayman** [comment]
I still have no output for 'which fastq-dump'

**Comment by klymenko** [comment]
The following command should add the absolute path to sratoolkit.2.9.0-mac64/bin to your PATH:
```
export PATH=$PATH:`pwd`
```

**Comment by morganclayman** [comment]
The same thing ocurred

**Comment by klymenko** [comment]
what is the output of `echo $PATH` ?

**Comment by morganclayman** [comment]
/Applications/anaconda/bin:/anaconda/bin:/Users/me/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:pwd:pwd:pwd

**Comment by kwrodarmer** [comment]
The backticks are critical in the command. Please copy/paste the command as it was given rather than retyping it. The backticks cause your shell to generate a working directory in place of pwd.

**Comment by morganclayman** [comment]
Okay it worked, thank you
