### ISSUE TITLE
fastq-dump should save singletons to separate files. 

### ISSUE THREAD

**Issue by biocyberman** [ncbi/sra-tools#138]
I ran fastqdump like the following:

`$fastqdump -W --qual-filter-1 --split-files --gzip ${acc}.sra;
`
The output  ${acc}_1.fastq.gz and ${acc}_2.fastq.gz do not have the same number of reads. This created confusion to downstream tools, which expect reads are properly pair. That is an reasonable assumption because the fastq files are telling they are paired.

More detailed about the problem can be found here:
https://github.com/marcelm/cutadapt/issues/316#event-1727732362

So I would suggest fastq-dump to save singleton reads to separate files, and keep the reads in *_{1,2}.fastq.gz properly paired.

**Comment by kwrodarmer** [comment]
I don't think you actually ran the command you mention (i.e. you didn't copy/paste the command line).
```
fastq-dump -W --qual-filter-1 --split-3 ${acc}.sra
```
This is probably the command you want. The `--split-files` option behaves *exactly* the way it was designed and requested, but as it happens is not what you had in mind.

Incidentally, if you are running this command directly on *.sra files, then you are obviously downloading them first, and probably not using the `prefetch` tool, which can be problematic. If you are doing things according to best practice, you would `prefetch` the files if so desired first, then run `fastq-dump` or the newer [fasterq-dump](https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump) using simple accession without the `.sra` extension.

It is not recommended to use the `--gzip` option of `fastq-dump` as it tends to give slower performance than running gzip externally. I realize that with split files it is more difficult to script this, but just be aware that it can cause slower operation.

**Comment by biocyberman** [comment]
Thanks for you comments. 

The command is extracted from a script. I will remove the gzip compression option and work on uncompressed data directly. The fastq files are intermediate files anyway.
