### ISSUE TITLE
Cannot run fastq-dump 2.9.1 to convert sra files: "cannot be opened as database or table"

### ISSUE THREAD

**Issue by bjarnebartlett** [ncbi/sra-tools#142]
Greetings,

Would someone here be able to help me with a fastq-dump problem that really has me stumped? I am trying to convert some sra files that I donwloaded to fastq files using version 2.9.1 of the sra toolkit, specifically fastq-dump. The project is controlled access.  

**First thing I did is restore defaults and run vdb-config to import the key file:**
```
bjarne@node2:~/mnt/Project18661/ncbi$ vdb-config --restore-defaults
Fixed default configuration
bjarne@node2:~/mnt/Project18661/ncbi$ vdb-config --import prj_18661_D15673.ngc
prj_18661_D15673.ngc was imported.
Repository directory is: '/home/bjarne/mnt/Project18661/ncbi/dbgap-18661/dbGaP-1                                   8661'.
```

**For reference, the sra files are in:** '/home/bjarne/mnt/Project18661/ncbi/dbgap-18661/dbGaP-1                                   8661/sra'

**The second thing I did was fun fastq-dump from the project directory:**
```
bjarne@node2:~/mnt/Project18661/ncbi/dbgap-18661/dbGaP-18661$ fastq-dump -X 5 -Z                                    SRR6504361
2018-07-28T21:39:04 fastq-dump.2.9.1 _**err: item not found while constructing with                                   in virtual database module - the path 'SRR6504361' cannot be opened as database                                    or table**_
```
**The test-sra file is attached here:** [test-sra(vs2).txt](https://github.com/ncbi/sra-tools/files/2238348/test-sra.vs2.txt)
**NLM Case #:** CAS-245972-F2X9J2 
**PDF of the error message:**[bartlett_sraerror.pdf](https://github.com/ncbi/sra-tools/files/2238319/bartlett_sraerror.pdf)

I would appreciate it so much if anyone on here could provide some insight into what I am doing wrong. 

Bjarne

**Comment by kwrodarmer** [comment]
You almost certainly have a download-only NGC file. The latest version of the toolkit is 2.9.2 which will tell you if this is the case. If so, you need to request a full NGC file with the permission to read files.


SRA Toolkit Team

________________________________

**Comment by bjarnebartlett** [comment]
Mahalo, kwrodarmer. 

Thank you so much, I ran toolkit 2.9.2 and the error messages were very helpful. I am not the PI, just a downloader, so I will ask the project PI for a full NGC file with read/decrypt permissions. For security purposes, it might be helpful if accounts designated to download could have read/decrypt permissions to avoid project members having to send each other different key files. 

Bjarne

```
2018-07-30T17:44:09 fastq-dump.2.9.2 err: You do not have read permissions to decrypt data from this project.
2018-07-30T17:44:09 fastq-dump.2.9.2 err: Please contact your PI to request an NGC token with decrypt permissions.
2018-07-30T17:44:09 fastq-dump.2.9.2 err: Import the new NGC file before decrypting again.
2018-07-30T17:44:09 fastq-dump.2.9.2 err: If you continue to have problems, contact sra@ncbi.nlm.nih.gov for assistance.
2018-07-30T17:44:09 fastq-dump.2.9.2 err: item not found while constructing within virtual database module - the path 'SRR6504361' cannot be opened as database or table
```

![toolkit2 9 2_errormessage_bartlett](https://user-images.githubusercontent.com/31433034/43442562-047902d6-943a-11e8-8034-cda59fe38937.png)

**Comment by kwrodarmer** [comment]
We are taking this issue into account and considering options. Thank you for your feedback.
