### ISSUE TITLE
Some ERR files fail to download properly

### ISSUE THREAD

**Issue by matnguyen** [ncbi/sra-tools#144]
fasterq-dump.2.9.2 err: concatenator.c execute_concat_un_compressed() creating ouput-file '/data/reseq_raw_multi/ERR025847_2.fastq' -> RC(rcExe,rcFile,rcPacking,rcName,rcExists)

**Comment by kwrodarmer** [comment]
The error you are seeing here comes from repeating a prior attempt without using the `--force` option.

Depending upon your location and network configuration, you may experience issues downloading data. You should try again with the `--force` option. If it continues to fail, we recommend that you use the tool `prefetch` to download the file before running `fasterq-dump`.

**Comment by kwrodarmer** [comment]
By the way, you may find something of value in the article https://github.com/ncbi/sra-tools/wiki/Network-and-Connection-Errors .
