### ISSUE TITLE
constraint violated error when fastq-dump sra file

### ISSUE THREAD

**Issue by xuan-wang** [ncbi/sra-tools#145]
Hi, developers!

I have already downloaded a sra file, and then I used fastq-dump to decompress it. I can't find any useful information about this error. Could anyone help me?

$ fastq-dump --split-3 --gzip -G ./ERR2094838
2018-08-27T01:48:35 fastq-dump.2.9.2 warn: block-size in local file 131072 does not match requested value 32768
2018-08-27T01:48:38 fastq-dump.2.9.2 warn: block-size in local file 131072 does not match requested value 32768
2018-08-27T01:48:47 fastq-dump.2.9.2 err: constraint violated while opening file - failed ./ERR2094838

There will be a few reads decompressed from sra file to some fastq.gz files, but when the err is given, decompression will stopped.
Thanks!

**Comment by ATpoint** [comment]
You can get this directly from the [ENA](https://www.ebi.ac.uk/ena/data/view/ERR2094838). Have a look [at this tutorial](https://www.biostars.org/p/325010/) on how to download from there.

**Comment by kwrodarmer** [comment]
@xuan-wang - as I believe we already told you, your download is corrupt and you need to retrieve it again.
@ATpoint - a corruption in download can also occur in fastq format, is far far far more likely and the result is worse because you'd have no idea whether the corruption was present. Your advice is dangerous. If your intent is to advertise for something, please use a forum dedicated for it.

**Comment by ATpoint** [comment]
@kwrodarmer I do not aim to advertise for anything, but feel a certain pleasure in giving back my experience to the community after benefitting from it a lot while I was an unexperienced beginner in the field. That is why I spend time posting and moderating on Biostars, which is 100% non-commercial. I of course understand that you stand up for your software, but after downloading hundreds of files from both NCBI and ENA, I can clearly say that the Aspera-driven download from ENA is (--in my very humble experience--) more convinient and faster that using prefetch/fastq-dump. I did not mean any disrespect, and therefore I apologize if you took any insult.

**Comment by kwrodarmer** [comment]
Perhaps you can clearly say how using the Aspera-driven download of ENA differs from the Aspera-backed download of prefetch, other than the obvious effects of geography?

**Comment by xuan-wang** [comment]
I solved by decompressing without --gzip parameter. I can make sure my download is intact because the md5 is same when I reteived it again. @ATpoint The fastq from ENA is merged from different lane's data, and the bam file is too large, so sra from NCBI is better.
