### ISSUE TITLE
fastq-dump: mbedtls_ssl_read returned -76

### ISSUE THREAD

**Issue by zji90** [ncbi/sra-tools#147]
Hi,
I encountered the following error message on multiple accessions. I first downloaded the sra file for SRR1638520 using wget and then run fastq-dump --split-files SRR1638520.sra. I am running this on a computing cluster with CentOS 7.
Error message:
fastq-dump.2.9.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

**Comment by klymenko** [comment]
@zji90 , do you still need help?
