### ISSUE TITLE
Singularity and fasterq-dump

### ISSUE THREAD

**Issue by brucemoran** [ncbi/sra-tools#148]
Hi, running `fasterq-dump` inside a Singularity container results in the error below, similar to that of issue #124. Cannot quite see how to get around this, tried setting /repository/user/main/public/root = /tmp in default.kfg, and setting VDB_CONFIG=/path/to/default.kfg, but same outcome.

Ideas would be much appreciated. 

```
2018-09-14T20:13:18 fasterq-dump.2.9.2 err: path not found while creating directory within file system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/sra22/SRR/001569/SRR1607580'
2018-09-14T20:13:18 fasterq-dump.2.9.2 err: invalid accession 'SRX728623'
```

**Comment by brucemoran** [comment]
Using `prefetch -O ./ SRX728623` and then `fasterq-dump` on the SRA works, closing.

**Comment by kwrodarmer** [comment]
The problem was actually that you were specifying an **experiment** accession instead of a **run** accession. This is a common issue that we are addressing. Had you given a run accession, the original command would have worked.

**Comment by manasa-surakala** [comment]
@brucemoran , I prefetched sra file and I am now trying to convert it into fastq files using fasterq-dump. Its giving me the same invalid accession error. My command is fasterq-dump -S SRR1219802.sra. I tried with ./ as well but same error. Any views?

**Comment by brucemoran** [comment]
@manasa-surakala did you use ```prefetch -O ./ SRR1219802```? Then the ```fasterq-dump``` command should work, with or without the ```-O ./```

**Comment by manasa-surakala** [comment]
@brucemoran , yes. I got SRR1219802.sra from prefetch command. 
Then I tried fasterq-dump -S SRR1219802.sra
