### ISSUE TITLE
fasterq-dump must not include .sra extension to output.

### ISSUE THREAD

**Issue by antonkulaga** [ncbi/sra-tools#149]
When I provide .sra file to fasterq-dump like:
```bash
fasterq-dump --outdir extracted --threads 2 --progress --split-files --skip-technical /cromwell-executions/chip/67a158d8-033e-4129-866e-4031ccdef6a3/call-extract_treatment/inputs/-213424315/SRR633615.sra
```
it generates.
```
SRR633615.sra_1.fastq  SRR633615.sra_2.fastq
```
inside extracted folder, while ".sra" should not be included

**Comment by kwrodarmer** [comment]
Thanks for the report. You may be interested in reading this page:

https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process

If runs are downloaded as designed, there will be no need for the `.sra` extension, nor even the ability to use it. As soon as you specify paths to our tools, we assume that you want the path name, and we generally do not try to manage the extension.

That said, some of our tools in the past have manipulated extensions, so maybe you're used to that. I recommend that you take a look at how name resolution works and our download scheme to see if that wouldn't work better for you.

**Comment by klymenko** [comment]
The issue was fixed in our latest release.
