### ISSUE TITLE
Performing Many Downloads In Parallel Causes `ascp: failed to authenticate, exiting.` Messages

### ISSUE THREAD

**Issue by Miserlou** [ncbi/sra-tools#151]
We use Aspera/`ascp` to download many `.sra` files. When we perform our downloads across many machines in our cluster, we start to see many of these messages:

```
Final shell call of `.aspera/cli/bin/ascp -T -k1 -i .aspera/cli/etc/asperaweb_id_dsa.openssh anonftp@ftp.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/ERR/ERR185/ERR1857983/ERR1857983.sra /home/user/data_store/ERP011556/ERR1857983/ERR1857983.sra` to ascp failed with error message: ascp: failed to authenticate, exiting.
``` 

These are occasionally peppered with:

```
Final shell call of `.aspera/cli/bin/ascp -T -k1 -i .aspera/cli/etc/asperaweb_id_dsa.openssh anonftp@ftp.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/ERR/ERR175/ERR1757553/ERR1757553.sra /home/user/data_store/ERP016474/ERR1757553/ERR1757553.sra` to ascp failed with error message: ascp: Failed to open TCP connection for SSH, exiting.
```

We don't normally see these problems when operating in small batches, but we do see them happen  when we scale up. (We saw similar behavior interacting with ENA, which is why we moved backed to NCBI!)

Is there anything we can do to avoid this problems and assure a consistent performance? Is this the result of us hitting a rate-limit, or are we inadvertently DDoS'ing the SRA Aspera servers? Is there anything we can do to avoid these rate limits/overconnection problems? For instance - can you tell us the total available upload capacity?

**Comment by kwrodarmer** [comment]
@Miserlou - Aspera (a 3rd party product) is not really designed for parallel download, and is not a limitation of either the SRA or NCBI.

You should be using prefetch to drive these downloads, because it performs many additional functions to `ascp` (which it uses for primary download). It also knows how to resolve accessions properly, while you appear to be using an obsolete URL generation algorithm.

**Comment by Miserlou** [comment]
But surely the goal should be to keep server-side performance be consistent even in times of high traffic? (Prefetch is using `ascp` under the hood anyway - reasonable transfer speed would be impossible otherwise.)

We need to consume a lot of SRA data in parallel - it will literally take years to transfer all of the data in serial. In our tests this works well up to (almost) 2x1GiBs, but beyond that we start to see `failed to authenticate, exiting` swamp everything else. Unlike ENA, it seems that existing transfers are able to continues, but new connections cannot be formed.

Furthermore, I'm led to believe that this is server-side because once the errors start occurring, they start occurring _all over_, including on my local machine (on a different network 3 states away):

```
$ ./ncbi_test.sh
ascp: failed to authenticate, exiting.
Session Stop  (Error: failed to authenticate)
```

and the same behavior can be seen against the "private" server as well:
```
$ ./ncbi_private_test.sh
ascp: failed to authenticate, exiting.

Session Stop  (Error: failed to authenticate)
```
and even in our CI:

https://circleci.com/gh/AlexsLemonade/refinebio/7176?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

So, this leads me to think that the NCBI Aspera servers are being overwhelmed, or anonymous access is being rate-limited.

Do you have any insights into this, and any ideas what we can do to help resolve it? What is your maximum throughput capacity?

**Comment by kwrodarmer** [comment]
I'm getting information from our systems group that somebody from AWS is overloading the Aspera servers. Is that you? If so, can you hold on until we can try to find a way to deal with this?

**Comment by Miserlou** [comment]
Yep, that's us. Shutting our downloaders down for now. If you want to talk off-list you can email me at `miserlou [at sign] gmail [dot] com`

**Comment by cgreene** [comment]
One thing that comes to mind: is there already a copy of the public `.sra` files that make up SRA on AWS in something like S3 in a readable form?

**Comment by osris** [comment]
Thanks.  I’m trying to gather use cases for cloud compute on SRA data. when we start moving data to cloud service providers, I’d like to make sure we prioritize moving the data that will benefit active users and early adopters.
Feedback is always welcome.
You can write to me directly at osulliva@ncbi.nlm.nih.gov/
-Chris

*********************************
Christopher O’Sullivan PhD
Sequence Read Archive
NCBI/NLM/NIH
osulliva@ncbi.nlm.nih.gov
*********************************

**Comment by inutano** [comment]
Hi @osris, we're also using AWS to process a bunch of SRA data - for the purpose of bulk re-analysis such as our database chip-atlas.org or the other RNA-seq projects. We're using AWS's ap-northeast-1 (N. Virginia) region. It'd be fantastic if the data are available on S3 as well!!

**Comment by alexukr** [comment]
ap-northeast-1 is Tokyo, not N.Virginia.

**Comment by inutano** [comment]
Ah sorry, I was confused! I use N. Virginia to get a large number of data from NCBI, and also use the Tokyo region to get data from DDBJ. We use both since a transfer from DDBJ's ftp server sometimes goes very slow (we're investigating the reason).

**Comment by JZL** [comment]
Sorry for pinging this old thread but it was only thing I could find concerning NCBI's ascp giving this error. For anyone else who gets this error:

I found, for uploads at least, that it was possibly to do very parallelized uploads (60+ simultaneous uploads but I didn't push it farther) but that I had to stagger each upload's start. I did a (probably overkill) 2 seconds delay between each upload's start and it seems to work fine, so it might be rate-limiting on the authentication step, not the UDP transfer. I found this only kicked in when I was trying to start 10+ simultaneous upload sessions that it gave this error.

**Comment by klymenko** [comment]
Sorry, ascp download is not available anymore.

**Comment by Baytars** [comment]
@klymenko Sorry to hear that. Is there any official announcement that accounts for that? Today I used ascp download as ususal and encountered this error:
```
ascp: failed to authenticate, exiting
```
Even directly copying command from [SRA Explorer](https://sra-explorer.info/#) returned the same error. How I miss the streamlined experience using Aspera!

**Comment by kwrodarmer** [comment]
> Sorry to hear that. Is there any official announcement that accounts for that? 

NCBI has not supported `ascp` for a long time now. Our team supports the SRA Toolkit and we have nothing to do with `ascp` or its support. We will forward this message to a different team that may be able to give you more specific information.
