### ISSUE TITLE
downloading Fastq files (fasterq-dump) and keeping file name from website

### ISSUE THREAD

**Issue by ybohak** [ncbi/sra-tools#153]
Hi, Been using fasterq-dump.2 to download and save fastq files. 

How can I download the fastq files using fasterq-dump and still keep original read names with details about each read as seen on ncbi website? The names on the website contain info that is important in order to identify reads and their origin.
e.g. read name that I'm trying to save: Targeted deep sequencing of HIV-1 RV217_10463_day30_V3(gp120)
site: https://www.ncbi.nlm.nih.gov/sra
Cheers!

**Comment by kwrodarmer** [comment]
Hi @ybohak ,

Please see https://github.com/ncbi/sra-tools/wiki/Read-Names for information about this.
