### ISSUE TITLE
Unable to find libmagic and libhdf5

### ISSUE THREAD

**Issue by samyuktr** [ncbi/sra-tools#155]
Unable to find these packages. Using ubuntu 16.04 
```
libmagic (needed for copycat)
libhdf5 (needed for pacbio-load)
```

How do I proceed?

**Comment by kwrodarmer** [comment]
You don't need them. The configuration has told you that they can't be located and that two tools that are not normally usable by end users _(although critical to our loading process)_ won't be built. It's okay. Your build should be just fine and perfectly usable.
