### ISSUE TITLE
sam-dump.2.8.2 int: data inconsistent while executing function within transform module - VCursorCellDataDirect

### ISSUE THREAD

**Issue by hsiehph** [ncbi/sra-tools#158]
Hi,

I downloaded the SRR2165094.sra using prefetch without any error.
# prefetch -X 200G SRR2165094

I used the following command to convert it into a BAM, but received the following error. I have also tried to re-download the .sra file as well as using the --primary option in the sam-dump command as suggested in one of the open issues found on this repository, but have not had any success. Can you point me to the problem and solution for this? I have encountered the same error for other .sra files I downloaded from dbGaP.

Thanks,
Benson

# Commands   
    module load ncbi-sra/2.8.2
    module load samtools/1.9
    TMP=$TMPDIR/SRR2165094
    sam-dump -u -r --primary SRR2165094  | samtools view -bS -@4 - | samtools sort -@4 -T $TMP -o SRR2165094.sorted.bam -

# Error:
sam-dump.2.8.2 int: data inconsistent while executing function within transform module - VCursorCellDataDirect( row#28385669 . idx#8 . READ ) INSDC_dna_text (ptr) failed
[W::sam_read1] Parse error at line 1506941081
[main_samview] truncated file.
[bam_sort_core] merging from 624 files and 4 in-memory blocks...
Error in job process_data while creating output file SRR2165094.sorted.bam

**Comment by hsiehph** [comment]
err.... I really hope someone can point me some direction on this issue.....

**Comment by wraetz** [comment]
We are investigating the problem. This accession SRR2165094 does indeed have inconsistent data at row #28385669. This is in the range of the unaligned data. Do you need the unaligned READS? To make your conversion finish you can just omit the '-u'. If you definitely need the unaligned READS, we have to reload the data. I do not know how long that will take.

**Comment by hsiehph** [comment]
Thanks, wraetz, for the reply.
Yes, I do would like to get all the reads because I am interested in structural variants in these GTEx genomes. I have to add that similar errors have been found in many GTEx genomes downloaded from dbGaP using the same commends. Is it possible to estimate how much time is needed for reloading these GTEx genomes? 

Thanks!

**Comment by kwrodarmer** [comment]
@hsiehph -  you should update your software to the latest version, although the problem you're having is not with the toolkit. Rather, the data uploaded had inconsistencies. Our data curators are working on a fix and hope to regenerate the run. Once we have something for you, we'll let you know so you can download the updated run.

**Comment by klymenko** [comment]
@hsiehph, do you still need help?
