### ISSUE TITLE
about sam-dump what is the corresponding fasta file?

### ISSUE THREAD

**Issue by AliceYu0911** [ncbi/sra-tools#160]
Hi. Sorry to bother you. I have some confusion about the sam-dump instruction. I searched the previous issues but didn't find related ones.
first I want to appreciate you that the fasterq-dump is much faster than the older version fastq-dump.at first I run fastq-dump SRR2048267 for more than 1 hour, but I changed to fasterq-dump and used 10 cores, it just cost 10 mins. Thanks a lot for your improvement!
second is my question. because my tool's input is .sam files, so I wonder if I can transfer the .sra file directly. and i find there is a sam-dump instruction, but the parameters don't include the corresponding fasta files. and after I try one using the command 
sam-dump --output-file SRR2048276.sam SRR2048276 
I get the .sam file, I want to see the reference it used, for example for human, the hg19.fa file. but when I output the header using command
samtools view -HS SRR2048276.sam 
it output nothing and i use vim to see the file, there is no header here.
so i wonder which file the fastq aligns to?

look forward to your reply! thank you!

**Comment by osris** [comment]
Thank you for your question.
Sam-dump produces Sam format even for unaligned data. SRR2048267 was submitted in fastq format so the Sam-dump utility will format it as Sam, but there is no alignment information.

-Chris


________________________________

**Comment by AliceYu0911** [comment]
Thanks for your reply! 
could I understand it in this way: 
whether there is corresponding sam files or not depends on the submitter. If he only submit the fastq file, the sam-dump can work but it's useless.  If he submit the fastq file and sam file, sam-dump can download its sam file correctly.
