### ISSUE TITLE
can not split SRR paired sequence

### ISSUE THREAD

**Issue by JinjinyuCityu** [ncbi/sra-tools#162]
Dear all,

I used sra tools to download sequence data  by the command below

.. /sratoolkit/bin/fastq-dump --split-files SRR2153427 
to download and split the data from SRR2153427, while only the paired sequence has been made(output given below )

Rejected 21346 READS because READLEN < 1
Read 21346 spots for SRR2153427
Written 21346 spots for SRR2153427

I browsed the SRR number SRR2153427 in the NCBI and the information showed it should was paired sequence, but I can not split it

The same issues found in the sequences form SRR2153416-SRR2153448, no split sequences can be made.

Does anyone can help me to make the split sequences from paired SRR data?

Thanks

Jinjin

**Comment by kwrodarmer** [comment]
The actual sequence data submitted to the SRA was single-ended, and the run contains empty reads for each pair. We will see if the user-submitted metadata can be corrected to reload the run.

**Comment by JinjinyuCityu** [comment]
> The actual sequence data submitted to the SRA was single-ended, and the run contains empty reads for each pair. We will see if the user-submitted metadata can be corrected to reload the run.

Hi,

I check the length of download samples, the sequences are around 250 dp each, also the authors mentioned in the paper"Performance Assessment of Full-Scale Wastewater Treatment Plants Based on Seasonal Variability of Microbial Communities via High-Throughput Sequencing" that paired-end sequenced (2×150) were processed in Meseq platform. 

So if it is only single ended, is it possible with 253 bp per each sequence?

J

**Comment by kwrodarmer** [comment]
I may be misleading with the wording I used - the intention was that the run should have paired-end data. However, the submission itself did not indicate this, which is why our loading software produced a "pair" where the second read was always empty.
