### ISSUE TITLE
VResolverQuery error

### ISSUE THREAD

**Issue by tomdrake** [ncbi/sra-tools#166]
​Hello,

I am getting the following error when trying to download bulk data using prefetch from dbGaP.

The folders generated within the ncbi project folder appear correct and this is the location I have cd'ed to in order to run prefetch from there. All permissions are 777 to just try and get it to work. The institution I work for has a proxy, but I have set this in the interactive config to a wwwcache address.

I keep getting this error message:

VResolverQuery: Assertion `VPathHasRefseqContext ( query ) && notequal == 2' failed.
Aborted

Does anyone have any ideas how to fix this?

Running Ubuntu and the latest version of sra-tools on ubuntu as of 27/11/2018 (got via apt-get)
​
Best wishes

Tom

**Comment by klymenko** [comment]
Unfortunately apt-get does not give you the latest version of SRA toolkit.
Download it from https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software

**Comment by chilampoon** [comment]
I got the same error when fetched files using .krt, so how to resolve it?

**Comment by chilampoon** [comment]
Oh I find the problem, only the latest version of prefetch can succeed downloading.

**Comment by klymenko** [comment]
@tomdrake , was your issue resolved?
