### ISSUE TITLE
Can fasterq-dump work in "scratch" locations when using a dbGaP key?

### ISSUE THREAD

**Issue by seandavi** [ncbi/sra-tools#167]
Sorry for the naive question, but I am currently happily using fasterq-dump for non-dbGaP data in a cluster environment, but because of disk performance issues must do work on a disk that is local to each node. Therefore, there is no shared "project" directory. What is the recommended approach to use sra-tools generally and fasterq-dump specifically when the "project" directory varies for each accession?

**Comment by kwrodarmer** [comment]
Hi @seandavi - the requirement for the tool to work is that your working directory be within the dbGaP workspace. The temporary scratch directories _should_ be set to something else _(I assume you've read the Wiki page with its recommendations)_ and even the output can be directed somewhere else. Your only obligation with regard to dbGaP is to do this in a way that does not violate the confidentiality and data handling agreements.

So just in case that was not clear, the tool is technically capable of doing its work and producing its output in directories of your choice, where the only technical requirement to use dbGaP key is to issue the command from within the dbGaP workspace working directory.

**Comment by seandavi** [comment]
Thx, @kwrodarmer, for the clear explanation. That, indeed, addresses my use case quite well.
