### ISSUE TITLE
SRA tools are not working on Mac OS X

### ISSUE THREAD

**Issue by sfchen** [ncbi/sra-tools#170]
* SRA Version: July 24, 2018, version 2.9.2 release:
* Mac OS X: 10.13.6

fastq-dump, fasterq-dump, prefetch ...

Whatever you input, these tools only give you the help info.

The same command works on Linux.

**Comment by kwrodarmer** [comment]
We will search for a machine with OS 10.13.6, but on a current system this behavior cannot be reproduced. Furthermore, our release pipeline would fail completely if the software did not perform properly, so whatever is producing the effect you are observing is abnormal.

Perhaps you could provide more clues?
