### ISSUE TITLE
prefetch download error

### ISSUE THREAD

**Issue by huangl07** [ncbi/sra-tools#175]
2019-02-01T02:31:51 prefetch.2.9.3 err: path not found while resolving tree within virtual file system module - 'SRR1544031' cannot be found.

**Comment by kwrodarmer** [comment]
That's not enough information to go on. Please run
`test-sra SRR1544031`
and send the output to sra-tools@ncbi.nlm.nih.gov

**Comment by huangl07** [comment]
thank for replay so soon
I have already send the email

**Comment by benjaminfang** [comment]
I got same error too. any solution to this error?

**Comment by klymenko** [comment]
@huangl07 , @benjaminfang , was your issue fixed?
