### ISSUE TITLE
fasterq-dump -t option not working

### ISSUE THREAD

**Issue by psur9757** [ncbi/sra-tools#178]
I am trying to run fasterq-dump to get some datasets from SRA. I have been following the instructions here: https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump
 
Even though I specify a temp directory, it still creates the cache in home directory. Since home directory does not have enough space (<10G), the program gets terminated. I just need to know how to accurately specify the temporary directory, because the instructions are not working. Thank you.

PBS Script:
```
#! /bin/bash
#PBS -P WSRseq
#PBS -N fasterq_dump
#PBS -l select=1:ncpus=6:mem=48G
#PBS -l walltime=6:00:00
#PBS -q defaultQ
#PBS -o /scratch/WSRseq/barberry_rna_seq/run_outs/fasterq_dump_run.out
#PBS -e /scratch/WSRseq/barberry_rna_seq/run_outs/fasterq_dump_run.out

module load sratoolkit

fasterq-dump SRX4693477 -O /scratch/WSRseq/barberry_rna_seq/data -t /scratch/WSRseq/barberry_rna_seq/tmp
```

Error file
> 2019-02-12T23:56:13 fasterq-dump.2.9.2 err: unknown while writing file within file system module - unknown system error errno='Disk quota exceeded(122)'
> 2019-02-12T23:56:13 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:18 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:25 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely
> 2019-02-12T23:56:36 fasterq-dump.2.9.2 int: no error - skipping the cache-tee completely

I also tried `vdb-config -i` and `vdb-config -i --interactive-mode textual` and got a similar error.
> 2019-02-13T04:49:03 vdb-config.2.9.2 err: unknown while writing file within file system module - unknown system error errno='Disk quota exceeded(122)'

I can see the xml file when I just run `vdb-config` without any commands. For this part, I followed the instructions from https://github.com/ncbi/sra-tools/blob/master/README-vdb-config.

**Comment by psur9757** [comment]
I got help from our HPC facilities and sorted this out. Thank you.

Best,
Priyanka

**Comment by kpj** [comment]
I experienced the same problem and was able to resolve it by executing `vdb-config -i` and then setting the public cache directory to a location with more quota.

See https://github.com/ncbi/sra-tools/wiki/03.-Quick-Toolkit-Configuration and https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration for more information.
