### ISSUE TITLE
Trying to decrypt data using Windows

### ISSUE THREAD

**Issue by dps2501** [ncbi/sra-tools#18]
Hello,

I am using Windows 7 and have downloaded the SRA Toolkit version 2.5.4-win64.  I am trying to decrypt recently downloaded data.  I have also saved the decryption key to my desktop.  According to the instructions on the NCBI webpage I need to access vdb-config which I do but when I double click nothing appears.  How can I go about decrypting using the windows version of the toolkit?

Thank you

**Comment by kwrodarmer** [comment]
The SRA Toolkit is a command-line based tool suite today. You cannot double-click on the tools to launch a GUI application, but must run them within a command shell. Please see [First help on decryption dbGaP data](https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data)
