### ISSUE TITLE
timeout exhausted while reading file within network system module

### ISSUE THREAD

**Issue by zhxiaokang** [ncbi/sra-tools#180]
I'm downloading multiple fastq files from one study. So I'm using this command to download all the fastq files in this study (altogether 324 fastq files):
`esearch -db sra -query PRJNA381549 | efetch --format runinfo | cut -d ',' -f 1 | grep SRR | xargs fastq-dump`
I can see that it's downloading the files one by one. But I got this error from time to time (here I paste the first few lines):
```
Read 13615962 spots for SRR5412799
Written 13615962 spots for SRR5412799
Read 12845287 spots for SRR5412800
Written 12845287 spots for SRR5412800
Read 12944607 spots for SRR5412801
Written 12944607 spots for SRR5412801
2019-02-25T18:07:14 fastq-dump.2.9.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
Read 13083533 spots for SRR5412802
Written 13083533 spots for SRR5412802
```
But I have the files downloaded:
```
$ ll
total 89166396
-rw-r--r-- 1 XX YY 3826122752 Feb 25 16:38 SRR5412799.fastq
-rw-r--r-- 1 XX YY 3605004288 Feb 25 17:35 SRR5412800.fastq
-rw-r--r-- 1 XX YY 3634495488 Feb 25 18:25 SRR5412801.fastq
-rw-r--r-- 1 XX YY 3667918848 Feb 25 19:28 SRR5412802.fastq
```
(I'm doing this on a server where there's plenty space left on disk.)

Can I simply ignore this error? Or does it mean that some of my downloaded files are broken files? If yes, how can I know which one and I need to re-download them.

**Comment by frymor** [comment]
I have the same problem now. Did you get an answer / find a solution?
thanks

**Comment by zhxiaokang** [comment]
> I have the same problem now. Did you get an answer / find a solution?
> thanks

Unfortunately, I haven't got any answer to it. I just ignored that warning and didn't get any problem using those files.

**Comment by klymenko** [comment]
Yes, just ignore these warnings.

The last message indicates that the dump was successful:
```
Read 13083533 spots for SRR5412802
Written 13083533 spots for SRR5412802
```

You should not see such messages with the current release.

@zhxiaokang , do you have any other questions?
