### ISSUE TITLE
`fastq-dump` and `fasterq-dump` try to connect to internal Amazon EC2 address

### ISSUE THREAD

**Issue by paulmenzel** [ncbi/sra-tools#181]
With SRA Toolkit 2.9.4, running `fastq-dump -p SRR5077628` and `fasterq-dump -p SRR5077628`, according to strace it tries to connect the unreachable IP `169.254.169.254`.

    connect(3, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("169.254.169.254")}, 16

This eventually times out.

**Comment by kwrodarmer** [comment]
Yes - very sorry about that. We have prepared a new release that we expect to put out today to address this issue. Please stay tuned.

**Comment by klymenko** [comment]
Try release 2.9.4-1 from https://github.com/ncbi/sra-tools/wiki/Downloads

**Comment by paulmenzel** [comment]
On 03/04/19 18:49, Andrew Klymenko wrote:
> Try release 2.9.4-1 from https://github.com/ncbi/sra-tools/wiki/Downloads

Thanks, but my report is from the 2.9.4 release.

PS: It’d be very confusing if provided binaries do not agree with
the releases.

**Comment by klymenko** [comment]
Are you building the toolkit of download the binaries from our site?

**Comment by paulmenzel** [comment]
On 03/04/19 19:07, Andrew Klymenko wrote:
> Are you building the toolkit of download the binaries from our site?

(Sorry, I do not fully understand your question – did you mean *or*
instead of *of*?)

We download the source from the [releases page]
(https://github.com/ncbi/sra-tools/releases), and build that ourselves.

**Comment by klymenko** [comment]
Source code was updated.
Download the latest code from https://github.com/ncbi/ncbi-vdb/ and rebuild ncbi-vdb and sra-tools.

**Comment by paulmenzel** [comment]
On 03/04/19 19:30, Andrew Klymenko wrote:
> Source code was updated. Download the latest code from
> https://github.com/ncbi/ncbi-vdb/ and rebuild ncbi-vdb and
> sra-tools.

Thank you. I’ll do that tomorrow.

**Comment by paulmenzel** [comment]
Thank you, the issue was indeed fixed. Sorry for not reporting bug, and closing the issue myself. (GitHub allows referencing issues in commits though, so if you have

> Closes: https://github.com/ncbi/sra-tools/issues/181

in the commit message, then GitHub will automatically close the issue, once the commit is in the “master” branch.
