### ISSUE TITLE
fasterq-dump memory

### ISSUE THREAD

**Issue by juansearch** [ncbi/sra-tools#183]
I have a server with 512G RAM and 128 cores, wondering how many fasterq-dump processess I should run at once, and how many threads/ram should I assign to each. Any suggestions? I tried running 12 processes, each with 10 threads and 40 G ram but they were crashing. Seems to use more than the 40G
Is the memory limit per-thread or total for all threads? 
What is the suggested parallelization strategy?

**Comment by wraetz** [comment]
The memory limits are per thread – not cumulative.
My experience is that when you are running with more than 6 threads - the gain in speed is diminishing.
You are exhausting the IO-bandwith of the machine. ( lots of threads fighting to read from the same file ).
You also might get blacklisted at our perimeter as a DOS attempt if you are running too many processes in parallel.
You also have to take into consideration the amount of temporary space you need.
( fasterq-dump is trading speed for space. )
It is at least double the amount of the final output-file.
The final output-file is about 4-10 times the size of the input-file.
If you are using RAM-disk as temporary space ( the fastest solution ) it has to be big enough to take that.
The best strategy is to run one acccession at a time, but give it all of temp. space you can give.
I hope that helps.

More information is in this file:
https://github.com/ncbi/sra-tools/tree/master/tools/fasterq-dump
