### ISSUE TITLE
[Question(s)] API limits and/or blacklisting?

### ISSUE THREAD

**Issue by seandavi** [ncbi/sra-tools#185]
I noticed in #183 that there is mention of blacklisting based on parallel processes. That raises a few questions, then:

1. What are the usage limits and how does one discover them programmatically?
2. How would one determine that one is blacklisted?
3. What is the process for removing oneself from the blacklist?
4. On what basis is a single user identified (ie., multiple users might share an IP address based on proxy)?
5. If the answers to questions above are not documented, could they be codified somewhere?

Thanks!

**Comment by kwrodarmer** [comment]
We are going to try to move servers to avoid blacklisting.

**Comment by seandavi** [comment]
Thanks, @kwrodarmer, for the quick and authoritative response! That is useful to know.
