### ISSUE TITLE
How to check for 100% complete transfer and download?

### ISSUE THREAD

**Issue by anandksrao** [ncbi/sra-tools#189]
I have a general **QUESTION**:

How do I make sure that all my downloads of the SRA files for any given BioProject completed 100%? Is there a checksum or some other approach for such verification?

Could an SRATOOLS team member or experienced user please answer this question? Thanks!

Here is some additional context...

**1.** I wanted to download all of the SRA data for a certain BioProject 
from its corresponding NCBI BioProject link

**2.** For this BioProject, I downloaded its `SraRunTable.txt` and `SRR_Acc_List.txt` files.

**3.** From the latter, I set up my downloads like so:

```
PRJNA269201_SRR_Accession_List=PRJNA_ID_SRR_Acc_List.txt
SRR=$(cat $PRJNA_ID__SRR_Accession_List | head -n $SLURM_ARRAY_TASK_ID | tail -n 1)
parallel --verbose -j 144 prefetch {} ::: $SRR >>sra_download.log
```

and it completed on a compute cluster running SLURM queue management.

**4.** I then compared expected file size from column 5 of SraRunTable.txt versus observed file size from my downloaded files. However, there are some minor discrepancies, hence this email.

**5.** From STDERR and STDOUT files on my cluster, I don't think any of my downloads failed, unlike what has been reported in past issues here, e.g. [here](https://github.com/ncbi/sra-tools/issues/186). 

But on the same token, I am not entirely sure if 100% of the files were transferred. Hence this request for assistance about how to determine whether download was 100% complete.

**Comment by kdurbrow** [comment]
You can run our vdb-validate tool. For example:
vdb-validate --option-file PRJNA_ID_SRR_Acc_List.txt
This will verify the internal checksums for all of the accessions in your accession list file.

You can also validate one at a time. For example:
vdb-validate SRR000001
You can turn off referential integrity checks if you just want to verify the checksums. It could speed things up. For example:
vdb-validate -I no --option-file PRJNA_ID_SRR_Acc_List.txt

________________________________
