### ISSUE TITLE
item not found on CentOS6 with configured ./fastq-dump

### ISSUE THREAD

**Issue by DSLituiev** [ncbi/sra-tools#19]
I downloaded CentOS (64 bit) binaries and ran the configuration file to set the output directory. 

I ran

      ./bin/fastq-dump -X 5 -Z SRR390728
      2015-12-12T22:11:26 fastq-dump.2.5.5 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table

I was not sure whether this means a connection error. I tried to set the proxy to one which is used on that machine (`echo $ftp_proxy` same as `echo $http_proxy`), with no effect (the same error message).

Is it a connectivity issue?

**Comment by kwrodarmer** [comment]
If you are using a proxy, then you need to configure for proxy usage. See [Toolkit Configuration](https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration).
