### ISSUE TITLE
still get sra extension after fastq-dump

### ISSUE THREAD

**Issue by meishiue** [ncbi/sra-tools#191]
Hello, 

I am trying to download some Sra data using fastq-dump command from the SRA Toolkit. I use Ubuntu Linux 64 bit environment.

My command is : sratoolkit.2.9.6-ubuntu64/bin/fastq-dump --split-3 SRR1740062

I got the following message (NOT  Error message): 
	Read 21900245 spots for SRR1740062
	Written 21900245 spots for SRR1740062

However, there is only SRR1740062.sra (NOT fastq) in my output directory. 
Is someting wring with my command ? 

Thank you very much for your help.

**Comment by kwrodarmer** [comment]
The location of SRR1740062.sra is not the output directory. The fastq output files should be in your current (working) directory at the time you ran the command. The SRA file will remain in the cache.

**Comment by meishiue** [comment]
Yes, I find my fastq files in my current directory.
Thank you very much!
