### ISSUE TITLE
fasterq-dump error: concatenator.c

### ISSUE THREAD

**Issue by gnilihzeux** [ncbi/sra-tools#193]
`fasterq-dump.2.9.6 err: concatenator.c execute_concat_un_compressed() creating ouput-file  '/geneseed2/Data/PRJ801/106T/ERX070430/ERX070430_1.fastq' -> RC(rcExe,rcFile,rcPacking,rcName,rcExists)`
I hadn't found that why suffers this on the 2nd batch of data.
cpu process crash ?

**Comment by klymenko** [comment]
@gnilihzeux , do you still need help?

**Comment by gnilihzeux** [comment]
Er, I had forgot it. Thanks.

**Comment by durbrow** [comment]
If you are using the same ancient version of `fasterq-dump` as the original poster, please upgrade. If you are using the latest version, please create a new issue.
