### ISSUE TITLE
--stdout not working for fasterq-dump

### ISSUE THREAD

**Issue by will-rowe** [ncbi/sra-tools#195]
Hi,

I've been swapping my `fastq-dump` commands with `fasterq-dump`. The stdout functionality doesn't seem to be working.

This prints to STDOUT:
```
fastq-dump --stdout ERX168346
```

This doesn't print to STDOUT, it just writes the file to disk:
```
fasterq-dump --stdout ERX168346
```

Version:
fasterq-dump : 2.9.1 ( 2.9.1-1 )

**Comment by wraetz** [comment]
fasterq-dump is not a drop-in replacement for fastq-dump.
There are some differences regarding defaults and options.
The fact that stdout does not work is one of them.


For the full story see this file:

https://github.com/ncbi/sra-tools/blob/master/tools/fasterq-dump/readme.txt

**Comment by will-rowe** [comment]
Thanks for getting back to me.

I've read the info at the link you posted but the only reference to `--stdout` is that it doesn't work with `--split-3` and `--split-files` options. So should the example I posted not print to STDOUT as it doesn't use the `--split-3` and `--split-files` options?

I've also tried `--concatenate-reads --stdout`` but no luck either. Can you please recommend how to use fasterq-dump and print to STDOUT?

**Comment by wraetz** [comment]
Ok the readme-file is not precise enough about that. It has to be updated.
The full story is that fasterq-dump does not print to STDOUT at all.
We will also update the tool to not take the --stdout option any more and report an error instead.
The tool produces output into files only. Even if you force it to produce just one file.
You have to adjust your pipeline to pick up the produced file(s) and pipe it into other tools after that.

**Comment by will-rowe** [comment]
Ah - okay. Thanks for getting back to me.
