### ISSUE TITLE
blastn_vdb does not allow downloading full sequence of hits

### ISSUE THREAD

**Issue by austinreidmanny** [ncbi/sra-tools#198]
For formatting results, `blastn_vdb` allows “sseq” which will output the aligned portion of the reads. 

However there is no option that I can find which would allow fetching the entire read. 

So my resulting fasta has sequences ranging from 50 nt to 100 nt. I would love the option to just download the entire read (full 100 nt) for all of my hits. 

 I’m using blastn_vdb for the great increase in speed, but that does not give me access to the fastq, so taking the hit list and fetching the reads myself is not an option either.

**Comment by klymenko** [comment]
Please send this question to blast-help@ncbi.nlm.nih.gov

**Comment by austinreidmanny** [comment]
Email sent!

**Comment by klymenko** [comment]
@austinreidmanny, do you still need help?
