### ISSUE TITLE
Prefetch successfully downloads accession, followed by additional download/error/non-zero exit code

### ISSUE THREAD

**Issue by jaicher** [ncbi/sra-tools#199]
(sra-tools version 2.9.6 (downloaded binary))

I've been downloading some SRAs from GTEx using the `prefetch` tool. I have found that some of them persistently give an error on download. Specifically, the SRA file appears to download correctly, but an additional download is started which fails and returns an error. This doesn't seem like expected behavior and is inconvenient for pipelining where I want to be able to use a non-zero exit code to signal that the job failed and to delete the resulting output.

For example, using verbose for `SRR1399904`, I see the messages:

<pre>
# $ prefetch --verbose SRR1399904
{...} KClientHttpOpen {...} (x4 lines)
{...} 1) Downloading 'SRR1399904'...
{...} KClientHttpOpen {...} (2 lines, https URL -> path, 2 more lines, the path from 3 lines ago)
<b>{...} 1) 'SRR1399904' was downloaded successfully</b>
</pre>

Great, right? Except that it is immediately followed by:

<pre>
{...} KClientHttpOpen - connected from {...}
{...} KClientHttpOpen - verifying CA cert  (these 2 lines 20-ish times)
{...} 'SRR1399904' has 0 unresolved dependencies'
<b>{...} 1) Downloading 'SRR1399904'...</b>
{...} KClientHttpOpen {...} (x8-16)
<b>{...} int: file not found while opening file within network system module - failed to open file 'https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/sragap/SRR1399904.vdbcache?tic={...}'</b>
{...} (another url / more KClientHttpOpen stuff, 10-20 lines)
<b>{...} int: self NULL while reading file within network system module - Cannot KStreamRead: p????</b>
{...} https download failed
{...} 1) failed to download SRR1399904
</pre>

If I check in my `sra/` directory, I see that the file `SRR1399904.sra` exists. All the checks from `vdb-validate` are successful -- it appears to have downloaded successfully. If I run `prefetch` a second time (with the SRA file still there, the command returns successfully without error.

Again, the issue is that the fact that the SRA was downloaded successfully is buried further up in my output, and the error code suggests that my download failed -- so my pipeline manager deletes the SRA (which otherwise would have been just fine). Any idea why this happens -- is this normal behavior (and, if so, why?) or is this some unexpected bug?

Happy to provide additional details on request (i.e. the full log, etc.) if they are pertinent -- wanted to give a minimal example, especially with the highly redundant verbose output. Thank you!

**Comment by klymenko** [comment]
In case of SRR1399904 - prefetch downloads the run and all dependencies:
74 reference sequences and vdbcache.

prefetch skips download of already found files.

It will exit with 0 when all downloads were successful.
It will exit with non-0 when any download failed.

It means than after prefetch exits with non-0 -
run the same command again to try to download the missing files.
But don't remove already downloaded files.

Except that there are some bugs in prefetch.2.9.6 that cause impossibility to download vdbcache files.

I rolled back prefetch to 2.9.3 and published new SRA toolkit tarballs.
Download it and run prefetch again.

**Comment by YasaminRaziee** [comment]
Here when you utilized the `prefetch` SRR1399904, you give .sra format of file and for visibility of your file inclusion you need the .fastq format so just utilize ` fasterq-dump --split-files `SRR1399904
