### ISSUE TITLE
openssh key for ascp

### ISSUE THREAD

**Issue by indexofire** [ncbi/sra-tools#2]
when I use sratools in linux, it looks like the sratools is not update with the ascp settings. i.e when I `prefetch something`, it will use `asperaweb_id_dsa.putty` as private key. But I remember the new ascp connect program has changed to use `asperaweb_id_dsa.openssh ` in linux. So if I am not misunderstanding something, it should be a issue.

:)

**Comment by klymenko** [comment]
It was fixed in release 2.4.3.
