### ISSUE TITLE
Failing the test download

### ISSUE THREAD

**Issue by 9aren** [ncbi/sra-tools#20]
I downloaded sra-toolkit from sra website for 64bit Windows.
After extracting I tested it from bin folder:
sra-toolkit\bin> **fastq-dump --stdout -X 2 SRR390728**
but it throws error:
***2015-12-15T09:54:40 fastq-dump.2.5.5 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table***
also did:
**vdb-config --restore-defaults**
no use.
what may be the cause and how to get it working.

**Comment by klymenko** [comment]
Please run
test-sra SRR390728
and send the output to sra-tools@ncbi.nlm.nih.gov

**Comment by kwrodarmer** [comment]
Did this work for you, or is there still a problem?
