### ISSUE TITLE
Determine reference for reference-compressed SRA file 

### ISSUE THREAD

**Issue by standage** [ncbi/sra-tools#202]
I have 241 SRA files that appear to be reference compressed. I didn't even know this was a thing until I tried to convert them to Fastq files without an internet connection. I got the "name not found while resolving..." error described at the bottom of [this page](https://ncbi.github.io/sra-tools/fastq-dump.html) when I attempted to do the conversion.

The instructions say:

> *If you have elected to prevent the toolkit from contacting NCBI, you will need to manually acquire the reference(s) here*

We have many NCBI databases mirrored locally, including RefSeq, so it's likely that we already have all the references. I have two questions:

- How do I determine the reference used to compress a reference-compressed SRA file? (Note this needs to be scripted for 241 SRA files, so manual inspection is out of the question.)
- Once I've determined the correct reference and ensured it is available locally, how to I tell `fastq-dump` where to find it?

**Comment by suzannesctt** [comment]
I have the same question!  Did you ever get a response?

**Comment by kwrodarmer** [comment]
If you have refseq files stored in a shared local area, this is known as a _site repository_. Our system has historically maintained a notion of tri-level repository, where the closest level was a user's personal cache, then an institutional site-repository, and NCBI's remote archive was the farthest.

Such a configuration is useful, but rarely employed. For this reason, we have not provided support for it in the interactive/graphical mode of `vdb-config` but have encouraged site admins to write to us for specific instructions on how to hand-edit a site configuration file.

The fix involves installing files in `/etc/ncbi/` that are accessible to all tools and description of a site repository in a configuration file. If you have admin capabilities over such systems, this is possible.

For your own purposes, you can hand-edit your own configuration file under `$HOME/.ncbi/user-settings.mkfg` to add a similar entry. I will try to add some instructions in the Wiki.

**Comment by standage** [comment]
Hi @klymenko, has the wiki been updated as @kwrodarmer suggested in May? If so, could you provide a link to the relevant content? If not, could you please re-open this ticket to reflect its unresolved status?

**Comment by klymenko** [comment]
Run `align-info <accession>` to see the references used.
Run `prefetch </path/to/sra/file>` to download missed references.

**Comment by klymenko** [comment]
See [an example of configuration for centralized repository of RefSeq files](https://github.com/ncbi/sra-tools/issues/416#issuecomment-802946574).
