### ISSUE TITLE
problems in using tblastn_vdb to analyze bacteria genomes

### ISSUE THREAD

**Issue by zsutx2005** [ncbi/sra-tools#205]
Recently I download 3000 archae genomes and tens thounds of bacteria genomes with "prefetch",  and all genomes were deposited in the default location: /home/ncbi/public/wgs. 

: tblastn_vdb -query query.fas -db ~/ncbi/public/archae_wgs -out archae_wgs_result.out
I ran this script, and met an error, part of them were copied here

VDB: 2019-05-28T07:53:50 . int: file descriptor exhausted while opening directory within file system module - Error in VDBManagerOpenTableRead(MNKC01)
VDB: 2019-05-28T07:53:50 . int: file descriptor exhausted while opening directory within file system module - Error in VDBManagerOpenTableRead(MNKD01)
VDB: 2019-05-28T07:53:50 . int: file descriptor exhausted while opening directory within file system module - Error in VDBManagerOpenTableRead(MNKG01)
VDB: 2019-05-28T07:53:50 . int: file descriptor exhausted while opening directory within file system module - Error in VDBManagerOpenTableRead(MNKH01)
Error: Error opening the following db(s): FOTC01 FOTL01 FOUJ01 FOXI01 FOYN01 FOYS01 FOYT01 FOZK01 FOZS01 FQWV01 FRAN01 FRFC01 FTNO01 FTNP01 FTNR01 FUYK01 FWYE01 FXBN01 FZMP01 FZNK01 FZNQ01 JDTG01 JDTH01 JFZT01 JHUT02 JHWX01 JJOR01 JJOS01 JJOT01 JJOU01 JJOV01 JJOW01 JJOX01 JJOY01 JJOZ01 JJPA01 JJPB01 JJPC01 JJPD01 JJPE01 JJPF01 JJPG01 JJPH01 JJPI01 JJPJ01 JJPK01 JJPL01 JJPM01 JJPN01 JJPO01 JJPP01 JJPQ01 JJPR01 JJPS01 JJPT01 JJPU01 JJPV01 JJPW01 JJPX01 JJPY01 JJPZ01 JJQA01 JJQB01 JJQC01 JJQD01 JJQE01 JJQF01 JJQG01 JJQH01 JJQI01 JJQJ01 JJQK01 JJQL01 JJQM01 JJQN01 JJQO01 JJQP01 JJQQ01 JJQR01 JJQS01 JJQT01 JJQU01 JJQV01 JJQW01 JJQX01 JJQY01 JJQZ01 JJRA01 JJRB01

I don't know why.

previously, I can run the script with viruses_wgs, but now it also report an error, part of them were copied here 
tblastn_vdb -query query.fas -db /home/ncbi/public/viruses_wgs -num_threads 10 -out tblastn_viruses.out

VDB: 2019-05-28T08:08:21 . sys: timeout exhausted while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'sra-download.ncbi.nlm.nih.gov:443'
VDB: 2019-05-28T08:08:21 . err: timeout exhausted while creating file within network system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/wgs03/WGS/BA/KC/BAKC01.7'
VDB: 2019-05-28T08:08:21 . int: timeout exhausted while creating file within network system module - Error in VDBManagerOpenDBRead(BAKC01)
VDB: 2019-05-28T08:10:30 . sys: timeout exhausted while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'sra-download.ncbi.nlm.nih.gov:443'
VDB: 2019-05-28T08:10:30 . err: timeout exhausted while creating file within network system module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/wgs03/WGS/BA/KC/BAKC01.7'
VDB: 2019-05-28T08:15:02 . sys: timeout exhausted while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'sra-download.ncbi.nlm.nih.gov:443'

**Comment by klymenko** [comment]
@zsutx2005 , do you still need help?
