### ISSUE TITLE
Don't know how to install program in linux

### ISSUE THREAD

**Issue by ManuelMoradiellos** [ncbi/sra-tools#211]
Hi everyone,
I'm a student new to bioinformatics; I'm trying to install the program on Linux Mint but i cannot find any INSTALL executable in the extracted .tar, how do I continue?

Thanks in advance

**Comment by twohrdrive** [comment]
Hi Manuel,

There is no installation executable. Once you extract the contents of the .tar file, it should be ready to use.

The toolkit comes with a test you can run to make sure everything is working.  Have you tried that? If you're having trouble, try navigating in your terminal to the /bin/ directory of the extracted .tar file.  Then, run the fastq-dump test as explained for linux users in the manual.  You can read it here:

https://ncbi.github.io/sra-tools/install_config.html

**Comment by ManuelMoradiellos** [comment]
Thanks! Seems that I did something wrong, I reinstalled it and used that test method and now it works.
Thanks for the help
