### ISSUE TITLE
undefined reference to `VDBManagerMakeSRASchema'  Error when building from source

### ISSUE THREAD

**Issue by ltnetcase** [ncbi/sra-tools#212]
The version I built of sra_tools is 2.9.6, my env:

        centos 6.9 final kernel 2.6.32-696.6.3.el6.x86_64

So glibc version is lower than the binary tar ball requirement, I can only try to build the tools from source.

I build it using devtoolset-6(gcc 6.3.1) without any extra configure option,
After successful building of ngs-sdk and ncbi-vdb, when building sra_tools, the following error reported:

> make[3]: Entering directory '/home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/obj/tools/util'
gcc -static-libstdc++ -static-libgcc -o /home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/test-sra.2.9.6 -DNDEBUG -m64 PrintOS.o test-sra.o -L/home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/lib -L/home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/ilib -L/home/xxx/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib -L/home/xxx/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib -L/home/xxx/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib -Wl,-Bstatic -lkapp -ltk-version -lncbi-vdb -Wl,-Bdynamic -ldl -lpthread -lxml2 -Wl,-Bdynamic -lm
test-sra.o: In function ‘KMain':
test-sra.c:(.text+0x6ecc): undefined reference to `VDBManagerMakeSRASchema'
collect2: error: ld returned 1 exit status
/usr/local/repos/sra-tools/tools/util/Makefile:193: recipe for target '/home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/test-sra' failed
make[3]: *** [/home/xxx/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/test-sra] Error 1

Any suggestion would be appreciated.

**Comment by ltnetcase** [comment]
With inspecting with "nm", I found that the symbol  "VDBManagerMakeSRASchema" in libncbi-vdb is marked as undefined symbol. And I checked both dynamic and static libraries, the results are the same, both are undefined symbol.  Was it what we expected? Then how can I fix this problem then?

Thanks.

**Comment by kwrodarmer** [comment]
We don't have access to any system that old. I just tested it on a 7.2 system and was unable to duplicate your report. Tools built fine, `VDBManagerMakeSRASchema` is there.

At this point, the only suggestion is to move to a more current system, for what it's worth.

**Comment by ltnetcase** [comment]
Alright, thanks.
