### ISSUE TITLE
prefetch connection error

### ISSUE THREAD

**Issue by tdw1221** [ncbi/sra-tools#217]
Hi, I'm new to SRA tools and have followed the official guide to configure it with the key.  Now I'm experiencing connection issue when trying to download with prefetch:

I issued the prefetch command from the configured working directory as follow:

`../../sra_working/sratoolkit.2.9.6-1-ubuntu64/bin/prefetch --verbose SRR5790106`

or 

`../../sra_working/sratoolkit.2.9.6-1-ubuntu64/bin/prefetch SRR5790106`

And got the following error message:

**2019-08-16T18:47:07 prefetch.2.9.3 sys: error unknown while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'www.ncbi.nlm.nih.gov:443'
2019-08-16T18:48:08 prefetch.2.9.3 sys: error unknown while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'www.ncbi.nlm.nih.gov:443'
2019-08-16T18:48:08 prefetch.2.9.3 err: path not found while resolving tree within virtual file system module - 'SRR1273938' cannot be found.**

It seems there are two things going wrong: the connection failure and resolving virtual tree (not sure what this means). I've tried downloading using accession list files or with different accession numbers, but still getting exactly the same error. 

Thanks in advance

**Comment by CSuperlei** [comment]
I have the same problem, I can't deal with it.

**Comment by kwrodarmer** [comment]
Your configuration and toolkit are out of date.

Please upgrade to the latest software and update your configuration. If you continue to have this issue, then write back and we can take it from there.
