### ISSUE TITLE
vdb-validate not work with fasterq-dumped .fastq file

### ISSUE THREAD

**Issue by yhg926** [ncbi/sra-tools#218]
I use vdb-validate to check the completeness of .fastq file download by fasterq-dump. But return nothing even if the file download is apparently wrong(e.g. odd lines)

**Comment by osris** [comment]
vdb-validate is for SRA formatted files. it does not validate fastq. what is the accession that you have questions about?

**Comment by yhg926** [comment]
I see, thanks
