### ISSUE TITLE
New instance of SRA

### ISSUE THREAD

**Issue by SudheerAppana** [ncbi/sra-tools#22]
Hi all,
We are currently working on SRA tool. Our client need a separate instance to view the advancement in the project more or less like a sandbox. Could you please suggest the way to create a new instance.

Please do the needful. Kindly let me know if you need any further details.

Regards,
Sudheer

**Comment by kwrodarmer** [comment]
Yes, I think that we need many more details. You can post them here or send them to sra-tools@ncbi.nlm.nih.gov . From your description, I am unable to understand what it is you are asking for.

**Comment by seandavi** [comment]
@SudheerAppana, the normal way to create a new "instance" of code on github is to "fork" the repository.  Is this what you mean you'd like to do for your client?

**Comment by alanhoyle** [comment]
I think @SudheerAppana has the wrong project.  I received an email from him asking about SRA where that stands for "Security Risk Assessment" tool not the "Sequence Read Archive" tool.

**Comment by kwrodarmer** [comment]
Thanks!
