### ISSUE TITLE
faster-dump getting slow 

### ISSUE THREAD

**Issue by yhg926** [ncbi/sra-tools#223]
I have lots of accessions (nearly 200k) need to be download, fasterq-dump is very quick from the beginning (i download nearly 5000 files in first four days), but now it gets very slow now, and i can only download 30 files per day( the files sizes are similar with previous since i have shuffled the accessions list),  I am wondering if it is the problem of fasterq-dump or just NCBI limited the data transfer?

**Comment by klymenko** [comment]
We recommend to prefetch runs first.
