### ISSUE TITLE
Error occurs when running fastq-dump

### ISSUE THREAD

**Issue by huangxingnan1994** [ncbi/sra-tools#227]
Hi,
I was trying to convert SRA files to fastq files. When running fastq-dump command, it always reported errors. Error information is the attachment. 
[SRR6257336.txt](https://github.com/ncbi/sra-tools/files/3589331/SRR6257336.txt)
[SRR6257337.txt](https://github.com/ncbi/sra-tools/files/3589333/SRR6257337.txt)

**Comment by aboshkin** [comment]
The version of the toolkit you are running is 2.8.2, which is quite old. Please upgrade to the latest version (2.10.0), by using the links on this page: https://github.com/ncbi/sra-tools/wiki

**Comment by huangxingnan1994** [comment]
@aboshkin 
Hi guy,
I tried the version 2.9.6, it still reported another error

> 2012-01-13T07:17:55 fastq-dump.2.9.6 sys: connection not found while validating within network system module - Failed to Make Connection in KClientHttpOpen to 'www.ncbi.nlm.nih.gov:443'

and then the same error occured

> 2012-01-13T07:17:55 fastq-dump.2.9.6 err: connection not found while validating within network system module - failed ../geo/SRR6257337

**Comment by huangxingnan1994** [comment]
I tried the version 2.10.0, it displayed the error as following text.

[SRR6257337.txt](https://github.com/ncbi/sra-tools/files/3596494/SRR6257337.txt)
[SRR6257336.txt](https://github.com/ncbi/sra-tools/files/3596495/SRR6257336.txt)

**Comment by aboshkin** [comment]
The error messages state that he tool cannot find directory ../geo/SRR6257337, relative to the directory it is being run in. Can you verify that there is such a directory and it is not a file?

Also, it would help if you give us the full command line you are using to run fastq-dump.

**Comment by huangxingnan1994** [comment]
I ran `run_unpack.sh` to execute a bunch of files to `fastq-dump` at the same time. `do_unpack.sh` was used to execute the command.

![image](https://user-images.githubusercontent.com/53215509/64635304-ef9c6180-d431-11e9-8579-73276a5388ac.png)

**Comment by aboshkin** [comment]
Please check that this directory exists:
/public/home/xnhuang_gibh/4F/data/PM-...../Timecourse/geo/SRR6257337

To make sure fastq-dump is run from the correct directory, please add this line to do_unpack.sh, right after the line `echo "good"` :
`pwd; ls -l ../geo/*`

Then, run the script again ans post the output.

**Comment by huangxingnan1994** [comment]
good
../geo/SRR6257337
2012-01-13T10:25:59 fastq-dump.2.8.2 err: connection not found while validating within network system module - failed ../geo/SRR6257337

=============================================================
An error occurred during processing.
A report was generated into the file '/public/home/xnhuang_gibh/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================

good
../geo/SRR6257337
/public/home/xnhuang_gibh/4F/data/PM-YWGD190851-01clean_data/OT/Timecourse/geo
-rw-r--r-- 1 xnhuang_gibh dqpei        204 Sep 11 02:29 ../geo/do_unpack.sh
-rw-r--r-- 1 xnhuang_gibh dqpei        607 Sep 11 02:03 ../geo/run_unpack.sh
-rwxr-xr-x 1 xnhuang_gibh dqpei 4255938215 Sep  8 19:25 ../geo/SRR6257336
-rwxr-xr-x 1 xnhuang_gibh dqpei 6012927059 Sep  8 19:31 ../geo/SRR6257337
-rwxr-xr-x 1 xnhuang_gibh dqpei 4273204327 Sep  8 19:41 ../geo/SRR6257338
-rwxr-xr-x 1 xnhuang_gibh dqpei 5168604947 Sep  8 19:51 ../geo/SRR6257339
-rwxr-xr-x 1 xnhuang_gibh dqpei 4053654113 Sep  8 19:57 ../geo/SRR6257340
-rwxr-xr-x 1 xnhuang_gibh dqpei 4706167722 Sep  8 20:09 ../geo/SRR6257341.1
-rwxr-xr-x 1 xnhuang_gibh dqpei 3680924025 Sep  8 20:11 ../geo/SRR6257342
-rwxr-xr-x 1 xnhuang_gibh dqpei 3686040727 Sep  8 20:24 ../geo/SRR6257343
-rwxr-xr-x 1 xnhuang_gibh dqpei 3568995157 Sep  8 20:25 ../geo/SRR6257344
-rwxr-xr-x 1 xnhuang_gibh dqpei 4551459939 Sep  8 20:43 ../geo/SRR6257345
-rwxr-xr-x 1 xnhuang_gibh dqpei 4622298151 Sep  8 20:44 ../geo/SRR6257346.1
-rwxr-xr-x 1 xnhuang_gibh dqpei 4756951297 Sep  8 21:00 ../geo/SRR6257347
-rwxr-xr-x 1 xnhuang_gibh dqpei 4655113254 Sep  8 21:01 ../geo/SRR6257348
-rwxr-xr-x 1 xnhuang_gibh dqpei 4430314785 Sep  8 21:16 ../geo/SRR6257349
-rwxr-xr-x 1 xnhuang_gibh dqpei 5760885245 Sep  8 21:22 ../geo/SRR6257350
-rwxr-xr-x 1 xnhuang_gibh dqpei 4156381634 Sep  8 21:31 ../geo/SRR6257351
-rwxr-xr-x 1 xnhuang_gibh dqpei 4421576530 Sep  8 21:37 ../geo/SRR6257352
-rwxr-xr-x 1 xnhuang_gibh dqpei 5268768943 Sep  8 21:49 ../geo/SRR6257353
-rwxr-xr-x 1 xnhuang_gibh dqpei 4285352723 Sep  8 21:52 ../geo/SRR6257354
-rwxr-xr-x 1 xnhuang_gibh dqpei 3515284413 Sep  8 22:00 ../geo/SRR6257355
-rwxr-xr-x 1 xnhuang_gibh dqpei 4385979066 Sep  8 22:06 ../geo/SRR6257356
-rwxr-xr-x 1 xnhuang_gibh dqpei 4822097467 Sep  8 22:11 ../geo/SRR6257357
-rw------- 1 xnhuang_gibh dqpei        487 Jan 13  2012 ../geo/SRR.txt
-rw-r--r-- 1 xnhuang_gibh dqpei        189 Sep 11 02:08 ../geo/test.sh

../geo/fqs:
total 204046
-rw-r--r-- 1 xnhuang_gibh dqpei 208942844 Sep 11 02:29 SRR6257336.fastq.gz
-rw------- 1 xnhuang_gibh dqpei       613 Sep 11 02:47 SRR6257337.txt
-rw------- 1 xnhuang_gibh dqpei         0 Jan 13  2012 SRR6257338.txt
2019-09-10T18:47:03 fastq-dump.2.8.2 err: connection not found while validating within network system module - failed ../geo/SRR6257337

=============================================================
An error occurred during processing.
A report was generated into the file '/public/home/xnhuang_gibh/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================

**Comment by aboshkin** [comment]
Please add another line to your script, right after `ls -l ../geo/*`:
`hexdump -C -n 16 $inp`

Run the script again and send us the output.

**Comment by huangxingnan1994** [comment]
good
../geo/SRR6257337
/public/home/xnhuang_gibh/4F/data/PM-YWGD190851-01clean_data/OT/Timecourse/geo
-rw-r--r-- 1 xnhuang_gibh dqpei        227 Sep 11 09:12 ../geo/do_unpack.sh
-rw-r--r-- 1 xnhuang_gibh dqpei        607 Sep 11 02:03 ../geo/run_unpack.sh
-rwxr-xr-x 1 xnhuang_gibh dqpei 4255938215 Sep  8 19:25 ../geo/SRR6257336
-rwxr-xr-x 1 xnhuang_gibh dqpei 6012927059 Sep  8 19:31 ../geo/SRR6257337
-rwxr-xr-x 1 xnhuang_gibh dqpei 4273204327 Sep  8 19:41 ../geo/SRR6257338
-rwxr-xr-x 1 xnhuang_gibh dqpei 5168604947 Sep  8 19:51 ../geo/SRR6257339
-rwxr-xr-x 1 xnhuang_gibh dqpei 4053654113 Sep  8 19:57 ../geo/SRR6257340
-rwxr-xr-x 1 xnhuang_gibh dqpei 4706167722 Sep  8 20:09 ../geo/SRR6257341.1
-rwxr-xr-x 1 xnhuang_gibh dqpei 3680924025 Sep  8 20:11 ../geo/SRR6257342
-rwxr-xr-x 1 xnhuang_gibh dqpei 3686040727 Sep  8 20:24 ../geo/SRR6257343
-rwxr-xr-x 1 xnhuang_gibh dqpei 3568995157 Sep  8 20:25 ../geo/SRR6257344
-rwxr-xr-x 1 xnhuang_gibh dqpei 4551459939 Sep  8 20:43 ../geo/SRR6257345
-rwxr-xr-x 1 xnhuang_gibh dqpei 4622298151 Sep  8 20:44 ../geo/SRR6257346.1
-rwxr-xr-x 1 xnhuang_gibh dqpei 4756951297 Sep  8 21:00 ../geo/SRR6257347
-rwxr-xr-x 1 xnhuang_gibh dqpei 4655113254 Sep  8 21:01 ../geo/SRR6257348
-rwxr-xr-x 1 xnhuang_gibh dqpei 4430314785 Sep  8 21:16 ../geo/SRR6257349
-rwxr-xr-x 1 xnhuang_gibh dqpei 5760885245 Sep  8 21:22 ../geo/SRR6257350
-rwxr-xr-x 1 xnhuang_gibh dqpei 4156381634 Sep  8 21:31 ../geo/SRR6257351
-rwxr-xr-x 1 xnhuang_gibh dqpei 4421576530 Sep  8 21:37 ../geo/SRR6257352
-rwxr-xr-x 1 xnhuang_gibh dqpei 5268768943 Sep  8 21:49 ../geo/SRR6257353
-rwxr-xr-x 1 xnhuang_gibh dqpei 4285352723 Sep  8 21:52 ../geo/SRR6257354
-rwxr-xr-x 1 xnhuang_gibh dqpei 3515284413 Sep  8 22:00 ../geo/SRR6257355
-rwxr-xr-x 1 xnhuang_gibh dqpei 4385979066 Sep  8 22:06 ../geo/SRR6257356
-rwxr-xr-x 1 xnhuang_gibh dqpei 4822097467 Sep  8 22:11 ../geo/SRR6257357
-rw------- 1 xnhuang_gibh dqpei        487 Jan 13  2012 ../geo/SRR.txt
-rw-r--r-- 1 xnhuang_gibh dqpei        189 Sep 11 02:08 ../geo/test.sh

../geo/fqs:
total 407411
-rw-r--r-- 1 xnhuang_gibh dqpei 417188353 Sep 11 03:14 SRR6257336.fastq.gz
-rw------- 1 xnhuang_gibh dqpei       102 Sep 11 09:30 SRR6257337.txt
00000000  4e 43 42 49 2e 73 72 61  88 19 03 05 01 00 00 00  |NCBI.sra........|
00000010
2019-09-11T01:30:31 fastq-dump.2.8.2 err: connection not found while validating within network system module - failed ../geo/SRR6257337

=============================================================
An error occurred during processing.
A report was generated into the file '/public/home/xnhuang_gibh/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra@ncbi.nlm.nih.gov' for assistance.
=============================================================

**Comment by klymenko** [comment]
@huangxingnan1994 , do you still have problems?
