### ISSUE TITLE
 timeout exhausted while reading file within network

### ISSUE THREAD

**Issue by Shicheng-Guo** [ncbi/sra-tools#228]
Hi, 

Today, I meet a warning. I guess it is not an error since the downloading is continuing 

```
2019-09-09T18:04:31 fastq-dump.2.9.6 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
```
Thanks. 

Shicheng

**Comment by huangxingnan1994** [comment]
Hi Guo,

I had the same error yesterday. Do you solve this problem now?

Cheers,
Xingnan

**Comment by aboshkin** [comment]
@Shicheng-Guo , you are correct. The tools try to recover from network timeouts and if the tool continues after such a message, the message can be ignored.

@huangxingnan1994 , did the tool continue in your case?

**Comment by Shicheng-Guo** [comment]
> Hi Guo,
> 
> I had the same error yesterday. Do you solve this problem now?
> 
> Cheers,
> Xingnan

It is a warning, not an error, therefore, we don't need to do anything. 

Shicheng

**Comment by millerh1** [comment]
I had this error today with prefetch

**Comment by klymenko** [comment]
@millerh1, try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
We improved tolerance against network failures.
