### ISSUE TITLE
fasterq-dump -Z not work

### ISSUE THREAD

**Issue by yhg926** [ncbi/sra-tools#229]
here is an example:
fasterq-dump -Z did not anything, just print out usage information, i have test on other machines, it works, but failed on amazon EC2 instance, any reason? 

ubuntu@ip-172-31-89-138:~$ fasterq-dump -Z SRR5365387

Usage:
  fasterq-dump <path> [options]

Options:
  -o|--outfile                     output-file
  -O|--outdir                      output-dir
  -b|--bufsize                     size of file-buffer dflt=1MB
  -c|--curcache                    size of cursor-cache dflt=10MB
  -m|--mem                         memory limit for sorting dflt=100MB
  -t|--temp                        where to put temp. files dflt=curr dir
  -e|--threads                     how many thread dflt=6
  -p|--progress                    show progress
  -x|--details                     print details
  -s|--split-spot                  split spots into reads
  -S|--split-files                 write reads into different files
  -3|--split-3                     writes single reads in special file
  --concatenate-reads              writes whole spots into one file
  -Z|--stdout                      print output to stdout
  -f|--force                       force to overwrite existing file(s)
  -N|--rowid-as-name               use row-id as name
  --skip-technical                 skip technical reads
  --include-technical              include technical reads
  -P|--print-read-nr               print read-numbers
  -M|--min-read-len                filter by sequence-len
  --table                          which seq-table to use in case of pacbio
  --strict                         terminate on invalid read
  -B|--bases                       filter by bases
  -A|--append                      append to output-file
  -h|--help                        Output brief explanation for the program.
  -V|--version                     Display the version of the program then
                                   quit.
  -L|--log-level <level>           Logging level as number or enum string. One
                                   of (fatal|sys|int|err|warn|info|debug) or
                                   (0-6) Current/default is warn
  -v|--verbose                     Increase the verbosity of the program
                                   status messages. Use multiple times for more
                                   verbosity. Negates quiet.
  -q|--quiet                       Turn off all status messages for the
                                   program. Negated by verbose.
  --option-file <file>             Read more options and parameters from the
                                   file.

/home/ubuntu/tools/sratoolkit.2.10.0-ubuntu64/bin/fasterq-dump : 2.10.0

**Comment by durbrow** [comment]
Don't give -Z option to fasterq-dump. fasterq-dump won't work as you are expecting with SRR5365387; it will split the reads into separate fastq files.

fastq-dump will work as you are expecting with -Z to produce a single output to stdout.

You should consider what you are doing with the fastq. If you are going to pipe it into a program that splits the reads, you should let fasterq-dump do that. If you are going to pipe it directly into an aligner, it will almost certainly NOT produce the correct result, as any pairing between the reads will be lost.

**Comment by wraetz** [comment]
The commandline-options on fasterq-dump are not 100% the same as for fastq-dump.
The default for fasterq-dump is –split-3. And split-3 cannot output to stdout, because it creates up to 3 different output-streams.

The equivalent of “fastq-dump -Z SRR5365387” is “fasterq-dump -Z –split-spot SRR5365387”.

There are more things to watch out for. Please read the wiki at

https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump

**Comment by yhg926** [comment]
On amazon EC2 free instance, "fastq-dump -Z SRR5365387" works, but it is slow. i have also tried "fasterq-dump -Z –split-spot SRR5365387" it did not works. I am just wondering why the same command "fasterq-dump -Z –split-spot SRR5365387" works on my local machine, but not work(even not run, just print out usage) on another.

**Comment by klymenko** [comment]
`fasterq-dump`  does not have '-Z` option.
