### ISSUE TITLE
Issues with fastq-dump

### ISSUE THREAD

**Issue by tayabsoomro** [ncbi/sra-tools#230]
I need to download a dataset from SRA so I first got the list of accessions and ran prefetch command with `--option-file` option to get the .sra files for all of the accessions in the list. Then I wanted to convert those to FASTQ so I ran `fastq-dump` command for that. Here is the result:

```
[mts066@tux5 sra]$ fastq-dump.2.10.0 SRX1547590.sra --split-3
Read 14261298 spots for SRX1547590.sra
Written 14261298 spots for SRX1547590.sra
2019-09-10T14:29:19 fastq-dump.2.10.0 err: unknown while destroying file within file system module - unknown system error 'Input/output error(5)'
2019-09-10T14:29:19 fastq-dump.2.10.0 err: unknown while destroying file within file system module - unknown system error 'Input/output error(5)'
```

Any ideas as to what the issue is and how to fix it?

**Comment by aboshkin** [comment]
The tool is reporting an I/O error attempting to close a file at the end of its execution. While it may be hard to find out the exact reason for this error, chances are that the tool's work is done and the output FASTQ files are complete. Can you check whether the FASTQ outputs have been created?
