### ISSUE TITLE
error: fastq-dump, buffer insufficient 

### ISSUE THREAD

**Issue by bakerwm** [ncbi/sra-tools#231]
I failed to run `fastq-dump 2.10.0` for some `sra` files. 
To check whether the `sra` file is downloaded correctly, I've tried two commands to download the sra:  `prefetch` and `fastq-dump`. Also, I've tried different version of `sra-toolkits`: `2.8.2`, `2.9.2` and `2.10.0`.

after that, the errors remain not fixed.

I do not know why `fastq-dump` failed for some `sra` files, but works for others.

+ failed:     
  
  - SRR9158300  
  - SRR9158302  
  - SRR9158303  

+ success:

  - SRR7777549  
  - SRR7777550    

```bash

$ fastq-dump SRA/SRR9158298.sra

2019-09-11T13:24:44 fastq-dump.2.9.2 err: buffer insufficient while executing function within transform module - failed SRA/SRR9158298.sra

=============================================================
An error occurred during processing.
A report was generated into the file '/home/wangming/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================


```

**Comment by aboshkin** [comment]
@bakerwm, we are investigating. Meanwhile, you can help us by running `vdb-validate` on one of the failing files (e.g. `vdb-validate SRA/SRR9158298.sra`) and posting the output.

**Comment by bakerwm** [comment]
@aboshkin 

```
$ vdb-validate SRA/SRR9158298.sra

2019-09-11T16:37:23 vdb-validate.2.9.0 info: Database 'SRR9158298.sra' metadata: md5 ok
2019-09-11T16:37:23 vdb-validate.2.9.0 info: Table 'SEQUENCE' metadata: md5 ok
2019-09-11T16:37:23 vdb-validate.2.9.0 info: Column 'ALTREAD': checksums ok
2019-09-11T16:37:23 vdb-validate.2.9.0 err: binary large object corrupt while validating binary large object within database module - Column 'QUALITY': contains bad data
2019-09-11T16:37:23 vdb-validate.2.9.0 err: binary large object corrupt while validating binary large object within database module - Database 'SRR9158298.sra' check failed

```

**Comment by bakerwm** [comment]
I found, it works when I tried to convert a small part of the `SRA` file, using `-X` option of `fastq-dump`: 


```
$ fastq-dump -X 10 SRA/SRR9158298.sra
Read 10 spots for SRA/SRR9158298.sra
Written 10 spots for SRA/SRR9158298.sra

$ seqkit stat SRR9158298.fastq
file              format  type  num_seqs  sum_len  min_len  avg_len  max_len
SRR9158298.fastq  FASTQ   DNA         10    1,510      151      151      151

```

**Comment by aiskhakov** [comment]
Anatoly,

for that particular but I have a fix. I am working on propagating it to VDB.

Alexey Iskhakov
CoNtRaCtOr
====================================================
If I’m going to have a past, I prefer it to be multiple choice!
(c) The Joker

**Comment by bakerwm** [comment]
@aboshkin Thanks for your suggestion. The `*.sra` file is not correct.

The `.sra` file downloaded using `prefetch` or `fastq-dump` might not be correct (possible my network issue!?). Finally, I use `FTP` to download the previously failed `*.sra` files with no so fast speed, it is ok now.

**Comment by bakerwm** [comment]
issue fixed.

**Comment by apredeus** [comment]
I got the same issue with `SRR13997822` - while other 104 SRA files from the same dataset have processed normally. Here's the full error:

> 2023-01-07T12:38:56 fastq-dump.2.11.0 err: buffer insufficient while executing function within transform module - failed SRR13997822
> =============================================================
> An error occurred during processing.
> A report was generated into the file '/nfs/users/nfs_c/cellgeni-su/ncbi_error_report.txt'.
> If the problem persists, you may consider sending the file
> to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
> =============================================================
> fastq-dump quit with error code 3

The `vdb-validate` output seems to be OK: 

> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Database 'SRR13997822' metadata: md5 ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Table 'SEQUENCE' metadata: md5 ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'ALTREAD': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'NAME_FMT': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'QUALITY': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'READ': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'SPOT_GROUP': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'X': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'Y': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 warn: type unrecognized while validating database - Database 'SRR13997822' has unrecognized type 'NCBI:SRA:Illumina:db'
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Database 'SRR13997822' is consistent

Do you know what might be causing it? I've tried re-downloading the archive from both ENA and Amazon. Thanks!
