### ISSUE TITLE
ERROR when running fast-dump in HPC

### ISSUE THREAD

**Issue by cahuparo** [ncbi/sra-tools#232]
Hi, 

I am trying to run `fast-dump` using the HPC in my institution, please see below the job I prepared and the confirmation that `sra-toolkit` is installed:

`installed packages
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
openjdk@1.8.0_202-b08  perl@5.16.3  sra-toolkit@2.9.6`

The job:

```
#!/bin/csh

#BSUB -o out.%J
#BSUB -e err.%J 
#BSUB -W 120
#BSUB -n 4
#BSUB -J quicksra

time fastq-dump --split-files ERR392055
```
This is a simple job to confirm that it works. 

Now the **error**:

```
2019-09-13T12:53:51 fastq-dump.2.9.6 sys: timeout exhausted while creating file within network system module - Failed to Make Connection in KClientHttpOpen to 'trace.ncbi.nlm.nih.gov:443'
2019-09-13T12:53:51 fastq-dump.2.9.6 err: item not found while constructing within virtual database module - the path 'ERR392055' cannot be opened as database or table
```
Please help me figure this out! I have tried with different SRA files, try using `vdb-config --restore-defaults`. When I run it in my local computer it works. 

Thanks, 

Camilo

**Comment by klymenko** [comment]
Run first "prefetch ERR392055"
Then try fastq-dump.

**Comment by cahuparo** [comment]
Thanks Klymenko. I tried `prefetch` in a previous job and it did not work.

**Comment by charmichaeld** [comment]
The compute nodes on your HPC may only be on a local network and not have access to the internet as is the case with our HPC systems. If that is the case, you could run prefetch on the login node and then fastq-dump the .sra file on the compute node. Check with the HPC admin on compute node connectivity.

**Comment by cahuparo** [comment]
charmichaeld ! That was the reason. Thanks for the feedback. I appreciate that. Compute nodes don't have access to Internet.
