### ISSUE TITLE
Is it possible to keep the original sequence name when extracting with fasterq-dump 

### ISSUE THREAD

**Issue by YonkoBigMom** [ncbi/sra-tools#233]
Hi,

After converting sra files to fastq files using fasterq-dump, the fasta files look like this:

> @SRR2129314.1 1 length=83
> TAACCCTAACCCTAACCCTAACCCTTACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC
> +SRR2129314.1 1 length=83
> ?;=ACEEBDFCCEBBDBBDBCDBBD?AECCEBBDCBDBCDCBD?CDEADBD@DDE?=CEAF@BD:EB<CFCFF@=C>=C;>@B

It missed the original sequences' names. Back in fastq-dump, we can use _--origfmt_ option, but I couldn't find this option in fasterq-dump. 

Is there a way to work around?

Thanks

**Comment by kwrodarmer** [comment]
Correct. This format is not a part of fasterq-dump's interface. If you want the original names, and if they are still available within the run (they often are not), then you can use fastq-dump.

See https://github.com/ncbi/sra-tools/wiki/Read-Names for more information.

**Comment by YonkoBigMom** [comment]
Any chance the team can bring back the --origfmt option? It is a drawback for some analyses of WGS. Says you download the bam files (bwa aligned) from GDC, and you need to grep the raw reads in  fastq files (from dbGaP) for structural rearrangements analyses. This task is impossible without the original sequence name.

**Comment by kwrodarmer** [comment]
The option was never added to this tool, which is a new fastq extractor. The decision was taken because it complicates the tool to some extent _(and slows it down)_, and many runs do not contain the original read names.
