### ISSUE TITLE
error about extracting PE fastq files

### ISSUE THREAD

**Issue by kunUCSD** [ncbi/sra-tools#234]
Hi there,
I'm trying to use SRAtools to extract paired end fastq from SRR8427519 but failed. Could you check if I run some wrong codes, or there are some issues about the data? Thanks.
My SRAtoolkit version: sratoolkit.2.9.6-1-centos_linux64
This is the codes I'm running:
$fastq-dump --outdir 165 --gzip --skip-technical --readids --read-filter pass --split-3 --clip SRR8427519
I also tried the fasterq-dump:
$fasterq-dump SRR8427519 -O 165 --split-files
Both of them can only get 1 fastq file, they are not separated.

Best, Kun

**Comment by aboshkin** [comment]
Please email your question to sra-tools@ncbi.nlm.nih.gov

**Comment by klymenko** [comment]
@kunUCSD , was your issue resolved?
