### ISSUE TITLE
Next page link on 04.-Cloud-Credentials is incorrect

### ISSUE THREAD

**Issue by ianfore** [ncbi/sra-tools#235]
On the page at https://github.com/ncbi/sra-tools/wiki/04.-Cloud-Credentials
Amazon step 7
and 
Google step 8
have a Next Page link
The link for that page should be
https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration
It currently has a typo
https://github.com/ncbi/sra-tools/wiki/04.-Toolkit-Configuration

**Comment by kwrodarmer** [comment]
Thanks! It has been updated.

**Comment by ianfore** [comment]
Thanks for the fix!
