### ISSUE TITLE
prefetch issue ( path not found while resolving tree within virtual file system module)

### ISSUE THREAD

**Issue by Frogdong** [ncbi/sra-tools#236]
Hi, I am using CentOS7 and I am tring to download gtex sra data from dbGap. I configured sra-toolkit as the manual said (imported my .ngc file by vdb-config). And I downlaod a list of SRR number from dbGap file selector. I use prefetch to download the data. However, some of the SRR file can be download successfully, some can not. It will give the error like:
prefetch.2.9.3 err: path not found while resolving tree within virtual file system module - 'SRR8233106' cannot be found.
The version of sra-toolkit I use is 2.9.6. How can I deal with this problem? Many thanks!

**Comment by hinz1** [comment]
Same issue here: 

```
prefetch -L 5 -v -p 1 SRR3581889​

2019-10-17T12:19:41 prefetch.2.8.2 err: path not found while resolving tree within virtual file system module - 'SRR3581889​' cannot be foun
```

Slightly older version, but that doesn't seem to make a difference.

**Comment by hinz1** [comment]
``wget`` on the other hand can download the data just fine from https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos/sra-pub-run-1/SRR3581889/SRR3581889.1 so it obviously is there.

**Comment by kwrodarmer** [comment]
I cannot reproduce it, even with version 2.8.2.

> Slightly older version, but that doesn't seem to make a difference.
In this case, there was a big change between 2.9.x and 2.10 with regard to access having to do with cloud and storage rearrangements within NCBI. 2.10 is only available on Linux so far.

**Comment by kwrodarmer** [comment]
I had another problem with 2.8.2 that found the run but ran into timeouts during download. This is the most likely error with earlier versions. Version 2.10.0 has been reliable.

**Comment by kwrodarmer** [comment]
Since 2.10.0 is a Linux-only _(i.e. partial)_ release, current still points to 2.9.6. The download page does show 2.10, and its full URL is http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.0/sratoolkit.2.10.0-ubuntu64.tar.gz

**Comment by hinz1** [comment]
I'm very sorry, and if it's just a problem on my end, I can work around it with manual downloads,  but with 2.10 I get this: 

```
2019-10-18T08:39:52 prefetch.2.10.0: KClientHttpOpen - verifying CA cert 
2019-10-18T08:39:52 prefetch.2.10.0: KClientHttpOpen - connected from 'xxx.xxx.xxx.xxx' to sra-downloadb.be-md.ncbi.nlm.nih.gov (130.14.250.27) 
2019-10-18T08:39:52 prefetch.2.10.0: KClientHttpOpen - verifying CA cert 
2019-10-18T08:39:53 prefetch.2.10.0: 1) Downloading 'SRR3581889'...
2019-10-18T08:39:53 prefetch.2.10.0:  Downloading via https...
2019-10-18T08:39:53 prefetch.2.10.0: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos/sra-pub-run-1/SRR3581889/SRR3581889.1 -> /home/hinz1/ncbi/public/sra/SRR3581889.sra.tmp.19769.tmp
2019-10-18T08:39:53 prefetch.2.10.0: KClientHttpOpen - connected from 'xxx.xxx.xxx.xxx' to sra-downloadb.be-md.ncbi.nlm.nih.gov (130.14.250.25) 
2019-10-18T08:39:53 prefetch.2.10.0: KClientHttpOpen - verifying CA cert 
2019-10-18T08:53:20 prefetch.2.10.0 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos/sra-pub-run-1/SRR3581889/SRR3581889.1
2019-10-18T08:53:20 prefetch.2.10.0:  https download failed
2019-10-18T08:53:20 prefetch.2.10.0: 1) failed to download SRR3581889
```

**Comment by kwrodarmer** [comment]
In order for us to provide further assistance, we will need more in-depth information and so will have to take this offline. Please write to us at sra-tools@ncbi.nlm.nih.gov to start the process.

**Comment by outpaddling** [comment]
I'm getting the same with 2.9.6 on CentOS 7.

**Comment by klymenko** [comment]
@Frogdong , @hinz1 , @outpaddling, do you still have this issue?

**Comment by outpaddling** [comment]
I no longer have the krt files that triggered this, so I'm not sure.
I gave up on this approach and I'm now using Fusera to mount the directories in an AWS instance.  I also tried sratools on AWS but was getting permission denied on many SRRs.  Fusera appears to be abandoned and does not work properly on CentOS 8 (abysmal read throughput), so I worry that there may be no way to access the files in the near future.

**Comment by klymenko** [comment]
Sorry, use of Fusera to access SRA data is deprecated.

**Comment by outpaddling** [comment]
A few months ago, I was told that Fusera is still the only way to access restricted CRAM files in the cloud because sratools does not have the same authentication capabilities.  Should this be working with the latest sratools?

**Comment by kwrodarmer** [comment]
The answer is complicated today. Fusera has been deprecated as mentioned above, and the ability to access data within the cloud has been incorporated into the SRA Toolkit since the introduction of the 2.10 series (for over a year).

Since that time, CRAM files have been moved to offline storage, requiring specific requests to retrieve them. CRAMs from public access SRA can be retrieved using a web interface, while dbGaP is not currently accessible. We are currently working on adding offline support for both public and dbGaP access to the SRA Toolkit, which will be made available in the 2.11 series slated for early next year.

@skripche , can you give more information on how the user can access CRAM files today?

**Comment by outpaddling** [comment]
Alright, thanks for the info.  FYI, we're in the middle of a study that involves extracting allele info from ~2.5 petabytes of TOPMed CRAMs.  We've gotten through about half using Fusera on AWS and we'll need the ability to stream the rest of them over the next few months in order to complete the project.  I'd like nothing more than to stop using Fusera.  Building a pipeline that runs unattended using Fusera has been a game of Twister.

**Comment by klymenko** [comment]
Do you still need help?

**Comment by outpaddling** [comment]
Was the offline dbGaP access completed in time for 2.11?  I haven't had time to test sra-tools as a replacement for Fusera yet, but I will do that ASAP.  Thanks...

**Comment by klymenko** [comment]
Send your question about offline dbGaP access to sra-tools@ncbi.nlm.nih.gov
