### ISSUE TITLE
Specify read lengths for fastq-dump due to improper SRA parsing or submission

### ISSUE THREAD

**Issue by santiagorevale** [ncbi/sra-tools#237]
Hi there,

I've been experiencing issues when downloading data from SRA and then extracting the paired-end FastQ files.

For some reason, sometimes when data is being uploaded to SRA, the lengths for Reads 1 and 2 for Illumina sequencing files is wrongfully recorded. For the set of accession numbers I'm looking at, on the SRA website the read lengths are being shown incorrectly, so then `fastq-dump` dumps the FastQs improperly too.

So, would it be possible to specify to `fastq-dump` the read length for each paired end, or even each read when more than two (considering technical, indices, etc.)?

Any additional tip on how to deal with these files in the meantime would be much appreciated.

Here are some Run IDs to get some examples on what I'm saying:

[SRR7191896](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7191896): should be 26x100 bp, shown as 27x99 bp
[SRR7191900](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7191900): should be 26x100 bp, shown as 27x99 bp
[SRR7191916](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7191916): should be 151x151 bp, shown as 152x150 bp
[SRR7191920](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7191920): should be 151x151 bp, shown as 152x150 bp

Thank you very much in advance.

Cheers,
Santiago

**Comment by klymenko** [comment]
`fastq-dump` creates files from information recorded in sra files.
It it is wrong -  sra files was loaded incorrectly.
Submit your request to sra-tools@ncbi.nlm.nih.gov.
