### ISSUE TITLE
fasterq-dump hanging indefinitely

### ISSUE THREAD

**Issue by nickp60** [ncbi/sra-tools#238]
Hi, I am running into  a strange situation.  Sometimes, I end up with a fasterq-dump hanging, with the following message being repeated at the bottom of my log file:
```
2019-10-09T15:27:02 fasterq-dump.2.10.0: KQueuePop() : RC(rcPS,rcSemaphore,rcWaiting,rcTimeout,rcExhausted), store = 0
```
What is this referring to, and how can I fix it?

This was generated with the following command:
```
fasterq-dump ERR461570 -O ./ERR461570/ --split-files -vvv > download.log
```

**Comment by kwrodarmer** [comment]
Please send a detailed description of the problem to sra-tools@ncbi.nlm.nih.gov and we will try to diagnose it. Thank you.

**Comment by nickp60** [comment]
Hi @kwrodarmer ,
I definitely not trying to be difficult, and am very grateful to all the hard work by the folks @ncbi, but the benefit of GitHub issues is that when other people run into the same issue, they can see how to solve it.  Is there a reason that [so many of the Issues](https://github.com/ncbi/sra-tools/search?q=%22sra-tools%40ncbi.nlm.nih.gov%22&unscoped_q=%22sra-tools%40ncbi.nlm.nih.gov%22&type=Issues) are directed to be resolved via email?

**Comment by kwrodarmer** [comment]
Hi @nickp60,
The reason for this is that for cases when NCBI engineers intervene to debug, we often ask for information that generally should not be posted publicly. We won't know the nature of the problem until we get into it, and if that conversation occurs in public, then it's too late. Certainly the data are not confidential, the fact that you are accessing certain accessions is yours to reveal if that is not a problem, and general knowledge about what a user can do is fine to post in public.

**Comment by nickp60** [comment]
Update:  Emailed on the 11th, sent a followup email on the 15th, final heard back  on the 21st.  Here is the gist of the conversation:

```
From: NLM Support <nlm-support@nlm.nih.gov>
Date: Monday 21 October 2019 at 18:30
Subject: [Sra-tools] Download Hanging
 
Apologies for the late reply. Please see here for a description of common network and connection issues:
https://github.com/ncbi/sra-tools/wiki/Network-and-Connection-Errors

Are you using a linux operating system? What Run are you trying to download? Are you able to download the Run using fastq-dump (https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump)?

Thank you,
SRA Curator 

```

```
To: nlm-support@nlm.nih.gov
Subject: Re: case #CAS-XXX: Re: [Sra-tools] Download Hanging 

Hi ,
Yes, downloading with fastq-dump works.  The error I sent ”KCacheTeeFileReadFromRAM - RAM cache read error: RC(rcCont,rcVector,rcAccessing,rcItem,rcNotFound)” is not in the link you send. How can I avoid such errors in the future, apart from not using fasterq-dump?
 
```

```
Your temp directory may be out of space. You can try to change location of the temporary directory:
$fasterq-dump SRR000001 -O /mnt/big_hdd -t /tmp/scratch
```

 
 I was indeed downloading lots of data, so I'll assume that's the solution.

**Comment by danieldanciu** [comment]
Thanks for sharing the response, it was helpful!

**Comment by klymenko** [comment]
@nickp60 , was your issue resolved?

**Comment by nickp60** [comment]
@klymenko no unfortunately, that was the last I heard from them.  I'm sticking to fastq-dump :(

**Comment by klymenko** [comment]
@nickp60 , please try our latest 2.10.6 release.
We added lots of improvements.
