### ISSUE TITLE
fasterq-dump Permissions Error

### ISSUE THREAD

**Issue by DarioS** [ncbi/sra-tools#240]
I seem to have set up the key correctly, but I get an error about permissions.

```
/savona/nobackup/biostat/datasets$ vdb-config --import /savona/nobackup/biostat/keys/prj_17653.ngc /savona/nobackup/biostat/datasets/test/
/savona/nobackup/biostat/keys/prj_17653.ngc was imported.
Repository directory is: '/savona/nobackup/biostat/datasets/test'.

/savona/nobackup/biostat/datasets$ cd test/
/savona/nobackup/biostat/datasets/test$ fasterq-dump --split-spot --split-files --bufsize 4000MB --curcache 4000MB --mem 4000MB --outdir FASTQ --progress --print-read-nr SRR2701663
srapath.2.10.0 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR2701663' - Access denied - please request permission to access phs000452

error from srapath:
{
"CE-Token": null,
"responses": [
]}

```

Is there something else I should do? I use version 2.10.0. I notice that I can't load the dbGaP website at the moment, which often happens for various bioinformatics services on Mondays in Australia which are Sunday nights in USA and servers are offline for maintenance. For example, https://dbgap.ncbi.nlm.nih.gov/aa results in (after a couple of minutes)

> Secure Connection Failed

> An error occurred during a connection to dbgap.ncbi.nlm.nih.gov. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

> * Please contact the website owners to inform them of this problem.

Google and Bing search engine websites load immediately on the same computer in the same internet browser window.

**Comment by klymenko** [comment]
@DarioS, do you still need help?
