### ISSUE TITLE
v.2.10.0 tools do not report version

### ISSUE THREAD

**Issue by linsalrob** [ncbi/sra-tools#241]
With version 2.10.0, several of the tools do not report their version number. e.g. none of the following return or print anything.

```bash
fastq-dump --version
fastq-dump -V
fasterq-dump --version
fasterq-dump -V
```

**Comment by wanyuac** [comment]
On Ubuntu 18.04, I encountered the same issue with v2.10.0. There was no output from the command ```fastq-dump -V``` or ```fastq-dump --version```.

**Comment by klymenko** [comment]
@linsalrob , @wanyuac , do you still have this issue?

**Comment by linsalrob** [comment]
It works now!

Rob
