### ISSUE TITLE
prefetch script - Undefined subroutine &main::parseOptionFile called at .../prefetch line 1282.

### ISSUE THREAD

**Issue by prehensilecode** [ncbi/sra-tools#244]
Using 
- Perl 5.26.2
- sra-tools 2.10.0

Follow the example here: https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/#download-sequence-data-files-usi  and dowloaded the SraAccList.txt file

Run:
`    prefetch --option-file=SraAccList.txt
`
(Example on website does not use the "=" but I had to put it in to avoid an error in parsing command line options.)

Error message:
`    Undefined subroutine &main::parseOptionFile called at /my/location/bin/prefetch line 1282.
`
That subroutine does seem to be defined in the prefetch script at line 1186:
```
### \brief: parse the options file
###
### \param: filename
###
### \return: array of parsed arguments
sub parseOptionsFile($)
{
    my @rslt = ();
    my $string = '';
    {
        my $fh = IO::File->new($_[0]) or die "can't open option file $_[0]: $!";
        binmode $fh, ':utf8';
        $string = join '', $fh->getlines();
        close $fh;
    }
```

**Comment by prehensilecode** [comment]
If I leave off the "=":

```
$ prefetch --option-file SraAccList.txt
Use of uninitialized value $1 in substr at /myloc/bin/prefetch line 1280.
substr outside of string at /myloc/bin/prefetch line 1280.
Undefined subroutine &main::parseOptionFile called at /myloc/bin/prefetch line 1282.
```

**Comment by prehensilecode** [comment]
This is an error in `tools/driver-tool/sratools.pl`
* line 1186: `sub parseOptionsFile($)
* but all calls to the subroutine are `parseOptionFile`

**Comment by prehensilecode** [comment]
Pull request https://github.com/ncbi/sra-tools/pull/245 addresses this

**Comment by klymenko** [comment]
@prehensilecode , do you still have this issue?

**Comment by prehensilecode** [comment]
Just tested with "master" branch, and the issue is resolved. Thanks!
