### ISSUE TITLE
blastn_vdb - HTTP read failure

### ISSUE THREAD

**Issue by MyProgramWorks** [ncbi/sra-tools#247]
Hi, i'm getting the following error for some of the SRA files:
VDB: 2019-11-11T10:17:29 . info: HTTP read failure: URL="https://sra-download.ncbi.nlm.nih.gov/traces/sra74/SRR/009725/SRR9959083.vdbcache" status=404; tried 1/6 times for 0 milliseconds total
VDB: 2019-11-11T10:17:29 . info: HTTP read failure: URL="https://sra-download.ncbi.nlm.nih.gov/traces/sra74/SRR/009725/SRR9959083.vdbcache" status=404; tried 2/6 times for 5 milliseconds total
VDB: 2019-11-11T10:17:29 . info: HTTP read failure: URL="https://sra-download.ncbi.nlm.nih.gov/traces/sra74/SRR/009725/SRR9959083.vdbcache" status=404; tried 3/6 times for 15 milliseconds total
VDB: 2019-11-11T10:17:30 . info: HTTP read failure: URL="https://sra-download.ncbi.nlm.nih.gov/traces/sra74/SRR/009725/SRR9959083.vdbcache" status=404; tried 4/6 times for 30 milliseconds total

I've successfully ran blastn_vdb for several archives, but for all Illumina runs from PRJNA559933 the above problem pops up. I've tried getting them using both prefetch and wget, but for local files I get "Cannot get VDB column: /Mosquitoes/SRR9959056/SRR9959056.sra.SEQUENCE.ACCESSION"

I would be grateful if you could help with this error. Thanks.

**Comment by klymenko** [comment]
@MyProgramWorks , do you still have problems?

**Comment by MyProgramWorks** [comment]
Hi Andrew, I can't seem to find blastn_vdb in my installation of sra-toolkit: sra-tools-2.9.1_1, so can't say if the issue is still there.

**Comment by klymenko** [comment]
Please download our latest toolkit from (https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit)
