### ISSUE TITLE
fastq-dump v2.10.0 verbose mode does not work?

### ISSUE THREAD

**Issue by dariober** [ncbi/sra-tools#249]
Hi- The flag `-v/--verbose` in fastq-dump 2.10.0 gives me the following error:

```
fastq-dump -v SRR6676681
2019-11-12T09:55:18 fastq-dump.2.10.0 err: param incorrect while reading argument list within application support module - --verbose
```

Without `-v` it works.

EDIT: `fasterq-dump -v SRR6676681` also works so I guess we could/should just switch to `fasterq-dump` anyway?

**Comment by durbrow** [comment]
Thank you. We are aware of this problem. The code to fix it is already included in the next release.

**Comment by edgardomortiz** [comment]
The issue persists in version 2.10.7 for Linux, what version has the fix?

**Comment by klymenko** [comment]
I just tried 2.11.0 for Linux - both `fastq-` and `fasterq-` `dump` support `-v`.
