### ISSUE TITLE
prefetch.2.9.3: failed to download vdbcache

### ISSUE THREAD

**Issue by Syu1106** [ncbi/sra-tools#250]
when i used prefetch to download SRA file ,error occued:
![image](https://user-images.githubusercontent.com/56663195/69474176-b18bc880-0df8-11ea-9a7a-d41e1a2a8564.png)  
then i used vdb-validate:

 
![image](https://user-images.githubusercontent.com/56663195/69474203-12b39c00-0df9-11ea-95a1-8cbf2d928900.png)  
what can i do to solve the problem?

**Comment by klymenko** [comment]
@Syu1106 , do you still have this issue?
