### ISSUE TITLE
fasterq-dump 2.9.6 transient errors READ.len(50) != QUALITY.len(0) 

### ISSUE THREAD

**Issue by MikeAxtell** [ncbi/sra-tools#251]
Experienced some "transient" errors using fasters-dump (2.9.6) to get some reads.
An example call:
`fasterq-dump SRR1163504`
Errors:
`2019-12-03T21:20:24 fasterq-dump.2.9.6 err: row #18677761 : READ.len(50) != QUALITY.len(0) 
2019-12-03T21:20:24 fasterq-dump.2.9.6 err: cmn_iter.c cmn_read_uint8_array( #18677762 ).VCursorCellDataDirect() -> RC(rcNS,rcFile,rcReading,rcTransfer,rcIncomplete)`

I call these "transient" because if I re-run the same command, they don't necessarily re-occur. Using persistence, I was able to get the reads. 

But it does seem like some kind of issue. Could it be a network issue? Or some transient interruptions in SRA itself? Or a bug in fasterq-dump?

**Comment by klymenko** [comment]
@MikeAxtell , do you still need help?
