### ISSUE TITLE
fastq-dump error

### ISSUE THREAD

**Issue by hirokomatsui** [ncbi/sra-tools#254]
I'm trying to download RNA-Seq data under the project phs000424 which we have approved, and getting the following error.

> fastq-dump -O work  --gzip --split-files SRR8232120
2019-12-10T19:33:16 fastq-dump.2.8.2 err: item not found while constructing within virtual database module - the path 'SRR8232120' cannot be opened as database or table

What is the problem?
Best,
Hiroko

**Comment by kwrodarmer** [comment]
Hello @hirokomatsui,

The first issue is that your software is out of date. Please update your toolkit to version 2.9.6.

The next issue will be around configuration and file encryption. Please be certain you have read
https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data
If this does not answer your questions, please respond.

Also please note that dbGaP is modifying its access procedures, so we recommend that you continue to use version 2.9.6 of our software until the modification is complete. After that, the 2.10.x versions will be needed.

Finally, use of `fastq-dump` is no longe recommended - especially with the 'gzip' option. Instead, you should use `fasterq-dump`. See
https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump

**Comment by hirokomatsui** [comment]
Hello,

I’ve updated sra-tools and still have a problem:

(base) fl-hn1:~/ncbi/dbGaP-8959> fasterq-dump -V

fasterq-dump : 2.9.6

(base) fl-hn1:~/ncbi/dbGaP-8959> pwd
/frazer01/home/hiroko/ncbi/dbGaP-8959

(base) fl-hn1:~/ncbi/dbGaP-8959> fasterq-dump SRR8232120 -O /projects/GTEx_v8/data/download/work/191209
2019-12-10T23:34:51 fasterq-dump.2.9.6 err: invalid accession 'SRR8232120'

Any suggestion?
Thank you for your help. Best regards,
Hiroko

**Comment by hirokomatsui** [comment]
Hello @kwrodarmer,
Please let me know if there's any update.
Thank you!
Hiroko

**Comment by klymenko** [comment]
@hirokomatsui , do you still have problems?

**Comment by hirokomatsui** [comment]
No, I'm good. Thank you!
