### ISSUE TITLE
sra-tools compile fail "undefined reference to `JsonScan_yylex'"

### ISSUE THREAD

**Issue by ppricemun** [ncbi/sra-tools#257]
I get this error while compiling on REL x86_64 7.6
[buildadm@cm-a1-n004 sra-tools]$ ./configure --prefix=/admin/site-packages/sra-tools/2.10.0/x86_64/rhel/76/
Configuring SRA-TOOLS package
checking system type... Linux
checking OS distributor... Red
checking machine architecture... x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking whether g++ accepts -static-libstdc++... no
checking for QMake... no
checking for fuse library... no
checking for hdf5 library... no
checking for magic library... no
checking for xml2 library... yes
checking for ngs-sdk package...
	includes... ../ngs/ngs-sdk
	libraries... /home/buildadm/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
includes: /gpfs/home/buildadm/build/ncbi/ngs/ngs-sdk
libraries: /gpfs/home/buildadm/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
checking for ncbi-vdb package source files and build results...
	includes... ../ncbi-vdb
	src... ../ncbi-vdb
	libraries... /home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib
includes: /gpfs/home/buildadm/build/ncbi/ncbi-vdb/interfaces
sources: /gpfs/home/buildadm/build/ncbi/ncbi-vdb
libraries: /gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib
ilibraries: /gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib

configure: creating 'build/ld.linux.exe_cmd.sh'
configure: creating 'build/Makefile.config.linux.x86_64'
configure: creating 'Makefile.config'
configure: creating 'reconfigure'
build type: release
build prefix: /home/buildadm/ncbi-outdir/sra-tools
build output path: /home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel
includedir: /admin/site-packages/sra-tools/2.10.0/x86_64/rhel/76/include
bindir: /admin/site-packages/sra-tools/2.10.0/x86_64/rhel/76/bin
libdir: /admin/site-packages/sra-tools/2.10.0/x86_64/rhel/76/lib
CC = gcc -c
CPP = g++
configured with: "'--prefix=/admin/site-packages/sra-tools/2.10.0/x86_64/rhel/76/'"
[buildadm@cm-a1-n004 sra-tools]$ c++
c++: fatal error: no input files
compilation terminated.
[buildadm@cm-a1-n004 sra-tools]$ make
make[1]: Entering directory `/gpfs/home/buildadm/build/ncbi/sra-tools/shared'
make[2]: Entering directory `/gpfs/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/obj/shared'
make[2]: Nothing to be done for `/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/std'.
make[2]: Leaving directory `/gpfs/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/obj/shared'
make[1]: Leaving directory `/gpfs/home/buildadm/build/ncbi/sra-tools/shared'
make[1]: Entering directory `/gpfs/home/buildadm/build/ncbi/sra-tools/tools'
make[2]: Entering directory `/gpfs/home/buildadm/build/ncbi/sra-tools/tools/util'
make[3]: Entering directory `/gpfs/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/obj/tools/util'
gcc -static-libgcc -o /home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/rcexplain.2.10.0 -DNDEBUG -m64 rcexplain.o -L/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/lib -L/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/ilib -L/gpfs/home/buildadm/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib -L/gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib -L/gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib -Wl,-Bstatic -lkapp -ltk-version -lncbi-vdb -Wl,-Bdynamic -ldl -lpthread -lxml2 -Wl,-Bdynamic -lm
/gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib/libncbi-vdb.a(klib-json.pic.o): In function `KJsonValueMake':
json.c:(.text+0x5cf): undefined reference to `JsonScan_yylex_init'
json.c:(.text+0x630): undefined reference to `JsonScan_yylex_destroy'
/gpfs/home/buildadm/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib/libncbi-vdb.a(klib-json-grammar.pic.o): In function `Json_parse':
json-grammar.c:(.text+0x1063): undefined reference to `JsonScan_yylex'
collect2: error: ld returned 1 exit status
make[3]: *** [/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/rcexplain] Error 1
make[3]: Leaving directory `/gpfs/home/buildadm/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/obj/tools/util'
make[2]: *** [std] Error 2
make[2]: Leaving directory `/gpfs/home/buildadm/build/ncbi/sra-tools/tools/util'
make[1]: *** [util] Error 2
make[1]: Leaving directory `/gpfs/home/buildadm/build/ncbi/sra-tools/tools'
make: *** [tools] Error 2

**Comment by aboshkin** [comment]
Please post the output of `ls -lt ../ncbi-vdb/libs/klib`

**Comment by ppricemun** [comment]
Thanks for responding so fast. Please see below

[buildadm@cm-a1-n004 sra-tools]$ ls -lt ../ncbi-vdb/libs/klib
total 2031
-rw-r----- 1 buildadm 529      0 Dec 13 12:25 json-lex.c
-rw-r----- 1 buildadm 529   2651 Dec 13 12:25 json-tokens.h
-rw-r----- 1 buildadm 529  55368 Dec 13 12:25 json-grammar.c
-rw-r----- 1 buildadm 529   5695 Dec 13 12:25 json-grammar.output
-rw-r----- 1 buildadm 529  19271 Dec 13 10:34 writer.c
-rw-r----- 1 buildadm 529   5209 Dec 13 10:34 writer-priv.h
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 win
-rw-r----- 1 buildadm 529  26679 Dec 13 10:34 vlen-encode.c
-rw-r----- 1 buildadm 529  19767 Dec 13 10:34 vector_namelist.c
-rw-r----- 1 buildadm 529  17370 Dec 13 10:34 vector.c
-rw-r----- 1 buildadm 529  32541 Dec 13 10:34 utf8.c
-rw-r----- 1 buildadm 529  25918 Dec 13 10:34 unpack.c
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 unix
-rw-r----- 1 buildadm 529   4802 Dec 13 10:34 trieval.c
-rw-r----- 1 buildadm 529  41478 Dec 13 10:34 trie.c
-rw-r----- 1 buildadm 529   6524 Dec 13 10:34 trie-priv.h
-rw-r----- 1 buildadm 529  34394 Dec 13 10:34 token.c
-rw-r----- 1 buildadm 529   1359 Dec 13 10:34 time.c
-rw-r----- 1 buildadm 529  28979 Dec 13 10:34 text.c
-rw-r----- 1 buildadm 529  20496 Dec 13 10:34 symtab.c
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 sun
-rw-r----- 1 buildadm 529  12409 Dec 13 10:34 status.c
-rw-r----- 1 buildadm 529   5067 Dec 13 10:34 status-rc.c
-rw-r----- 1 buildadm 529   1521 Dec 13 10:34 status-rc-strings.c
-rw-r----- 1 buildadm 529   8648 Dec 13 10:34 sra-release-version.c
-rw-r----- 1 buildadm 529  25155 Dec 13 10:34 report-klib.c
-rw-r----- 1 buildadm 529   1640 Dec 13 10:34 release-vers.h
-rw-r----- 1 buildadm 529  16300 Dec 13 10:34 refcount.c
-rw-r----- 1 buildadm 529   1442 Dec 13 10:34 rc-tbl.c
-rw-r----- 1 buildadm 529   1520 Dec 13 10:34 rc-idx-tbl.c
-rw-r----- 1 buildadm 529  11736 Dec 13 10:34 qsort.c
-rw-r----- 1 buildadm 529  62919 Dec 13 10:34 ptrie.c
-rw-r----- 1 buildadm 529  33561 Dec 13 10:34 ptpersist.c
-rw-r----- 1 buildadm 529   7090 Dec 13 10:34 progressbar.c
-rw-r----- 1 buildadm 529 109131 Dec 13 10:34 printf.c
-rw-r----- 1 buildadm 529   9580 Dec 13 10:34 pbstree.c
-rw-r----- 1 buildadm 529   1358 Dec 13 10:34 pbstree-swapped.c
-rw-r----- 1 buildadm 529  18026 Dec 13 10:34 pbstree-priv.h
-rw-r----- 1 buildadm 529   1358 Dec 13 10:34 pbstree-native.c
-rw-r----- 1 buildadm 529  21645 Dec 13 10:34 pbstree-impl.c
-rw-r----- 1 buildadm 529  13912 Dec 13 10:34 pack.c
-rw-r----- 1 buildadm 529   6080 Dec 13 10:34 out.c
-rw-r----- 1 buildadm 529  32307 Dec 13 10:34 num-gen.c
-rw-r----- 1 buildadm 529   4307 Dec 13 10:34 namelist.c
-rw-r----- 1 buildadm 529  14119 Dec 13 10:34 md5.c
-rw-r----- 1 buildadm 529   2343 Dec 13 10:34 maybeswap.h
-rw-r----- 1 buildadm 529  29039 Dec 13 10:34 log.c
-rw-r----- 1 buildadm 529   2445 Dec 13 10:34 log-priv.h
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 linux
-rw-r----- 1 buildadm 529   3498 Dec 13 10:34 ksort.c
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 judy
-rw-r----- 1 buildadm 529  56866 Dec 13 10:34 judy-vector.c
-rw-r----- 1 buildadm 529  27282 Dec 13 10:34 json.c
-rw-r----- 1 buildadm 529   1977 Dec 13 10:34 json-priv.h
-rw-r----- 1 buildadm 529   4132 Dec 13 10:34 json-lex.l
-rw-r----- 1 buildadm 529   2059 Dec 13 10:34 json-lex.h
-rw-r----- 1 buildadm 529   5418 Dec 13 10:34 json-grammar.y
-rw-r----- 1 buildadm 529   5155 Dec 13 10:34 iso8859.c
-rw-r----- 1 buildadm 529   2070 Dec 13 10:34 iso8859-1.c
-rw-r----- 1 buildadm 529  21069 Dec 13 10:34 hashtable.c
-rw-r----- 1 buildadm 529  26154 Dec 13 10:34 hashfile.c
-rw-r----- 1 buildadm 529   8401 Dec 13 10:34 debug.c
-rw-r----- 1 buildadm 529  20214 Dec 13 10:34 data-buffer.c
-rw-r----- 1 buildadm 529  30538 Dec 13 10:34 crc32.c
-rw-r----- 1 buildadm 529   3322 Dec 13 10:34 cp1252.c
-rw-r----- 1 buildadm 529  38967 Dec 13 10:34 container.c
-rw-r----- 1 buildadm 529  52632 Dec 13 10:34 btree.c
-rw-r----- 1 buildadm 529   7385 Dec 13 10:34 bstpersist.c
-rw-r----- 1 buildadm 529   2966 Dec 13 10:34 bsearch.c
drwxr-x--- 2 buildadm 529   4096 Dec 13 10:34 bsd
-rw-r----- 1 buildadm 529  16043 Dec 13 10:34 base64.c
-rw-r----- 1 buildadm 529   1704 Dec 13 10:34 all-vdb-version.c
-rw-r----- 1 buildadm 529   8777 Dec 13 10:34 SHA-64bit.c
-rw-r----- 1 buildadm 529   9280 Dec 13 10:34 SHA-32bit.c
-rw-r----- 1 buildadm 529   4417 Dec 13 10:34 Makefile
-rw-r----- 1 buildadm 529  28476 Dec 13 10:34 Judy.h

**Comment by aboshkin** [comment]
Please checkout ../ncbi-vdb/libs/klib/json-lex.c and rebuild ncbi-vdb. then rebuild sra-tools.

**Comment by ppricemun** [comment]
Same error :( Please let me know if you need more info. Thanks again for your help.

**Comment by ppricemun** [comment]
My apologies... seems like I did not clean my build dir and it caused the build to fail. Seems like after make clean's it works. Thanks for your help.
