### ISSUE TITLE
sratoolkit 2.10.0 issue downloading dbGap data with fasterq-dump

### ISSUE THREAD

**Issue by jplaverdure** [ncbi/sra-tools#259]
Hello,

My key is imported in vdb-config and I can download files when using sratoolkit 2.8.0 (using fastq-dump) but when trying to download a file with 2.10.0, I get the following error:
```
%> fasterq-dump -v SRR1079830
2019-12-16T20:53:10 srapath.2.10.0 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR1079830' - Access denied - please request permission to access phs000424 / GRU in dbGaP ( 403 )
error from srapath:
{
"CE-Token": null,
"responses": [
]}
```

Could you please point me to the appropiate documentation or help me resolve this error ?
Thank you.

**Comment by kwrodarmer** [comment]
For the moment, it's best to use version 2.9.6 to access dbGaP data. We will be releasing 2.10.2 very soon, and it is the first in the 2.10.x series to handle dbGaP.

The 2.10.2 release will be accompanied with documentation in our Wiki and on NCBI web pages TBD, and involves some changes.

So again, for today, please revert to 2.9.6 and use the NGC file and follow instructions that exist. This will get you access to phenotype data and ETL'd SRA runs.
