### ISSUE TITLE
Got retrieved a xml report 

### ISSUE THREAD

**Issue by Caro-Ca** [ncbi/sra-tools#260]
Hi!
what does it mean to get retrieved a .xml report?? The exact filename is ncbi_error_report.xml, and the SRA file got downloaded. How can I check if the file downloaded completely?  
Thank you in advance for your help!

**Comment by klymenko** [comment]
@Caro-Ca , generation of ncbi_error_report.xml means that there was a failure.

**Comment by Caro-Ca** [comment]
I already solved the problem. Thank you.
