### ISSUE TITLE
Problem to download protected data

### ISSUE THREAD

**Issue by m-kouhsar** [ncbi/sra-tools#262]
I have an account in NCBI and access to protected data in SRA.

I tried to test the SRA configuration to download the data on my laptop at my home. I downloaded the repository key file and followed the protected data user guide. it was worked properly.

Now I am trying to download the data in my lab on a server with the same configuration (previously tested on the laptop). but this error is occurred (attached image):

"query unauthorized while resolving query within virtual file system module-failed to resolve accession "SRR6677691"-Access denied-please request permission to access phs000676/GRU-MDS in dbGaP (403)"

please help me to resolve this problem.

**Comment by klymenko** [comment]
@m-kouhsar , do you still have problems?

**Comment by m-kouhsar** [comment]
> @m-kouhsar , do you still have problems?
Yes. I successfully downloaded 6 data file. But for the others I still have problems.

**Comment by klymenko** [comment]
@m-kouhsar , email your questions about access to protected data to sra-tools@ncbi.nlm.nih.gov

**Comment by m-kouhsar** [comment]
> @m-kouhsar , email your questions about access to protected data to [sra-tools@ncbi.nlm.nih.gov](mailto:sra-tools@ncbi.nlm.nih.gov)

Ok. Thanks
