### ISSUE TITLE
sratoolkit configuration for ubuntu HPC cluster

### ISSUE THREAD

**Issue by DenisGoryunov** [ncbi/sra-tools#263]
Hi,
I've locally installed (i.e. downloaded and extracted from tarball) sratoolkit.2.10.0-ubuntu64  to my home directory on HPC cluster. I'd like to re-confirm if my configuration is correct:
-[X]Enable Remote Access
-[X]enable local file-caching
-prefetch downloads  to :
(*)current working directory

Am i right or i've missed something?

Many thanks,
Denis

**Comment by klymenko** [comment]
@DenisGoryunov , you configuration looks good.
Do you have any issues?

**Comment by DenisGoryunov** [comment]
No. It works fine. Thank you.
