### ISSUE TITLE
Wide character in subroutine entry error in sratools info on run

### ISSUE THREAD

**Issue by thondeboer** [ncbi/sra-tools#265]
I got an error in sratools info when trying to get info on a specific run, not on others.
Similar to #248 

PROBLEM:
$ sratools info SRR3714631
Wide character in subroutine entry at /opt/sratoolkit/bin/sratools line 764.

NO PROBLEM:
$ sratools info SRR390728
Runs matching SRR390728: 2

Sample    : SRS212581 
Organism  : taxid=9606 Homo sapiens
Study     : SRP020237 CGCI: Non-Hodgkin Lymphoma (NHL)
Submitter : SRA039051 BCCAGSC
Experiment: SRX079566 RNA-Seq (polyA+) analysis of DLBCL cell line HS0798
Run       : SRR292241
Run       : SRR390728

I know this is a UTF error in some perl command and I understand that you are going to retire PERL (YAY!) but since I am not sure when this retirement happens, thought I report it here.

**Comment by kwrodarmer** [comment]
We are evaluating a release candidate for 2.10.2 which has retired perl, so the release is imminent.

**Comment by klymenko** [comment]
@thondeboer, do you still have this issue?
