### ISSUE TITLE
Not able to extract per cell data from smart-seq2 data

### ISSUE THREAD

**Issue by jvikkula** [ncbi/sra-tools#266]
Best SRA team,

We were granted an access to phs001680.v1.p1 data from dbGap. I downloaded all the scRNAseq (Smart-seq2) files with prefetch command and I have been trying to convert the SRA files to either FASTQ files (using fastq-dump) or BAM files (using sam-dump and samtools), but I have not been able perform this step as I hoped. Finally, I would like to use RNA Velocyto to count the exonic and the intronic reads.

I understood that each file contains data from multiple cells and thus, I would need some kind of identifiers to specify the cell of origin for each read. However, I am not able detect any identifiers in FASTQ or in BAM files and that's why also RNA Velocyto counts that all the reads come from one cell. 

Ideally, I would like to split the SRA files to "one file per cell". How should I modify my commands? For now, I have been using following commands to download and convert to BAM files:

`prefetch my_cart_file.cart`
`sam-dump my_sra_file.sra | samtools view -bS -@ 6 -m 2G - > my_bam_file.bam`

Thanks for your help!

-Johanna

**Comment by arshiyaakeel** [comment]
Hello Johanna, 
Could you manage to split the SRA files to "one file per cell"?
I am struggling with same phs001680.v1.p1 data from dbGap. Any help will be highly appreciated.
Thank you.
Best
Arsh

**Comment by lapointr** [comment]
If the cell information is preserved in the read group then you can split the phs001680 Runs into separate fastq files using fastq-dump with -G flag: 
$ fastq-dump -G --split-files SRR9611283

or split the sam-dump'ed bam with samtools split flag
$ samtools split SRR9611283.bam

If the cell information isn't in the read group then you may be able to download the original files with the SRA toolkit in a Google or Amazon cloud instance. 
$ prefetch --type all SRR# 

Please write to sra@ncbi.nlm.nih.gov , and reference this case, for additional options

**Comment by klymenko** [comment]
@jvikkula, do you need more help?

**Comment by tkarginov** [comment]
@klymenko
Hi! I am actually working with the same phs001680.v1.p1 dataset and am running into the same issue as the original author. I tried to run fasterq-dump with --split-files on one of the SRR files and still ended up with 2 fastq files. Per the reported study they combined all Smartseq2 libraries as expected and sequenced - and contacting the author of the study apparently all FASTQ files were deposited for individual cells. However, each "tumor site" has only 2 FASTQ files and I still can't seem to find any identifiers or reference for these sets. Any insight on what else could help/what I'm missing?
Thanks very much!
Tima

**Comment by klymenko** [comment]
@tkarginov, open a new issue.
