### ISSUE TITLE
error from srapath when using fastq-dump

### ISSUE THREAD

**Issue by solo7773** [ncbi/sra-tools#267]
System: Ubuntu 16.04.6 LTS

SRA toolkit version 2.10.0

perl v5.22.1

**fastq-dump gets error**

"*********** LOG 1***********"

`sratoolkit.2.10.0-ubuntu64/bin/fastq-dump -X 5 -Z SRR390728`

>error from srapath:

>Error: RC(rcVFS,rcQuery,rcExecuting,rcConnection,rcUnexpected)

"****************************"

**prefetch does not download file**

"*********** LOG 2***********"

`sratoolkit.2.10.0-ubuntu64/bin/prefetch -X 1024 -v -O ncbi/files/ SRR390728`

>2020-01-14T02:59:55 prefetch.2.10.0: KClientHttpOpen - connected from '172.18.4.138' to trace.ncbi.nlm.nih.gov (130.14.29.113) 

>2020-01-14T02:59:56 prefetch.2.10.0: KClientHttpOpen - verifying CA cert

"****************************"

**Comment by klymenko** [comment]
@solo7773 , do you still have this issue?

**Comment by solo7773** [comment]
> @solo7773 , do you still have this issue?

I think so (not very sure). I solved the problem by downgrading to 2.9.6. I noticed there are minor updates of 2.10 after this thread, but to my experience 2.9.6 is more stable.

**Comment by klymenko** [comment]
@solo7773 , please try 2.10.7 release.

**Comment by elbakrifz** [comment]
I still have the same prob when I run with : astq-dump --split-files ERR013300
2020-07-04T12:30:58 srapath.2.10.1 int: transfer incomplete while writing file within network system module - cannot Get Cloud Location
error from srapath:
Error: RC(rcNS,rcFile,rcCreating,rcTimeout,rcExhausted)

**Comment by elbakrifz** [comment]
sratoolkit.2.10.8-mac64 mac$ fastq-dump --split-files ERR013300
error from srapath:
Error: RC(rcNS,rcNoTarg,rcValidating,rcConnection,rcNotFound)
 and firstly I get the Sra with 184,2Mo and then 246Mo ??

**Comment by klymenko** [comment]
@solo7773, @edraizen, do you still need help?

**Comment by solo7773** [comment]
@klymenko Thanks. No.
