### ISSUE TITLE
Configure step does not work, can't find NCBI VDB

### ISSUE THREAD

**Issue by bosborne** [ncbi/sra-tools#27]
Not really sure what the right combination of options is, here's the closest I can get:

sudo ./configure --prefix=/software/apps/sratoolkit/gcc/64/2.5.8 --with-ngs-sdk-prefix=/software/apps/ngs-sdk/gcc/64/1.2.3 --with-ncbi-vdb-sources=/software/builds/ncbi-vdb/gcc/64/2.5.8/ncbi-vdb-2.5.8/ --with-ncbi-vdb-build=/software/apps/ncbi-vdb/gcc/64/2.5.8/
Configuring SRA-TOOLS package
checking system type... Linux
checking machine architecture... x86_64
checking SRA-TOOLS version... 2.5.8
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking for fuse library... no
checking for hdf5 library... no
checking for magic library... no
checking for xml2 library... yes
checking for ngs-sdk package...
	includes... /software/apps/ngs-sdk/gcc/64/1.2.3
	libraries... /software/apps/ngs-sdk/gcc/64/1.2.3/lib64
includes: /software/apps/ngs-sdk/gcc/64/1.2.3/include
libraries: /software/apps/ngs-sdk/gcc/64/1.2.3/lib64
checking for ncbi-vdb package source files and build results...
	includes... /software/builds/ncbi-vdb/gcc/64/2.5.8/ncbi-vdb-2.5.8
	libraries... /software/apps/ncbi-vdb/gcc/64/2.5.8/lib64
no
configure: error: required ncbi-vdb package not found.

NCBI VDB is installed like this:

2518 > ls /software/apps/ncbi-vdb/gcc/64/2.5.8/lib64/  
total 18340
   0 libncbi-ngs-c++.a@            0 libncbi-vdb.a.2@          0 libncbi-vdb-static.a@     0 libncbi-wvdb.so.2@
   0 libncbi-ngs-c++.a.2@       5752 libncbi-vdb.a.2.5.8       0 libncbi-wvdb.a@        3512 libncbi-wvdb.so.2.5.8*
   8 libncbi-ngs-c++.a.2.5.8       0 libncbi-vdb.so@           0 libncbi-wvdb.a.2@         0 libncbi-wvdb-static.a@
   0 libncbi-ngs-c++-static.a@     0 libncbi-vdb.so.2@      5216 libncbi-wvdb.a.2.5.8
   0 libncbi-vdb.a@             3852 libncbi-vdb.so.2.5.8*     0 libncbi-wvdb.so@

2519 > ls /software/apps/ncbi-vdb/gcc/64/2.5.8/include/ncbi-vdb/
total 4
4 NGS.hpp*

No problem finding NGS SDK, as you can see.

**Comment by klymenko** [comment]
In order to build 'sra-tools' you need the source files and build results of 'ncbi-vdb'.

--with-ncbi-vdb-sources is directory where the source files of 'ncbi-vdb' git package are.

 --with-ncbi-vdb-build is the output directory of 'make' build running in 'ncbi-vdb'.
By default it is ~/ncbi-outdir .
Or it is the value of '--build-prefix' option from 'configure' of 'ncbi-vdb'.

**Comment by bosborne** [comment]
Thank you for that prompt response. I tried setting the "--build-prefix" of NCBI VDB and the "--with-ncbi-vdb-build" of SRA toolkit to the same value as you suggested, still seeing:

configure: error: required ncbi-vdb package not found.

Can you show me an example "configure" command for NCBI VDB that sets --build-prefix? Then please show the corresponding example "configure" command  for SRA Toolkit that sets --with-ncbi-vdb-build and --with-ncbi-vdb-sources.

**Comment by klymenko** [comment]
Normally, you should not use these options.
The output by default goes to ~/ncbi-outdir.

Here is recommended build sequence:

rm -r ~/ncbi-outdir
mkdir ~/ncbi
cd ~/ncbi
git clone https://github.com/ncbi/ngs.git
git clone https://github.com/ncbi/ncbi-vdb.git
git clone https://github.com/ncbi/sra-tools.git
ngs/ngs-sdk/configure --prefix=~/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C ngs/ngs-sdk
ncbi-vdb/configure --prefix=~/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C ncbi-vdb
sra-tools/configure --prefix=~/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C sra-tools

**Comment by seandavi** [comment]
Thanks, @klymenko.  Is there a downside to using these options, for example, for a system-level installation?

**Comment by kwrodarmer** [comment]
@seandavi , can you elaborate a bit on what you mean?

**Comment by kwrodarmer** [comment]
Certainly for a system-level installation, you should never build as root, but only install as root, so
`cd ncbi-vdb; make; sudo make install` 
would be more appropriate. Also, `~/ncbi` is often used as a default cache location, so you might want to choose a different build location.

**Comment by bosborne** [comment]
@klymenko Those configure examples don't work. If you do "ngs/ngs-sdk/configure --prefix=/software/apps/sratoolkit/gcc/64/2.5.8" then the corresponding SRA configure has to have this: "--with-ngs-sdk-prefix=/software/apps/sratoolkit/gcc/64/2.5.8/". Doing that does work, and the SDK is found. However, I'm still seeing this after trying various permutations of --with-ncbi-vdb-build and --with-ncbi-vdb-sources:

configure: error: required ncbi-vdb package not found

Can you show the values of --with-ncbi-vdb-sources and --with-ncbi-vdb-build that would work in this example?

**Comment by klymenko** [comment]
More complete example:

sudo mkdir -p /sw/sra/src
sudo chmod o+w /sw/sra/src

mkdir -p /sw/sra/src/1
cd /sw/sra/src/1
git clone https://github.com/ncbi/ngs.git
mkdir -p /sw/sra/src/2
cd /sw/sra/src/2
git clone https://github.com/ncbi/ncbi-vdb.git
mkdir -p /sw/sra/src/3
cd /sw/sra/src/3
git clone https://github.com/ncbi/sra-tools.git

sudo mkdir /sw/sra/build
sudo chmod o+w /sw/sra/build

cd /sw/sra/src/1/ngs/ngs-sdk/
./configure --prefix=/sw/sra/gcc/64/2.5.8 --build-prefix=/sw/sra/build/ngs-sdk
make
sudo make install

cd /sw/sra/src/2/ncbi-vdb/
./configure --prefix=/sw/sra/gcc/64/2.5.8 --build-prefix=/sw/sra/build/ncbi-vdb --with-ngs-sdk-prefix=/sw/sra/gcc/64/2.5.8
make
sudo make install

cd /sw/sra/src/3/sra-tools/
./configure --prefix=/sw/sra/gcc/64/2.5.8 --build-prefix=/sw/sra/build/sra-tools --with-ncbi-vdb-sources=/sw/sra/src/2/ncbi-vdb --with-ncbi-vdb-build=/sw/sra/build/ncbi-vdb --with-ngs-sdk-prefix=/sw/sra/gcc/64/2.5.8
make
sudo make install

**Comment by jerviedog** [comment]
It works.

**Comment by darra56-Csir** [comment]
hi everyone,

Can someone please help me with the commands of downloading data from ncbi sra using new sra tools, the prefetch command I used is SHOWING ERROR AND FASTDUMP COMMAND SHOWS THIS AS AN ERROR:
fastq-dump: symbol lookup error: fastq-dump: undefined symbol: KDirectoryNativeDir


and thanks @klymenko  for sharing the build sequence for sra tools.

I

**Comment by kwrodarmer** [comment]
Hi @darra56-Csir ,

While this issue is closed, please start off by reading [https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data](https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data) and win particular you should notice that tools from last March are guaranteed to fail now. Please see [https://github.com/ncbi/sra-tools/wiki](https://github.com/ncbi/sra-tools/wiki).

If you continue to experience issues, please open a new ticket. Thanks!

**Comment by mariakondili** [comment]
> 

Hello, I highly recommend to post this kind of instructions in first page of the package ,for making Installation available to everyone who downloads the tool. It is not evident how to install, and especially because ncbi-vdb is required. Furthermore , 
I would like more help explaining where should the equivalent of the dir `/sw/sra/gcc/64/2.5.8` files  be for any user, and which script is actually called , e.g cmake ,cc  , or other ?

**Comment by klymenko** [comment]
Instructions are here: https://github.com/ncbi/sra-tools/wiki/Building-and-Installing-from-Source
