### ISSUE TITLE
Cannot find ami-0d57e13fe62227b2e

### ISSUE THREAD

**Issue by ianfore** [ncbi/sra-tools#271]
I am unable to find the Amazon Machine image mentioned in the SRA documentation -ami-0d57e13fe62227b2e

In the EC2 console when I select AMIs from under images I get 
"An error occurred fetching image data: An unknown error occurred"

If I go to Instances - Launch Instance
In Quickstart I can find the following
SDDP workbench - ami-0236e72477e0624c1

Does that replace ami-0d57e13fe62227b2e

**Comment by phillipbuckhaults** [comment]
Phillip Buckhaults, Ph.D.
Director, Cancer Genetics Lab
Associate Professor, Department of Drug Discovery and Biomedical Sciences
The University of South Carolina College of Pharmacy 
715 Sumter Street, Columbia, SC 29208

Lab & office location: Jones Physical Sciences Building, Room 620
https://www.google.com/maps/@33.9947055,-81.0306623,3a,75y,37.26h,112.22t/data=!3m6!1e1!3m4!1swgVLAM_63td3BeThm6ezXQ!2e0!7i13312!8i6656

phillip.buckhaults@gmail.com
phillip.buckhaults@sc.edu
buckhaul@cop.sc.edu
https://twitter.com/P_J_Buckhaults
https://www.facebook.com/phillipbuckhaults

Lab     Phone=803-777-9192
Office Phone=803-777-3621

"Let us not confuse effort with achievement"
-Dad

**Comment by stineaj** [comment]
ami-0236e72477e0624c1 is in us-east-2 (Ohio),  ami-0d57e13fe62227b2e is in us-east-1(N. Virginia).  If you change your instance location you should be able to find the AMI.

**Comment by ianfore** [comment]
Thanks, got it. I thought I'd checked that!
