### ISSUE TITLE
Error in locality example request in SRA Data Locator Documentation

### ISSUE THREAD

**Issue by ianfore** [ncbi/sra-tools#272]
See https://www.ncbi.nlm.nih.gov/Traces/sdl/1/

**Locailty**
The URL given for the example request for locality is as follows
https://www.ncbi.nlm.nih.gov/Traces/sdl/1/locality?acc=SRR2043623&acc=SRR2043622&acc=SRR867664&acc=SRR1219805&location=s3.us-east-1

The location parameter is not a documented parameter for this API function. It is also unnecessary; the point of this function is to list localities at which a given accession is available.

Suspect this is a copy and paste error from the example request for the retrieve function.

**Comment by kwrodarmer** [comment]
I appreciate the input. The SDL is not a part of the SRA Toolkit, but is a service we use.

By the way, why do you say that the location is unnecessary?

**Comment by ianfore** [comment]
Location is not a necessary parameter  the purpose of the locality function is to discover the locations at which given SRR accession is available. 

Having discovered that, one would then choose one of the given location and use it as the &location= parameter in a call to retrieve.

I did a test call to https://www.ncbi.nlm.nih.gov/Traces/sdl/1/locality including &location=s3.us-east-1 and it still returned the gs.us locations too. The location parameter didn't make any difference to what was returned.

**Comment by kwrodarmer** [comment]
The location is not guaranteed to make a difference, but a difference can occur.

The current version of SDL is 2, by the way.

**Comment by ianfore** [comment]
Thanks for the note about version 2. I came across version 1 from the links in the 

The following guess at the URL for the documentation for version 2 seemed to give the right result.
https://www.ncbi.nlm.nih.gov/Traces/sdl/2/

Another clue why location does not make sense as a parameter to "locality" comes from the documentation for "retrieve"
'Location should match "service" and "region" fields of locality output'
Location is derived from the output of "locality" rather than being an input to it.
Also it doesn't appear in the list of documented parameters for "locality".

**Comment by kwrodarmer** [comment]
I'll relay your comments to the maintainers. Thanks!
