### ISSUE TITLE
Basic fasterq-dump command is failing from `SIGNAL - Segmentation fault`

### ISSUE THREAD

**Issue by jolespin** [ncbi/sra-tools#273]
Here's my versions:
```
(base) -bash-4.1$ fasterq-dump -h | tail -n 2
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/bin/fasterq-dump : 2.10.0

(base) -bash-4.1$ fastq-dump -h | tail -n 2
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/bin/fastq-dump : 2.10.0
```
Here's my command:
```
(base) -bash-4.1$ fasterq-dump -t 4 ERR599092
```
Here's my error:
```
2020-01-17T22:52:55 fasterq-dump.2.10.0 err: cmn_iter.c cmn_read_uint8_array( #166936577 ).VCursorCellDataDirect() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-01-17T22:52:55 fasterq-dump.2.10.0 err: row #166936577 : READ.len(202) != QUALITY.len(0) (F)
2020-01-17T22:52:55 fasterq-dump.2.10.0 fatal: SIGNAL - Segmentation fault
```

**Comment by Vojczech** [comment]
For my version of `fasterq-dump 2.10.2` error `SIGNAL - Segmentation fault` is occurring as well. Especially for some big SRA accessions (e.g. SRR5456973). 
Also mentioned in issue #224 and #242. It prevents from smooth download of the data.

**Comment by kwrodarmer** [comment]
We are aware of this issue. You can use 2.10.1 for the time being to avoid the problem. We will be issuing a fix this week.

**Comment by egoltsman** [comment]
I ran into the same issue, but when downgrading only found 2.10.0 available on the ftp site.  I'm getting the same error with that version as well.

**Comment by kwrodarmer** [comment]
I'm so sorry! Yes, I meant 2.10.0.

**Comment by egoltsman** [comment]
The same error comes up with 2.10.0.   Like other posters said, it seems to happen with large data sets.   Since the error is about a mismatch between sequence and qual string lengths,  I looked at the tails of the fastq files generated so far, and yes, the last line is truncated in some cases.

**Comment by ejwright39** [comment]
Same problem here. Went ahead and used wget to pull the .gz files from AWS directly. Really shouldn't be this convoluted.

**Comment by annaorteu** [comment]
I had the same issue using an older version, 2.9.2

**Comment by skripche** [comment]
We apologize for the difficulties and are working on fixing this bug. Getting data directly from our AWS bucket is a solution that can work for newer records for which we made that data available. 

You can also get that data by using prefetch with the "--type" flag and specifying the file type like "fastq". You can also use the keyword "any" to download all associated file types for the accession.

**Comment by klymenko** [comment]
Please try our latest 2.10.6 toolkit.
