### ISSUE TITLE
i have a problem.i dont runing prefetch SRRxxxxxxx

### ISSUE THREAD

**Issue by tppf** [ncbi/sra-tools#275]
when i runing ‘prefetch SRR2148814’,the terminal will show for example （1）. ONLY when i runing ’prefetch https:...-o /....‘, file can download.

Forexample（1）
`root@iZbp1b8f6yfdzvctt5jbhjZ:/biosoft/srafile# prefetch SRR2148814
root@iZbp1b8f6yfdzvctt5jbhjZ:/biosoft/srafile#`

**Comment by kwrodarmer** [comment]
Please let us know the version you are running. Also, we do not recommend running as root...

**Comment by tppf** [comment]
> Please let us know the version you are running. Also, we do not recommend running as root...
it's 2.10.2. And runing other versin,it have other error.

**Comment by tppf** [comment]
> Please let us know the version you are running. Also, we do not recommend running as root...

it's 2.10.2

**Comment by tppf** [comment]
> Please let us know the version you are running. Also, we do not recommend running as root...

And runing other versin,it have other error.

**Comment by kwrodarmer** [comment]
Thank you! We will follow up tomorrow.

**Comment by tppf** [comment]
> Thank you! We will follow up tomorrow.

thank you

**Comment by klymenko** [comment]
@tppf , do you still have this issue?

**Comment by tppf** [comment]
> @tppf , do you still have this issue?

i don't use this tools. i download sra file from website.
