### ISSUE TITLE
Prefetch is unable to download complete file

### ISSUE THREAD

**Issue by rohitsuratekar** [ncbi/sra-tools#276]
I am using latest `sra-tools` (2.10.2) to download few .sra files from the NCBI server. It was working perfectly fine till 2 days ago but from 22 Jan 2020, suddenly I am unable to download the full file with `prefetch`. Process starts properly but download fails in between. I have tried to use older version as well but it also had the same error. 

For example, I run following
` prefetch SRR7882022`

and I get following messages after few minutes.
 
```

2020-01-24T12:17:36 prefetch.2.10.2: 1) Downloading 'SRR7882022'...
2020-01-24T12:17:36 prefetch.2.10.2:  Downloading via https...
2020-01-24T12:23:39 prefetch.2.10.2 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos1/sra-pub-run-2/SRR7882022/SRR7882022.1
2020-01-24T12:23:39 prefetch.2.10.2:  https download failed
2020-01-24T12:23:39 prefetch.2.10.2: 1) failed to download SRR7882022
```
I have also tried this few other SRA IDs and for them also it was giving same error. 

System details -- 
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.15.0-74-generic

**Comment by jayguoxue** [comment]
I had exactly the same problem as you, yet I have no solutions.
Would you tell me whether you have solved the problem, thanks a lot.

**Comment by rohitsuratekar** [comment]
@jayguoxue Unfortunately, I couldn't find any solution. No matter how I implement and on which system, `prefetch` was always unreliable. I also tried to use directly `fasterq-dump` but it was extremely slow (compared to when you use on downloaded SRA file) and also ended up in interruption in the download. 

Hence, finally, I just removed downloading step from my pipeline and made it as an input. I have discussed this issue with few of my colleagues and they also advised me to not rely on `prefetch`. One alternative is to download SRA files from EMBL-EBI servers. Use their ENA browser (https://www.ebi.ac.uk/ena) to get URL and then just download with wget or curl (which is not recommended by SRA-Tools developers but I couldn't find any other way). I hope in future they might implement it more robustly.

**Comment by glev-doug** [comment]
@rohitsuratekar I have recently encountered similar issues with `prefetch` using 2.9.1 and 2.10.0 and found that updating to 2.10.4 solved this particular issue. I did not see anything mentioned in the changelog (https://github.com/ncbi/sra-tools/blob/master/CHANGES.md), but updating `sra-tools` may be worth attempting. 

Deeper knowledge on the matter is highly welcome.

**Comment by klymenko** [comment]
Please try our latest 2.10.6 toolkit.
