### ISSUE TITLE
Typo is fasterq-dump options?

### ISSUE THREAD

**Issue by rohitsuratekar** [ncbi/sra-tools#277]
In 2.10.2 version, `fasterq-dump` has `--progres` instead `--progress` which is breaking existing pipelines. Is it intentional change or typo?

**Comment by kwrodarmer** [comment]
This would be a bug. Thank you for reporting it! We'll look into it.

**Comment by s-andrews** [comment]
It also doesn't seem to enable the progress option if you add ``--progres``` and throws an error with ```--progress```

**Comment by s-andrews** [comment]
This is still present in 2.10.5.  It's a one letter fix so I've submitted a pull request with the fix (pull #332) if someone could check and merge it.

**Comment by klymenko** [comment]
@s-andrews , please check 2.10.7.

**Comment by s-andrews** [comment]
This is fixed in 9ac1a26
