### ISSUE TITLE
error shows when fasterq-dump renders on local .sra

### ISSUE THREAD

**Issue by zyqfrog10** [ncbi/sra-tools#280]
Hello,

Due to the 'segmentation fault' error, I downloaded .sra file with ```prefetch``` first then transform it to .fastq. There is an error message about the accession id although the fastq files are generated as expected (but why is SRR000001.sra.fastq also generated?)

```
> sraid=SRR000001
> prefetch ${sraid}
2020-01-30T20:47:05 prefetch.2.10.2: 1) Downloading 'SRR000001'...
2020-01-30T20:47:05 prefetch.2.10.2:  Downloading via https...
2020-01-30T20:47:10 prefetch.2.10.2:  https download succeed
2020-01-30T20:47:10 prefetch.2.10.2: 1) 'SRR000001' was downloaded successfully
> fasterq-dump ./${sraid}/${sraid}.sra
2020-01-30T20:47:51 fasterq-dump.2.10.2 err: name not found while resolving query within virtual file system module - failed to resolve accession './SRR000001/SRR000001.sra' - Cannot resolve accession ( 404 )
spots read      : 470,985
reads read      : 1,883,940
reads written   : 707,026
reads 0-length  : 468,635
technical reads : 708,279
> ls
SRR000001
SRR000001.sra_1.fastq
SRR000001.sra_2.fastq
SRR000001.sra.fastq
```
Thanks,
YZ

**Comment by kwrodarmer** [comment]
Thank you for your report. We know about this condition and will address it in the next release.
Meanwhile, the report generated is a good indication that the tool succeeded. You may find that the 404 error goes away if you simply say `fasterq-dump SRR000001` rather than providing the path to the file.

**Comment by zyqfrog10** [comment]
If I simply use ```fasterq-dump SRR000001```, would it download remotely or it use my local pre-downloaded file? 'Cause the reason I choose to use ```prefetch``` is to avoid 'segmentation fault'.

**Comment by kwrodarmer** [comment]
It should find the already downloaded file and not download it a second time.

**Comment by zyqfrog10** [comment]
Wonderful. Thank you very much.

**Comment by DrQuestion** [comment]
Hello,
I'm experiencing a similar issue when running fasterq-dump both with local path and with SRA ID only (after prefetch).
`path/where/SRR8351023/is/located$ fasterq-dump SRR8351023
2020-02-15T13:22:26 fasterq-dump.2.10.2 fatal: SIGNAL - Segmentation fault
fasterq-dump (PID 39024) was killed (signal 11)`

Thank you in advance,
AA.
