### ISSUE TITLE
vdb-config: Missing `--import` function?

### ISSUE THREAD

**Issue by nishit-parekh** [ncbi/sra-tools#281]
**Using version `2.10.2`**

`vdb-config` does not have the `--import` option to import NGC keys, and the interactive mode `vdb-config -i` doesn't have that as an option in any menu either.

I wanted to decrypt files, and initially thought this might be an issue if I am unable to import the key. However, I found out that `vdb-decrypt --ngc <path/to/key> ...` will solve this issue for me.

So, has importing keys into `vdb-config` been deprecated? Or is this a genuine bug?

**Comment by kwrodarmer** [comment]
Yes - the `--import` functionality has been deprecated from vdb-config.

**Comment by douym** [comment]
Hi @kwrodarmer ,
I'm trying to download controlled-access data from dbGap, and from here (https://statgen.us/lab-wiki/productivity_tips/dbGaP-download.html) I need to import dbGaP repository key before downloading:

`vdb-config --import ~/prj_3253_D17102.ngc`

What should I do if the "import" functionality has been deprecated?

Thanks!!
