### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by haowenz** [ncbi/sra-tools#283]
Hi,

I failed to build sra-tools from source. I used GCC 7.3.0 and the system is Red Hat Enterprise Linux Server release 7.6. The related message is as follows.

> make[6]: Entering directory `/tmp/sra-tools/tools/driver-tool/utf8proc'
gcc -c  -std=gnu11  -DNDEBUG -m64   -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so  -I/tmp/sra-tools/interfaces/override -I/tmp/sra-tools/tools/driver-tool/json/linux -I/tmp/sra-tools/tools/driver-tool/json/unix -I/tmp/sra-tools/tools/driver-tool/json -I/tmp//ncbi-vdb/interfaces/ -I/tmp/ncbi-vdb/interfaces/cc/gcc/x86_64 -I/tmp/ncbi-vdb/interfaces/cc/gcc -I/tmp/ncbi-vdb/interfaces/os/linux -I/tmp/ncbi-vdb/interfaces/os/unix -I/tmp/ncbi-vdb/interfaces/ext -I/tmp/ngs/ngs-sdk -I. -MD -I/usr/local/pacerepov2/hdf5/1.10.3/intel-18.0/include -I/usr/local/pacerepov2/bzip2/1.0.6/intel-18.0/include -I/usr/local/pacerepov2/gcc/7.3.0/include -std=gnu11 -DNDEBUG -m64 -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so -I/tmp/sra-tools/interfaces/override -I/tmp/sra-tools/tools/driver-tool/json/linux -I/tmp/sra-tools/tools/driver-tool/json/unix -I/tmp/sra-tools/tools/driver-tool/json -I/tmp/ncbi-vdb/interfaces/ -I/tmp/ncbi-vdb/interfaces/cc/gcc/x86_64 -I/ncbi-vdb/interfaces/cc/gcc -I/tmp/ncbi-vdb/interfaces/os/linux -I/tmp/ncbi-vdb/interfaces/os/unix -I/tmp/ncbi-vdb/interfaces/ext -I/tmp/ngs/ngs-sdk -I. -fPIC -std=c99 -Wall -pedantic -DUTF8PROC_EXPORTS -c -o utf8proc.o utf8proc.c
rm -f libutf8proc.a
ar rs libutf8proc.a utf8proc.o
ar: creating libutf8proc.a
gcc -c  -std=gnu11  -DNDEBUG -m64   -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so  -I/tmp/sra-tools/interfaces/override -I/tmp/sra-tools/tools/driver-tool/json/linux -I/tmp/sra-tools/tools/driver-tool/json/unix -I/tmp/sra-tools/tools/driver-tool/json -I/tmp/ncbi-vdb/interfaces/ -I/tmp/ncbi-vdb/interfaces/cc/gcc/x86_64 -I/tmp/ncbi-vdb/interfaces/cc/gcc -I/tmp/ncbi-vdb/interfaces/os/linux -I/tmp/ncbi-vdb/interfaces/os/unix -I/tmp/ncbi-vdb/interfaces/ext -I/tmp/ngs/ngs-sdk -I. -MD -DNDEBUG -m64 -shared -o libutf8proc.so.2.2.0 -Wl,-soname -Wl,libutf8proc.so.2 utf8proc.o
gcc: warning: utf8proc.o: linker input file unused because linking not done
chmod a-x libutf8proc.so.2.2.0
chmod: cannot access ‘libutf8proc.so.2.2.0’: No such file or directory
make[6]: *** [libutf8proc.so.2.2.0] Error 1
make[6]: Leaving directory `/tmp/sra-tools/tools/driver-tool/utf8proc'
make[5]: *** [/tmp/sra-tools/tools/driver-tool/utf8proc/utf8proc.o] Error 2
make[5]: Leaving directory `/tmp/ncbi/build/sra-tools/linux/gcc/x86_64/rel/obj/tools/driver-tool/json'
make[4]: *** [std] Error 2
make[4]: Leaving directory `/tmp/sra-tools/tools/driver-tool/json'
make[3]: *** [/tmp/ncbi/build/sra-tools/linux/gcc/x86_64/rel/ilib/libjson.a] Error 2
make[3]: Leaving directory `/tmp/ncbi/build/sra-tools/linux/gcc/x86_64/rel/obj/tools/driver-tool'
make[2]: *** [std] Error 2
make[2]: Leaving directory `/tmp/sra-tools/tools/driver-tool'
make[1]: *** [driver-tool] Error 2
make[1]: Leaving directory `/tmp/sra-tools/tools'
make: *** [tools] Error 2

From the warning message, we know the "-c" should be removed when generating libutf8proc.so.2.2.0. Please help fix this problem in the make file of the project.

Thanks,
Haowen

**Comment by darwinchangz** [comment]
Not a dev, but I had a similar issue and fixed it by downloading libutf8proc.so.2.2.0 and placing it in the directory where the makefile was searching for it.

install it here - https://github.com/JuliaStrings/utf8proc/archive/v2.2.0.tar.gz

```
tar xzvf utf8proc-2.2.0.tar.gz
cd utf8proc-2.2.0
make
cp libutf8proc.so.2.2.0 /tmp/sra-tools/tools/driver-tool/utf8proc
cd /tmp/sra-tools/
make
make install
```

**Comment by haowenz** [comment]
I assume it should be compiled when building the tool. It is very easy for me to fix the problem that is I can just start a second round of make and finish the compilation. And to me it looks like that the "-c" should be removed when generating libutf8proc.so.2.2.0.

**Comment by klymenko** [comment]
@haowenz , do you still have this issue?

**Comment by Char-Aznable** [comment]
I have the same error when building from source:
```
gcc-5: warning: utf8proc.o: linker input file unused because linking not done
chmod: cannot access ‘libutf8proc.so.2.2.0’: No such file or directory
make[7]: *** [libutf8proc.so.2.2.0] Error 1
```

**Comment by Char-Aznable** [comment]
The fix mentioned by @haowenz works for me. Can the maintainer of this repo fix this in future release? This is an obvious bug and very easy to fix
