### ISSUE TITLE
timeout exhausted

### ISSUE THREAD

**Issue by kehuangke** [ncbi/sra-tools#286]
Hi, 
I have an unfortunately error ‘’**timeout exhausted while reading file within network system module**‘’ when using SRAtools 2.10.2.

2020-02-15T06:20:33 prefetch.2.10.2: 7) Downloading '2001281'...
2020-02-15T06:20:33 prefetch.2.10.2:  Downloading via https...
2020-02-16T21:39:42 prefetch.2.10.2 int: **timeout exhausted while reading file within 
network system module -** Cannot KStreamRead: https://gap-download.be-md.ncbi.nlm.nih.gov/gap_files/C399B014-0CBF-444F-B90B-5FABA8D2C01D/2001281?tic=4E046CDB-EB3B-4945-8DF0-D812442256FA
2020-02-16T21:39:42 prefetch.2.10.2:  https download failed
2020-02-16T21:40:20 prefetch.2.10.2: 7) failed to download 2001281

I intended to download GTEx V8 data and other files about 50G can be downloaded successfully, only one WGS file about 600G was failed after downloading one day or two days.

My code of SRAtools 2.10.2  is 

**vdb-config -s /http/timeout/read=1000000**
**~/bin/prefetch  -X 1200000000   cart_DAR46160_202001302145.krt**

The same error has been printed in SRAtools 2.8.2.

According to the similar error reported in GitHub, I have updated SRAtools to 2.10.2 and error still was printed. I have also set the value of HTTP read timeout and error didn't disappear.

I have tested many times, one test will spend two days. Can you help me to solve this problem!!!

**Comment by orangeSi** [comment]
I met the silimar error:
```
2020-02-17T08:03:30 fastq-dump.2.10.2 err: timeout exhausted while waiting condition within process system module - failed SRR8509777
```
then I fixed it by ```vdb-config -s /libs/kns/connect/timeout=200000```

**Comment by skripche** [comment]
Hello,

We will investigate the problem to see if we can make it better, but we have had problems serving very large files recently and we are actively working in improving the performance.

**Comment by kehuangke** [comment]
Thanks！ I have sent an email to sra@ncbi.nlm.nih.gov .

**Comment by kehuangke** [comment]
> Hello,
> 
> We will investigate the problem to see if we can make it better, but we have had problems serving very large files recently and we are actively working in improving the performance.
> 
> Could you please write to [sra@ncbi.nlm.nih.gov](mailto:sra@ncbi.nlm.nih.gov) so we can help you better. thank you.

Thanks! I have sent an email to sra@ncbi.nlm.nih.gov .

**Comment by klymenko** [comment]
@kehuangke , do you still need help?
