### ISSUE TITLE
is there tool to take a random set of reads from a sequencing run? 

### ISSUE THREAD

**Issue by pamedina** [ncbi/sra-tools#290]
Hi everyone, 

I am trying to download two million random reads from a sequencing run, but I don't want to take just the first two million reads, I want a random set of two million reads. Currently, I am downloading all the reads from a sequencing run using fastq-dump and then randomly subsampling using a python script. However, it takes up a lot of hard drive space and time to download the entire sequencing run, and I am trying to avoid this. Is there a tool available do download a random subsample of a sequencing run?

**Comment by nsheff** [comment]
this doesn't answer your question directly, but [samtools](http://www.htslib.org/doc/samtools-view.html) can do this natively, which might be faster than your python script.

```
-s FLOAT

    Output only a proportion of the input alignments. This subsampling acts in the same way on all of the alignment records in the same template or read pair, so it never keeps a read but not its mate. 
```

So you could sam-dump and pipe to `samtools view` to subsample. you'd still have to download everything but could at least ameliorate some of the disk use problems and perhaps speed...

**Comment by kwrodarmer** [comment]
The SRA toolkit has several tools that do this natively as well. As a matter of fact, we've been able to do it for many many years since our storage was built that way from the start.

The issue is random sets coming from a storage mechanism that is not good at it.
