### ISSUE TITLE
err: data corrupt while selecting function within transform module - failed SRR1593960

### ISSUE THREAD

**Issue by millerh1** [ncbi/sra-tools#292]
Hello!

I am getting an error when using fastq-dump:

```
(ewsPaperEnv) millerh1@cbbi16:~$ fastq-dump -O tmp/ --split-files SRR1593960
2020-02-25T16:12:38 fastq-dump.2.10.1 err: connection failed while opening file within cryptographic module - error with https open 'https://sra-download.ncbi.nlm.nih.gov/traces/refseq/GL000207.1'
2020-02-25T16:12:41 fastq-dump.2.10.1 err: data corrupt while selecting function within transform module - failed SRR1593960
```

It seems like this error also terminates the download early on my machine. What might be causing this? I'm using fastq-dump v2.10.1

Best,
Henry Miller

**Comment by skripche** [comment]
Hello,
One thing you can try is `prefetch SRR1593960` as a first step and then run either `fastq-dump` _(deprecated)_ or `fasterq-dump`. There are a large number of network delivery bumps that can interrupt the process that we are working on smoothing out, and `prefetch` can help. Prefetch downloads the needed dependencies and if your configuration does not set the cache area then the dependencies are downloaded into your home area. I suggest setting the cache area to a large storage directory before downloading/converting data. 

Also, we have a new release 2.10.3 and are about to release 2.10.4 - these having bug fixes for cloud deployment.

**Comment by millerh1** [comment]
Thank you for the quick reply! I have added `prefetch` into my pipeline and it's working great. Thank you!
