### ISSUE TITLE
update `conda` package

### ISSUE THREAD

**Issue by jbloom** [ncbi/sra-tools#293]
Is it possible to update the `conda` package for `sra-tools` ([here](https://anaconda.org/bioconda/sra-tools)). Right now it is at version 2.10.1.

**Comment by max1c** [comment]
Came here for the same reason. Are there plans to add sra-tools 2.10.4 to conda?

**Comment by seandavi** [comment]
Perhaps a pull request to update the recipe?

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sra-tools/meta.yaml

**Comment by Ni-Ar** [comment]
What about `sratoolkit`? 
I was only able to find [the older version 2.5.7](https://anaconda.org/daler/sratoolkit)

Thanks!

**Comment by klymenko** [comment]
We don't support conda
Please use [our build](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
