### ISSUE TITLE
Source build error [utf8proc]

### ISSUE THREAD

**Issue by raivivek** [ncbi/sra-tools#298]
Hi,

I was trying to compile the package from source and ran into the following error --
```
make[6]: Entering directory '/home/vivekrai/src/sra-tools/tools/driver-tool/utf8proc'
...
rm -f libutf8proc.a
ar rc rs libutf8proc.a utf8proc.o
ar: libutf8proc.a: No such file or directory
Makefile:77: recipe for target 'libutf8proc.a' failed
```

It looks like it is using `gcc -c` for the linker operations and `ar rc rs` here in place of just `ar rs` causing the problem. This issue is what #283 is also about, I think. 

I am not sure if it's a utf8proc or sra-tools, but any guidance will be useful.

**Comment by klymenko** [comment]
@raivivek , do you still have this issue?

**Comment by raivivek** [comment]
@klymenko I will test this and get back to you. Thanks!
