### ISSUE TITLE
kff lib?

### ISSUE THREAD

**Issue by jbyars** [ncbi/sra-tools#3]
I'm having an issue building sra-tools on Ubuntu 14.04. When building /tools/copycat, I get an ld -lkff not found error. I'm not quite sure where the kff lib is generated. Could you point me to the source for that library? I don't see anything in the ngs or ncbi-vdb repos. Thanks

**Comment by lidaof** [comment]
I am having this problem in Ubuntu 16.04 after install libmagic...any suggestions?
