### ISSUE TITLE
Prefetch  transfer incomplete error

### ISSUE THREAD

**Issue by DenisGoryunov** [ncbi/sra-tools#306]
Hi,
During several days i'm struggling with the following error:

 prefetch.2.10.0 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos2/sra-pub-run-13/SRR6XXXXXXX/SRRXXXXXXX.1

I'm running the prefetch command inside for loop and got this kind of error for every accession i tried.

How can i fix that?

Best,
Denis

**Comment by kwrodarmer** [comment]
The first thing is to try the latest code. Please see https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit for the latest.

By the way, we will be releasing 2.10.5 this week (Linux and OS-X).

**Comment by DenisGoryunov** [comment]
Thanks for your response. Will try the latest version and come back with the feedback.

**Comment by kwrodarmer** [comment]
Thanks - no guarantee that things will change, but at least we can be talking about the same version of software and go from there!

**Comment by DenisGoryunov** [comment]
Sorry, is there way to upgrade my current SRA toolkit version instead of installing the new version and configuring it from scratch again?

**Comment by kwrodarmer** [comment]
If you pick up the latest binaries, they will respect your current configuration. Configuration information is saved in your $HOME directory and survives from one toolkit version to another with few exceptions.

**Comment by DenisGoryunov** [comment]
Thank you for the clarification!
