### ISSUE TITLE
How to run GATK variant calling directly on SRA file ?

### ISSUE THREAD

**Issue by kb472** [ncbi/sra-tools#31]
Hello, I tried run GATK variant calling directly on a SRA file.

I downloaded GenomeAnalysisTK-3.5 jar file to my computer. My current directory is the folder where my SRA file and key file are located. I tried both these commands:
```
java -jar /path/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar -T HaplotypeCaller -R SRRFileName -I SRRFileName -stand_call_conf 30 -stand_emit_conf 10 -o SRRFileName.vcf 

java -jar /path/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar -T UnifiedGenotyper -R SRRFileName -I SRRFileName -stand_call_conf 30 -stand_emit_conf 10 -o SRRFileName.vcf 

```
For both these  commands, I got this error:
`ERROR MESSAGE: Invalid command line: The GATK reads argument (-I, --input_file) supports only BAM/CRAM files with the .bam/.cram extension and lists of BAM/CRAM files with the .list extension, but the file SRR1718738 has neither extension.  Please ensure that your BAM/CRAM file or list of BAM/CRAM files is in the correct format, update the extension, and try again.`

Should I be using some wrapper or modified version of GATK to get it to work on the SRA file ? I did see the SRA/dbGAP webinar and this is not clear to me.

Please advise. 
K

**Comment by kwrodarmer** [comment]
We are working with the GATK team to get the SRA-capable version released.

**Comment by kb472** [comment]
Thank you for the update. I saw screenshots and examples of this on the NCBI webinars, so that's why I tried it out.
