### ISSUE TITLE
vdb-config for computer cluster

### ISSUE THREAD

**Issue by KaushikPanda1** [ncbi/sra-tools#310]
Hello,

I installed sratoolkit.2.10.5-centos_linux64 successfully and configured using vdb-config -i, enabled remote access and set an empty directory in 'process-local'. I can run faster-dump successfully in any one session of the cluster, but when I submit a job file to the computing cluster to fetch multiple files in parallel, the command errors out saying this installation of sra-toolkit is not configured and is asking to set it using vdg-config -i (that is exactly what I did the first time around).

I read somewhere that for computing cluster, local folder should not be set and so I tried that in the configuration as well - disabled local file-caching. That did not help.

I prefetched the sra files so that faster-dump do not have to access the same location, and provided individual sra files to faster-dump command but continue to get the same error:

configuration not loaded: no vdb-config found
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

I appreciate any guidance to get around this issue.

**Comment by OrielResearchCure** [comment]
Hi Kaushik,
I have the same issue. were you able to solve that issue? 
I was trying to run the following multiple command line with the subprocess (python) and it didn't execute the second command.
Please let me know if you were able to find another solution.
Thanks,
eilalan

```
vdb-config and the fasterq-dump in one shell command using subprocess. 
path/to/vdb-config -L debug -v --prefetch-to-cwd -C --accept-gcp-charges yes; path/to/fasterq-dump -p -t ./tmp srrXXX 
```

**Comment by KaushikPanda1** [comment]
Hi Eilalan, 

Unfortunately, so solution yet. I am not running faster-dump in parallel for now.

**Comment by gustavoisidio** [comment]
I'm having the same issue here on macOS Mojave. For some reason looks like vdv-config is not registering it's configuration. No matter how many times we do it, "configuration not loaded: no vdb-config found" continues appearing

**Comment by zjf19870628** [comment]
I had the same issue. This is the reply I got from SRA team:

To me this sounds like the toolkit cannot access the location of the configuration file from cluster machines as that area is not mounted. By default we use your home area as the location of the configuration file. Using the vdb-config utility please set a directory that is accessible by the cluster machines and contains the configuration file(you can just copy it from your home area in this new directory) . 

I solved my problem by adding "cp -R /root/.ncbi/ ~" to my script.

**Comment by skripche** [comment]
To me this sounds like the toolkit cannot cannot access the location of the configuration file from cluster machines as that area is not mounted. By default the tools use your home area as the location of the configuration file. Using the vdb-config utility please set a directory that is accessible by the cluster machines and contains the configuration file (you can just copy it from your home area in this new directory) .

**Comment by klymenko** [comment]
Yes, SRA toolkit is looking for configuration in `$HOME/.ncbi/`

**Comment by ziziqolo** [comment]
> Yes, SRA toolkit is looking for configuration in `$HOME/.ncbi/`

Hi, would you please explain more about solving this problem? I am struggling with this error for 2 days. and I'm noob in working with cmd... 😭
