### ISSUE TITLE
SRA-toolkit test with fastq-dump producing error

### ISSUE THREAD

**Issue by duanjingqi** [ncbi/sra-tools#311]
Installed sratoolkit.2.10.5-centos_linux64 on an AWS parallel cluster. In vdb-config:
-enabled Remote Access
-provided location of user-repository
-enabled "accept charges for AWS"
-enabled "report cloud instance identity"
-provided AWS credential
Test with command "fastq-dump --stdout -X 2 SRR390728" and got the following error: 
2020-04-17T13:21:29 fastq-dump.2.10.5 err: encryption key not found while identifying column within <INVALID-MODULE> module - error with https open 'https://sra-pub-run-3.s3.amazonaws.com/SRR390728/SRR390728.2'
2020-04-17T13:21:29 fastq-dump.2.10.5 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table
fastq-dump (PID 17834) quit with error code 3

Please help with troubleshooting.

**Comment by kwrodarmer** [comment]
I was unable to reproduce this behavior. Please run the following command and send us the output file:

```
test-sra SRR390728 > test-sra-out.txt
```

You can send the file to sra-tools@ncbi.nlm.nih.gov . Please do **not** post it here!

**Comment by kwrodarmer** [comment]
When running on a cluster, we no longer recommend to **not** use a user-repository. Also, it is important that your cluster support `$HOME` to get back to the results of your `vdb-config` setup; sometimes $HOME is not set.

**Comment by duanjingqi** [comment]
Thank you, I sent test-sra-out.txt to the email address. How to check if $HOME is set or not for sra-toolkit?

**Comment by kwrodarmer** [comment]
If you run a script on your cluster that just runs a test and prints to an output file, you can check it later. There are many ways to do it, of course, e.g.:

```
echo "$HOME"
```
or
```
set | grep HOME
```
or...

All you want to see is if your cluster has access to your home directory.

**Comment by duanjingqi** [comment]
My cluster can recognize it. 
$ echo $HOME
/home/ec2-user

**Comment by kwrodarmer** [comment]
That's what we would expect, but always want to ensure!

**Comment by duanjingqi** [comment]
Thanks. Hope you had got my test output in the email. 

Jingqi

**Comment by kwrodarmer** [comment]
I have sent a message to the help-desk to be on the lookout so we can review it soon. Thank you for your input and your patience!

**Comment by kwrodarmer** [comment]
If you are executing from "us-east-1", can you try disabling the "accept charges for AWS"?

**Comment by duanjingqi** [comment]
No error from fastq-dump test! Thank you very much. But problem solved? Should I just leave it disabled in future? 

Jingqi

**Comment by kwrodarmer** [comment]
As long as you operate from "us-east-1" there is no need to enable user-pays.

You should not have had this problem in the first place. The bug is in a service used by the SRA Toolkit and we have already started working on a fix. In the meantime, you should be able to make progress.

**Comment by duanjingqi** [comment]
Thanks a lot for your help. I could make progress while staying home.
