### ISSUE TITLE
fasterq-dump error code 3 - small files issue?

### ISSUE THREAD

**Issue by mfansler** [ncbi/sra-tools#314]
I am working with the data under [GSE94883](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE94883). While there were a few random hiccups downloading some files, most dumped fine with `fasterq-dump` using default settings. However, I did find four runs that were not processable with `fasterq-dump`, namely

 - SRR5256310
 - SRR5256431
 - SRR5256471
 - SRR5256511

which all failed with something like (this specifically is for SRR5256431):

```
2020-04-24T18:34:45 fasterq-dump.2.10.5 err: sorter.c run_producer_pool() : processed lookup rows: 6 of 7
2020-04-24T18:34:45 fasterq-dump.2.10.5 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcSize,rcInvalid)
2020-04-24T18:34:45 fasterq-dump.2.10.5 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcSize,rcInvalid)
fasterq-dump (PID 54742) quit with error code 3
```

Running `fastq-dump` on the cached SRAs resulted in tiny files (less than 10 reads per run), which seems to correspond with the SRA metadata for # of spots.

I'm going to throw these out anyway, but this is more to document that `fasterq-dump` may have issues when there are only a handful of reads.

**Comment by psc3** [comment]
Same problem for GSE53697.  Downloads for SRR22926 & SRR242927, but repeated attempts for SRR2422928 fail.

**Comment by klymenko** [comment]
@mfansler, @psc3, do you still need help?

**Comment by mvinyard** [comment]
I am having the same issue. I also tried regular `fastq-dump` only to get: 

```
fastq-dump quit with error code 3
```

**Comment by YYDS-MengYE** [comment]
Just like these questions, Updating  your software  can solve your  about 50 ％ errors

**Comment by klymenko** [comment]
Correct.
First, download the latest toolkit from https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit
