### ISSUE TITLE
fasterq-dump error #19968

### ISSUE THREAD

**Issue by OrielResearchCure** [ncbi/sra-tools#315]
Hello,

I am executing fasterq-dump on a worker machine using the python os library:

```
cmd_vdg = "{}/vdb-config --prefetch-to-cwd".format(sra_toolkit_folder)
ret_val_cmd_vdg = os.system(cmd_vdg)
cmd_fasterq = "{}/fasterq-dump {} -O {} -f".format(sra_toolkit_folder,srr,local_fld)
ret_val_cmd_fasterq = os.system(cmd_fasterq) #,shell=True)

```
Execution cmd_fasterq value is: /opt/userowned/sratoolkit.2.10.5-centos_linux64/bin/fasterq-dump SRR4784332 -O /SRR4784332/READS -f

This the error that is being fired:
line 358, in process TypeError: unorderable types: list() > int()

Any advice on what might be the issue.

Many thanks,
eilalan

**Comment by OrielResearchCure** [comment]
Hello,

Adding to my question. is there a way to pipe $HOME/.ncbi/user-settings.mkfg to the fasterq-dump command? thanks, eilalan

**Comment by klymenko** [comment]
@OrielResearchCure, do you still need help?
