### ISSUE TITLE
Firewall critical message

### ISSUE THREAD

**Issue by mapsa** [ncbi/sra-tools#317]
blastn_vdb is displaying the message:
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils201] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112

but the command is executed correctly .. why is this message appearing? 
I checked the ports needed by NCBI but the ones mentioned on their website aren't the same:

https://www.ncbi.nlm.nih.gov/IEB/ToolBox/NETWORK/firewall.html

Should I worry about this message?
Many thanks.

**Comment by klymenko** [comment]
Please send this question to blast-help@ncbi.nlm.nih.gov
