### ISSUE TITLE
The *_pass_3.fastq file generated by fastq-dump --split-files

### ISSUE THREAD

**Issue by lauraht** [ncbi/sra-tools#320]
Hello!

I used the following options in fastq-dump:
```
--split-files 
-I 
--skip-technical 
--clip 
--read-filter pass 
-N 
-X 
```
For some paired-end SRA Runs, instead of generating `*_pass_1.fastq` and `*_pass_2.fastq`, it generated `*_pass_1.fastq` and `*_pass_3.fastq` (or `*_pass_2.fastq` and `*_pass_3.fastq`).
For some single-end SRA Runs, instead of generating `*_pass_1.fastq` (or `*_pass_2.fastq`), it generated `*_pass_3.fastq`.

I was wondering what `*_pass_3.fastq` is? I understand that `*_pass_1.fastq` and `*_pass_2.fastq` are for left and right sequences. But what is `*_pass_3.fastq` for, and why was `*_pass_3.fastq` generated?

I would appreciate your advice.

Thank you very much!

**Comment by kwrodarmer** [comment]
Given the settings you used, `fastq-dump` will place mated reads in the `*_1.fastq` and `*_2.fastq` outputs, and any unmated reads in `*_3.fastq`. So a run with perfectly mated reads would only generate the `*_1.fastq` and `*_2.fastq`, while a run with only unmated reads produces `*_3.fastq`.
