### ISSUE TITLE
fasterq-dump compressed result

### ISSUE THREAD

**Issue by huangl07** [ncbi/sra-tools#323]
Hi

I have tested the fasterq-dump to extract some SRR files

it was extremely faster than older one. 

But I have a little question that cou.ld fasterq-dump output fastq.gz file

it will same storage spaces

thankyou!

**Comment by kifeonu** [comment]
I'm curious about this also.
Thanks!

**Comment by klymenko** [comment]
Sorry, fasterq-dump does not support compression.

**Comment by splaisan** [comment]
this is very unfortunate!
can we output to a pipe and compress on the fly then?
thanks
