### ISSUE TITLE
issue with fastq-dump and fasterq-dump GSE139522

### ISSUE THREAD

**Issue by throwaway123-problems** [ncbi/sra-tools#326]
Hi, still very new to sequencing and related softwares. I'll try to be as detailed as possible.
Basically I'm working on an ubuntu command line server.
I created a new directory called ~/sraToolkit
Went into the new directory and typed `wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz`

Then unpacked it using `tar -xzf sratoolkit.current-ubuntu64.tar.gz`
Then added the following the line to my .bashrc:
`export PATH=$PATH:$HOME/sraToolkit/sratoolkit.2.10.5-ubuntu64/bin`

I then typed `vdb-config --interactive` and immediately exited so I wouldn't change the default parameters.
In my ~/ directory I then typed `prefetch GSE139522`
This created 4 directories in my ~/ directory called
SRR10357640
SRR10357641
SRR10357642
SRR10357643
Corresponding to the 4 files associated with this accession number, each with a corresponding .sra files.
I ran `vdb-validate` on each of the .sra files and everything was returned as OK & consistent at the end of the command.
To get fastq files:
First I tried to `fasterq-dump GSE139522` and it failed. I also tried `fastq-dump GSE139522` and it failed.
I then tried to run `fasterq-dump SRR10357640` `fasterq-dump SRR10357641` `fasterq-dump SRR10357642` `fasterq-dump SRR10357643` within the corresponding directories and they all failed. I then tried fastq-dump in each of the directories by typing `fastq-dump SRR10357640` `fastq-dump SRR10357641` `fastq-dump SRR10357642` `fastq-dump SRR10357643` and they all failed except for SRR10357640. SRR10357640 produced a fastq file approx 138GB. The failed attempts on the others gave back error code 3 and produced fastq files that were < 20GB.

I can't tell if the files are bad on NCBI or if I'm not downloading it correctly.
I don't really understand either why I am downloading .sra files if I have to just redownload the .fastq files from the web and why the one is working and the other is failing.
All I really care is how to get the .fastq files associated with this accession #. What am I doing wrong and how do I go about getting the fastq files. Thanks for reading!

**Comment by kwrodarmer** [comment]
@throwaway123-problems  - you closed this without any explanation. What changed?

**Comment by throwaway123-problems** [comment]
@kwrodarmer The files I was trying to download seem to .bam files based on: https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP227279

The original paper that provided the accession number said it was sequenced on a 10x platform. 
https://www.nature.com/articles/s41593-020-0587-9
Based on the 10x website: https://support.10xgenomics.com/single-cell-gene-expression/sequencing/doc/technical-note-instructions-to-download-and-process-bam-files-of-13-million-brain-cells

10x directly advises against using prefetch and sra toolkit. I figured this was the issue I was having. I haven't yet tried to download the files using wget or aria2c but expect it will work. It would have been great if somewhere on the NCBI github page or .gov website I would be able to find this information. Rather all I could find were consistent mentions that I should use sra toolkit (not complaining, just thinking how to make this more user friendly moving forward).
