### ISSUE TITLE
- unable to obtain a password

### ISSUE THREAD

**Issue by montenegrina** [ncbi/sra-tools#327]
Hello,

I was trying to decrypt files I downloaded from DbGap via:

anamaria@login-1[SABER]: /projects/com_grassim/anamaria/anamaria/anamaria/GOKIND/75327/PhenoGenotypeFiles/RootStudyConsentSet_phs000018.GAIN_GoKinD.v2.p1.c1.DS-T1DCR-IRB/GenotypeFiles $ /home/anamaria/sratoolkit.2.10.5-centos_linux64/bin/vdb-decrypt phg000008.v1.GoKinD_all_samples.genotype-qc.Affy500K.c1.DS-T1DCR-IRB.tar.ncbi_enc 
2020-05-11T22:05:35 vdb-decrypt.2.10.5 err: encryption key not found while opening manager within virtual file system module - unable to obtain a password
2020-05-11T22:05:35 vdb-decrypt.2.10.5: exiting: RC(rcVFS,rcMgr,rcOpening,rcEncryptionKey,rcNotFound) (2615479768)

I did downloaded the prj_14881.ngc encryption file from the DbGap and place it in the same directory from where I am running this

I also did 
vdb-config -i prj_14881.ngc

Can you please advise?

**Comment by kwrodarmer** [comment]
Please see https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data for more information. If you still need help, let us know!

**Comment by montenegrina** [comment]
Hello,

I did try to do this:
export
VDB_PWFILE=/home/anamaria/sratoolkit.2.10.5-centos_linux64/bin/vdb-passwd

but still it doesn't work. Can you please look into this?

Thanks
Ana

**Comment by kwrodarmer** [comment]
Hi Anna. I advise you to actually read the page I sent you. One of the things is says emphatically is to never try to set VDB_PWFILE. I'm not sure what you want us to look into.

**Comment by montenegrina** [comment]
Thank you so much, this works
vdb-decrypt --ngc prj_14881.ngc
phg000008.v1.GoKinD_all_samples.genotype-qc.Affy500K.c1.DS-T1DCR-IRB.tar.ncbi_enc

Can you please tell me just how I would decrypt all files in current directory?
Can I do this?
vdb-decrypt --ngc prj_14881.ngc  *.tar.ncbi_enc

**Comment by kwrodarmer** [comment]
Running `vdb-decrypt --help` gives you a description of its operation. You want
```
vdb-decrypt --ngc <path-to-ngc-file> <path-to-directory>
```
Note that all files in the directory that are encrypted at all will be decrypted and overwritten using the keys obtained using the _NGC_ token. If you are not certain that you have the right _NGC_ token, you can make a copy of the files first.

**Comment by Clover2019** [comment]
I followed what are mentioned in this post (vdb-decrypt --ngc <path-to-ngc-file> <path-to-directory>), and still I got error "too many parameters". I have been trying to find solutions all day long, but failed to get one. Is there an older version compared to 2.10.5 that I can use? Thank you!

**Comment by Clover2019** [comment]
Never mind. I just figured it out. Thank you!

**Comment by GhaliaRehawi** [comment]
Hi, I am having the same issue on my CentOS. I have installed the sra-tools(v2.10.8) and downloaded the ngc file. I am following the exact instruction stated [here](https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data.)

when executing: vdb-decrypt --ngc prj_phsEXAMPLE.ngc <encrypted_file> on my .ncbi_enc file I get the following error:

vdb-decrypt.2.10.8 warn: file wrong type while reading file within configuration module - could not build vfs-resolver
vdb-decrypt.2.10.8 err: encryption key not found while opening manager within virtual file system module - unable to obtain a password
vdb-decrypt.2.10.8: exiting: RC(rcVFS,rcMgr,rcOpening,rcEncryptionKey,rcNotFound) (2615479768)

I appreciate any help.
Thanks

**Comment by klymenko** [comment]
@GhaliaRehawi, do you still need help?
