### ISSUE TITLE
fasterq-dump.2.10.5 err: index.c get_nearest_offset() -> too many rounds pos

### ISSUE THREAD

**Issue by glev-doug** [ncbi/sra-tools#331]
I'm running prefetch on many SRA accessions to download .sra files before performing fasterq-dump. I've encountered this error multiple times, and am unable to find any guiding information. I am not sure if there is something improper about the .sra file itself or an issue with the tool. 

`fasterq-dump.2.10.5 err: index.c get_nearest_offset() -> too many rounds pos = 24 of 40`

Thank you in advance for any guidance. Hopefully others may be better informed from this issue as well.

**Comment by kwrodarmer** [comment]
Thank you for the report - we'll investigate.

**Comment by klymenko** [comment]
@glev-doug, have you tries our latest release? Do you still have this issue?
