### ISSUE TITLE
fastq-dump split-files results

### ISSUE THREAD

**Issue by bapoorva** [ncbi/sra-tools#333]
Hi,

I recently downloaded single cell RNA seq data [GSE132880](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE132880) from GEO using the following commands

```
prefetch --max-size 100000000 SRR9313695
fastq-dump --outdir ~/Desktop/server/SRA --split-files SRR9313695
```

This gave me 3 files SRR9313695_1.fastq, SRR9313695_2.fastq and SRR9313695_3.fastq. I want to align them using [STARSolo](https://github.com/alexdobin/STAR/blob/2.7.3a/docs/STARsolo.md). I wasn't  entirely sure if the three fastq's are equivalent of the result of Cellranger mkfastq output files file_R1_001.fastq.gz, file_R2_001.fastq.gz, file_I1_001.fastq.gz which are reads 1(barcode) and 2 (cDNA) and sample index.  I looked at the files and I think SRR9313695_1.fastq is cDNA and SRR9313695_2.fastq is barcode. Am i right to assume that ?

**Comment by durbrow** [comment]
I believe you are correct, but there appears to be something wrong with the data file itself. Can you email sra-tools@ncbi.nlm.nih.gov and ask the SRA data curation team to look? 

(This is the software development team, we don't generally deal with the data, and we can't fix it ourselves.)

**Comment by bapoorva** [comment]
It was right. Just went back and looked at the metadata

https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR9313701
