### ISSUE TITLE
fastq-dump: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./fastq-dump)

### ISSUE THREAD

**Issue by ghost** [ncbi/sra-tools#335]
Hi Team,

I tried to use SRAtools on our CentOS server:

However, when I try to use sra:
./fastq-dump
 I always get the error
./fastq-dump: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./fastq-dump)

When trying 

it shows that version 2.12 of GLIBC is installed.
So I tried
module load glibc/2.14
but I still get the same error.
Do you have any idea how I could solve this?

Thank you so much,
-Karl

**Comment by kwrodarmer** [comment]
Hello, Karl. I'm afraid you have 2 options:
1. build everything from source - 4 projects, **_-OR-_**
2. use a more modern version of the OS
