### ISSUE TITLE
issue with samtools-dump

### ISSUE THREAD

**Issue by kb472** [ncbi/sra-tools#34]
Hello,
I downloaded the binary for sra-tools for Ubuntu 64 bit. I tried to test sam-dump, but its giving me an error

> sam-dump -h
/home/software/sratoolkit.2.6.3-ubuntu64/bin/sam-dump: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/software/sratoolkit.2.6.3-ubuntu64/bin/sam-dump)

**Comment by kwrodarmer** [comment]
It's not sam-dump that gives the error, but your Ubuntu version that does not have a necessary library. Please let us know what version of Ubuntu you are running. Chances are good you'll need to download the sources and build the toolkit for your system.
