### ISSUE TITLE
fastq-dump.2.10.7 err: directory not found

### ISSUE THREAD

**Issue by jenniferyjlin** [ncbi/sra-tools#340]
Hi,
I tried to run
_**./fastq-dump --gzip --split-e /home/jennifer/RNA/SRR/SRR10611698.sra --outdir /home/jennifer/RNA/SRR/**_

However, I got these messages:

> 2020-06-01T07:40:30 fastq-dump.2.10.7 err: directory not found while opening manager within virtual file system module - failed /home/jennifer/RNA/SRR/SRR10611698.sra
>> An error occurred during processing.
>> A report was generated into the file '/home/jennifer/ncbi_error_report.txt'.
>> If the problem persists, you may consider sending the file
>> to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
>
> fastq-dump quit with error code 3

I made sure the SRR10611698.sra did exist in the directory because when I
_**ls /home/jennifer/RNA/SRR/**_
it did show:
**_SRR10611698.sra_**

I am stuck in this step for so long...
If I did anything wrong, please let me know.

**Comment by klymenko** [comment]
@jenniferyjlin, do you still need help?
