### ISSUE TITLE
an error when running fasterq-dump

### ISSUE THREAD

**Issue by wisekh6** [ncbi/sra-tools#341]
Hi,

I wanted to download a pair of fastq files (~50 Gb in total), but I have the following error.
Would you please guide me on how to work around this error?

Thank you in advance,

```
$ fasterq-dump --split-files SRR8670775
2020-06-02T03:27:29 fasterq-dump.2.10.7 err: sorter.c write_to_store().pack_read_2_4na() failed RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)
2020-06-02T03:43:44 fasterq-dump.2.10.7 err: transfer canceled while allocating buffer within file system module - Cannot KHttpFileTimedReadChunked: to=480
2020-06-02T03:43:45 fasterq-dump.2.10.7 err: sorter.c run_producer_pool().join_and_release_threads -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)
2020-06-02T03:43:45 fasterq-dump.2.10.7 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)
2020-06-02T03:43:45 fasterq-dump.2.10.7 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcWriting,rcFormat,rcNull)
fasterq-dump quit with error code 3
```

**Comment by kwrodarmer** [comment]
There is not a _lot_ of information to go on there. Please ensure that you have sufficient working space on your volume. `fasterq-dump` has to download the SRA files and make use of temporary files to perform its task, as well as produce the final output.

You can break these phases up by first retrieving the files using `prefetch` and afterward running `fasterq-dump`. Please try that and write back if your problem persists.

**Comment by wisekh6** [comment]
Thanks a lot for your response, and sorry for providing a limited information.
I was working in a HPC with a large amount of available space.

And thanks for suggesting `prefetch` and then `fasterq-dump`. May I ask you to provide a link describing this two-step approach?

Thanks in advance,

**Comment by kwrodarmer** [comment]
I don't know that we have a page explaining exactly that, but here are a couple of pages:

_This page is fairly out of date, but shows use of prefetch_
https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data

_This page is more up to date_
https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump

**Comment by wisekh6** [comment]
Thanks a lot for your quick response.
I will go over those pages, and will try the two-step approach.

Best,

**Comment by wisekh6** [comment]
Hi,
It looks like the following two approaches download different sizes of fastq files. 
Would you give me your comment on how I can get identical files from the two different approaches?

Thank you in advance,

Using `fasterq-dump SRR000001`, I have the following:
```
$ ll fastq/
total 350608
-rw-r--r-- 1 kimh jaxuser  70846962 Jun  2 09:53 SRR000001_1.fastq
-rw-r--r-- 1 kimh jaxuser  78848372 Jun  2 09:53 SRR000001_2.fastq
-rw-r--r-- 1 kimh jaxuser 147526886 Jun  2 09:53 SRR000001.fastq
```

And, using `prefetch --max-size 100000000 SRR000001 && fasterq-dump --split-files SRR000001/SRR000001.sra`, I have the following:
```
$ ll prefetch2fastq/
total 356752
drwxr-sr-x 2 kimh jaxuser        31 Jun  2 10:16 SRR000001
-rw-r--r-- 1 kimh jaxuser 221878910 Jun  2 10:17 SRR000001.sra_2.fastq
-rw-r--r-- 1 kimh jaxuser  80999518 Jun  2 10:17 SRR000001.sra_4.fastq
```

**Comment by durbrow** [comment]
`fasterq-dump --split-files` produces different output than `fasterq-dump` without `--split-files`. This is by design. By default, `fasterq-dump` without additional options is the same as `fasterq-dump --split-3 --skip-technical`.

**Comment by wisekh6** [comment]
Thanks for your quick response.

I would like to have `prefetch --max-size 100000000 SRR000001 && fasterq-dump [OPTIONS] SRR000001/SRR000001.sra` generate `SRR000001_1.fastq, SRR000001_2.fastq, SRR000001.fastq`. 
Can you suggest what should be [OPTIONS]?

Thanks in advance,

**Comment by durbrow** [comment]
Did you try `prefetch --max-size 100000000 SRR000001 && fasterq-dump SRR000001`? It is supposed to work. It did for me just now.

**Comment by wisekh6** [comment]
Yes, I tried. but the file sizes are different between the following two approaches.
Can you help with how I can have identical file sizes?

Thanks,


Using `fasterq-dump SRR000001`, I have the following:
```
$ ll fastq/
total 350608
-rw-r--r-- 1 kimh jaxuser  70846962 Jun  2 09:53 SRR000001_1.fastq
-rw-r--r-- 1 kimh jaxuser  78848372 Jun  2 09:53 SRR000001_2.fastq
-rw-r--r-- 1 kimh jaxuser 147526886 Jun  2 09:53 SRR000001.fastq
```

Using, `prefetch --max-size 100000000 SRR000001 && fasterq-dump SRR000001`, I have:
```
ll test2/
total 356720
-rw-r--r-- 1 kimh jaxuser  72735290 Jun  2 10:37 SRR000001.sra_1.fastq
-rw-r--r-- 1 kimh jaxuser  80736700 Jun  2 10:37 SRR000001.sra_2.fastq
-rw-r--r-- 1 kimh jaxuser 149406438 Jun  2 10:37 SRR000001.sra.fastq
```

**Comment by durbrow** [comment]
Try `head -n 1 SRR000001.fastq` and `head -n 1 SRR000001.sra.fastq`. You should see that the read names are slightly different. If you do `wc -l` on the two file sets, you should see that the line counts of corresponding files is the same.

**Comment by wisekh6** [comment]
Thanks for the comments.

I confirmed that # of file lines are identical between the two groups.
Do you know how we can confirm both have identical contents? In other words, can we check file integrity between the two groups of files?

**Comment by wisekh6** [comment]
I compared the files after sorting, but they are different.
Was I wrong? Your help will be highly appreciated.

Thank you in advance.

```
sort SRR000001_1.fastq > SRR000001_1.sorted.fastq
sort SRR000001.sra_1.fastq > SRR000001.sra_1.sorted.fastq
diff SRR000001_1.sorted.fastq  SRR000001.sra_1.sorted.fastq

...
< @SRR000001.sra.308664 EM7LVYS01B2N7F length=123
< +SRR000001.sra.308664 EM7LVYS01B2N7F length=123
< @SRR000001.sra.308671 EM7LVYS01EROED length=16
< +SRR000001.sra.308671 EM7LVYS01EROED length=16
< @SRR000001.sra.308673 EM7LVYS01AS1XU length=50
< +SRR000001.sra.308673 EM7LVYS01AS1XU length=50
< @SRR000001.sra.308674 EM7LVYS01ETOF6 length=182
< +SRR000001.sra.308674 EM7LVYS01ETOF6 length=182
< @SRR000001.sra.308677 EM7LVYS01E3AEY length=159
< +SRR000001.sra.308677 EM7LVYS01E3AEY length=159
< @SRR000001.sra.308679 EM7LVYS01CYLNY length=124
< +SRR000001.sra.308679 EM7LVYS01CYLNY length=124
< @SRR000001.sra.308681 EM7LVYS01EORYA length=49
< +SRR000001.sra.308681 EM7LVYS01EORYA length=49
< @SRR000001.sra.308684 EM7LVYS01DZ6SP length=77
...
```

**Comment by durbrow** [comment]
It's not hard in this particular case but I don't have a ready solution for it. You should read up on [the FASTQ 'format'](https://en.wikipedia.org/wiki/FASTQ_format).

There is no general solution. There is so much legitimate variability in FASTQ files that there is no general means of determining that two different sets of FASTQ are in fact the same. For example, there is no requirement that the read names should match between the two sets, and no requirement that the reads should be in the same order between the two sets, or that read orientation (5'-3' vs 3'-5') should be the same.

However, in this particular case, if you filtered out lines starting with `@SRR000001` or `+SRR000001`, the rest should be identical.

**Comment by wisekh6** [comment]
Got it.
Very appreciating for your prompt responses, and I definitely agree with your comments.
I will close this ticket. Stay healthy.

**Comment by wisekh6** [comment]
Hi
While the above download using a small file worked without error, download a big file fails.
Our HPC environment has available space >=100 T bp.
Can you help me with the following errors?

Thank you in advance,

```
$ prefetch --max-size 100000000 SRR8670775 --output-directory /fastscratch/prefetch
...
...
2020-06-02T21:58:13 prefetch.2.10.7: 1) Downloading 'SRR8670775.vdbcache'...
2020-06-02T21:58:13 prefetch.2.10.7: 1) 'SRR8670775.vdbcache' was downloaded successfully

$ fasterq-dump /fastscratch/prefetch/SRR8670775/SRR8670775.sra --outdir /fastscratch/fastqs -t /fastscratch/tmp
2020-06-02T22:10:32 fasterq-dump.2.10.7 err: cmn_iter.c cmn_iter_open_db().VDBManagerOpenDBRead( 'SRR8670775.sra' ) -> RC(rcVFS,rcMgr,rcOpening,rcDirectory,rcNotFound)
2020-06-02T22:10:32 fasterq-dump.2.10.7 err: sorter.c run_producer_pool(): row_count == 0!
2020-06-02T22:10:32 fasterq-dump.2.10.7 err: sorter.c execute_lookup_production() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
2020-06-02T22:10:32 fasterq-dump.2.10.7 err: fasterq-dump.c produce_lookup_files() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
fasterq-dump quit with error code 3
```

**Comment by durbrow** [comment]
Where you able to get around your problem?
