### ISSUE TITLE
sra toolkit premade binary for windows seems out of date compared to source.

### ISSUE THREAD

**Issue by dengel92** [ncbi/sra-tools#342]
I downloaded the latest prebuilt package of SRAtoolkit for windows and it seems that the commands that are available seem to be outdated compared to what is available on github. For one thing there is no `fasterq-dump` command nor is there a `--split-3` option for `fastq-dump`. I was wondering if someone could help me with installing the package from source. Thanks.

**Comment by klymenko** [comment]
Currently `fasterq-dump` is not available on Windows.
`fastq-dump` on Windows is the same as on Linux.
`fastq-dump` and `fasterq-dump` have different set of options.
