### ISSUE TITLE
Accession might be available in a different region or on a different cloud provider

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ncbi/sra-tools#345]
THIS IS NOT A DUPLICATE. 
I know that there is another issue dedicated to this but no actionable outcome. 

I'm using SRA-toolkit version 2.10.7 

I was running fasterq-dump with no special flags. 
I tried to get a few accessions which was working yesterday and then all of a sudden I'm getting... 

ERROR: 
`Accession might be available in a different region or on a different cloud provider.
Or you can get an ngc file dbGaP, and rerun with --ngc <file>` 

How can I get past this error?

**Comment by kwrodarmer** [comment]
> THIS IS NOT A DUPLICATE

I'm not sure how you could know that - it's not apparent to me. We are analyzing backend components for a problem. This is not an error in your toolkit. Please bear with us.

**Comment by YogiOnBioinformatics** [comment]
I mean to say it's not a duplicate since there is another issue that is identical but there were no actionable outcomes from it. 

thanks for helping. 
Please let me know if you would like the SRR numbers if that might help in debugging.

**Comment by kwrodarmer** [comment]
Yes, any information is helpful - thanks!

**Comment by YogiOnBioinformatics** [comment]
Here are the exact commands I ran which include the SRR identifiers. 
`/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985461
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985462
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985463
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985464
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985465
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985466
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985467
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985468
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985469
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985470
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985471
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985472
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985473
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985474
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985475
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985476
/usr/local/sratoolkit/bin/fasterq-dump -O raw_fastq/ SRR10985477
`

**Comment by kwrodarmer** [comment]
Thank you! And sorry about the disruption.

**Comment by YogiOnBioinformatics** [comment]
Yes this fixed my issue! 
this is awesome! 

i appreciate you working so quickly to fix this. 
will you plan on re-deploying those changes you made? 
asking so I know if i should download my data by a certain time.

**Comment by kwrodarmer** [comment]
> asking so I know if i should download my data by a certain time

Haha! Thanks, that made my day.

**Comment by YogiOnBioinformatics** [comment]
oh alright well no worries! 
thanks so much for your quick work and help with this! 

take care!

**Comment by amizeranschi** [comment]
@kwrodarmer 
> Please bear with us.

Now THAT line made my day, hehe. Thanks again for looking into these issues.
