### ISSUE TITLE
How to access data with token?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ncbi/sra-tools#347]
I have a dataset I want to download since I have a token to access it but don't know how to do so with `fasterq-dump`.  
To be more specific, I have a token to access the GSE130570 data. 
I don't know how to download this data with the token I have using `fasterq-dump`. 
Is there any way to download not-yet public data using a token with `fasterq-dump`?

I'm using SRA-toolkit version 2.10.7

**Comment by YogiOnBioinformatics** [comment]
sorry just wanted to follow up on this.

**Comment by YogiOnBioinformatics** [comment]
sorry to bother. 
just wanted to follow up on this again.

**Comment by kwrodarmer** [comment]
If you go to https://www.ncbi.nlm.nih.gov and type in `GSE130570` in the search bar, it will show you a hit in PubMed Central. This identifier cannot be used with the SRA Toolkit.

**Comment by pablo-baeza** [comment]
Hi @YogiOnBioinformatics , in the end, did you manage to download the restriced-access data? I am reviewing a paper and so I'm in a similar position, but I can't seem to figure out how to download the raw sequencing data.

**Comment by kwrodarmer** [comment]
@pablo-baeza - please see https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data and follow links it gives.

**Comment by pablo-baeza** [comment]
Thanks for the reply, but I'm not sure how this applies. My data is not on dbGap, it's uploaded to GEO and has it's own SRA numbers. My reviewer token is a string of numbers and letters, not a file.

**Comment by kwrodarmer** [comment]
I suggest that for GEO-related questions you contact the GEO team.

**Comment by YogiOnBioinformatics** [comment]
Hello @pablo-baeza 

I was on vacation so sorry! 
Sorry to hear you're in this situation as well. 

I ended up contacting the authors directly and having to get the data from their servers.

**Comment by pablo-baeza** [comment]
Yes this seems to be the only workaround for me as well. Thanks!
