### ISSUE TITLE
path not found while resolving argument list - can not use source 'vdb-decrypt'

### ISSUE THREAD

**Issue by montenegrina** [ncbi/sra-tools#349]
Hello,

I am trying to decrypt some files, and I installed the software here:
/home/anamaria/sratoolkit.2.10.5-centos_linux64/bin
when I run the software I am in:
/projects/com_grassim/anamaria/anamaria/anamaria/eMerge

and I do:
export PATH=/home/anamaria/sratoolkit.2.10.5-centos_linux64/bin:$PATH
anamaria@login-1[SABER]: /projects/com_grassim/anamaria/anamaria/anamaria/eMerge $ vdb-decrypt --ngc prj_14881.ngc vdb-decrypt /projects/com_grassim/anamaria/anamaria/anamaria/eMerge/75874/PhenoGenotypeFiles/RootStudyConsentSet_phs000360.eMERGE_MergedSet.v3.p1.c4.HMB-GSO
2020-06-05T18:35:21 vdb-decrypt.2.10.5 err: path not found while resolving argument list - can not use source 'vdb-decrypt'
2020-06-05T18:35:21 vdb-decrypt.2.10.5: exiting: RC(rcExe,rcArgv,rcResolving,rcPath,rcNotFound) (8522008)

Can you please assist with this?

Thanks
Ana

**Comment by durbrow** [comment]
Have you figured out your problem?

If not, it looks like you have an extra `vdb-decrypt` in your command. `vdb-decrypt` is interpreting the second `vdb-decrypt` as the name of a file to process and then not finding it. Your command should be:
`vdb-decrypt --ngc prj_14881.ngc /< ... >/RootStudyConsentSet_phs000360.eMERGE_MergedSet.v3.p1.c4.HMB-GSO`

**Comment by montenegrina** [comment]
Hello,

yes I did and:
vdb-decrypt --ngc prj_14881.ngc /...files
worked for me.

Cheers,
Ana
