### ISSUE TITLE
fastq-dump.2.10.1 err: item not found...

### ISSUE THREAD

**Issue by rderrico** [ncbi/sra-tools#358]
Hi, I'm running fastq-dump (`fastq-dump --split-files SRR1972917`) and getting this error: `2020-06-14T23:21:46 fastq-dump.2.10.1 err: item not found while constructing within virtual database module - the path 'SRR1972917' cannot be opened as database or table`.

I get the same error with any SRR id. I couldn't find any solution anywhere... 

Thanks in advance for your help.

**Comment by kwrodarmer** [comment]
Hi @rderrico - it would help us to have you first upgrade to the latest release 2.10.7 and try that. If you have problems with that version, please report them here and we can follow up.

**Comment by wt12318** [comment]
Hi, I have encountered the same problem, and I used 2.10.7:
```
fastq-dump --split-e SRR481248.sra -O ./
```
```
2020-08-08T15:17:45 fastq-dump.2.10.7 err: item not found while constructing within virtual database module - the path 'SRR481248.sra' cannot be opened as database or table
fastq-dump quit with error code 3
```

**Comment by klymenko** [comment]
@rderrico, @wt12318, do you still need help?

**Comment by rderrico** [comment]
Thanks, I could resolved it. It was that I was using an old version. With the last version I had no problem.

Thank you!

-------------------------------------------------------------
GenDI - Centro de Estudios Genéticos
Análisis de ADN - Paternidad
San Lorenzo 1630 - Local 103
Posadas - Misiones
Tel. fijo (0376) 5260170 - Cel. +5493764282639
www.genid.com.ar <http://www.genid.com.ar/>
