### ISSUE TITLE
100bp size limitation to blastn_vdb 

### ISSUE THREAD

**Issue by ghost** [ncbi/sra-tools#36]
Using blastn_vdb to search for short sequences, I only get reads of >100bp as hits, whereas if I blast two sequences locally with same SRA read file downloaded, I get hits to the small fragments (which I want). Is blast_vdb fitlering the reads into is db? Is there a way to remove this size filtering?

**Comment by bioinformatics-deakin** [comment]
Also getting this error frequently:
BLAST engine error: NCBI C++ Exception:
    T0 "/export/home/tomcat/TeamCity/Agent5/work/77e03de3cd30af63/blastn/c++/src/algo/blast/api/prelim_stage.cpp", line 300: Error: BLAST::ncbi::blast::CBlastPrelimSearch::Run() - search cannot proceed due to errors retrieving sequences from databases

**Comment by bioinformatics-deakin** [comment]
Is this program still supported?

**Comment by kwrodarmer** [comment]
By “this program” do you mean blastn_vdb? Yes, of course.

Your reports are being forwarded to the blast team.

Thank you,
SRA Toolkit Team


On Aug 25, 2016, at 9:25 PM, Deakin University Bioinformatics Team <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this program still supported?

**Comment by klymenko** [comment]
Do you still need help?
