### ISSUE TITLE
prefetch only completes ~30% of data

### ISSUE THREAD

**Issue by satzel** [ncbi/sra-tools#360]
Hi, I am using sratoolkit.2.10.7 with this command

`prefetch cart_Dxxxx_xxxxx.krt -X 200G --ngc prj_xxxxxx.ngc`

and it's only 10 SRR-IDs in the cart to try it out.
But it seems like the majority of downloads does not finish, only 3 out of 10 SRR*.sra files are downloaded entirely and the other 7 stay as *.sra.tmp files.
Also I tried this 3 times or so and there were always some files missing (more than have completed the download) but never the same files.
Is there a better way to download? I will have to get ~800 files, this seems a bit tedious when over half will be missing?

Many thanks
Satz

**Comment by klymenko** [comment]
@satzel , please send an email to sra-tools@ncbi.nlm.nih.gov
