### ISSUE TITLE
Parallel use of prefetch of SRA files from AWS S3 leads to NCBI abuse message & blocking?

### ISSUE THREAD

**Issue by taltman** [ncbi/sra-tools#363]
Hi all,

My apologies if this is not the right place to file this issue.

I'm downloading SRA files using prefetch on an AWS EC2 instance in the
us-east-1 region. I've used vdb-config -i to make sure that I'm using
AWS S3 to fetch the SRA files. Here's the output of srapath to show that I'm fetching from S3:

```
> srapath ERR169824
https://sra-pub-run-5.s3.amazonaws.com/ERR169824/ERR169824.1
```

I'm on a beefy EC2 instance with 96 cores, with each core running prefetch and then processing the SRA file with blast_vdb. Sometimes the two processes complete in a few seconds, sometimes it takes them up to 4 minutes. After my job was running for a while, I got this message:

```
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils201] Auto-blocked
for abuse, please contact NCBI help desk <info@ncbi.nlm.nih.gov>
```

Are there resource limitations when downloading on S3, as there are with
using EUtils? Time-of-day, time-of-week, and/or rate limits? How to avoid this issue?

Thank you!

**Comment by yaschenk** [comment]
It looks like you are uncovering some unintended pathways. We are investigating. There should be no limitation on S3 downloads.

**Comment by taltman** [comment]
Just in case you are not aware, I've been posting some more details here:

https://github.com/ncbi/ncbi-vdb/issues/28

**Comment by kwrodarmer** [comment]
I'm going to close this issue and refer everyone to the VDB ticket referenced above:

ncbi/ncbi-vdb#28
