### ISSUE TITLE
fasterq-dump is runing but no output in temp

### ISSUE THREAD

**Issue by Zhuxitong** [ncbi/sra-tools#364]
I have downloaded a sra file with prefetch with following code:
```
prefetch -X 100G -O ./ SRR1171005
```
and I got SRR1171005.sra then when I run 
```
fasterq-dump -O ./ -e 10 SRR1171005.sra
```
Here is a tmp dir called 'fasterq.tmp.login.28163' but for half hours, nothing in there and the command didn't stop, any suggestions?  Is this related to the 'RAM used' in vdb-config -i because there 0 RAM by default?

**Comment by klymenko** [comment]
Use `-p` to see progress of `prefetch` and `fasterq-dump`.
Don't use `-O ./ for` `prefetch`. Run instead: `prefetch -X 100G SRR1171005`

Then run 'fasterq-dump' as `fasterq-dump -e 10 SRR1171005`
Do you really have 10 CPU cores?
See information about fasterq-dump in https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump

**Comment by klymenko** [comment]
Do you still need help?
