### ISSUE TITLE
Transfer Canceled While Allocating Buffer Within File System

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ncbi/sra-tools#365]
I am using SRA-toolkit version 2.10.7 and these were the EXACT commands I ran that gave me the output below:

/usr/local/sratoolkit/bin/fasterq-dump SRR8119837
/usr/local/sratoolkit/bin/fasterq-dump SRR8119865

`2020-06-19T02:39:46 fasterq-dump.2.10.7 err: cmn_iter.c cmn_read_String( #30867457 ).VCursorCellDataDirec
t() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-06-19T02:39:46 fasterq-dump.2.10.7 err: cmn_iter.c cmn_read_String( #16171009 ).VCursorCellDataDirec
t() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-06-19T02:39:46 fasterq-dump.2.10.7 err: cmn_iter.c cmn_read_String( #74350593 ).VCursorCellDataDirec
t() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-06-19T02:39:46 fasterq-dump.2.10.7 err: cmn_iter.c cmn_read_String( #45219841 ).VCursorCellDataDirec
t() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)
2020-06-19T02:56:33 fasterq-dump.2.10.7 err: transfer canceled while allocating buffer within file system
 module - Cannot KHttpFileTimedReadChunked: to=480
2020-06-19T02:56:33 fasterq-dump.2.10.7 err: transfer canceled while allocating buffer within file system
 module - Cannot KHttpFileTimedReadChunked: to=480
2020-06-19T02:56:33 fasterq-dump.2.10.7 err: transfer canceled while allocating buffer within file system
 module - Cannot KHttpFileTimedReadChunked: to=480
2020-06-19T02:56:33 fasterq-dump.2.10.7 err: transfer canceled while allocating buffer within file system
 module - Cannot KHttpFileTimedReadChunked: to=480
fasterq-dump quit with error code 3`

**Comment by kwrodarmer** [comment]
Thanks, @YogiOnBioinformatics. We will try to duplicate.

**Comment by YogiOnBioinformatics** [comment]
alright no worries! 
let me know what happens. 

how is the new toolkit update QA/QC going? :)

**Comment by kwrodarmer** [comment]
We didn't get it out yesterday, and can't today due to the Friday rule. So look for Monday. I'm very sorry!

**Comment by YogiOnBioinformatics** [comment]
hey no worries at all! 
that's understandable, it happens. :D

**Comment by YogiOnBioinformatics** [comment]
sorry to bother. 
just wanted to see if you were able to replicate this error?

**Comment by kwrodarmer** [comment]
We discovered cases where `fasterq-dump` was running out of stack space on some hosts and with certain runs. We are assembling the release now.

**Comment by YogiOnBioinformatics** [comment]
interesting. 
just to make sure I understand, this issue is also going to be solved in the upcoming release along with my other [issue](https://github.com/ncbi/sra-tools/issues/348) ????

**Comment by kwrodarmer** [comment]
I don't know that specifically. At this time we have our hands full with your previous issue.

**Comment by YogiOnBioinformatics** [comment]
alright that makes sense! 
so then after the previous issue, would you be able to tackle this? 😄

**Comment by YogiOnBioinformatics** [comment]
no clue how or why but this it worked all of a sudden when re-trying it many days later.
