### ISSUE TITLE
how to import .ngc file

### ISSUE THREAD

**Issue by TTTTaro** [ncbi/sra-tools#367]
Now the **vdb.config --import** is not available.
When I used the new command **vdb-decrypt.2.10.7 --ngc PATH directory**, I got this error: encryption key not found while opening manager within virtual file system module - unable to obtain a password
How can I correctly import the .ngc file? 
Thank you!

**Comment by TTTTaro** [comment]
**vdb-decrypt.2.10.7 --ngc <PATH> <directory>**

**Comment by durbrow** [comment]
Please email sra-tools@ncbi.nlm.nih.gov

**Comment by kseob** [comment]
The same error occurred to me. How do I solve this?

**Comment by klymenko** [comment]
See [github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data](https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data)
