### ISSUE TITLE
problem creating alias file from NCBI WGS database using taxid2wgs.pl

### ISSUE THREAD

**Issue by mdmarie9** [ncbi/sra-tools#368]
When I try to run this call to taxid2wgs.pl: 

$ ~ Desktop/taxid2wgs.pl -title "Bison WGS" -alias_file bison-wgs 9901

I get the message "zsh: permission denied: Desktop/taxid2wgs.pl"
I've tried downloading various BioPerl modules, redownloading the taxid2wgs.pl file itself, changing the location of the file, and other random troubleshooting methods, but nothing has worked. If anyone can help, I would really appreciate it!

**Comment by durbrow** [comment]
I am sure why you are asking this here. That isn't one of our tools. But...

Almost certainly Desktop/taxid2wgs.pl does not have the execute permissions set. Try:
{code}
chmod +x Desktop/taxid2wgs.pl
{code}
and try your command again.
