### ISSUE TITLE
Strange behavior prefetch/dbGAP

### ISSUE THREAD

**Issue by mikessh** [ncbi/sra-tools#37]
After adding a dbGAP project using `prj_XXX.ngc` file (downloaded from dbGAP web page) via `vdb-config -i`, I was not able to run the `prefetch` command due to **access denied** error. Upon manual inspection, the `~/.ncbi/dbGAP_XXX.enc_key` appears to contain a dbGap password that was previously used for my account. After changing it to the new password everything works fine. It seems quite strange for me that the file generated by `vdb-config` contains the old password that was changed.

**Comment by kwrodarmer** [comment]
Did you import the new ngc file?
