### ISSUE TITLE
faste-dump

### ISSUE THREAD

**Issue by elbakrifz** [ncbi/sra-tools#370]
I used fastq-dump --split-files SRR639657
I got 👍 
failed to resolve accession 'SRR639657' - Access denied - please request permission to access phs000465 / PCR in dbGaP. ( 403 )
error from srapath:
{
"CE-Token": null,
"responses": [
]}

after update the sratools 2.10.7

**Comment by kwrodarmer** [comment]
Please see
https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration
and
https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data
