### ISSUE TITLE
fastq-dump

### ISSUE THREAD

**Issue by petrovsn** [ncbi/sra-tools#371]
I've launched the standart test: fastq-dump --stdout -X 2 SRR390728 for sratoolkit 2.10.7. 
Application freeze and returns no any output. 
Elder version, 2.8.2 returns correct output.

**Comment by kwrodarmer** [comment]
At the time you filed this report, there were server problems on the backend.

**Comment by kwrodarmer** [comment]
If you try again with the latest toolkit, please report back if you are still having issues.
