### ISSUE TITLE
Downloading SRR using prefetch doesn't work, but no error. 

### ISSUE THREAD

**Issue by wt12318** [ncbi/sra-tools#375]
Dear author(s),

After I downloaded sra toolkit(2.10.8) and config it, I can't download SRR using prefetch:
```
prefetch --option-file runids.txt
```
and it does not report an error.
![image](https://user-images.githubusercontent.com/39486023/86307058-5cdee480-bc48-11ea-9970-762579987253.png)

**Comment by durbrow** [comment]
`--option-file` is currently broken. When we added the ability to our tools to handle cloud storage of SRA data, `--option-file` did not survive the update. We do intend to fix it, though.

**Comment by wt12318** [comment]
Thank you !
