### ISSUE TITLE
`blastn_vdb` inserts placeholder name for "query" sequence in SAM output

### ISSUE THREAD

**Issue by taltman** [ncbi/sra-tools#377]
I'm not sure if this is a Blast team question, but I suspect that this issue might arise due to the unique way that `blastn_vdb` deals with reference sequences and query sequences.

When I take a CoV genome such as:

https://github.com/ababaian/serratus/wiki/assets/Fr4NK.fa

which was derived from the following SRA:

https://www.ncbi.nlm.nih.gov/sra/?term=ERR2756788

And I try to map the reads back to the genome using `-outfmt 17` for SAM output, I noticed that, as per the SAM format specification, the read identifiers are stored in the QNAME column, and in the RNAME column there is the string `Query_1`. In the case of the genome above, the RNAME value should be `Bat`. 

Example text: 
```
SRA:ERR2756788.16422492.1       0       Query_1 1       255     151M    *       0       0       *       *       AS:i:151        EV:f:0  NM:i:0  PI:f:100        BS:f:279.964
SRA:ERR2756788.15291497.1       0       Query_1 1       255     151M    *       0       0       *       *       AS:i:130        EV:f:0  NM:i:0  PI:f:95.36      BS:f:241.185
SRA:ERR2756788.15233193.1       0       Query_1 1       255     65M86H  *       0       0       *       *       AS:i:65 EV:f:4.05202e-23        NM:i:0  PI:f:100        BS:f:121.153
```

This causes all sorts of mayhem downstream, as genome browsers cannot correctly show the mapped reads on the genome due to the ID mismatch.

Is this something unique to `blastn_vdb`? I haven't seen the issue reported for `blastn` itself. Any help you can provide in figuring this out would be greatly appreciated!

**Comment by kwrodarmer** [comment]
Hi @taltman,

Yes - this may be better answered by members of the blast team, but with regard to read names, please see this page in our Wiki - https://github.com/ncbi/sra-tools/wiki/Read-Names . It tries to show how/why we eventually arrived at the point of not supporting them, and it wasn't for lack of trying.

**Comment by taltman** [comment]
Hi @kwrodarmer,

Thanks for your reply. Perhaps my issue wasn't written clearly. I do not have any problem with the read identifiers in the QNAME column. I have a problem with the `-query` FASTA file argument to `blastn_vdb` not properly parsing the FASTA defline for the sequence identifier, and then placing that in the third column (aka RNAME). 

Can you confirm that this issue is not something sra-tools specific? If so, I'll forward it on to the Blast Team. Thanks!

**Comment by kwrodarmer** [comment]
The SRA Toolkit is not involved with parsing FASTA deflines - that would be a blast issue.

**Comment by taltman** [comment]
I confirmed that this is reproducible with plain `blastn`, reported issue to Blast Team via NCBI Help Desk.
