### ISSUE TITLE
Prefetch on windows ignores all arguments passed to ascp with --ascp-options

### ISSUE THREAD

**Issue by fhansen-qiagen** [ncbi/sra-tools#38]
The entire flag --ascp-options is broken on windows. 

prefetch --ascp-options -l1M SRRxxxxxxx
and 
prefetch --ascp-options '-l1M' SRxxxxxxx

has no effect on the actual parameters passed to the ascp-binary. 
Works fine on linux and mac.

**Comment by lg4search** [comment]
Any updates on this, please?

**Comment by klymenko** [comment]
@lg4search , FYI: currently availability to download via ascp from NCBI is being discontinued.
