### ISSUE TITLE
command-line help and --split-3

### ISSUE THREAD

**Issue by jayoung** [ncbi/sra-tools#381]
hi there, 

just a minor typo to fix in the command line help for fastq-dump, in v2.10.8:
`fastq-dump -h` says `NOTE! The '--split-3' option is recommended.` 

but that option doesn't seem to exist any more:
` fastq-dump --split-3
unrecognized option: '--split-3' `

I guess it should be --split-e now, right?

thanks very much,

Janet Young

**Comment by durbrow** [comment]
Thank you for letting us know. [This will be fixed in our next release.](https://github.com/ncbi/sra-tools/commit/183ee7bb94405f8aa3545a03005c4fa02711b79c)

**Comment by jayoung** [comment]
thanks!

**Comment by linsalrob** [comment]
This is not a minor typo. You have switched the option from `--split-3` to `--split-e`  and so all processing breaks. However, the documentation still mentions `--split-3`. 

Please clarify whether moving forward the option will be `--split-3` or `--split-e`?

**Comment by durbrow** [comment]
> This is not a minor typo. You have switched the option from `--split-3` to `--split-e`  and so all processing breaks. However, the documentation still mentions `--split-3`. 
> 
> 
> 
> Please clarify whether moving forward the option will be `--split-3` or `--split-e`?

https://github.com/ncbi/sra-tools/issues/336#issuecomment-670543465

split-3 is the correct spelling of the option.

**Comment by klymenko** [comment]
@jayoung, @linsalrob, do you still need help?

**Comment by Self-clarita** [comment]
Hi,

Im trying to use the --split-3 command and I get **--split-3: command not found**
Could someone please help me? 
Thanks

**Comment by durbrow** [comment]
`--split-3` is not a command, it is an option to `fastq-dump`. `fastq-dump` is the command.
