### ISSUE TITLE
mbedtls_ssl_read problems

### ISSUE THREAD

**Issue by roni-fultheim** [ncbi/sra-tools#382]
I am trying to download FASTQ files from the SRA archives for a few days now, with no success.
**FASTQ-DUMP gives this error:** 
`transfer interrupted while reading file within network system module - mbedtls_ssl_read returned -26880 ( SSL - Connection requires a read call )`
**FASTERQ-DUMP gives these errors:** 
`cmn_iter.c cmn_read_String( #31375361 ).VCursorCellDataDirect() -> RC(rcPS,rcCondition,rcWaiting,rcTimeout,rcExhausted)`
`row #88735745 : READ.len(202) != QUALITY.len(0) (F)`
and eventually 
`fatal: SIGNAL - Segmentation fault`

I would appreciate your help.
SRAToolkit Version: 2.10.8

**Comment by durbrow** [comment]
Use the `prefetch` tool and then try `fasterq-dump`. `prefetch` is much better at dealing with network issues.

**Comment by roni-fultheim** [comment]
still doesn't work when running a few processes together

**Comment by durbrow** [comment]
What doesn't work? `prefetch` or extracting fastq from the prefetched files?

**Comment by roni-fultheim** [comment]
Prefetch. Haven't gotten to trying multiprocessed fasterq dump after
prefetch.
Same problems occur using fastq dump, fasterq dump and prefetch, when
running a few files together.
I get a timeout error. Could that be a problem in the ncbi servers? We've
been constantly checking ours

Thank you

**Comment by durbrow** [comment]
Yes, the problem could be with NCBI's infrastructure. That isn't something the SRA Toolkit team can fix.

`prefetch` should be able to resume its operations with minimal re-download. Have you tried re-issuing the commands?

**Comment by roni-fultheim** [comment]
I have, and succeeded.
How can the problem be solved for future downloads?
In the future I would like to download using fasterq-dump only, as that is
the fastest tool available.

Thank you

**Comment by durbrow** [comment]
In my experience, `prefetch`+`fasterq-dump` is faster than `fasterq-dump` on its own. And `prefetch` is much better able to handle networking issues, that is its specialty. You use more disk space, but you get much faster processing.

`fasterq-dump` uses multiple threads to get more work done at once, but its multiple threads end up getting serialized by the network I/O. It is only really faster if it is operating on local files.

**Comment by klymenko** [comment]
@roni-fultheim, do you still need help?

**Comment by roni-fultheim** [comment]
Thank you for your response.
I currently download using prefetch and then fasterq-dump. Works fine so
far, very fast too.

**Comment by klymenko** [comment]
@roni-fultheim, do you need more help?

**Comment by roni-fultheim** [comment]
Thank you for your response.
I currently download using prefetch and then fasterq-dump. Works fine so
far, very fast too.
I apologise, for some reason my previous email was wrongly addressed.

Thank you
