### ISSUE TITLE
Number of files returned by fasterq-dump

### ISSUE THREAD

**Issue by mdanb** [ncbi/sra-tools#385]
Most of the time, when I have paired end data, and I do fasterq-dump, I get two files, one containing sra_1 and the other sra_2 in their filenames. However, I sometimes get an extra file (this happens with for example SRR000001 which is given as an example in the tutorial on the home page). Why is that?

**Comment by durbrow** [comment]
Every read that is in the _1 file has its mate in the _2 file, and every read that is in the _2 file has its mate in the _1 file, and the reads in the two files are in the same order with no missing entries. The reads which can not meet this strict requirement go into the third file.

**Comment by mdanb** [comment]
@durbrow so what exactly can be done with this third file? Is it just useless then?

**Comment by kwrodarmer** [comment]
> Is it just useless then?

That is up to you.

A decade ago, there was a lot of effort to salvage as much information as possible, and resulted in storage of unpaired mates. Now that processing is much cheaper, you may want to ignore them.
