### ISSUE TITLE
Error Code 3 in fasterq-dump

### ISSUE THREAD

**Issue by priyatamapandey** [ncbi/sra-tools#386]
Hi,
I have downloaded multiple SRA files and then converting those files in fast format using the faster-dump but returning an error for a single file (attached). I am using the lastest version of sratool kit.
Command used 

fasterq-dump -O /fastq_files/  $sra_fl

<img width="747" alt="Screen Shot 2020-07-31 at 4 19 33 PM" src="https://user-images.githubusercontent.com/17990280/89087707-01d50600-d34a-11ea-8169-cef419909f48.png">

Thank you for help in advance,
Priya

**Comment by durbrow** [comment]
Please upgrade to the latest version of the tools. We fixed a problem in `fasterq-dump` that was causing errors like yours.
