### ISSUE TITLE
sam-dump Parse error

### ISSUE THREAD

**Issue by ekushele** [ncbi/sra-tools#387]
During downloading sam file with sam-dump, I'm getting the following errror:
(The SRR: SRR8670674)
```
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 643009372
[main_samview] truncated file.
sam-dump was killed (signal 13)
```

What is it? What can I do to prevent this error?

Edit: sam-dump version 2.10.8

**Comment by klymenko** [comment]
@ekushele, what command do you execute?
