### ISSUE TITLE
does not load data from fastq files to directory

### ISSUE THREAD

**Issue by tillea** [ncbi/sra-tools#39]
I'm forwarding a bug from Debian.  You can find the full bug log [here](https://bugs.debian.org/824402).
I have build sra-toolkit 2.7.0 and got:
`$ latf-load --quality PHRED_33 -o test /usr/share/doc/python-biopython-doc/Tests/Quality/sanger_93.fastq`
`2016-09-01T13:27:09 latf-load.2.7 warn: file="/usr/share/doc/python-biopython-doc/Tests/Quality/sanger_93.fastq"`
`2016-09-01T13:27:09 latf-load.2.7 warn: /usr/share/doc/python-biopython-doc/Tests/Quality/sanger_93.fastq:1:12:syntax error, unexpected fqWS`
`2016-09-01T13:27:09 latf-load.2.7 warn: The file contained no records that were processed.`
`2016-09-01T13:27:09 latf-load.2.7 err: libs/kproc/queue.c:356:KQueuePop: data empty while reading file within alignment module - accession="test" errors="1" status="failure"`
`2016-09-01T13:27:09 latf-load.2.7 err: libs/kproc/queue.c:356:KQueuePop: data empty while reading file within alignment module - load failed`

So the issue seems to remain that there is some problem with loading data from fastq files.

Kind regards,  Andreas.

**Comment by tillea** [comment]
Hi Anatoly,

On Thu, Sep 01, 2016 at 08:43:44AM -0700, Anatoly Boshkin wrote:
> Can you provide a portion of the input file /usr/share/doc/python-biopython-doc/Tests/Quality/sanger_93.fastq ? Just several first lines would suffice.

Full four-liner from BioPython attached to this mail.

Kind regards

       Andreas.

-- 
http://fam-tille.de

@Test PHRED qualities from 93 to 0 inclusive
ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGAN
+
~}|{zyxwvutsrqponmlkjihgfedcba`_^]\[ZYXWVUTSRQPONMLKJIHGFEDCBA@?>=<;:9876543210/.-,+*)('&%$#"!

**Comment by kwrodarmer** [comment]
The phred quality values you are using to test are nonsense.

A phred value of 0 means 100% error. A value of 3 means 50% error. A value of 60 means 99.9999% confidence.

latf-load uses an SRA schema that requires phred quality scores to be `0 < phred < 64`. Any test that tries to load `0..93` and retrieve them will fail.

**Comment by aboshkin** [comment]
Yes, but in this particular case the loader fails to parse the tagline. 
Our FASTQ tag line parser has been built based on real submissions and one of its features is extraction of certain data (spot names, read groups, read numbers) from a multitude of variations on the FASTQ format that NCBI has to deal with. As such, even though the tagline parsing rules are somewhat loose, it is not a free format. 
In your test's tagline, white space is what causes the failure. Please try replacing spaces with underscores.

**Comment by tillea** [comment]
Hi,

On Thu, Sep 01, 2016 at 11:55:22AM -0700, Anatoly Boshkin wrote:
> Yes, but in this particular case the loader fails to parse the tagline. 
> Our FASTQ tag line parser has been built based on real submissions and one of its features is extraction of certain data (spot names, read groups, read numbers) from a multitude of variations on the FASTQ format that NCBI has to deal with. As such, even though the tagline parsing rules are somewhat loose, it is not a free format. 
> In your test's tagline, white space is what causes the failure. Please try replacing spaces with underscores. 

I can confirm that replacing spaces by underscores in
  /usr/share/doc/python-biopython-doc/Tests/Quality/sanger_93.fastq
solved the issue and the file can be easily loaded.  I have tested
a couple of other fastq files successfully (with one exception where
removing a space has helped.

While I think there could be some enhancement regarding the error
message ("syntax error, unexpected fqWS" is a bit weak in my personal
opinion) I'm hereby closing the Debian bug report which was about not
found vschema files anyway.

Jana, please test the new version of sra-toolkit thoroughly and keep
on reporting bugs.

Kind regards

     Andreas.

-- 
http://fam-tille.de
