### ISSUE TITLE
Multiple repeated failures with fasterq-dump

### ISSUE THREAD

**Issue by s-andrews** [ncbi/sra-tools#391]
I've been trying to download some files with fasterq-dump and have experienced repeated failures after a large amount of data has been downloaded.  There seems to be more than one mode of failure, but the tool will sometimes succeed (in one case after 4 failed attempts).  If there's any way to improve the retry logic so that these errors don't cause a complete restart it would save a huge amount of bandwidth since we're downloding things multiple times.

I'll attach the log file from downloading 3 accessions:

SRR11189098 worked at the 5th attempt
SRR11189100 failed 5 times in a row
SRR11189103 worked on the first attempt

This was all run on a server sitting on the main UK JANET network with a 20Gb/s connection.  No other network issues were apparent during these runs and we've seen similar behaviour in other downloads using fasterq-dump.

All of this was using sra-tools v2.10.8 on CentOS7.

[nohup.txt](https://github.com/ncbi/sra-tools/files/5035574/nohup.txt)

**Comment by kwrodarmer** [comment]
While it is a technicality to our users, the SRA Toolkit itself is client-side software. When there are issues in backend or server-side delivery (as was the case here), there's literally nothing that can be done within SRA tools to address the issue.

The amount of retry logic that exists within the tools has been increased an order of magnitude over the last year. But all systems have limits. The place to fix problems is not within the toolkit. NCBI is working on improving the stability of backend components where the problem originates.

The time period you mention corresponds with some known issues that either have been addressed already or are being addressed. Please retry and let us know. Thank you for your report.

**Comment by s-andrews** [comment]
[lots_of_retries.txt](https://github.com/ncbi/sra-tools/files/5062084/lots_of_retries.txt)

I tried 20 times over the course of two days and all of them failed.  The temp directories contained coming on for a terrabyte of temporary data (from 5GB up to 189GB), but it never completed:

```
$ du -sh fasterq.tmp.headstone.babraham.ac.uk.*
4.9G    fasterq.tmp.headstone.babraham.ac.uk.109217
26G     fasterq.tmp.headstone.babraham.ac.uk.110003
22G     fasterq.tmp.headstone.babraham.ac.uk.112581
189G    fasterq.tmp.headstone.babraham.ac.uk.114797
11G     fasterq.tmp.headstone.babraham.ac.uk.133327
12G     fasterq.tmp.headstone.babraham.ac.uk.141818
109G    fasterq.tmp.headstone.babraham.ac.uk.144267
75G     fasterq.tmp.headstone.babraham.ac.uk.44897
150G    fasterq.tmp.headstone.babraham.ac.uk.95089
```

**Comment by wraetz** [comment]
It would be a better strategy to first download the sra-accession via 'prefetch'. You can do that in a loop, because prefetch picks up a partial download ( fasterq-dump does not - it always starts over ). Then run fasterq-dump on the downloaded accession by giving it the path to the downloaded accession instead of just an accession. When doing that it pays off to turn multiple threads on again - it will be faster.

**Comment by klymenko** [comment]
@s-andrews, did you try to prefetch?
