### ISSUE TITLE
prefetch --type fastq  consistent failure

### ISSUE THREAD

**Issue by waleadebayo** [ncbi/sra-tools#395]
Hello,
thanks for the good work

Is prefetch --type fastq   ?   I ask because  it has not worked at all (for different files) for several days (prefetch 2.10.8) , consistently fails with error 
e.g
prefetch.2.10.8 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR634.......' - no data ( 404 )
but the accession has such data available https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR6343608

 I am more interested in prefetch --type fastq rather rather than default prefetch && fastq-dump. (as i think the results may differ) , or is this assumption wrong?
 
many thanks

**Comment by klymenko** [comment]
@waleadebayo, you cannot download SRR6343608 in fastq format directly.
You have to run prefetch, fastq-dump | fasterq-dump.
