### ISSUE TITLE
fastq-dump.2.4.1 err: binary large object corrupt 

### ISSUE THREAD

**Issue by chamalis** [ncbi/sra-tools#4]
Hello,

When I try to download/convert an SRA to fastq (http://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR847533) using:

fastq-dump --split-files SRR847533

I get:

2014-12-14T11:18:36 fastq-dump.2.4.1 err: binary large object corrupt while reading binary large object within virtual database module - failed SRR847533
# 

An error occurred during processing.
A report was generated into the file '/home/sbarberakis/ncbi_error_report.xml'.
If the problem persists, you may consider sending the file
# to sra @ ncbi.nlm.nih.gov for assistance.

Xml file is here: http://cineserver.3p.tuc.gr/d/ncbi_error_report.xml

**Comment by gauravkadu** [comment]
I encountered with same problem. Hv you found any solution.

**Comment by chefarov** [comment]
In my case the disk space was exhausted :S
