### ISSUE TITLE
Some tests inside test suite are failing

### ISSUE THREAD

**Issue by tillea** [ncbi/sra-tools#40]
Hi,
I've updated the Debian packaging of sra-toolkit to version 2.7.0.  The Debian build is running the test suite but unfortunately I needed to ignore some tests since these are failing.  In this [patch](https://anonscm.debian.org/cgit/debian-med/sra-sdk.git/tree/debian/patches/ignore_failing_tests_for_the_moment.patch) you can find all those tests I needed to exclude to pass the test suite.  I would have a way better feeling if this could be sorted out properly than just closing the eyes by commenting out the failing bits.
Can you verify these failures?
Just let me know if you need more detailed information.
Kind regards, Andreas.

**Comment by aboshkin** [comment]
Hi Andreas,
Can you provide the outputs of the failing tests? 
Thank you,
Anatoly

**Comment by kwrodarmer** [comment]
Hi @tillea - also let us know what ABI they are failing under.

**Comment by tillea** [comment]
@aboshkin here is an archive
[sra-sdk_test_stderr.zip](https://github.com/ncbi/sra-tools/files/451883/sra-sdk_test_stderr.zip)
containing all non-zero stderr files.  I have moved them to two different directories.  In "critical" are those that I needed to exclude from the test suite.  In non-critical the test suite did not stopped but something smells wrong anyway.
Hope this helps, Andreas.

**Comment by tillea** [comment]
@kwrodarmer What do you mean by "what ABI they are failing under"?  I was building sra-toolkit against ncbi-vdk 2.7.0 if you mean this.

**Comment by kwrodarmer** [comment]
Hi @tillea - I mean, were you building for i386/i686, x64, or x32? We only officially support x64.

**Comment by aboshkin** [comment]
@tillea - all these tests are supposed to generate error messages, they are error cases. As long as make returns 0, non-empty stderr files do not matter here. Did make return something else for you?

**Comment by tillea** [comment]
On Fri, Sep 02, 2016 at 06:51:25AM -0700, kwrodarmer wrote:
> Hi @tillea - I mean, were you building for i386/i686, x64, or x32? We only officially support x64.

Ahhh, youe mean the architecture:  I was building on amd64 (which is
what you call x64).

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment]
On Fri, Sep 02, 2016 at 08:44:59AM -0700, Anatoly Boshkin wrote:
> @tillea - all these tests are supposed to generate error messages, they are error cases. As long as make returns 0, non-empty stderr files do not matter here. Did make return something else for you?

Yes.  I needed to exclude the tests *since* make returned false.
Otherwise I would not have noticed this.  But as I wrote there where two
tests that create stderr output but make receives true.

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
I meant more than the architecture, since x32 isn't an architecture. But you've answered my question. Now to discover why you get errors when we don't!

**Comment by aboshkin** [comment]
@tillea  May I ask you to run make on the original set of tests and send us the output? The error cases behave as expected and should not cause make to return false, so there must be something else at work.
