### ISSUE TITLE
getting prefetch error

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [ncbi/sra-tools#401]
getting this error for this command.
./prefetch --type fastq -O . --max-size 200000000 -p SRR7613781

2020-08-19T10:26:55 prefetch.2.10.8 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR7613781' - no data ( 404 )

**Comment by durbrow** [comment]
Do not specify a type. It looks like you want to get the fastq from SRR7613781. Have you tried to run `fastq-dump SRR7613781`? If you want to prefetch the data first (often a good idea), run `prefetch -p SRR7613781 && fasterq-dump SRR7613781`. This will create a directory SRR7613781 with SRR7613781.sra (which you can delete), and couple fastq files named SRR7613781*.fastq.

**Comment by RamakrishnaChilaka** [comment]
Thanks @durbrow. The above worked, but i only got one fastq file - SRR7613781.fastq.  is this correct ? and just curious, why specifying a type causes error. Thanks.

**Comment by RamakrishnaChilaka** [comment]
@durbrow , your above command converts the "run" file to sra file, but we need access to the originally submitted files @durbrow .

**Comment by skripche** [comment]
@RamakrishnaChilaka the source files will be more easily available next week once that new feature is released. I apologize for the confusion that page caused. I will supply the documentation link in case #403 once it is live.

**Comment by klymenko** [comment]
@RamakrishnaChilaka, do you still need help?
