### ISSUE TITLE
Can we use bare metal servers to access data

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [ncbi/sra-tools#402]
Can we use bare metal servers to access data. There are some raw srr files that do not give free egress, for example https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR7613781, when tried using prefetch on a raw machine, we are getting this error. https://github.com/ncbi/sra-tools/issues/401

**Comment by klymenko** [comment]
@RamakrishnaChilaka, do you still need help?
