### ISSUE TITLE
Please help in understanding `cloud data delivery` and how we can use it.

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [ncbi/sra-tools#403]
![image](https://user-images.githubusercontent.com/49393831/90669588-80e59c00-e26f-11ea-8da1-343de675ffdc.png)

**Comment by skripche** [comment]
Hello,

The new cloud data delivery feature is going to be released next week. That was placed there prematurely. We will be releasing instructions next week when the functionality goes live. 

Thank you.

**Comment by skripche** [comment]
Hello, 

if you would like to get the source files from our cold storage in the cloud, please see the documentation here:
https://www.ncbi.nlm.nih.gov/sra/docs/data-delivery/

The data will be deposited into your own bucket.

**Comment by salil9999** [comment]
Hello,

I just wanted to know if it is possible to access the data using cloud data delivery programmatically somehow? Do you have any APIs or any type of documentation that supports this?

Thanks.

**Comment by skripche** [comment]
Hello,

The programmatic access to the system will be coming in the future and the documentation will be updated once it is released. Thank you.

**Comment by salil9999** [comment]
Hi,

Is there any ETA for the same?

Thanks.

**Comment by leipzig** [comment]
Hi just checking on this. Is there an API version of the cloud delivery service?

**Comment by durbrow** [comment]
Cloud data delivery started working with version 2.10 of the toolkit (the current version is 2.11.1). To make it work, you need to do a little setup. See https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration In short, you want to "Enable Remote Access" and "report cloud instance identity" in the appropriate tab for the cloud provider. Then if you are running in the cloud, when you request data from NCBI and there is a copy in the same cloud, NCBI will send back the URL for that data in the same cloud as you.
