### ISSUE TITLE
How to decrypt Non-SRA Data? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [ncbi/sra-tools#405]
Dear Sir/Madam, 

How to decrypt Non-SRA Data?  for example SNP-array data? the follow link didn't mention the approach. 

https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data

Thanks. 

Shicheng

**Comment by skripche** [comment]
Hello Shicheng,

We can only advise on how to decrypt data that we encrypt. We cannot help you if you want to decrypt data not supplied by SRA/dbGaP. 

Thank you.
