### ISSUE TITLE
is it possible to force or validate S3 path, or get direct links?

### ISSUE THREAD

**Issue by chubukov** [ncbi/sra-tools#406]
I am trying to grab data from SRA on an AWS EC2 instance. I did my best to follow all the instructions here https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/ including the video tutorial. But as far as I can tell, when I run `sam-dump`, it doesn't actually use the S3 location (based on the download speed and the error messages I get). 

Is there a way to either validate that S3 access is configured and ready, or to force sra toolkit to use a particular location?

Alternatively, is there a systematic way to retrieve the S3 bucket locations for a set of SRRs (e.g. as shown on the run browser page https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8788980)? The run selector metadata appears to not quite have enough information (it says data is available on S3, but doesn't have the bucket name).

**Comment by kwrodarmer** [comment]
Hi @chubukov,

Without knowing exactly what you did to configure your toolkit in AWS or what region you are in, it is impossible for us to comment on what is happening or recommend anything. Please take a moment to give us more information.

What we did do was to go into AWS us-east-1, configure the toolkit to not accept charges but to provide location information, and then we accessed the run you mentioned (as well as others). We were able to confirm that the retrieval was from S3, which indicates that the system is working as designed. It should be noted that if the toolkit was not configured for AWS or if you are operating outside of us-east-1, you will be routed back to NCBI because of the cloud providers' billing policies.

`sam-dump` does not execute directly out of S3, but instead out of local POSIX filesystem cache area which is populated on demand from S3. This is because random access is involved, and object stores are not as good at random access as POSIX filesystems.

You may still find that prefetching the object and running `sam-dump` on that gives a better response.

**Comment by chubukov** [comment]
@kwrodarmer Thanks. I followed the same steps, as outlined in the docs, and I've verified that the instance is in us-east-1. I could share the config file if that would help?

>We were able to confirm that the retrieval was from S3
What would be your recommend way of doing this?

**Comment by kwrodarmer** [comment]
> What would be your recommended way of doing this?

It hasn't been considered as an end-user feature so far, but it can be confirmed by use of `strace` and watching the `connect` addresses or DNS resolution.

> I could share the config file if that would help?

That would help, but don't post it here: send it to sra-tools@ncbi.nlm.nih.gov and let us know (here) once you've sent it. We'll have to request that our help desk forward it to us for review.

In the meanwhile, as long as your AWS panel in configuration was set up to send the proof of compute environment (location), and your location is us-east-1, we have verified that the system is working as designed and handing out URLs into S3.

The exact mechanism is quite a bit more complex and somewhat difficult to describe succinctly. It behaves differently if you ask for public SRA vs. dbGaP. But there are 3 classes of buckets in S3 for purposes of this comment: _(open, public, controlled)_, plus there are the URLs into NCBI. Access to open-data buckets _(where Amazon allows free access with no egress charges)_ is given as a simple URL. Access to normal public buckets _(guest access but you have to pay)_ will be generated as simple URLs that require the toolkit to provide AWS with requester pays credentials, so they know how to charge for egress. When you enable the toolkit to send location information to NCBI in configuration, we're able to optimize for the case that you're calling from a "no-egress" region and we give you back a much more complicated, indirect URL, but it's only complicated for the toolkit (!) and the end result is you get access to public buckets without having to provide payment credentials.

dbGaP is somewhat different from above, in that the only mode supported is the latter: you must be within us-east-1 when using AWS.

**Comment by klymenko** [comment]
@chubukov , which version of SRA toolkit do you run?

**Comment by chubukov** [comment]
@klymenko sratoolkit.2.10.8-ubuntu64

**Comment by klymenko** [comment]
@chubukov, do you still need help?

**Comment by chubukov** [comment]
@klymenko I ended up switching to the new cloud delivery service, which made this point moot but ran into other issues (#427 as you saw).

I still think it would be great to be have an easy way to see more explicitly where the files are being fetched from, but that's essentially a feature request.

I also haven't been able to access many of the buckets directly through s3, which may be a separate issue.

So I think there are still quite some gaps but feel free to close this particular issue or mark it as a feature suggestion.

Thanks for the followup!

**Comment by klymenko** [comment]
@chubukov, how do you get data on the cloud?

**Comment by klymenko** [comment]
To check the files are being fetched from - you can run `srapath SRR8788980`.
You will not always be able to use the returned URL directly but it will give you information about the source.

`I also haven't been able to access many of the buckets directly through s3, which may be a separate issue.`
Please clarify.

**Comment by chubukov** [comment]
Thanks, and sorry for dropping the thread, I had moved on completely from the project that needed this.
