### ISSUE TITLE
Is it possible to download dbGaP authorized access data to a GCS bucket? 

### ISSUE THREAD

**Issue by njbernstein** [ncbi/sra-tools#407]
I think the title covers it.  Is it possible to download dbGaP authorized access data to a GCS bucket? 

Otherwise, I assume the best option is to download to a GCS instance and copy to a bucket from there.

**Comment by skripche** [comment]
Hello,

For now you need to download it to a GCP instance and move it to a bucket. We will be adding functionality to deliver data to a bucket instead of just  a GCP instance, but we have not quite finished it. 

Best,
Yuriy

**Comment by njbernstein** [comment]
Thanks
