### ISSUE TITLE
instructions for non-interactive vdb-config?

### ISSUE THREAD

**Issue by chubukov** [ncbi/sra-tools#409]
I'm trying to set up sra toolkit on databricks.

Are there instructions somewhere for non-interactive `vdb-config` use?

I tried the following:

```
wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.8/sratoolkit.2.10.8-ubuntu64.tar.gz
tar xvzf sratoolkit.2.10.8-ubuntu64.tar.gz 
sratoolkit.2.10.8-ubuntu64/bin/vdb-config --report-cloud-identity yes
```

that seemed to work, but when I ran `prefetch` I still got the error

> This sra toolkit installation has not been configured.
> Before continuing, please run: vdb-config --interactive
> For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
>

**Comment by chubukov** [comment]
Additionally, I tried to set the temp directories as such:
```
sratoolkit.2.10.8-ubuntu64/bin/vdb-config --report-cloud-identity yes -s /repository/user/main/public/root=/dbfs/victor.chubukov/sra_temp
```

but I got this error
>2020-08-30T19:33:12 vdb-config.2.10.8 err: condition violated while updating node - Warning: normally this application should not be run as root/superuser
>
which I guess is not a warning after all

so instead I just did the following
```
echo "/repository/user/main/public/root = \"/dbfs/victor.chubukov/sra_temp"" >> .ncbi/user-settings.mkfg
echo "/repository/user/main/public/root = \"/dbfs/victor.chubukov/sra_temp\"" >> .ncbi/user-settings.mkfg
```

Let me know if there's another way. 

But of course basic issue is in the first post -- still can't run anything without running `vdb-config -i`

**Comment by chubukov** [comment]
Wanted to bump this. @kwrodarmer it really looks like vdb-config is designed with the option of running it non-interactively -- any thoughts?

Thanks a lot.

**Comment by kwrodarmer** [comment]
We don't have a good answer for this today. You are not running into any limitations on how to configure from the command line: you are running into a limitation of how to complete a toolkit installation. That said, we are working on other options for the future.

**Comment by chubukov** [comment]
@kwrodarmer Ok thanks for the reply.

**Comment by chubukov** [comment]
I don't know if this is going to be the recommended method, but 

`echo "Aexyo" | sratoolkit.2.10.8-ubuntu64/bin/vdb-config -i`

did the trick

**Comment by jlehrer1** [comment]
@kwrodarmer Is there any update on this? Forced to install with an interactive mode makes running this in containerized environments a bit difficult.

**Comment by kwrodarmer2** [comment]
@kdurbrow - can you link this to the issue where you explain how to use our docker containers?

**Comment by durbrow** [comment]
You might want to look into using our docker image https://github.com/ncbi/sra-tools/wiki/SRA-tools-docker
 It comes pre-configured.

**Comment by mdanb** [comment]
@durbrow @kwrodarmer any updates?

**Comment by XuJahcenia** [comment]
> I don't know if this is going to be the recommended method, but
> 
> `echo "Aexyo" | sratoolkit.2.10.8-ubuntu64/bin/vdb-config -i`
> 
> did the trick



> I don't know if this is going to be the recommended method, but
> 
> `echo "Aexyo" | sratoolkit.2.10.8-ubuntu64/bin/vdb-config -i`
> 
> did the trick

It worked. Thanks!
