### ISSUE TITLE
Can you check this error plz?

### ISSUE THREAD

**Issue by kunnyJung** [ncbi/sra-tools#410]
![srrError](https://user-images.githubusercontent.com/39253052/91683231-fd8d4a00-eb8e-11ea-9289-a2f6b2f8d9c1.PNG)

Hi, I attach the error.
I used 'prefetch -X 200G SRR6808334' before this command.

**Comment by klymenko** [comment]
@kunnyJung, please try [our new 2.10.9 release](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
We improved tolerance against network failures.
