### ISSUE TITLE
Prefetch (fastq-dump) not working for some GSM numbers

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [ncbi/sra-tools#411]
I am not entirely sure what a GSM number should represent, however I can prefetch (some) of those:

```
prefetch GSM2837480

2020-09-04T08:52:00 prefetch.2.10.7 fatal: string unexpected while executing query within virtual file system module - multiple response SRR URLs for the same service 'sra-sos'
2020-09-04T08:52:01 prefetch.2.10.7: 1) Downloading 'SRR6245277'...
2020-09-04T08:52:01 prefetch.2.10.7:  Downloading via HTTPS...
etc.
```

However for others this does not seem to work:

```
prefetch GSM3832552

2020-09-04T08:46:51 prefetch.2.10.7 err: name not found while resolving query within virtual file system module - failed to resolve accession 'GSM3832552' - Cannot resolve accession ( 404 )
```

How/why does it work for some of those and not for others? Do they represent a different type of data? How can I recognize that for some I can download them, and others I need to use the underlying SRR number?

**Comment by durbrow** [comment]
GSM accessions aren't SRA accessions, so in general, you can't use the SRA Toolkit to access GSM datasets. I was not aware that *any* GSM accessions could be accessible via the SRA Toolkit. Apparently, some GSM accessions have SRA accessions associated with them. You got lucky with GSM2837480, but it won't work in general.

If you are interested, you can try https://www.ncbi.nlm.nih.gov/sra?term=GSM3832552 and see there is no data in SRA for it.

**Comment by Maarten-vd-Sande** [comment]
Oh, this is not the answer I was expecting! I have downloaded loads of data so far through GSM numbers, and was surprised when it did not work for this sample.

Anyways, thanks. I should avoid using GSM numbers in the future and start using the SRR numbers :+1:

**Comment by Maarten-vd-Sande** [comment]
Just FYI, a couple more examples to show that it is more widespread than you would expect!

GSM2942627, GSM2837485, GSM2385309, GSM3756599, GSM2219678, GSM3440170, GSM1933921, GSM2837499,GSM2520641, GSM4121478, GSM3762913
