### ISSUE TITLE
SRA config error saving changes

### ISSUE THREAD

**Issue by peynard** [ncbi/sra-tools#412]
Hi ! I am struggling with the SRA configuration because I cannot use it without configure it first. Will doing it by running vdv-config -I; When I configure my downloading path, I cannot save the changes and an error message appear every time "error while saving changes". 

Does anyone have an idea ? 

I'm working on a Mac with Catalina and I am trying to use the last version SRA Toolkit 2.10.8-mac64. 

Thank you very much in advance.

**Comment by skripche** [comment]
Hello,

Please email us at sra@ncbi.nlm.nih.gov and we will try to help you.

Thank you.

**Comment by qiileee** [comment]
Hi! I got the same error with you. Did you deal with it?

**Comment by peynard** [comment]
Hi ! Yes NCBI told me to look at my permissions. You have to give to the sra-toolkit the permissions to write and read on your computer. Then it is supposed to work !

**Comment by qiileee** [comment]
OK, thank you very much. I would try it.

**Comment by klymenko** [comment]
@peynard, @qiileee, do you still need help?

**Comment by peynard** [comment]
@klymenko No it’s okay for me, thanks !

**Comment by ilisulh** [comment]
> Hi ! Yes NCBI told me to look at my permissions. You have to give to the sra-toolkit the permissions to write and read on your computer. Then it is supposed to work !

How do you set up the permission?

**Comment by gubrins** [comment]
same problem here, I already gave permission to vdb-config but when I try, I obtain the same error as @peynard

**Comment by klymenko** [comment]
You need to have write permissions to your `$HOME`.
