### ISSUE TITLE
fastq-dump was killed (signal 13)

### ISSUE THREAD

**Issue by ramiromagno** [ncbi/sra-tools#413]
Hi

I am not sure this is a bona fide error per se as the output of:

```bash
./fastq-dump --stdout SRR390728 | head -n 8
```

produces the right output:

```
@SRR390728.1 1 length=72
CATTCTTCACGTAGTTCTCGAGCCTTGGTTTTCAGCGATGGAGAATGACTTTGACAAGCTGAGAGAAGNTNC
+SRR390728.1 1 length=72
;;;;;;;;;;;;;;;;;;;;;;;;;;;9;;665142;;;;;;;;;;;;;;;;;;;;;;;;;;;;;96&&&&(
@SRR390728.2 2 length=72
AAGTAGGTCTCGTCTGTGTTTTCTACGAGCTTGTGTTCCAGCTGACCCACTCCCTGGGTGGGGGGACTGGGT
+SRR390728.2 2 length=72
;;;;;;;;;;;;;;;;;4;;;;3;393.1+4&&5&&;;;;;;;;;;;;;;;;;;;;;<9;<;;;;;464262
fastq-dump was killed (signal 13)
```

 but exits with an error, so... I am not sure if this is really a bug.

I am installing the toolkit in Ubuntu 20.04 and I just followed the steps for Ubuntu:

1. `wget --output-document sratoolkit.tar.gz http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz`
2. `tar -vxzf sratoolkit.tar.gz`
3. `cd sratoolkit.2.10.8-ubuntu64/bin`
4. Here I configured with `vdb-config -i`
5. Finally I ran (from the bin folder): `./fastq-dump --stdout SRR390728 | head -n 8`

**Comment by durbrow** [comment]
`fastq-dump` was writing to stdout (a pipe in this case). `head` was reading from that pipe. `head` did its job and quit. The pipe was closed and a SIGPIPE was sent to `fastq-dump` which quit because of it. That is all the message means.

**Comment by ramiromagno** [comment]
how silly of me. cheers!

**Comment by durbrow** [comment]
No problem. Have a great day :)
