### ISSUE TITLE
How to set different SRA repository file system paths for "files", "sra", "wgs", "nannot" and "refseq"?

### ISSUE THREAD

**Issue by jgans** [ncbi/sra-tools#416]
When accessing many SRA records in parallel on a large computer cluster, it would be nice to simultaneously store all of the "refseq" sequences in a **central** repository (i.e. a directory visible to all compute nodes to avoid redundant downloads of the same refseq on different nodes) **and** to store the .sra.cache and .sra.vdbcache.cache files on node **local** storage devices (since this information is specific to individual SRA records, this will avoid unnecessary traffic on the mass storage device).

I suspect that this is possible via the `default.kfg` or `user-settings.mkfg` files and any advice would be appreciated!

**Comment by kwrodarmer** [comment]
This is exactly how our older caching system worked, but it creates race conditions among multiple writers who are performing download on demand. The recommended approach is to just go to NCBI's FTP site and download them all before you start your job, and yes - set the configuration to say that all of these files are in a static location.

**Comment by jgans** [comment]
Once all of the RefSeqs are downloaded into a central repository, it is possible to have the cache files (generated by download on demand) stored in a different file system path (i.e. on a local node)?

**Comment by kwrodarmer** [comment]
Yes it is. However, it ends up being a contradiction in that once you've downloaded all reference files, the set will contain all external references for all of the runs that were current at the time you downloaded the files. But yes - the design allows for having a centralized repository of refseq files and NGS/VDB will continue to download on demand anything that is missing.

**Comment by klymenko** [comment]
Here is an example of configuration for centralized repository of RefSeq files.

E.g., download all RefSeqs into `/usr/local/repo/refseq`
Then add the following lines into a file with `.kfg` extension located in `/etc/ncbi`
```
/repository/site/main/archive/apps/refseq/volumes/refseq = "refseq"
/repository/site/main/archive/root = "/usr/local/repo"

```
You can use a different name for repository instead if `archive`.
