### ISSUE TITLE
Prefetch doesnt download SRA file in version 2.10.8

### ISSUE THREAD

**Issue by bapoorva** [ncbi/sra-tools#417]
Hi,

I recently updated my sratoolkit from version 2.8 to 2.10.8. Now my prefetch command doesnt seem to be working. 

I tried this ` prefetch -p SRR8387813 -o ~/SRAfiles/sra`. It runs for some 5-10 mins. No progress messages despite the -p argument. No error messages. But then the file doesn't get downloaded either. How do I solve this ?

Thanks,
Apoorva

**Comment by bapoorva** [comment]
Anyone else having the same issue or any idea on how to fix this ?

**Comment by durbrow** [comment]
Could you try `cd ~/SRAfiles/sra ; prefetch -p SRR8387813 `? Do you get the same result?

**Comment by bapoorva** [comment]
Yes. I still have the same issue.  prefetch works fine when I run it locally. But I want to download the files to a remote server that I'm logged in to using secure shell so that i can process the raw files. This server has sratoolkit installed. fast-dump works on it. Just not prefetch.

**Comment by durbrow** [comment]
Were you able to run fastq-dump on the remote system without a prefetched copy of the data?

**Comment by bapoorva** [comment]
yes. For now I've been using prefetch on my local system, uploading all sra files to the remote system and then using fastq-dump on that. It is a very time consuming process.

**Comment by durbrow** [comment]
What sort of system is the remote? Is it a cloud compute system, like AWS or GCP?

**Comment by bapoorva** [comment]
Turns out the server doesn't have an outbound network access. My bad. Sorry. Closing issue now

**Comment by durbrow** [comment]
You might be able to use sshfs to mount a directory from your server as a local directory on your host, and then prefetch into it.
