### ISSUE TITLE
Fastq-dump for single cell RNAseq fastq files

### ISSUE THREAD

**Issue by bapoorva** [ncbi/sra-tools#418]
Hi,

I'm trying to download a single cell RNASeq dataset from GEO to run my analysis on them. I need the 3 fastq files to begin with (R1, R2 and I1). I used sra toolkit and got the .sra file using the prefetch command and then I ran fastq-dump to split them.

`prefetch SRR8387812`
`fastq-dump --split-files SRR8387812`

I got 3 files - SRR8387812_1.fastq, SRR8387812_2.fastq and SRR8387812_3.fastq. Now should i assume SRR9313701_1.fastq is I1, SRR9313701_2.fastq is R1 and SRR9313701_3.fastq is R2 ? Based on the trace [here](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8387812), that is what it appears to be. If not, how do I get them in the original format with the original names ?

Thanks, Apoorva

**Comment by haskankaya** [comment]
I had the same question as you, @bapoorva . I downloaded the .sra using `prefetch` and then ran `fasterq-dump -S --include-technical` to yield the 3 files you mention.

To check their identities I simply ran `head` on the files and looked at the contents, then cross-referenced with [this description of what each .fastq file should contain](https://davetang.org/muse/2018/06/06/10x-single-cell-bam-files/). For my data the assumption of order you made was correct - the first file was the I1, second R1 and third R2. Whether this order is maintained across all single cell data deposited on GEO I am not sure - I anticipate that it could depend on how the data is deposited. For now I will check this for each different project I want to download and work with.

**Comment by bapoorva** [comment]
Thank you @haskankaya. That is helpful. For each dataset i download from GEO, I've been looking at the metadata in SRA to determine which one is I1, R1 and R2. It would actually help if there was an option in sratools to run fasterq-dump and get the original filenames.
