### ISSUE TITLE
sra-tblastn  ERROR

### ISSUE THREAD

**Issue by SmallPackage** [ncbi/sra-tools#419]
Error: (2108.2) VDB 2.10.8: 2020-09-17T06:45:37 . int: param empty while constructing path within virtual file system module - Error in VDBManagerOpenTableRead()
Error: NCBI C++ Exception:
    T0 "/panfs/pan1/sra-test/vdb3/git/blast_vdb/sratoolkit_2_10_8/c++/src/internal/blast/vdb/vdb2blast_util.cpp", line 254: Error: (CException::eUnknown) ncbi::CVDBBlastUtil::x_MakeVDBSeqSrc() - Error opening the following db(s): xxxxxxxxx

have proceed "03. Quick Toolkit Configuration"; 
`fastq-dump --stdout SRR390728 | head -n 8` work;

**Comment by klymenko** [comment]
What db(s) is fails to open? (xxxxxxxxx?)

**Comment by SmallPackage** [comment]
> 
> 
> What db(s) is fails to open? (xxxxxxxxx?)
I have contacted NCBI support, and found it is a connection issue;

My ip address was temporarily banned (due to missuse) , and that makes many tools unusable;

After my access was restored, those issues solved.

I should just close this issue?
