### ISSUE TITLE
fastq-dump  fails on local SRA file

### ISSUE THREAD

**Issue by map2085** [ncbi/sra-tools#42]
I downloaded an SRA file manually via wget:

`wget  ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/ERR/ERR161/ERR161917/ERR161917.sra`

Then I perform fastq-dump on the local file:

`fastq-dump  ./ERR161917.sra`

And it fails with error message:

> 2016-10-19T14:52:50 fastq-dump.2.8.0 err: binary large object corrupt while reading binary large object within virtual database module - failed /tmp/740660.1.standard.q/485/data/ERR161917.sra
> 
> =============================================================
> An error occurred during processing.
> A report was generated into the file '/home/map2085/ncbi_error_report.xml'.
> If the problem persists, you may consider sending the file
> to 'sra@ncbi.nlm.nih.gov' for assistance.
> =============================================================

This happens for dozens of Run accessions.  However, for hundreds of other run accessions, the exact same above commands complete successfully.

Disk space is not an issue (4 TB free, while these .sra files are < 5 GB each).  Memory is also very large ( > 8 GB)

**Do not respond with the following:**

- "just use  `fastq-dump  <accession>` "
- "just use `prefetch  <accession>` "

fastq-dump is supposed to work on local SRA files, as it says in the fastq-dump help page.  **Do not tell me to do it another way.**  It should work as it claims to.

**Comment by klymenko** [comment]
ERR161917 refers to 211 refseq files.

You need to download them and configure toolkit to find them.

**Comment by map2085** [comment]
The local SRA is complete:

`$ vdb-validate  ./ERR118250.sra `

> 2016-10-19T15:16:30 vdb-validate.2.8.0 info: Database 'ERR118250.sra' metadata: md5 ok
> 2016-10-19T15:16:30 vdb-validate.2.8.0 info: Table 'PRIMARY_ALIGNMENT' metadata: md5 ok
> 2016-10-19T15:16:30 vdb-validate.2.8.0 info: Column 'GLOBAL_REF_START': checksums ok
> 2016-10-19T15:16:31 vdb-validate.2.8.0 info: Column 'HAS_MISMATCH': checksums ok
> 2016-10-19T15:16:31 vdb-validate.2.8.0 info: Column 'HAS_REF_OFFSET': checksums ok
> 2016-10-19T15:16:31 vdb-validate.2.8.0 info: Column 'MAPQ': checksums ok
> 2016-10-19T15:16:31 vdb-validate.2.8.0 info: Column 'MISMATCH': checksums ok
> 2016-10-19T15:16:32 vdb-validate.2.8.0 info: Column 'REF_LEN': checksums ok
> 2016-10-19T15:16:32 vdb-validate.2.8.0 info: Column 'REF_OFFSET': checksums ok
> 2016-10-19T15:16:32 vdb-validate.2.8.0 info: Column 'REF_OFFSET_TYPE': checksums ok
> 2016-10-19T15:16:32 vdb-validate.2.8.0 info: Column 'REF_ORIENTATION': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'SEQ_READ_ID': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'SEQ_SPOT_ID': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Table 'REFERENCE' metadata: md5 ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CGRAPH_HIGH': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CGRAPH_INDELS': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CGRAPH_LOW': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CGRAPH_MISMATCHES': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CMP_ALTREAD': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CMP_READ': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CS_KEY': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'OVERLAP_REF_LEN': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'OVERLAP_REF_POS': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'PRIMARY_ALIGNMENT_IDS': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'SEQ_ID': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'SEQ_LEN': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'SEQ_START': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Table 'SEQUENCE' metadata: md5 ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'ALIGNMENT_COUNT': checksums ok
> 2016-10-19T15:16:33 vdb-validate.2.8.0 info: Column 'CMP_ALTREAD': checksums ok
> 2016-10-19T15:16:35 vdb-validate.2.8.0 info: Column 'CMP_READ': checksums ok
> 2016-10-19T15:16:35 vdb-validate.2.8.0 info: Column 'PRIMARY_ALIGNMENT_ID': checksums ok
> 2016-10-19T15:16:49 vdb-validate.2.8.0 info: Column 'QUALITY': checksums ok
> 2016-10-19T15:16:51 vdb-validate.2.8.0 info: Column 'RD_FILTER': checksums ok
> 2016-10-19T15:16:53 vdb-validate.2.8.0 info: Column 'READ_TYPE': checksums ok
> 2016-10-19T15:17:29 vdb-validate.2.8.0 info: Database 'ERR118250.sra': SEQUENCE.PRIMARY_ALIGNMENT_ID <-> PRIMARY_ALIGNMENT.SEQ_SPOT_ID referential integrity ok
> 2016-10-19T15:17:49 vdb-validate.2.8.0 info: Database 'ERR118250.sra': REFERENCE.PRIMARY_ALIGNMENT_IDS <-> PRIMARY_ALIGNMENT.REF_ID referential integrity ok
> 2016-10-19T15:17:49 vdb-validate.2.8.0 info: Database 'ERR118250.sra' is consistent


Additionally:  

`$  prefetch  ./ERR118250.sra `

> 2016-10-19T15:35:41 prefetch.2.8.0: './ERR118250.sra' is a local non-kart file
> 2016-10-19T15:35:46 prefetch.2.8.0: './ERR118250.sra' has 0 unresolved dependencies
> 2016-10-19T15:35:47 prefetch.2.8.0: './ERR118250.sra' has no remote vdbcache

**Comment by map2085** [comment]
@klymenko     That is unacceptable.  I do not need alignments.  just the raw fastq files.  This has nothing to do with RefSeq files.

Further,  neither `fastq-dump -h` nor online man pages say anything about accompanying refseq files.  It simply says you can act on local SRA files.

Further, all of the above validation tools approve of the downloaded SRA file

**Comment by kwrodarmer** [comment]
@map2085 - "That is unacceptable?" You are not using the SRA or tools as designed and not following our guidelines or assistance.

**Comment by kwrodarmer** [comment]
The SRA stores data very differently from what you may be used to. We compress reads against the reference, which makes the reference sequences a requirement for regenerating the reads. When you download using `wget` rather than `prefetch`, you don't automatically get the benefit of recursive download that would have given you all of the data needed to run fastq-dump.

The taxpayer-funded advice you received was aimed at helping you to understand that for this to work, you need to ensure that the SRA Toolkit is properly configured and used according to guidelines so that you get access to the data.

**Comment by map2085** [comment]
@kwrodarmer   

I am indeed following the guidelines and using SRA toolkit correctly.

I am actually following this help page on the NCBI website:   https://www.ncbi.nlm.nih.gov/books/NBK158899/

Under the subsection heading "**Determining the location of SRA data files for automated or scripted downloads.**"

Gives the following example:

> Examples:
> Downloading SRR304976 by wget or FTP:
> wget ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR304/SRR304976/SRR304976.sra


Indeed, this is my exact scenario - automated/scripted downloads of large numbers of SRA files.

So I do exactly what the official NCBI manual page is suggesting.

Then I perform `fastq-dump` on the local file  - as specified in the fastq-dump help page - and it crashes.

This is unacceptable.

**Comment by kwrodarmer** [comment]
If you want help, please ask. If you want to flame, then I'll close the issue.

**Comment by map2085** [comment]
Certainly I would like help.

**Comment by kwrodarmer** [comment]
I am running a test on the ERR accession you gave earlier and once it has finished, we can work on this issue. In the meantime, I would like to point you to some more modern documentation to see if there's anything in there that might have been overlooked.

[https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data](https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data)  
[https://github.com/ncbi/sra-tools/wiki/Download-On-Demand](https://github.com/ncbi/sra-tools/wiki/Download-On-Demand)  
[https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process](https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process)

**Comment by kwrodarmer** [comment]
The test is still running (using an external host over network to simulate your presumed environment), but it is nearly complete. So far, I have generated 32G of fastq and consumed about 8G of SRA to do so, and there have been no errors generated from `fastq-dump`. Unless something happens at the very end, my guess is that you have either a bad configuration or a bad download. We'll explore these possibilities tomorrow.

**Comment by map2085** [comment]
yes.  when i deleted the local SRA file, and then did `prefetch  ERR161917`, and then did `fastq-dump  ERR161917`  it worked.

**Comment by kwrodarmer** [comment]
Good to hear.

**Comment by bounlu** [comment]
related to this, what does the error messages below mean?

`$ cat SRR1606195.prefetch 

2017-11-20T03:16:21 prefetch.2.8.2: 1) Downloading 'SRR1606195'...
2017-11-20T03:16:21 prefetch.2.8.2:  Downloading via https...
2017-11-20T04:24:56 prefetch.2.8.2: 1) 'SRR1606195' was downloaded successfully
2017-11-20T04:25:01 prefetch.2.8.2 err: file not found while opening file within network system module - Failed to KNSManagerVMakeHttpFileInt('https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/998744B7-E79E-4B21-A1AD-0B7F2B55C33B/SRR1606195.vdbcache?tic=CC004B6F-EE49-4AA9-B926-9D10472F5DFF' (130.14.250.17))
2017-11-20T04:29:10 prefetch.2.8.2: 'SRR1606195' has 0 unresolved dependencies
2017-11-20T04:29:14 prefetch.2.8.2 err: file not found while opening file within network system module - Failed to KNSManagerVMakeHttpFileInt('https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/998744B7-E79E-4B21-A1AD-0B7F2B55C33B/SRR1606195.vdbcache?tic=CC004B6F-EE49-4AA9-B926-9D10472F5DFF' (130.14.250.17))
2017-11-20T04:29:21 prefetch.2.8.2 err: file not found while opening file within network system module - Failed to KNSManagerVMakeHttpFileInt('https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/998744B7-E79E-4B21-A1AD-0B7F2B55C33B/SRR1606195.vdbcache?tic=CC004B6F-EE49-4AA9-B926-9D10472F5DFF' (130.14.250.17))
2017-11-20T04:29:21 prefetch.2.8.2: 'SRR1606195' has no remote vdbcache`

**Comment by kwrodarmer** [comment]
You're right - the output is misleading.

There is an auxiliary file we produce to accompany some runs that are badly formed, where the mates are strewn all over the place; the file has a `.vdbcache` extension. If the run you are looking at does not benefit greatly from such a file, then it will be missing.

So the sequence of events is
1. the run file is downloaded
2. its external reference sequence dependencies are analyzed and downloaded
3. we speculatively try to fetch an associated `.vdbcache` file

In your case, the run file downloads fine, it is analyzed for external references and found that it either has none or you already have all of them on your system, and finally it checks for the cache file - gets an error report on its access - and then tells you it didn't have it in the first place, and there you go.

We will create a ticket to silence this bogus error message. Thanks!

**Comment by chefarov** [comment]
@map2085 is right. What's the point of letting you download SRAs from FTP, if you can't use them afterwards (`fastq-dump --split-files local_file.sra`)? The documentation needs an update.

**Comment by kwrodarmer** [comment]
You _can_ use them afterwards, but it complicates issues.
