### ISSUE TITLE
S3 protocol defined, never used

### ISSUE THREAD

**Issue by bollig** [ncbi/sra-tools#421]
Found that eProtocolS3 is defined but never used. Would be useful in some cases to be able to have srapath generate s3 urls when using `srapath -a s3`. Instead I get: 

```
Error: RC(rcVFS,rcQuery,rcResolving,rcParam,rcInvalid)
``` 

https://github.com/ncbi/sra-tools/blob/8c7d15275c69a0cd760722de770bf36b4f154635/tools/srapath/services.c#L55

**Comment by klymenko** [comment]
Yes, use of s3 urls is not implemented.
Currently srapath can return you either remote location (http/https) or local location in your filesystem.
