### ISSUE TITLE
Error code 3

### ISSUE THREAD

**Issue by sarahwalling** [ncbi/sra-tools#423]
I'm attempting to access dbGaP data on AWS, but am getting error code 3 every time I try. prefetch --perm cart.jwt SRR1068808 downloads the accession properly, but if I then run fasterq-dump --perm cart.jwt SRR1068808 to convert it, I get this error:

> 2020-09-24T22:39:02 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='20'
> 2020-09-24T22:39:02 fasterq-dump.2.10.8 err: KFileWriteAll( key ) -> RC(rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
> 2020-09-24T22:39:02 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='20'
> 2020-09-24T22:39:14 fasterq-dump.2.10.8 err: fasterq-dump.c produce_lookup_files() -> RC(rcFS,rcFile,rcWriting,rcStorage,rcExhausted)
> fasterq-dump quit with error code 3

I saw #348, but I'm on the newest version of the toolkit and am still encountering this.

**Comment by durbrow** [comment]
The error is trying to tell you that you are out of disk space.

**Comment by sarahwalling** [comment]
> The error is trying to tell you that you are out of disk space.

That is strange, as there are still 145GB free when I'm getting this error. Are there enormous temporary files that have to be generated for the conversion?

**Comment by durbrow** [comment]
Yes, there are temp files generated, on the same order of size as the final output. `fasterq-dump` has an option to set the location of these files. These are created in the current directory by default, as is the final output. It can easily use 2x the size of the result, or more.
