### ISSUE TITLE
Error using prefetch on bulk downloads using cart file

### ISSUE THREAD

**Issue by SinjaFan** [ncbi/sra-tools#426]
Hello,

Recently I have been trying to download select SRR files from my PI's project on dbGaP. I have tried to use the prefetch function with a cart file in this manner:

prefetch --max-size 1000G --ngc ~/prj_00000.ngc --cart cart_prj00000_202009251150.krt

I have hidden the project number, but the implementation is the same. For every SRR run in the cart file, the same error pops up:

2020-09-29T15:10:31 prefetch.2.10.8 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR8229683' - no data ( 404 )

While at first I thought there was no data in all of the SRR runs, I tried to run prefetch on individual SRRs in my cart file using the below code:

prefetch --max-size 1000G --ngc ~/prj_00000.ngc SRR608002

Some of the runs successfully downloaded while others gave me the same error. I would just like to ask if I am doing anything wrong in trying to bulk download this data and why the error occurs for all of the runs if I use a cart file. Thank you very much!

**Comment by SinjaFan** [comment]
I'd like to say that I have solved this issue. Basically, my cart file included sample runs that were not in sra files. Prefetch only works on the SRR runs that have sra files (which were the files I wanted). Therefore, removing those extraneous runs and using a new cart file, I was able to download the data I wanted successfully using the same line of code.

**Comment by acirrincio** [comment]
Thank you so much! This helped! I was selecting ALL files in the run selector, and the download would not start. The downloads would only start when selecting only a subset of the files.

**Comment by klymenko** [comment]
@SinjaFan, [download the latest toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).
