### ISSUE TITLE
working with cloud delivered files

### ISSUE THREAD

**Issue by chubukov** [ncbi/sra-tools#427]
I recently used the cloud delivery service to get a bunch of runs in SRA format into my S3 bucket. It worked great! I had 20TB of data in my bucket overnight. But I'm having trouble using the rest of the toolkit.

If I go to the bucket root directory which contains all the SRR* directories, and I do `sam-dump SRR8639212` (Thanks to https://github.com/ncbi/sra-tools/issues/302#issuecomment-702849583 for steering me in this direction) I get an error

```
2020-10-02T21:21:51 sam-dump.2.10.8 err: item not found while reading file - input object(s) not found
sam-dump quit with error code 3
```

I noticed that the files I have in the SRR directory have a.`1` extension
```
$ls SRR8639212
SRR8639212.1  SRR8639212.vdbcache.1
```

whereas if I use prefetch, they have the `.sra` extension
```
$prefetch SRR000001
$ls SRR000001
SRR000001.sra
```

and I get different output from srapath also
```
$srapath SRR000001
/root/SRR000001/SRR000001.sra
$srapath SRR8639212
SRR8639212
```

Am I supposed to rename all the files, or is there something else I'm doing wrong?

**Comment by chubukov** [comment]
I've tried a few more things. I've run `vdb-validate`, and there seems to be no issue with the files. But whether I rename them to .sra or not, every time I try to run `sam-dump` or `fasterq-dump`, it tries to retrieve the sra data from the network.

Any advice much appreciated.

**Comment by osris** [comment]
Are you using explicit path to your local file?

**Comment by chubukov** [comment]
@osris no, as suggested in the other thread, I am invoking it from the parent directory

**Comment by osris** [comment]
sorry, i missed that.

**Comment by chubukov** [comment]
@osris did you have any other thoughts on potential issues? I'm inclined to get the files re-delivered as BAM, which will at least fix this particular case, but I'd love to have a more robust workflow with the SRA files.

**Comment by klymenko** [comment]
@chubukov, do you still need help?

**Comment by chubukov** [comment]
@klymenko That would be great -- I think I still haven't been able to get the toolkit to work as intended. 

It doesn't feel like I'm doing anything particularly special, so presumably this would be of general interest too.

**Comment by klymenko** [comment]
@chubukov, I created [a script for you](https://raw.githubusercontent.com/ncbi/sra-tools/VDB-4391/scripts/fix-sra-names.sh)

Run it as `sh fix-sra-names.sh SRR8639212` in directory where `SRR8639212/` directory is located.

Then run `sam-dump SRR8639212` in the same directory. It will find run files in `SRR8639212/` and use them.

**Comment by klymenko** [comment]
Can you give the commands you used to download the files?

**Comment by chubukov** [comment]
@klymenko I got these files through the cloud delivery service https://www.ncbi.nlm.nih.gov/sra/docs/data-delivery/ . 

Thanks a lot for the script, but when I previously tried playing with the filenames on a toy example, it didn't seem to help. Also, the way we've set it up the S3 environment for the large data files I actually don't have write access to the bucket (actually, will that in itself be a problem?).

Thanks a lot for your help -- I will be able to work on this more quickly after the holidays.

V.

**Comment by klymenko** [comment]
Currently the toolkit is expected to work with files downloaded by `prefetch` - it expect certain convention in file/directory names.
Having your names - it can encounter errors.

Most likely vdbcache files will not be detected.
Some runs require reference sequences.
Such files will be fetched over network and in can lead to failures during processing.

**Comment by klymenko** [comment]
@chubukov , do you still need help?
