### ISSUE TITLE
Error: Cannot open VDB 

### ISSUE THREAD

**Issue by jayagami** [ncbi/sra-tools#428]
So,  first I download sra database from website, then I got this error

```
Error: Cannot open VDB: /home/database/SRR364396/SRR364396.sra
```

I thought it could be something wrong with the file, so I  download again by `prefetch SRR364389`, the md5 is the same as the last one.

the command is: 

`tblastn_vdb -db /home/database/SRR364396/SRR364396.sra  -query ./c.part-01.fa -out ./test.out`

**Comment by durbrow** [comment]
Try `tblastn_vdb -db SRR364396 -query ./c.part-01.fa -out ./test.out` or `cd /home/database; tblastn_vdb -db SRR364396 -query ./c.part-01.fa -out ./test.out`

You do not need to give the full path to the .sra file; in fact, you probably do NOT want to.

The expected use pattern (the one we see the most often) is:
cd <path/to/big/disk>
prefetch <SRRxxxxxx>
<sra tool> <SRRxxxxxx>

**Comment by jayagami** [comment]
> Try `tblastn_vdb -db SRR364396 -query ./c.part-01.fa -out ./test.out` or `cd /home/database; tblastn_vdb -db SRR364396 -query ./c.part-01.fa -out ./test.out`
> 
> You do not need to give the full path to the .sra file; in fact, you probably do NOT want to.
> 
> The expected use pattern (the one we see the most often) is:
> `cd <path/to/big/disk>`
> `prefetch <SRRxxxxxx>`
> `<sra tool> <SRRxxxxxx>`



Thanks for your reply, the problem solved.

The `-db`  means the directory of the SRA database, not the file. 

Sorry, I miss misunderstand it.
