### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by gf-atebbe** [ncbi/sra-tools#43]
I'm trying to install the sra toolkit on a clean Debian (Jessie) system and I'm getting an error when I run make:

``` bash
make[1]: Entering directory '/usr/local/ncbi/sra-tools-2.8.0/shared'
make[1]: *** No rule to make target '/libs/kfg/certs.kfg', needed by '/root/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/ncbi/certs.kfg'.  Stop.
make: *** [shared] Error 2
make[1]: Leaving directory '/usr/local/ncbi/sra-tools-2.8.0/shared'
Makefile:48: recipe for target 'shared' failed
```

Below is other information on how I am attempting to run configure and make.  I would note that building sra-tools using the steps listed below completes successfully on 2.7.0.  I only seem to get this error on 2.8.0.

The following are the steps I took to build and install sra-tools, vdb and the ngs-sdk:

``` bash
NGS_VERSION=1.3.0
VDB_VERSION=2.8.0
SRA_VERSION=2.8.0

mkdir /usr/local/ncbi
cd /usr/local/ncbi

wget -O ngs.tar.gz https://github.com/ncbi/ngs/archive/${NGS_VERSION}.tar.gz
tar -xvzf ngs.tar.gz
cd ngs-${NGS_VERSION}
./configure --prefix=/usr/local
make
make install
cd ..
rm ngs.tar.gz

wget -O vdb.tar.gz https://github.com/ncbi/ncbi-vdb/archive/${VDB_VERSION}.tar.gz
tar -xvzf vdb.tar.gz
cd ncbi-vdb-${VDB_VERSION}
./configure --prefix=/usr/local
make
make install
cd ..
rm vdb.tar.gz

wget -O sra-tools.tar.gz https://github.com/ncbi/sra-tools/archive/${SRA_VERSION}.tar.gz
tar -xvzf sra-tools.tar.gz
cd sra-tools-${SRA_VERSION}
./configure --prefix=/usr/local --with-ngs-sdk-prefix=/usr/local/ncbi/ngs-${NGS_VERSION}/ngs-sdk --with-ncbi-vdb-build=/root/ncbi-outdir --with-ncbi-vdb-sources=/usr/local/ncbi/ncbi-vdb-${VDB_VERSION}
make
make install
cd ..
rm sra-tools.tar.gz
```

The following is the output from my ./configure step of sra-tools:

``` bash
Configuring SRA-TOOLS package
checking system type... Linux
checking OS distributor... 
checking machine architecture... x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking whether g++ accepts -static-libstdc++... yes
checking for fuse library... no
checking for hdf5 library... no
checking for magic library... yes
checking for xml2 library... yes
checking for ngs-sdk package...
    includes... /usr/local/ncbi/ngs-1.3.0/ngs-sdk
    libraries... no
    libraries... /root/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
includes: /usr/local/ncbi/ngs-1.3.0/ngs-sdk
libraries: /root/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib
checking for ncbi-vdb package source files and build results...
    includes... /usr/local/ncbi/ncbi-vdb-2.8.0
    src... /usr/local/ncbi/ncbi-vdb-2.8.0
    libraries... no
    src...  libraries... /root/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib
includes: /usr/local/ncbi/ncbi-vdb-2.8.0/interfaces
libraries: /root/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib
ilibraries: /root/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/ilib

configure: creating 'build/ld.linux.exe_cmd.sh'
configure: creating 'build/Makefile.config.linux.x86_64'
configure: creating 'Makefile.config'
configure: creating 'reconfigure'
build type: release
build prefix: /root/ncbi-outdir/sra-tools
build output path: /root/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel
includedir: /usr/local/include
bindir: /usr/local/bin
libdir: /usr/local/lib
CC = gcc -c
CPP = g++
configured with: "'--prefix=/usr/local' '--with-ngs-sdk-prefix=/usr/local/ncbi/ngs-1.3.0/ngs-sdk' '--with-ncbi-vdb-build=/root/ncbi-outdir' '--with-ncbi-vdb-sources=/usr/local/ncbi/ncbi-vdb-2.8.0'"
```

**Comment by vradore** [comment]
I am having the same make error. Does anyone know what was wrong?

**Comment by vradore** [comment]
My installation seems worked. 
How about added one more tag, --with-ncbi-vdb-build=/build/directory/xxx, in your sratools ./configuration step?

**Comment by max1c** [comment]
Having the same problem. @gf-atebbe please let me know if you find the solution.

**Comment by gf-atebbe** [comment]
@max1c I had to revert to the previous release.

**Comment by kwrodarmer** [comment]
You don't want to revert to the previous release: it will **STOP WORKING** over the next few weeks. Please see the README for this project.

**Comment by germelcar** [comment]
Same problem. Any hint?

Thanks in advance.

**Comment by max1c** [comment]
@germelcar Download the binary release here: https://github.com/ncbi/sra-tools/wiki/Downloads

**Comment by germelcar** [comment]
@max1c I did that but I always prefer to compile when possible. But for now, I have downloaded the binaries. Thanks.

**Comment by mvdbeek** [comment]
I also ran into this error, it seems there is an issue in the Makefile.
I could get it to build by doing:
```
export VDB_SRCDIR=<path_to_vdb_sources>
```
Given this is the xth time, and almost very time I upgrade the sratools, I am spending hours to get this to compile. I would strongly suggest that the maintainers build their software in an isolated environment.
This sort of error is so easy to catch nowadays in docker and travis and whatnot, and also serves as a demonstration of how to build. If that's welcome I am happy to submit a PR doing just that.

**Comment by samuelCollombet** [comment]
Hi,
I have the same problem but @mvdbeek fixe did not work for me :(
$ sudo ./configure --build-prefix=/usr/local/src/ncbi --build-prefix=/usr/local/src/ncbi --with-ngs-sdk-prefix=/usr/local/src/ncbi/ngs/ngs-sdk --with-ncbi-vdb-sources=/usr/local/src/ncbi/ncbi-vdb --with-ncbi-vdb-build=/usr/local/src/ncbi
$ export VDB_SRCDIR=/usr/local/src/ncbi/ncbi-vdb
$ sudo make
make[1]: Entering directory `/usr/local/src/ncbi/sra-tools/shared'
make[1]: *** No rule to make target `/libs/kfg/certs.kfg', needed by `/usr/local/src/ncbi/sra-tools/linux/gcc/x86_64/rel/bin/ncbi/certs.kfg'.  Stop.
make[1]: Leaving directory `/usr/local/src/ncbi/sra-tools/shared'
make: *** [shared] Error 2

Annyone as an idea?

This is a bit annoying as I cannot use the old version of prefetch to download SRA (as they switch to https from today...) but I cannot install the new version...

**Comment by mvdbeek** [comment]
@samuelCollombet you're loosing the environmental variable when you're doing sudo.
sudo -E would probably work.

**Comment by samuelCollombet** [comment]
@mvdbeek yes! sorry that was simple :) Thanks!

**Comment by kwrodarmer** [comment]
@mvdbeek - we welcome PRs, with the understanding that we maintain a release pipeline that makes these difficult to execute in an obvious way. We do not support any PR against our engineering branch which changes frequently, and cannot integrate any changes directly into the master branch because of our testing pipeline and binary releases.

That said, by all means we are receptive to changes you may want to submit. We will examine them, and if accepted, will integrate them ourselves either as-is or with modifications after which they will become available when the next release happens.

Regarding you spending hours to get sra-tools to build - our build environment doesn't normally change so rapidly, so whatever worked for you last time is very likely to work for you next time, except of course when people submit PRs to alter the process to their liking which changes it for the rest of the world!

@samuelCollombet - I'm curious why you would run make as root... Install, yes, but make?

**Comment by germelcar** [comment]
@mvdbeek solution works very well for me. Thanks for the solution.

**Comment by samuelCollombet** [comment]
@kwrodarmer as my I downloaded the source into /usr/local/src I am building there too, I have to be sudo to run make:

$sudo ./configure --prefix=/usr/local/src/ncbi/sra-tools --build-prefix=/usr/local/src/ncbi --build-prefix=/usr/local/src/ncbi --with-ngs-sdk-prefix=/usr/local/src/ncbi/ngs/ngs-sdk --with-ncbi-vdb-sources=/usr/local/src/ncbi/ncbi-vdb --with-ncbi-vdb-build=/usr/local/src/ncbi
$export VDB_SRCDIR=/usr/local/src/ncbi/ncbi-vdb
$make
make[1]: Entering directory `/usr/local/src/ncbi/sra-tools/shared'
mkdir: cannot create directory ‘/usr/local/src/ncbi/sra-tools/linux’: Permission denied
mkdir: cannot create directory ‘/usr/local/src/ncbi/sra-tools/linux’: Permission denied
make[1]: *** [/usr/local/src/ncbi/sra-tools/linux/gcc/x86_64/rel/bin/ncbi/certs.kfg] Error 1
make[1]: Leaving directory `/usr/local/src/ncbi/sra-tools/shared'
make: *** [shared] Error 2

**Comment by gf-atebbe** [comment]
Doing make and make install with VDB_SRCDIR set in the environment solved the issue for me.

**Comment by klymenko** [comment]
The issue was fixed.
Use tag 2.8.0-2 in sra-tools

**Comment by darra56-Csir** [comment]
hi everyone, I read the conversation about the installation of new sra tool kit. I have across the same problem, please help me.
the error I got is same, but I could not solve it

~/Downloads/sra-tools-master2.8.0-2$ make
make[1]: Entering directory '/home/aarti/Downloads/sra-tools-master2.8.0-2/shared'
make[1]: *** No rule to make target '/libs/kfg/certs.kfg', needed by '/home/aarti/ncbi-outdir/sra-tools/linux/gcc/x86_64/rel/bin/ncbi/certs.kfg'.  Stop.
make[1]: Leaving directory '/home/aarti/Downloads/sra-tools-master2.8.0-2/shared'
Makefile:48: recipe for target 'shared' failed
make: *** [shared] Error 2
 
I have installed on my home.

**Comment by klymenko** [comment]
@darra56-Csir, what tags of ngs/ncbi-vdb did you download,
how exactly did you run configure in every repository?

**Comment by klymenko** [comment]
We have a new tag 2.8.1 in ncbi-vdb and sra-tools.
Please confirm that this issue was fixed.

**Comment by darra56-Csir** [comment]
the issue was fixed, but now when I am installing it to my new workstation
it is giving me the following error at configure step:

configure: creating 'ld.linux.exe_cmd.sh'
cannot open ld.linux.exe_cmd.sh to write at konfigure.perl line 737.

I am following the following steps to install sra tool kit

rm -r /ncbi-outdir
sudo mkdir /ncbi
cd /ncbi

sudo apt install git
sudo git clone https://github.com/ncbi/ngs.git
sudo git clone https://github.com/ncbi/ncbi-vdb.git
sudo git clone https://github.com/ncbi/sra-tools.git
ngs/ngs-sdk/configure --prefix=/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C ngs/ngs-sdk
ncbi-vdb/configure --prefix=/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C ncbi-vdb
sra-tools/configure --prefix=/software/apps/sratoolkit/gcc/64/2.5.8
make default install -C sra-tools


Please help me.


Aarti Darra
*Research Scholar *(JRF)
Supervised by Dr. Anurag Agrawal <http://www.igib.res.in/?q=AnuragAgrawal>
Center of Excellence in Asthma & Lung Disease,
*CSIR -Institute of Genomics and Integrative Biology (IGIB)
<http://www.igib.res.in/>*
*Mall Road, Delhi-110007,India <http://www.igib.res.in/>*
