### ISSUE TITLE
Error while downloading RNA-seq data using fastq-dump

### ISSUE THREAD

**Issue by Student12364** [ncbi/sra-tools#432]
I was trying to download some data using "fastq-dump --split-files SRR number" and got this error: 

2020-10-23T18:06:45 fastq-dump.2.9.6 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

I have no idea what it means and can't seem to find it anywhere online. 

Any help would be amazing, thank you in advance!

**Comment by durbrow** [comment]
Version 2.9.6 tools do not work any longer. Please upgrade to the latest version of the toolkit.

**Comment by Student12364** [comment]
Okay, thank you!

**Comment by klymenko** [comment]
@Student12364, do you still have problems?

**Comment by Student12364** [comment]
@klymenko No, the problems were solved. But thank you. 

(Sorry, I forgot to close after the problem was solved.)
