### ISSUE TITLE
Prefetch accession limit

### ISSUE THREAD

**Issue by aakashsur** [ncbi/sra-tools#433]
I'm trying to download 377 SRR runs through prefetch and initially tried `prefetch accession_1 accession_2 ... accession_377` but it seems the limit is 256 accessions. If I use the `--option-file` flag it appears to work fine. I suppose having the limit listed in documentation or making the behavior consistent would be helpful.

**Comment by durbrow** [comment]
The limit is not in the tool. The shell or the OS places the limit on the maximum length of a command line.

**Comment by aakashsur** [comment]
I had no idea, thanks!
