### ISSUE TITLE
Error while trying to change the format of my sra Data to Fastq-Format

### ISSUE THREAD

**Issue by Azlan-Nis** [ncbi/sra-tools#436]
Hello Everyone, 

I am quite new to sratool and i am trying to download Seq Data from NCBI as FASTA Format. After some struggle i did manage to download the Data but by using 

Fastq-dump --split-files SRR6848166 

But the tool just downloaded a sra Datatype file. I thought i should get a Fastq one ? 

Then i tried to adjust the Problem by using 

fastq-dump F:\prefetch Datafiles\sra\SRR6848166.sra 

To convert the sra Data to Fastq Format but i just got a Error Message : 

An error occured: Error communicating with NCBI
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/

Mby someone of u guys could help me out. And sorry if my Mistake i a silly one. 

Thanks a lot 

Azlan

**Comment by klymenko** [comment]
Command `fastq-dump --split-files SRR6848166` will create fastq file[s] in your current directory.
