### ISSUE TITLE
location of prefetch download files

### ISSUE THREAD

**Issue by Golden-proteogenomics** [ncbi/sra-tools#437]
I use the command "prefetch --option-file SRR_Acc_List.txt", which was run in window like this 
![图片](https://user-images.githubusercontent.com/50616816/99471636-eede5400-2981-11eb-8664-9dfcb1f75fbb.png. However, the result could not find in the file that run command. So, where the location of the download files by the prefetch

**Comment by klymenko** [comment]
By default they are downloaded to current directory.
