### ISSUE TITLE
what does "clip" mean?

### ISSUE THREAD

**Issue by map2085** [ncbi/sra-tools#44]
`fastq-dump`  has the following option:

>   -W|--clip                        Apply left and right clips 

This is not elaborated anywhere on the sratoolkit page on github.

**Does clip mean "clip low quality bases"  or does it mean "clip adapter sequence" ?**

**Comment by kwrodarmer** [comment]
It means 454 (SFF) adapter clips.

**Comment by map2085** [comment]
OK.  thank you.

**Comment by kwrodarmer** [comment]
I supposed I should generate a ticket to clarify that in the help text, so I won't close this. But is there anything else you need?

**Comment by map2085** [comment]
I'm good for now.  I appreciate the fast response, too.  Thank you.

**Comment by kwrodarmer** [comment]
You're welcome!

**Comment by kwrodarmer** [comment]
I've created an NCBI internal ticket to update the help text, so I'll close it on GitHub.
