### ISSUE TITLE
sra-tools fails to build in aarch64

### ISSUE THREAD

**Issue by zaneChou1** [ncbi/sra-tools#441]
When I run `./configure`  in sra-tools source code，the error occurred，as followed.
```
$ ./configure
Configuring SRA-TOOLS package
checking system type... Linux
checking OS distributor... Ubuntu
checking machine architecture... aarch64
configure: error: unsupported architecture 'Linux'
```
The CPU architecture of my machine is arm64.  
Is there any way to help me run sra-tools on arm64？

**Comment by klymenko** [comment]
We are working on porting sra-tools to ARM64.

**Comment by klymenko** [comment]
We added support of aarch64 in 2.11.0. Please try.

**Comment by zaneChou1** [comment]
@klymenko thank you for supporting aarch64, and I will compile it on aarch64.

**Comment by CaldoSmash** [comment]
Can someone give me a guide in building from source code to make if compatible with Linux ARM64
