### ISSUE TITLE
fasterq-dump doesn't write the .fastq files

### ISSUE THREAD

**Issue by Josuerinho** [ncbi/sra-tools#446]
Hi all!! I'm using fasterq-dump with a loop to download some .sra files. I will paste all the code in case the mistake is somewhere else and I'm not seeing it but is quite an easy one:

#BSUB -J fasterq_dump
#BSUB -W 24:00
#BSUB -o ./
#BSUB -e ./
#BSUB -cwd ./
#BSUB -q transfer
#BSUB -B
#BSUB -N
#BSUB -u jcurto@mdanderson.org
#BSUB -n 1
#BSUB -M 6
#BSUB -R rusage[mem=6]

module load sratoolkit

for f in `cat SRR_Acc_List.txt`; do fasterq-dump -S $f; done

So the problem I'm having is that it starts downloading the temporary files and I can see them:

[jcurto@ldragon3 Clean_3]$ ls -lth fasterq-dump/fasterq.tmp.tdragon2.285397/
total 4.9G
-rwx------ 1 jcurto canbio 427M Dec  4 10:20 SRR9028909.tdragon2.285397.2.2
-rwx------ 1 jcurto canbio 427M Dec  4 10:20 SRR9028909.tdragon2.285397.2.1
-rwx------ 1 jcurto canbio 419M Dec  4 10:20 SRR9028909.tdragon2.285397.5.2
-rwx------ 1 jcurto canbio 419M Dec  4 10:20 SRR9028909.tdragon2.285397.5.1
-rwx------ 1 jcurto canbio 416M Dec  4 10:20 SRR9028909.tdragon2.285397.4.2
-rwx------ 1 jcurto canbio 416M Dec  4 10:20 SRR9028909.tdragon2.285397.4.1
-rwx------ 1 jcurto canbio 421M Dec  4 10:20 SRR9028909.tdragon2.285397.0.2
-rwx------ 1 jcurto canbio 421M Dec  4 10:20 SRR9028909.tdragon2.285397.0.1
-rwx------ 1 jcurto canbio 420M Dec  4 10:20 SRR9028909.tdragon2.285397.3.2
-rwx------ 1 jcurto canbio 420M Dec  4 10:20 SRR9028909.tdragon2.285397.3.1
-rwx------ 1 jcurto canbio 416M Dec  4 10:20 SRR9028909.tdragon2.285397.1.2
-rwx------ 1 jcurto canbio 416M Dec  4 10:20 SRR9028909.tdragon2.285397.1.1

But when the file is totally downloaded, the temporary files disappear and there aren't any .fastq files left. Just starts with the next file in the list, creates new temporary files, and deletes everything again at the end.

So why do you think is not creating the split .fastq files?

Thanks a lot!!

Josu

**Comment by klymenko** [comment]
Look in the current directory where fasterq-dump is executed.

**Comment by Josuerinho** [comment]
Because the directory where the temporary files appear is not where fasterq-dump is actually executed? Although I tried also specifying the directory where I want the program to write the .fastq files and I still have the same problem.

**Comment by klymenko** [comment]
fasterq-dump is actually executed in directory where you execute it.
Add "pwd" to your script and you see this directory.

**Comment by Josuerinho** [comment]
Ok. Then I've already checked that and the files don't appear in that directory. Is it just me having this problem with fasterq-dump?

**Comment by klymenko** [comment]
Did fasterq-dump exited with 0?

**Comment by Josuerinho** [comment]
Hi klymenko,

Sorry for the late response. Actually, it did not. Checking the log file it exited with error code 3. I'm posting the last lines of the file:

2020-12-05T00:50:05 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='5'
2020-12-05T00:50:06 fasterq-dump.2.10.8 err: cmn_iter.c cmn_read_String( #90972161 ).VCursorCellDataDirect() -> RC(rcXF,rcFunction,rcExecuting,rcParam,rcBadVersion) 
fasterq-dump quit with error code 3

**Comment by klymenko** [comment]
You are out of space.

**Comment by Josuerinho** [comment]
I've just remembered that I checked the log file at the beginning when I started having this problem and when I saw the error I thought about the possibility of a space problem as you've just said. But then I checked the server and how much space I have and I still have 5T of free space. On the other hand, fastq-dump normally works with no problems.

**Comment by kwrodarmer** [comment]
The message can be believed - you are out of space on the temporary volume being used. Many users are not aware that there are many volumes on a system. You are not giving any special indication as to which volume should be used, so by default `fasterq-dump` will use the dedicated temporary storage. That is clearly not your 5T.

Please read https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump and pay attention to the sections about temporary storage.

**Comment by Josuerinho** [comment]
Understood! This was indeed very helpful. Thanks a lot for all of your inputs. I will run fasterq-dump again just to test this and use a temporary folder where I know I have more than enough space.

**Comment by kwrodarmer** [comment]
Great to hear! Once you've confirmed that everything is working, we can close the ticket.
