### ISSUE TITLE
system bad file descriptor error fd='4'

### ISSUE THREAD

**Issue by moldach** [ncbi/sra-tools#449]
I'm getting an error trying to download one of the samples from Polaris 1 Diversity Cohort, [HG02771](https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=7143893) from the SRA and getting an error from `fastq-dump`

Each file should be `35Gb` but `fastq-dump` is failing when they get to ~`23Gb`

```
$ fastq-dump --split-files ERR1955420

020-12-10T01:01:34 fastq-dump.2.10.8 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
```

There is lots of storage room left on the server?

**Comment by klymenko** [comment]
Your fastq-dump command downloads to the current directory.
How much free space do you have there?
