### ISSUE TITLE
fasterq-dump documentation needed for --split-files and --outfile

### ISSUE THREAD

**Issue by KasperThystrup** [ncbi/sra-tools#451]
Hi
Thank you for the excellent tools!

One issue I have been facing was to determine the expected behavior of setting up `fasterq-dump` with the `--split-files` and `--outfile X` arguments. This is especially useful for defining the output in a snakemake rule.

Would it be possible to add a simple paragraph in the `--outfile` arguments, for how to define both output filenames?

**Comment by klymenko** [comment]
@wraetz , see VDB-4418.

**Comment by klymenko** [comment]
@KasperThystrup, it was fixed in 3.0.1 release.
Please check.

**Comment by KasperThystrup** [comment]
Thanks, it's really nice that development is ongoing :-)
