### ISSUE TITLE
multiple errors when decrypting dbgap pheotype data already downloaded

### ISSUE THREAD

**Issue by aimeejames** [ncbi/sra-tools#453]
I had success decrypting pdf study files, but now cannot successfully decrypt phenotype data for the same download or for other database downloads within the same project. [#### is in place of my key]
This is my code, which reads a number of files and states "Decrypting file in place" but the files are not decrypted. A number of errors are also mixed in there 
Code:  vdb-decrypt --ngc prj_####.ngc -f  "C:\Users\M237181\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\IBM Aspera\cli\79650-ADSP\PhenoGenotypeFiles\RootStudyConsentSet_phs000572.ADSP.v8.p4.c1.HMB-IRB\PhenotypeFiles"
Error example: err: path excessive while resolving directory within file system module - unable to resolve '.phs000572.v8.pht003391.v5.p4.ADSP_Pedigree.var_report.xml.ncbi_enc.vdb-decrypt-tmp'

For files in a different directory, I get these errors
Code: vdb-decrypt --ngc prj_####.ngc -f "C:\Users\M237181\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\IBM Aspera\cli\79654\PhenoGenotypeFiles\RootStudyConsentSet_phs000496.CIDR_LOAD_RiskandProgression.v1.p1.c1.GRU-IRB\PhenotypeFiles"
Errors:
2020-12-24T18:53:59 vdb-decrypt.2.10.9 err: path invalid while resolving argument list - can not use source '/C/Users/M237181/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/IBM Aspera/cli/79654/PhenoGenotypeFiles/RootStudyConsentSet_phs000496.CIDR_LOAD_RiskandProgression.v1.p1.c1.GRU-IRB/PhenotypeFiles'
 vdb-decrypt.2.10.9: exiting: RC(rcExe,rcArgv,rcResolving,rcPath,rcInvalid)

Please help! I have read everything and tried everything. I have very limited proficiency in using command line and have exhausted so much time, so lay terms and concrete examples are appreciated :)

**Comment by kwrodarmer** [comment]
The tool claims that there is a problem with your path "C:\Users\M237181\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\IBM Aspera\cli\79654\PhenoGenotypeFiles\RootStudyConsentSet_phs000496.CIDR_LOAD_RiskandProgression.v1.p1.c1.GRU-IRB\PhenotypeFiles". It makes this determination based upon what the operating system tells it.

We will have to experiment to discover the exact issue. The types of experiments you can make include changing your working directory to not pass in the full path. This would switch around operation so that you would need to add the path to the `vdb-decrypt` tool to the command, or better yet add the path to sra binaries into your `$PATH`.

**Comment by aimeejames** [comment]
I just tried working from the "cli" folder, which is the directory above all the paths I am using, and I still have the same error :( How do I add the path to sra binaries in my path?

**Comment by klymenko** [comment]
E.g. if toolkit is in directory `S:\TOOLKIT\sratoolkit.2.10.9\sratoolkit.2.10.9-win64\bin`
```
set PATH="S:\TOOLKIT\sratoolkit.2.10.9\sratoolkit.2.10.9-win64\bin";%PATH%
cd "C:\Users\M237181\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\IBM Aspera\cli"
vdb-decrypt --ngc prj_79654.ngc 79654
```

**Comment by aimeejames** [comment]
Sorry for the delay. I tried setting the path and am still having issues. Any other ideas?

**Comment by klymenko** [comment]
@aimeejames, what commands do you execute and what it their output?

**Comment by aimeejames** [comment]
@klymenko

I tried moving the files to make it easier and set the path:


H:\>set PATH "H:\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin\ncbi"
Path=C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\wbem;c:\programdata\oracle\java\javapath;C:\WINDOWS\system32\openssh\;c:\sybase15_0_7\ocs-15_0\bin;c:\sybase15_0_7\ocs-15_0\dll;c:\sybase15_0_7\ocs-15_0\lib3p;c:\sybase15_0_7\dataaccess\adonet\dll;c:\sybase15_0_7\dataaccess\odbc\dll;c:\sybase15_0_7\dataaccess\oledb\dll;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\IBM\SPSS\Statistics\25\JRE\bin;C:\Program Files\SASHome\SASFoundation\9.4\core\sasexe;C:\Program Files\SASHome\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\Secure\ccme4;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\wbem;c:\programdata\oracle\java\javapath;C:\WINDOWS\system32\openssh\;c:\sybase15_0_7\ocs-15_0\bin;c:\sybase15_0_7\ocs-15_0\dll;c:\sybase15_0_7\ocs-15_0\lib3p;c:\sybase15_0_7\dataaccess\adonet\dll;c:\sybase15_0_7\dataaccess\odbc\dll;c:\sybase15_0_7\dataaccess\oledb\dll;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\IBM\SPSS\Statistics\25\JRE\bin;C:\Program Files\SASHome\SASFoundation\9.4\core\sasexe;C:\Program Files\SASHome\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\Secure\ccme4;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\M237181\AppData\Local\Microsoft\WindowsApps;; C:\Users\M237181\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\IBM Aspera\cli\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
Path_old=C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\sybase15_0_7\OCS-15_0\bin;C:\sybase15_0_7\OCS-15_0\dll;C:\sybase15_0_7\OCS-15_0\lib3p;C:\sybase15_0_7\DataAccess\ADONET\dll;C:\sybase15_0_7\DataAccess\ODBC\dll;C:\sybase15_0_7\DataAccess\OLEDB\dll;C:\WINDOWS\system32\WindowsPowerShell\v1.0

H:\>cd "H:\78689\JAAMH\LOAD_6k_CIDR_GWAS\phs000160v1\p1\subject""

H:\78689\JAAMH\LOAD_6k_CIDR_GWAS\phs000160v1\p1\subject>vdb-decrypt --ngc prj_26611.ngc 78689
'vdb-decrypt' is not recognized as an internal or external command,
operable program or batch file.

H:\78689\JAAMH\LOAD_6k_CIDR_GWAS\phs000160v1\p1\subject>vdb-decrypt --ngc prj_26611.ngc 78689
'vdb-decrypt' is not recognized as an internal or external command,
operable program or batch file.

H:\78689\JAAMH\LOAD_6k_CIDR_GWAS\phs000160v1\p1\subject>

**Comment by aimeejames** [comment]
anytime I try something, I just get a different error. Before the command was working...

**Comment by aimeejames** [comment]
anytime I try something, I just get a different error. Before the command was working...

**Comment by aimeejames** [comment]
I also tried reversing this by setting the path to the folder with the encrypted files and working from the file with vdb-decrypt and got this-which looks good, but then when I look in the actual folder the files are still encrypted



C:\>cd "C:\Users\M237181\Desktop\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin\"

C:\Users\M237181\Desktop\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin>vdb-decrypt --ngc prj_26611.ngc 78689
2021-02-22T00:08:44 vdb-decrypt.2.10.9 err: path not found while resolving argument list - can not use source '78689'
2021-02-22T00:08:44 vdb-decrypt.2.10.9: exiting: RC(rcExe,rcArgv,rcResolving,rcPath,rcNotFound) (8522008)

C:\Users\M237181\Desktop\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin>vdb-decrypt --ngc prj_26611.ngc

Usage:
  vdb-decrypt [options] <source-file>
  vdb-decrypt [options] <source-file> <destination-file>
  vdb-decrypt [options] <source-file> <destination-directory>
  vdb-decrypt [options] <directory>

Summary:
  Decrypt a file or all the files (recursively) in a directory


Use option --help for more information.

2021-02-22T00:09:11 vdb-decrypt.2.10.9: exiting: success

C:\Users\M237181\Desktop\sratoolkit.2.10.9-win64\sratoolkit.2.10.9-win64\bin>

**Comment by aimeejames** [comment]
woah it just worked-I will let you know if I have more issues.
