### ISSUE TITLE
sratoolkit error in downloading sra/fastq files 

### ISSUE THREAD

**Issue by BhaktiDwivedi** [ncbi/sra-tools#460]
Hi,

I am trying to download _sra_ or _fastq_ files for RNA-seq experiment; however, I am having problems in downloading them successfully.

I have a list of ~400 SRR accessions (`SRRList.txt`) For example: (showing first three below)
`SRR1164986
SRR1164988
SRR1165007`

When I use `fasterq-dump -e 8 --ngc my_file.ngc --split-files --outdir /my_download/fastq SRRList.txt`

I get the error: `fasterq-dump.2.10.8 err: empty while validating file within network system module - error with https open 'https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/07420A13-4772-4E78-AD9B-3ACB859510DF/SRR1164986'`
`fasterq-dump.2.10.8 err: invalid accession 'SRR1164986'`
Same happens for the rest except may be few are successfully downloaded (e.g., SRR1165007)

I am using sratoolkit.2.10.8-centos_linux64. These are valid accessions. 

OR, when I use `prefetch --ngc my_file.ngc -O /my_download/sra  --option-file SRRList.txt`

I get the error: `prefetch.2.10.8 int: empty while validating file within network system module - cannot open remote file: https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/07420A13-4772-4E78-AD9B-3ACB859510DF/SRR1164986?pId=26366.....`
`prefetch.2.10.8 err: self NULL while reading file within file system module - Cannot KFileRead 'https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/07420A13-4772-4E78-AD9B-3ACB859510DF/SRR1164986?pId=26366': sz=1048576, to=0`
`prefetch.2.10.8: 1) Downloading 'SRR1164986'...
prefetch.2.10.8:  Downloading via HTTPS...
prefetch.2.10.8:  HTTPS download failed
prefetch.2.10.8: 1) failed to download SRR1164986`

Any idea what might be causing this error? How should I fix this? Appreciate your help and suggestions. Thank you.

**Comment by balags1** [comment]
I get this error even when trying individual SRA files, even the one given on the example page. Setting "--type" doesn't seem to work.

 $ prefetch --type fastq SRR11180057

2021-01-22T00:01:14 prefetch.2.10.9 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR11180057' - no data ( 404 )

**Comment by klymenko** [comment]
@BhaktiDwivedi, could you retry your failed `prefetch` command? Does it still fail?

@balags1, `fastq` is not a valid `type` value.
To get fastq for `SRR11180057`, run - `prefetch SRR11180057 && fastq-dump SRR11180057`.

**Comment by BhaktiDwivedi** [comment]
@klymenko 
Thank you for your response. Strangely, when I re-submit the command for let's say the same three SRR accessions: `SRR1164986 SRR1164988 SRR1165007`. I am able to download SRR1164986 successfully (which I couldn't in the earlier run), but unable to download SRR1164988 (couldn't earlier as well) or SRR1165007 (which was downloaded in the previous run). Why such inconsistency? If I had only few accessions to download, I could have tried the command until I retrieve them all, but with a list of SRR accessions (>400), it seems inefficient to keep trying the prefetch command on the failed downloads. What would be a good approach to this? or what would you recommend? Thank you so much.

**Comment by balags1** [comment]
If it is true that fastq isn't a valid value for "type", please refer here. https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/ . Does this mean it is a specific command for AWS or GCP? 
Also, when I look at "prefetch --help", supported "type"'s are not listed, only says default is sra. Would help to know what else can be downloaded by specifying "type". For users with laptops/desktops, is it only sra?

**Comment by BhaktiDwivedi** [comment]
Strangely, when I re-submit the command for let's say the same three SRR accessions: SRR1164986 SRR1164988 SRR1165007. I am able to download SRR1164986 successfully (which I couldn't in the earlier run), but unable to download SRR1164988 (couldn't earlier as well) or SRR1165007 (which was downloaded in the previous run). Why such inconsistency? If I had only few accessions to download, I could have tried the command until I retrieve them all, but with a list of SRR accessions (>400), it seems inefficient to keep trying the prefetch command on the failed downloads. What would be a good approach to this? or what would you recommend? Thank you so much.

**Comment by CurlsForScience** [comment]
An update in case anyone had the same problems I did. Turns out I had run out of memory in my home directory because sratools was storing the .sra.cache files there. I deleted the cached files and everything is running fine now. My understanding is that in the newer version of sratoolkit (2.10+) you can configure the cache to avoid this problem. With 2.9 which I am using, you can also use cache-mgr -c to clear the cached files.

**Comment by klymenko** [comment]
Please update toolkit to the latest release 2.11.0.
We were trying to improve tolerance against network problems.

> If it is true that fastq isn't a valid value for "type", please refer here. https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/ 
My mistake - I did not know it. GitHub issues are about problems with SRA toolkit and are sent to SRA tookit development team.
Send questions about file formats and https://www.ncbi.nlm.nih.gov/sra/docs/sradownload/  to sra-tools@ncbi.nlm.nih.gov or sra@ncbi.nlm.nih.gov.

[Here](https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump) is suggestion about the best way to use `fasterq-dump` and `prefetch`.

`SRR11180057` has `fastq` in cold store.

Networking problems are out of control of SRA toolkit team.
Report them to sra-tools@ncbi.nlm.nih.gov .

Today our best advise it to retry the failed `prefetch` command.

Meanwhile we will try to investigate network problems and improve tolerance against network errors even more.

**Comment by klymenko** [comment]
Do still have this issue?

**Comment by CurlsForScience** [comment]
It is resolved. Thank you.
