### ISSUE TITLE
vdb-confiq: command not found

### ISSUE THREAD

**Issue by ilisulh** [ncbi/sra-tools#461]
I got the error "This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive" 
After running the command, I got the error "-bash: vdb-config: command not found". 
How to fix this? I look at previous post about this, and to fix it I need to change the permission for SRA tool kit to allow read and write, however I don't know how to do this.

**Comment by gubrins** [comment]
Heys @ilisulh , 
I imagine you don't have the function into the path. Try to run the command like this ./vdb-config when you are inside the folder containing that function.
If this works, you should see an interactive blue terminal. If you are running in mac catalina, when you try to save the new options, you will get the message "error saving changes". I'm in that step, let's see if we can fix it!

**Comment by klymenko** [comment]
@ilisulh, which command did you run when you received `This sra toolkit installation has not been configured.`?

**Comment by klymenko** [comment]
@ilisulh, do you still need help?

**Comment by apuhegde** [comment]
(@klymenko Obviously "confiq" was a typo in their question)

WhenI download the current version of sratoolkit (https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit), I see that "vdb-config" within the /bin folder is a link pointing to "vdb-config.2".
"vdb-config.2" in turn is another link that points to "vdb-config.2.10.9".

When I run " ./vdb-config.2.10.9", I get the following output to std out:
`-bash-4.2$ ./vdb-config.2.10.9
<VdbConfig>

<Config>
  <APPNAME>vdb-config</APPNAME>
  <APPPATH>/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin</APPPATH>
  <BUILD>RELEASE</BUILD>
  <HOME>/home/ahegde</HOME>
  <HOST/>
  <NCBI_HOME>/home/ahegde/.ncbi</NCBI_HOME>
  <NCBI_SETTINGS>/home/ahegde/.ncbi/user-settings.mkfg</NCBI_SETTINGS>
  <OS>linux</OS>
  <PWD>/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin</PWD>
  <USER>ahegde</USER>
  <VDBCOPY>
    <DO_NOT_REDACT>CS_KEY,FLOW_CHARS,KEY_SEQUENCE,LINKER_SEQUENCE</DO_NOT_REDACT>
    <META>
      <IGNORE>col,.seq,STATS,BASE_COUNT,HUFFMAN_TREE_POS,HUFFMAN_TREE_POS_SIZE,HUFFMAN_TREE_PRB,HUFFMAN_TREE_PRB_SIZE,HUFFMAN_TREE_SIG,HUFFMAN_TREE_SIG_SIZE,MSC454_CLIP_QUALITY_LEFT,MSC454_CLIP_QUALITY_RIGHT,MSC454_FLOW_CHARS,MSC454_KEY_SEQUENCE,NREADS,NUMBER_POS_CHANNELS,NUMBER_PRB_CHANNELS_1,NUMBER_PRB_COLUMNS,NUMBER_SIG_CHANNELS,PLATFORM,READ_0,READ_1,SPOT_COUNT</IGNORE>
    </META>
    <NCBI_SRA_ABI_tbl_v1_1>
      <schema>sra/abi.vschema</schema>
      <tab>NCBI:SRA:ABI:tbl:v2</tab>
    </NCBI_SRA_ABI_tbl_v1_1>
    <NCBI_SRA_Illumina_tbl_v0a_1>
      <schema>sra/illumina.vschema</schema>
      <tab>NCBI:SRA:Illumina:tbl:phred:v2</tab>
    </NCBI_SRA_Illumina_tbl_v0a_1>
    <NCBI_SRA__454__tbl_v0_1>
      <schema>sra/454.vschema</schema>
      <tab>NCBI:SRA:_454_:tbl:v2</tab>
    </NCBI_SRA__454__tbl_v0_1>
    <READ_FILTER_COL_NAME>READ_FILTER</READ_FILTER_COL_NAME>
    <REDACTABLE_TYPES>INSDC:color:text,INSDC:x2cs:bin,INSDC:2cs:bin,INSDC:2cs:packed,INSDC:dna:text,INSDC:4na:bin,INSDC:4na:packed,INSDC:x2na:bin,INSDC:2na:bin,INSDC:2na:packed,NCBI:SRA:pos16,INSDC:quality:phred,INSDC:quality:log_odds,NCBI:qual4,INSDC:position:one,INSDC:position:zero,NCBI:fsamp4,NCBI:isamp1</REDACTABLE_TYPES>
    <REDACTVALUE>
      <INSDC_color_text>
        <VALUE>'.'</VALUE>
      </INSDC_color_text>
      <INSDC_dna_text>
        <VALUE>'N'</VALUE>
      </INSDC_dna_text>
      <NCBI_qual4>
        <VALUE>-6</VALUE>
      </NCBI_qual4>
      <TYPES>INSDC_color_text,INSDC_dna_text,NCBI_qual4</TYPES>
    </REDACTVALUE>
    <SCORE>
      <INSDC_2cs_bin>2</INSDC_2cs_bin>
      <INSDC_2cs_packed>2</INSDC_2cs_packed>
      <INSDC_2na_bin>2</INSDC_2na_bin>
      <INSDC_2na_packed>2</INSDC_2na_packed>
      <INSDC_SRA_read_type>1</INSDC_SRA_read_type>
      <INSDC_quality_log_odds>1</INSDC_quality_log_odds>
      <INSDC_quality_phred>1</INSDC_quality_phred>
      <INSDC_x2cs_bin>1</INSDC_x2cs_bin>
      <INSDC_x2na_bin>1</INSDC_x2na_bin>
    </SCORE>
    <_454_>
      <schema>sra/454.vschema</schema>
      <tab>NCBI:SRA:_454_:tbl:v2</tab>
    </_454_>
    <_ABSOLID_>
      <schema>sra/abi.vschema</schema>
      <tab>NCBI:SRA:ABI:tbl:v2</tab>
    </_ABSOLID_>
    <_ILLUMINA_>
      <schema>sra/illumina.vschema</schema>
      <tab>NCBI:SRA:Illumina:tbl:phred:v2</tab>
    </_ILLUMINA_>
  </VDBCOPY>
  <VDB_CONFIG/>
  <VDB_ROOT/>
  <config>
    <default>true</default>
  </config>
  <kfg>
    <arch>
      <bits>64</bits>
      <name>ft10.tgen.org</name>
    </arch>
    <dir>/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin/ncbi</dir>
    <name>vdb-copy.kfg</name>
  </kfg>
  <repository>
    <remote>
      <main>
        <CGI>
          <resolver-cgi>https://trace.ncbi.nlm.nih.gov/Traces/names/names.fcgi</resolver-cgi>
        </CGI>
        <SDL.2>
          <resolver-cgi>https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve</resolver-cgi>
        </SDL.2>
      </main>
      <protected>
        <CGI>
          <resolver-cgi>https://trace.ncbi.nlm.nih.gov/Traces/names/names.fcgi</resolver-cgi>
        </CGI>
        <SDL.2>
          <resolver-cgi>https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve</resolver-cgi>
        </SDL.2>
      </protected>
    </remote>
    <user>
      <ad>
        <public>
          <apps>
            <file>
              <volumes>
                <flat/>
                <flatAd>.</flatAd>
              </volumes>
            </file>
            <refseq>
              <volumes>
                <refseqAd>.</refseqAd>
              </volumes>
            </refseq>
            <sra>
              <volumes>
                <sraAd>.</sraAd>
              </volumes>
            </sra>
            <sraPileup>
              <volumes>
                <ad>.</ad>
              </volumes>
            </sraPileup>
            <sraRealign>
              <volumes>
                <ad>.</ad>
              </volumes>
            </sraRealign>
          </apps>
          <root>.</root>
        </public>
      </ad>
      <main>
        <public>
          <apps>
            <file>
              <volumes>
                <flat>files</flat>
              </volumes>
            </file>
            <nakmer>
              <volumes>
                <nakmerFlat>nannot</nakmerFlat>
              </volumes>
            </nakmer>
            <nannot>
              <volumes>
                <nannotFlat>nannot</nannotFlat>
              </volumes>
            </nannot>
            <refseq>
              <volumes>
                <refseq>refseq</refseq>
              </volumes>
            </refseq>
            <sra>
              <volumes>
                <sraFlat>sra</sraFlat>
              </volumes>
            </sra>
            <sraPileup>
              <volumes>
                <withExtFlat>sra</withExtFlat>
              </volumes>
            </sraPileup>
            <sraRealign>
              <volumes>
                <withExtFlat>sra</withExtFlat>
              </volumes>
            </sraRealign>
            <wgs>
              <volumes>
                <wgsFlat>wgs</wgsFlat>
              </volumes>
            </wgs>
          </apps>
        </public>
      </main>
    </user>
  </repository>
  <tls>
    <ca.crt>
      <ncbi1>-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4wOTAeBggrBgEFBQcD
BAYIKwYBBQUHAwEGCCsGAQUFBwMDDBdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQQ==
-----END CERTIFICATE-----
</ncbi1>
      <ncbi2>-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug
RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm
+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW
PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM
xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB
Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3
hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg
EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF
MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA
FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec
nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z
eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF
hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2
Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe
vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep
+OkuE6N36B9KMEQwHgYIKwYBBQUHAwQGCCsGAQUFBwMBBggrBgEFBQcDAwwiRGln
aUNlcnQgSGlnaCBBc3N1cmFuY2UgRVYgUm9vdCBDQQ==
-----END CERTIFICATE-----
</ncbi2>
    </ca.crt>
  </tls>
  <tools>
    <ascp>
      <max_rate>450m</max_rate>
    </ascp>
  </tools>
  <vdb>
    <lib>
      <paths>
        <kfg>/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin</kfg>
      </paths>
    </lib>
  </vdb>
</Config>

<ConfigurationFiles>
/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin/ncbi/certs.kfg
/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin/ncbi/default.kfg
/data/CCTMS/COH_FlaviaPichiorri_MyelomaPI/SRAtoolkit/sratoolkit.2.10.9-centos_linux64/bin/ncbi/vdb-copy.kfg
</ConfigurationFiles>
<Environment>
</Environment>
</VdbConfig>` 

I do not get an interactive screen as specified here:
https://github.com/ncbi/sra-tools/wiki/03.-Quick-Toolkit-Configuration

I read through some other issues posted to github (https://github.com/ncbi/sra-tools/issues/291) and the solution mentioned was to use a "docker file". I'm working on my institution's HPC system. Could you please elaborate a little so I could work with our HPC team to get the "docker file" to work for us? If the docker solution doesn't work on an HPC system (as the last comment in the above github issues pages alludes to, I think?), how can people like me download SRA files? Thanks.

**Comment by tiandachen** [comment]
you need to run the command,"./vdb-config --interactive" but not "vdb-config --interactive"

**Comment by Mallikarjun-s-beelagi** [comment]
make sure that path contains your particular function. then write ./vdb-config --interactive. this will popup a dialogue box where you can enable the access.
