### ISSUE TITLE
An error occured: std::exception

### ISSUE THREAD

**Issue by jjz-jj** [ncbi/sra-tools#465]
I encounter this error after the quick configuration. 
$fastq-dump --stdout SRR390728 | head -n 8
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/

I'm not sure what is wrong.
Thank you for any help

**Comment by klymenko** [comment]
What is the output of the following:
```
srapath -V
srapath SRR390728
```

**Comment by jjz-jj** [comment]
> What is the output of the following:
> 
> ```
> srapath -V
> srapath SRR390728
> ```

$srapath SRR390728
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
$srapath -V
"srapath" version 2.10.4


But I don't have this problem anymore after upgrade to version 2.10.9 :)
