### ISSUE TITLE
prefetch download error

### ISSUE THREAD

**Issue by dhivyaa-6** [ncbi/sra-tools#466]
I would like to download files from an authorized project and did 

prefetch --ngc prj_26128.ngc SRR5229207

There is no error message nor do the .sra files get downloaded. I use sra-toolkit/2.10.8. 

I guess it has something to do with the vdb-config --interactive, and removed the .ncbi folder to remove the cache and tried running prefetch again but it generates a message to configure vdb-config

When I do vdb-config --interactive, it is non-responsive.

**Comment by klymenko** [comment]
Please install 2.10.9.

Add `-p` to `prefetch` command line to see progress.
Does it download?

**Comment by klymenko** [comment]
Do you still need help?
