### ISSUE TITLE
Failed to call external services.

### ISSUE THREAD

**Issue by vinlin0801** [ncbi/sra-tools#467]
I install the latest SRAToolkit on the ubuntu server in our lab. After configured vdb-config I run fastq-dump --stdout SRR390728 | head -n 8
and it returns "Failed to call external services."

I have no idea why this happens, and the server is connected with the internet.

And I tried installing by conda install -c bioconda/label/cf201901 sra-tools, and configure and run fastq-dump --stdout SRR390728 | head -n 8
it returns "2021-02-07T09:41:53 fastq-dump.2.9.1 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table"

What information about the server environment do I need to provide to tackle this problem?

**Comment by klymenko** [comment]
Could you install 2.10.9?

**Comment by vinlin0801** [comment]
> Could you install 2.10.9?

Yes, I have install the latest version which I believe is 2.10.9, and I got "Failed to call external services."

**Comment by owensgl** [comment]
I want to echo this problem. I get the same issue when trying to call fasterq-dump.
`/home/owens/bin/sratoolkit.2.10.8-ubuntu64/bin/fasterq-dump SRR5912263 -e 10 -t ../tmp_sradump` returns
`Failed to call external services.`
The server is connected to the internet. I suspect its some sort of quota from the SRA because I had this command within a pipeline and it worked for several samples, until it downloaded a very large file and then subsequently wouldn't connect after that.

**Comment by klymenko** [comment]
Do you have internet access?

**Comment by vinlin0801** [comment]
> Do you have internet access?

Yes

**Comment by klymenko** [comment]
Please print the full command line and its output.

**Comment by vinlin0801** [comment]
I reinstall using conda, and it works now, I cannot reproduce the error. Thank you!

**Comment by DeevanshuGoyal** [comment]
Hi

I am facing the same problem currently. 

Input line: fastq-dump --stdout SRR390728 | head -n 8

Output: Failed to call external services.

@klymenko can you please help me here?

**Comment by liuxiaowei0401** [comment]
Now I have this problem，Failed to call external services.

**Comment by klymenko** [comment]
@DeevanshuGoyal , @liuxiaowei0401 , what is the output of `srapath SRR390728`?

**Comment by biomedswe** [comment]
why was this ticket closed? I have this error, I tried to reinstall with conda but still have the same problem.

`fastq-dump --gzip --defline-qual '+' SRR11412215     `                                                                                                                            Failed to call external services.

**Comment by durbrow** [comment]
The sra-tools available through conda is not NCBI's sra-tools. NCBI didn't create it and doesn't maintain it. At some point in the future, NCBI may create and maintain a distribution through conda, but it doesn't yet. I don't know when we will be able to get to it. (Hint, make a request for it via the email address at the top of our README)

**Comment by biomedswe** [comment]
> The sra-tools available through conda is not NCBI's sra-tools. NCBI didn't create it and doesn't maintain it. At some point in the future, NCBI may create and maintain a distribution through conda, but it doesn't yet. I don't know when we will be able to get to it. (Hint, make a request for it via the email address at the top of our README)


Thx for you answer! I tried the distribution from NCBI which worked fine:)

**Comment by pabisk** [comment]
Not using the conda version and I am getting the same error with the version 2.11.3 using the following command:

`fasterq-dump SRR9016180 -p -O folder -e 7 -t folder cache-mgr folder`

Is there perhaps an issue with the (apparently undocumented) cache-mgr command? Unfortunately, I need to clear up the cache because the tool is unusable for me otherwise since it does not clean up the cache by itself and ends up eating terabytes of space even on small projects. Let me know if there is a better workaround that solves the issue. Thank you.

**Comment by alexlenail** [comment]
I am still having this error with `fasterq-dump`, `sratoolkit-3.0.0`

**Comment by Fred-White94** [comment]
For me all versions of fastq dump on the latest sratoolkit return the initially reported error.
I can also not use the SRAdb R package to get around the problem, here I can search the database but when trying to download a set of samples it fails.

However fasterqdump from the latest sratoolkit works

**Comment by nliorni** [comment]
I am facing the same problem. Literally yesterday I was able to download a full dataset, this morning I receive this error while trying to download another dataset.

**Comment by mariana2323** [comment]
the solution for windows is adding double quotes before and after accession, like this: `fastq-dump --stdout -X 2 "SRR390728"`

**Comment by JoseBlanca** [comment]
Using fasterq-dump 3.2.0, I get the same error.


```
$ fasterq-dump --split-files "SRR23560428" --outdir tmp/ncbi_fastq_test  --temp tmp/ --split-3 --threads 6 --details  --skip-technical --defline-seq '@rd.$si:$sg:$sn'
Failed to call external services.
$ srapath SRR23560428
https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR23560428/SRR23560428
```

Any idea on how could I solve it?

**Comment by durbrow** [comment]
Do `prefetch SRR23560428` first.

NB, `--defline-seq` should be `--seq-defline`, then your "Failed to call external services." will go away. Also, you should not use both `--split-files` and `--split-3`, they are conflicting options; `--split-3` is almost always what you want.
