### ISSUE TITLE
--option-file does nothing when used for batches

### ISSUE THREAD

**Issue by KasperThystrup** [ncbi/sra-tools#470]
Hi
I have an issue with semi-automating fasterq-dump. I wish to dump a bunch of downloaded sra files in a batch using `--option-file`. However when using a text file consisting of each .sra files in a single text file, nothing happens.

Minimum example:
```
# setup
> ls ./
SRR12927182
SRR10991486
SRR10545428
SRR10037664
sras.txt

> cat sras.txt
SRR12927182/SRR12927182.sra
SRR10991486/SRR10991486.sra
SRR10545428/SRR10545428.sra
SRR10037664/SRR10037664.sra
```
This command provides no errors, no warnings, no help. It only prints the entire help page.
```
> fasterq-dump --option-file sras.txt
Usage:
fasterq-dump.2.10.9 <path> [options]

Options:
...
```

Since this format seems to work with prefetch, I don't understand why it wouldn't work with fasterq-dump.

**Comment by osris** [comment]
For files you have downloaded, explicit path should be used.  Prefetch relies on our data location service to find where the accession is stored at NCBI.


-Chris

**Comment by wraetz** [comment]
The fasterq-dump - tool does not handle more than one accession at a time.
The use of the option-file does not change that.
If you want more than one accession - use the driver-tool, it can handle multiple accessions.
But only from the commandline!
If you pass an option-file to the driver-tool, it passes it to fasterq-dump, which cannot handle more than one accession.

**Comment by klymenko** [comment]
@KasperThystrup, do you still need help?

**Comment by KasperThystrup** [comment]
Thank you.
No, this is not relevant anymore for me. However, I see it as being counter-intuitive that fasterq-dump can't handle multiple accession numbers directly when fastq-dump can i.e. via the --option-file argument.

You can close if there are no plans to change this behavior, but I don't see it as "fixed".

**Comment by durbrow** [comment]
fasterq-dump is a tool whose raison d'etre is SPEED. A Cadillac SUV and a Formula 1 race car are both automobiles, but would you ask that the race car have heated seats?

**Comment by lajoimat** [comment]
Asking for a downloading "tool" to handle a list of files (just like the other "tools" in the "toolbox") is not luxury.

**Comment by durbrow** [comment]
It's not a luxury, it's an unnecessary complication. `fasterq-dump` is not a downloading tool, downloading is a side effect and isn't recommended. The recommended way is to download with `prefetch` first. 

There are tools whose only purpose is to do this sort of thing. For example, try `xargs`.
