### ISSUE TITLE
getting "Segmentation fault" from "prefetch" with JWT cart

### ISSUE THREAD

**Issue by mjko1210** [ncbi/sra-tools#474]
Hi,

I'm trying to download BAMs from dbgap (from cloud) using AWS.

I downloaded jwt.cart file and I used prefetch command to download data (as it described from this page: https://www.ncbi.nlm.nih.gov/sra/docs/sra-dbGAP-cloud-download/)

However, I'm getting following error:

ubuntu@ip-172-31-22-60:~$ prefetch --perm MBC.jwt
Downloading jwt cart file 'MBC.jwt'

2021-03-04T23:34:16 prefetch.2.10.9 fatal: SIGNAL - Segmentation fault

I'm using most up to date sra toolkit (sratoolkit.2.10.9). Do you have any suggestions for this error?
Thanks,
MJ

**Comment by klymenko** [comment]
Please try our latest 2.11.0 release.

**Comment by mjko1210** [comment]
Thanks for this. I tried with latest release, however, I'm getting another error:

2021-03-17T17:49:35 prefetch.2.11.0 err: error unexpected while resolving query within virtual file system module - Claims have expired ( 400 )

Does this mean my JWT cart file has expired?

Thanks!

**Comment by klymenko** [comment]
Yes, you will have to make your JWT cart again.

**Comment by mjko1210** [comment]
Hi, 

I've tried with new JWT cart file, however, I ran into other issues:

![image](https://user-images.githubusercontent.com/9116362/113227990-c415dd80-9248-11eb-9fe2-5e636918cc08.png)

I assume this was caused by limited storage that I assigned  (40G) when I first created EC2 instance.

I heard from IT (from my institute) that I don't need to set this to the total size of all the datasets I want to download, just the size of the largest one (plus say 8GB for overhead). Maybe I'm misunderstanding this. Please correct me. (I need to download hundreds samples of SRA)

My questions are :
1) How to set storage properly (from AWS) if I want to download all the samples at once? I was also concerned about the cost if I have to increase the storage.
2) After few trials, I got another error: 
![image](https://user-images.githubusercontent.com/9116362/113228732-608caf80-924a-11eb-8b08-3e8f2f2ae005.png)
I don't understand why jwt cart file expired quickly (within an hour or so). Is there other method to download data without using JWT cart file? I need to download it from dbgap's cloud because I need original submitted data files. And these are all cell free DNA WES BAM files. 

I would appreciate your comments!

Thanks!

**Comment by mjko1210** [comment]
I also wonder why it creates files as SRA and not BAMs.
This was my command :
prefetch --perm phs001417.jwt

I only see few SRA files (first 3 samples has downloaded successfully before I met storage error above) saved under `download/sra` folder. but I don't see any BAM files.

**Comment by klymenko** [comment]
Email these questions to sra-tools@ncbi.nlm.nih.gov

**Comment by mjko1210** [comment]
Thanks. How about jwt cart file? Is this the only way to download data from cloud?

**Comment by mjko1210** [comment]
Just now I tried again with existing jwt cart file. 

ubuntu@ip-XXXX:~$ prefetch --perm phs001417_MBC.jwt -T all
Downloading jwt cart file 'phs001417_MBC.jwt'

and this time, it didn't give me any message and just stopped. I wish I can use existing jwt cart file (it was a hassle to create this file with hundreds of samples, had to manually clicked them all)

**Comment by klymenko** [comment]
Did `prefetch` finish?
Processing big cart takes big time.
I would recommend you to create multiple smaller carts.
For best practices email to sra-tools@ncbi.nlm.nih.gov

**Comment by mjko1210** [comment]
No. it didn't finish at all.

I was seeing errors yesterday (complain about storage and about expired jwt cart). but I don't see any messages now which is very strange. Is it because I don't have enough space?

ubuntu@ip-XXXXXXXX:~$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev              486564        0    486564   0% /dev
tmpfs             100208      700     99508   1% /run
/dev/xvda1      40593612 37417812   3159416  93% /
tmpfs             501036        0    501036   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs             501036        0    501036   0% /sys/fs/cgroup
/dev/loop0         28800    28800         0 100% /snap/amazon-ssm-agent/2012
/dev/loop1         56832    56832         0 100% /snap/core18/1997
/dev/loop2         34176    34176         0 100% /snap/amazon-ssm-agent/3552
/dev/loop3        101632   101632         0 100% /snap/core/10908
/dev/loop4        101632   101632         0 100% /snap/core/10859
tmpfs             100204        0    100204   0% /run/user/1000

**Comment by mjko1210** [comment]
After I increase the storage I can see error msg again : 
2021-04-01T22:10:26 prefetch.2.11.0 err: error unexpected while resolving query within virtual file system module - Claims have expired ( 400 )

Is there way to keep jwt cart file longer?  If I create multiple jwt cart files, it's going to expire within an hour, right?

**Comment by klymenko** [comment]
Yes,  all jwt cart files will have the same validity time.
Email questions about jwt carts and best practices to sra-tools@ncbi.nlm.nih.gov

**Comment by mjko1210** [comment]
Thanks! I also emailed and heard from them.

So, is this command below will create both .SRA and .BAM?
`prefetch --perm phs001417_MBC.jwt -T all`

I only need BAM. Is there way to download BAM only?

**Comment by klymenko** [comment]
Usually using `-T bam` will download BAM only.

**Comment by klymenko** [comment]
@mjko1210, do you still need help?
