### ISSUE TITLE
faster-dump not available for Windows version of toolkit

### ISSUE THREAD

**Issue by DeevanshuGoyal** [ncbi/sra-tools#476]
Hi,

I was trying to install the SRA toolkit on my Windows system and I figured that the fasterq-dump function wasn't available in the bin for the latest version of the Windows toolkit (2.10.9). However, this function is available in the MacOS version. 

This would greatly limit my work since I wish to download a large number of files fom the SRA database and fasterq would work better than fastq. Can someone help me with this?

**Comment by klymenko** [comment]
We have just released 2.11.0 that includes fasterq-dump for Windows:
https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.11.0/sratoolkit.2.11.0-win64.zip

Please try.
