### ISSUE TITLE
Seeks help to understand what is wrong with SRA extraction

### ISSUE THREAD

**Issue by Guillaume-Marseille** [ncbi/sra-tools#477]
Hello

I am looking to extract the reads of SRR10392092 in fastq format
According to https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10392092 this dataset has 34.8M spots and 2 reads per spot.

I first installed sratoolkit.2.11.0-ubuntu64 

Then I ran 
`prefetch SRR10392092`
SRR10392092 was downloaded successfully 

Then
`fasterq-dump SRR10392092`

spots read      : 34,849,884
reads read      : 69,699,768
reads written   : 34,849,884
reads 0-length  : 34,849,884

which resulted in a single fastq file containing 34.8M reads, whereas 2 files were expected, one for each read direction.

I tried various commands with different flags but without success

`fasterq-dump SRR10392092 --split-spot  --include-technical`

`fasterq-dump SRR10392092 --include-technical`

I also tried:
`prefetch --type fastq SRR10392092`

this error popped up:
2021-03-18T15:31:32 prefetch.2.11.0 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR10392092' - no data ( 404 )

For the moment I am stuck without finding the solution.
However it seems that the information is complete in the downloaded SRR10392092.sra file since fasterq-dump sees the right number of reads but only extracts half of them in the single fastq file.

Thank you for the help
Guillaume

**Comment by durbrow** [comment]
Please look again at the link you provided https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10392092
You will notice it has 2 reads, one with length 150, and one with length 0.
