### ISSUE TITLE
ngs-sdk package not found during configure

### ISSUE THREAD

**Issue by john-lee-johnson** [ncbi/sra-tools#48]
Hello!

I am trying to install the latest sra-tools, but during the configure command it fails saying it can't find the ngs-sdk package.

I have built ngs from source using the configure command:
`./configure --prefix=/mnt/data1/bin/ngs --build-prefix=/mnt/data1/bin/ncbi-outdir`

I then followed the rest of the instructions accordingly and ngs-sdk seemed to install fine. (Except that it told me to `Use $NGS_LIBDIR in your link commands` and I'm not sure what that means)

I then tried to run the configure command for sra-tools as such:
`./configure --prefix=/mnt/data1/bin/sra-tools --build-prefix=/mnt/data1/bin/ncbi-outdir`

But then i get the `configure: error: required ngs-sdk package not found`

Sorry, I'm very new to this. Appreciate the help!

**Comment by klymenko** [comment]
Did you follow "instructions for building and installing sra-tools from source" on https://github.com/ncbi/sra-tools/wiki/Building-and-Installing-from-Source ?

**Comment by john-lee-johnson** [comment]
Yes I did. Sorry, I should have clarified. And both ngs and ngs-vdb appears to have installed correctly as far as I can tell. However I get stuck when I try to run the configure command for sra-tools saying it can't find ngs-sdk. Not sure if it is because I used a custom path when installing ngs-sdk, but it does seem to find the location of the libraries when running configure:
`checking for ngs-sdk package...`
	`libraries... no`
	`libraries... /mnt/data1/bin/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/lib`
`configure: error: required ngs-sdk package not found.`

**Comment by klymenko** [comment]
What configure command did you use for ncbi-vdb ?

**Comment by john-lee-johnson** [comment]
I used
`./configure --prefix=/mnt/data1/bin/ncbi-vdb --build-prefix=/mnt/data1/bin/ncbi-outdir`

and when I run `echo $LD_LIBRARY_PATH` it says
`/mnt/data1/bin/ngs/lib64:/mnt/data1/bin/ncbi-vdb/lib64:`

**Comment by klymenko** [comment]
What are the names of directories where the sources of "ngs", "ncbi-vdb", "sra-tools" packages are?

**Comment by john-lee-johnson** [comment]
I cloned the github repositories of `ngs` and `ncbi-vdb` to:
`/mnt/data1/bin/ncbi`

I cloned the github repository of `sra-tools` to:
`/mnt/data1/bin/sra-tools`

I then used the configure --prefix option to install ngs and ncbi-vdb to
`/mnt/data1/bin/ngs` and `/mnt/data1/bin/ncbi-vdb`

**Comment by klymenko** [comment]
So, they are located in 

/mnt/data1/bin/ncbi/ngs ( /mnt/data1/bin/ncbi/ngs/sdk etc)
/mnt/data1/bin/ncbi/ncbi-vdb
/mnt/data1/bin/ncbi/sra-tools

?

**Comment by john-lee-johnson** [comment]
Yes that is correct.

**Comment by klymenko** [comment]
Please rerun configure in sra-tools, but add --debug to command arguments.
Send us the complete output.

**Comment by klymenko** [comment]
sra-tools is in /mnt/data1/bin/ncbi/sra-tools or /mnt/data1/bin/sra-tools ?

**Comment by john-lee-johnson** [comment]
I see my problem now! I had cloned sra-tools into /mnt/data1/bin/sra-tools, but I see now that it was expecting it to be in the same ncbi folder as ngs and ngs-vdb. I then cloned sra-tools into /mnt/data1/bin/ncbi along with ngs and ngs-vdb and it worked!

Thank you, I am sorry for wasting your time on such a simple problem.

**Comment by klymenko** [comment]
You are welcome.

Another possibility was to add  to arguments --with-ngs-sdk-prefix and --with-ncbi-vdb-sources .
