### ISSUE TITLE
arasida

### ISSUE THREAD

**Issue by arasida** [ncbi/sra-tools#480]
Hi, I have been trying to make SRA toolkit work on my Macbook but have been having issues with the configuration. No matter what I do, it gives me "vdb-config: command not found" every time. Does anybody have an idea what I could be doing wrong?

Thank you!

**Comment by klymenko** [comment]
Try to follow https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit#3-for-convenience-and-to-show-you-where-the-binaries-are-append-the-path-to-the-binaries-to-your-path-environment-variable
