### ISSUE TITLE
Add /bin/bash to Docker images

### ISSUE THREAD

**Issue by sminot** [ncbi/sra-tools#481]
For use of Docker images using Nextflow, it is best to have a working copy of `/bin/bash` installed. For these Alpine systems, this can be accomplished rather easily following https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/. If possible, people might find it useful if this were included in the automated image builds produced here.

**Comment by osris** [comment]
this seems like it could help a bunch of users.  i'm just trying to imagine cases where it might hurt (and not coming up with any, but this isn't my area of expertise)

**Comment by durbrow** [comment]
It would make the docker image bigger. The main reason to use Alpine as the base is that it is the bare minimum, thus giving you the smallest fastest images. If you can run a docker image, it is trivial to make your own and use that. An example `Dockerfile` would be:
`FROM ncbi/sra-tools:latest`
`RUN apk add --no-cache bash`
Then build it, eg:
`docker build -t sra-tools_bash .`

**Comment by sminot** [comment]
I appreciate the advice, although the issue I had with that approach is that it requires that `vdbconfig -i` be run interactively, and I couldn't figure out how to set up an automated build which accomplished that. Is there a solution to the `vdbconfig` issue that maybe I can try when making my own image?

**Comment by durbrow** [comment]
Could you try it again? It worked fine for me with that `Dockerfile`:
```
ken@iMac5K2019 sratools+bash % docker build -t sra-tools_bash .                                                                
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM ncbi/sra-tools:latest
 ---> 1d104bb91fb5
Step 2/2 : RUN apk add --no-cache bash
 ---> Running in a2c8b6b51242
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(2/4) Installing ncurses-libs (6.2_p20210109-r0)
(3/4) Installing readline (8.1.0-r0)
(4/4) Installing bash (5.1.0-r0)
Executing bash-5.1.0-r0.post-install
Executing busybox-1.32.1-r3.trigger
OK: 8 MiB in 18 packages
Removing intermediate container a2c8b6b51242
 ---> 396ea6a5cf90
Successfully built 396ea6a5cf90
Successfully tagged sra-tools_bash:latest
ken@iMac5K2019 sratools+bash % cd ..
ken@iMac5K2019 tmp % docker run -it --rm -v $PWD:/output:rw -w /output sra-tools_bash fasterq-dump -e 2 -p SRR10985476
lookup :|-------------------------------------------------- 100%   
merge  : 15536350
join   :|-------------------------------------------------- 100%   
concat :|-------------------------------------------------- 100%   
spots read      : 14,965,183
reads read      : 14,965,183
reads written   : 14,965,183
```

**Comment by sminot** [comment]
It looks like this is working in my hands as well!

If anyone else wants to use this image, the Dockerfile and image can be found here:
https://github.com/FredHutch/docker-sratools
https://quay.io/repository/hdc-workflows/sratools
