### ISSUE TITLE
fastq-dump error running on downloaded .sra

### ISSUE THREAD

**Issue by bjstewart1** [ncbi/sra-tools#482]
I am downloading a large number of .sra files.
Doing so with ```prefetch``` is simply far too slow for the volume of data, so I am acquiring these via Globus from ENA.
I follow this up with 
```fastq-dump --split-files --outdir ./${SMP}/${SMP}_fastq --gzip ./${SMP}/${SMP}.sra```

where 
SMP=SRRaccession

This works for most accessions and I get nice fastq files out.

But for some accessions it throws this error:
```fastq-dump.2.8.0 fatal: SIGNAL - Segmentation fault ```

An example of an accession that fails is SRR9320604

Any idea how to fix this?

**Comment by klymenko** [comment]
Download [the latest toolkit](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).

**Comment by bjstewart1** [comment]
fixes. many thanks
