### ISSUE TITLE
Failed to resolve accession 'ERR2752451'

### ISSUE THREAD

**Issue by probalica19** [ncbi/sra-tools#484]
Hi, 

I am trying to download the data with accessions [ERR2752451](https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=%20ERR2752451&o=acc_s%3Aa) and [ERR2752452](https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=%20ERR2752452&o=acc_s%3Aa). The version of SRA toolkit that I am using is 2.10.8.

Looking at the Run Selector, it seems like the data should be available. I have successfully downloaded other data from that project ([PRJEB27698](https://www.ncbi.nlm.nih.gov/bioproject/PRJEB27698)) before. For these two accessions I have tried with `prefech`, `fastq-dump`, `fasterq-dump` and `sam-dump` and I always get some of the following error messages:

(`prefetch`)
```
err: name not found while resolving query within virtual file system module - failed to resolve accession 'ERR2752452' - no data ( 404 )
```
or (`fastq-dump` and `fasterq-dump`)
```
err: item not found while constructing within virtual database module - the path 'ERR2752451' cannot be opened as database or table
fastq-dump quit with error code 3
```
or  (`sam-dump`)
```
err: invalid accession 'ERR2752451'
```

Could you please help me resolve this issue?

Thank you in advance, 

probalica19

**Comment by klymenko** [comment]
Please send this question to sra-tools@ncbi.nlm.nih.gov

**Comment by klymenko** [comment]
@probalica19, do you still need help?

**Comment by probalica19** [comment]
Hi @klymenko, 

I emailed sra-tools@ncbi.nlm.nih.gov the same day as your previous reply, but I never received an answer. So I do still need help with this, thank you!

Regards, 
@probalica19

**Comment by klymenko** [comment]
It looks like for ERR2752451 and ERR2752452 there are just bam-s but no sra files.

You can `prefetch` bam-s by adding `-T all`.
You cannot `fastq-dump`, `fasterq-dump` and `sam-dump` because they require sra-s.

**Comment by klymenko** [comment]
@probalica19, do you still need help?
