### ISSUE TITLE
Issues downloading fastq data

### ISSUE THREAD

**Issue by PabloJGiraudi** [ncbi/sra-tools#486]
Hello,

I am experiencing issues when downloading from SRA several data using the following command, and I do not understand how to manage it.......

# in ids_mod1.txt file there are 3 SRR ids and I am using WSL ubuntu.

$ cat ids_mod1.txt | parallel fastq-dump --split-files {}

2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 )
Failed to call external services.
2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 )
Failed to call external services.

I find similar problems using GUI parallel with other commands so I though the issue was with parallel but if I use parallel with echo... parallel do its work.....

Could somebody give me a hand with this.... many thanks in advance

**Comment by klymenko** [comment]
`fastq-dump` accepts accession[s] as command line argument[s].
`fasterq-dump` accepts a single accession as command line argument.

What arguments come to command line of `fastq-dump` that you mention?

**Comment by PabloJGiraudi** [comment]
The following accession ids were included in the ids_mod1.txt file:

SRR9883113
SRR9883116
SRR9883117

**Comment by klymenko** [comment]
`fastq-dump` will be able to process any combination of these accessions when they are present in its command line.
Could you verify what arguments come to command line of `fastq-dump`?

**Comment by PabloJGiraudi** [comment]
thanks klymenko
the following arguments:

fastq-dump --split-files SRR9883116
fastq-dump --split-files SRR9883117
fastq-dump --split-files SRR9883118

could be a problem related to WSL ?

**Comment by klymenko** [comment]
Does `fastq-dump --split-files SRR9883116` fail?
What is the complete output?
`No accession to process ( 500 )`?

Could you run just `fastq-dump --split-files SRR9883116`?
Without `parallel`?

**Comment by PabloJGiraudi** [comment]
yes, no problem when using fastq-dump without parallel, but I want to automate, there are 100 samples.

Pablo

**Comment by PabloJGiraudi** [comment]
-complete output was:

2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 )
Failed to call external services.

**Comment by klymenko** [comment]
So, it's a problem in parallel, not SRA toolkit.

We recommend to use prefetch + fasterq-dump - it will be more reliable and faster at the end but requires more resources.
See https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump

**Comment by PabloJGiraudi** [comment]
Ok, many thanks Andrew,

Pablo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Helxinki** [comment]
I had the sam problem exactly as yours. And it turns out to be the '\r' at the end of each lines of the accession number in the list when it is produces by Win instead of Linux. That's why fastq-dump can't get the correct accession name. Just delete using the command 'sed'. Hope this finds you well. Cause I have been stuch on this for 2 hours...

`sed -i 's/\r$//' your.listname.txt`

**Comment by Helxinki** [comment]
> Hello,
> 
> I am experiencing issues when downloading from SRA several data using the following command, and I do not understand how to manage it.......
> 
> # in ids_mod1.txt file there are 3 SRR ids and I am using WSL ubuntu.
> $ cat ids_mod1.txt | parallel fastq-dump --split-files {}
> 
> 2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 ) Failed to call external services. 2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 ) Failed to call external services.
> 
> I find similar problems using GUI parallel with other commands so I though the issue was with parallel but if I use parallel with echo... parallel do its work.....
> 
> Could somebody give me a hand with this.... many thanks in advance

Hi Pablo

I had the sam problem exactly as yours. And it turns out to be the '\r' at the end of each lines of the accession number in the list when it is produces by Win instead of Linux. That's why fastq-dump can't get the correct accession name. Just delete using the command 'sed'. Hope this finds you well. Cause I have been stuch on this for 2 hours...

`sed -i 's/\r$//' your.listname.txt`

**Comment by abdealijivaji** [comment]
> > Hello,
> > I am experiencing issues when downloading from SRA several data using the following command, and I do not understand how to manage it.......
> > # in ids_mod1.txt file there are 3 SRR ids and I am using WSL ubuntu.
> > $ cat ids_mod1.txt | parallel fastq-dump --split-files {}
> > 2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 ) Failed to call external services. 2021-04-07T18:10:26 fastq-dump.2.10.9 err: error unexpected while resolving query within virtual file system module - No accession to process ( 500 ) Failed to call external services.
> > I find similar problems using GUI parallel with other commands so I though the issue was with parallel but if I use parallel with echo... parallel do its work.....
> > Could somebody give me a hand with this.... many thanks in advance
> 
> Hi Pablo
> 
> I had the sam problem exactly as yours. And it turns out to be the '\r' at the end of each lines of the accession number in the list when it is produces by Win instead of Linux. That's why fastq-dump can't get the correct accession name. Just delete using the command 'sed'. Hope this finds you well. Cause I have been stuck on this for 2 hours...
> 
> `sed -i 's/\r$//' your.listname.txt`

Hi Helxinki,

I was struggling for hours and it was literally that one liner that fixed it all. And I am using a mac with the same issues. This has been really frustrating. 
Thank you so much for that response. You will always be a hero for me now.

**Comment by mariana2323** [comment]
the solution for windows is adding double quotes before and after accession, like this: `fastq-dump --stdout -X 2 "SRR390728"`
