### ISSUE TITLE
prefetch.2.11.0 err (id exists while registering manager within virtual file system module)

### ISSUE THREAD

**Issue by opqwwq** [ncbi/sra-tools#488]
Hi, 
I'm using CentOS Linux 7. I tried to download a dataset from dbGap with the command: $/path-to-your-sratoolkit-installation-dir/bin/prefetch --ngc /path-to-ngc-file-dir/xxxxx.ngc /path-to-your-cart-file/xxxxx.krt. However, I got the following error message: prefetch.2.11.0 err: id exists while registering manager within virtual file system module - Invalid kart file: cannot read next row.

I tried to download another dataset with the above command and it worked.

Any idea how to fix this?
Thanks a lot!

**Comment by klymenko** [comment]
Please email to sra-tools@ncbi.nlm.nih.gov

**Comment by opqwwq** [comment]
> Please email to [sra-tools@ncbi.nlm.nih.gov](mailto:sra-tools@ncbi.nlm.nih.gov)

Thank you! I sent an email to them yesterday but have not received feedback yet.

**Comment by klymenko** [comment]
What is your case number?

**Comment by opqwwq** [comment]
> What is your case number?

Case#: CAS-706923-B4C2Y4

**Comment by klymenko** [comment]
Please execute the following command:
`mv ~/.ncbi/objid.mapping ~/.ncbi/objid.mapping.saved`

Then run your failed `prefetch` command again.

**Comment by opqwwq** [comment]
> Please execute the following command:
> `mv ~/.ncbi/objid.mapping ~/.ncbi/objid.mapping.saved`
> 
> Then run your failed `prefetch` command again.

Yes, it works! Thank you so much!

**Comment by davidenoma** [comment]
This works thank you so much!
