### ISSUE TITLE
fastq-dump version 2.11 does not download all data for ERR479582

### ISSUE THREAD

**Issue by brendanwee** [ncbi/sra-tools#491]
Perhaps this issue is bigger than the one SRR, but this is the one we observed the bug in.

In NCBI and with version 2.9 we are able to observe ~10M spots for ERR479582:
![image (1)](https://user-images.githubusercontent.com/22348941/115094914-2b33c300-9ed4-11eb-9595-09f38f26b5b3.png)

However, in 2.11, only 327892 spots are found:
![image (2)](https://user-images.githubusercontent.com/22348941/115094957-5dddbb80-9ed4-11eb-9693-1314570d2ff7.png)

For the time being we've switched back to 2.9

**Comment by klymenko** [comment]
What's the output of `srapath ERR479582`  for version 2.11?
Run it from the same directory where you ran `fastq-dump`.

**Comment by brendanwee** [comment]
https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR479582/ERR479582

**Comment by klymenko** [comment]
I reported this problem to our data delivery service.

**Comment by klymenko** [comment]
The issue with ERR479582 was fixed.
Version 2.11 should now give the same results as 2.9.

**Comment by brendanwee** [comment]
Great! Thank you for the quick resolution. Would it be possible to explain what was wrong? We want to be confident in switching to 2.11 for our future projects.

**Comment by klymenko** [comment]
SRA data [are being moved to AWS](https://github.com/ncbi/sra-tools).
Some runs were uploaded corrupted and it's being fixed.
It is the case of ERR479582.

Some runs are still available from NCBI, like ERR479582 and version 2.9 gets the good version of data from NCBI.
However, NCBI storage will be closed soon and the data will be available from AWS only.
Old versions of sra-tools will not be able to access data from AWS.

**Comment by brendanwee** [comment]
I see, thank you for the explanation!

As a user, it is hard to detect if the SRA data is corrupted. This particular case was only found because we double checked the result with the metadata on NCBI and the result when using an older version. 

Is there a way for the toolkit to detect if data is corrupt? Or will there be a QA period during the data transition to compare data in AWS with NCBI metadata?

**Comment by klymenko** [comment]
If you `prefetch` first - it does check data for corruption.
See https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump

**Comment by brendanwee** [comment]
Sounds good, we will start using prefetch and fasterq-dump. Thanks!
