### ISSUE TITLE
Prefetch issue with large files

### ISSUE THREAD

**Issue by Enrico-biol** [ncbi/sra-tools#492]
Hello,
i'm trying to dowload a large sra file (DNA-seq data 75 Gb), but the download failed with this error. 

```
2021-04-17T22:14:26 prefetch.2.10.8: 1) Downloading 'SRR10951907'...
2021-04-17T22:14:26 prefetch.2.10.8:  Downloading via HTTPS...
|-------------------------------------------------- 100%   
2021-04-18T06:19:14 prefetch.2.10.8:  HTTPS download succeed
2021-04-18T06:19:14 prefetch.2.10.8:   verifying 'SRR10951907'...
2021-04-18T06:32:05 prefetch.2.10.8 int: no error - failed to verify
2021-04-18T06:32:05 prefetch.2.10.8: 1) failed to download SRR10951907

```
I tried several times but it always fails with the same error.
Here my command 

`prefetch --max-size 300G -p SRR10951907`

I am doing it on an PC with 4 Gb of RAM, could be the RAM memory the problem ? If this is the case, i can try to run it on a cluster.
Would appreciate any advice.
Thanks in advance !

**Comment by klymenko** [comment]
What's the output of `ls SRR10951907`,
`ls -l SRR10951907/SRR10951907.sra `,
`md5sum -b SRR10951907/SRR10951907.sra`?

Expected results are:
`SRR10951907.sra`,
`81017260646 SRR10951907/SRR10951907.sra`,
`aebbde8ba8fd37ef2883d8d924293a72 *SRR10951907/SRR10951907.sra`.

**Comment by Enrico-biol** [comment]
Thank you for you response, 
the ouptut of `ls SRR10951907`  is `SRR10951907.sra SRR10951907.sra.prf`
the output of `ls -l SRR10951907/SRR10951907.sra`  is  `81017260646 SRR10951907/SRR10951907.sra`
the ouput of  `md5sum -b SRR10951907/SRR10951907.sra` is `f90d4cd9e1b7180fc78aaa052c0fb506 *SRR10951907/SRR10951907.sra`

**Comment by klymenko** [comment]
The file is corrupted.

Please remove directory `SRR10951907` and send me the output of `srapath SRR10951907`

**Comment by Enrico-biol** [comment]
Here the output `srapath SRR10951907`

[https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR10951907/SRR10951907](url)

**Comment by klymenko** [comment]
I cannot reproduce it.
Could you download the latest [toolkit-2.11.0](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software) and try it again?

**Comment by Enrico-biol** [comment]
Off course ! I’ll try again and i’ll let you know

**Comment by Enrico-biol** [comment]
Hello.
with the latest version of toolkit I succeed in downloading the SRA file.
the output of ```
ls SRR10951907,
ls -l SRR10951907/SRR10951907.sra ,
md5sum -b SRR10951907/SRR10951907.sra
```
Is the expected one 
Thank you for the support.
