### ISSUE TITLE
sra-tools docker image on AWS not configured

### ISSUE THREAD

**Issue by qscacheri** [ncbi/sra-tools#496]
Apologies if this isn't the correct place for this, but i am unable to use the ncbi/sra-tools docker image on AWS ECS. Every time I run the container, I get: 

"This sra toolkit installation has not been configured. Before continuing, please run: vdb-config --interactive."  

The image works fine locally, but I'm not sure how to debug why would not be working remotely. I'm not sure if it's an issue on my end or there's some issue with the image. 

Thanks!

**Comment by klymenko** [comment]
See https://github.com/ncbi/sra-tools/wiki/SRA-tools-docker

**Comment by qscacheri** [comment]
I've taken a look at that wiki, but I'm not sure which part helps with my issue. I see the bit about tls errors on AWS but I don't know if that's related to the issue I'm having.

**Comment by durbrow** [comment]
I am not able to replicate any problem with the docker image. I created a fresh instance (Amazon Linux 2 AMI) on ec2 and installed docker. It worked as expected.
```
[ec2-user@ip-... ~]$ docker run -t --rm ncbi/sra-tools fastq-dump --version
Unable to find image 'ncbi/sra-tools:latest' locally
latest: Pulling from ncbi/sra-tools
ba3557a56b15: Pull complete 
7ea714837713: Pull complete 
f85e47256864: Pull complete 
c7c23dea6a7f: Pull complete 
Digest: sha256:84b6b8faf767d7bd7ba14f00caf7775e1005194e01c97e835714066b160598b7
Status: Downloaded newer image for ncbi/sra-tools:latest

"fastq-dump" version 2.11.0

[ec2-user@ip-... ~]$ docker run -t --rm ncbi/sra-tools vdb-dump --info SRR000001
acc    : SRR000001
path   : https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR000001/SRR000001
size   : 312,527,083
type   : Table
platf  : SRA_PLATFORM_454
SEQ    : 470,985
SCHEMA : NCBI:SRA:_454_:tbl:v2#1.0.7
TIME   : 0x0000000055248a41 (04/08/2015 01:54)
FMT    : SFF
FMTVER : 2.4.5
LDR    : sff-load.2.4.5
LDRVER : 2.4.5
LDRDATE: Feb 25 2015 (2/25/2015 0:0)
[ec2-user@ip-... ~]$ 
```
What is the command you are trying?

**Comment by cnexcale** [comment]
I'm currently stuck with the same problem.
My best guess so far is that non-root containers cannot access the `user-settings.mkfg`.

I can replicate the problem with:
`docker run -it --user=1000:1000 ncbi/sra-tools fastq-dump`

Leaving out the `user` flag in docker run and thus running the container as root eliminates the problem.

Since I'm really new to the sra-toolkit I'm afraid I cannot suggest an appropriate solution.

**Comment by durbrow** [comment]
The image is built assuming there is only one user inside the container. Is there some reason this shouldn't work for you?

**Comment by cnexcale** [comment]
We intend to use the image in a workflow engine. I'm not sure yet if we have control over the user and if so are permitted to run containers as root. I'll have to look into that.

Maybe this finding might at least help _qscacheri_  to debug the issue

**Comment by durbrow** [comment]
FYI, the user inside the container has no relationship the user of the host system. The host system doesn't care what user you run as inside the container (and it has no way of knowing). That is part of the whole point of using containers. (See: https://www.redhat.com/en/blog/understanding-root-inside-and-outside-container)

**Comment by cnexcale** [comment]
Thank you for the link, though my phrasing was imprecise: I meant running as root _in_ the container. I found a way to do so, but the issue persisted.

But then I found, since the workflow runner changed the HOME environment variable, the sra-tools went looking for the settings in the `/newhome/.ncbi/` folder which did not exists.

Creating this folder and copying the`user-settings.mkfg` there in a startup script solved the issue

**Comment by qscacheri** [comment]
Is there a way to see where sra-tools are looking for the settings? I've checked the HOME environment variable and it isn't changing but the tools still aren't picking up the config.

**Comment by durbrow** [comment]
It looks in `${HOME}/.ncbi/user-settings.mkfg`
When the docker image is built, that ends up being `/root/.ncbi/user-settings.mkfg`.

**Comment by qscacheri** [comment]
That's what I thought and i have the config at that location but I'm still getting the error

**Comment by klymenko** [comment]
@qscacheri, could you try it with the latest toolkit version 3.0.1?
