### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by octonion** [ncbi/sra-tools#50]
I'm doing some testing on a large ARM box. Am I correct that SRA Toolkit doesn't currently support ARM? If so, how involved do you believe adding ARM support would be? We could possibly do it and issue a pull request if it doesn't appear to be too involved.

**Comment by kwrodarmer** [comment]
We don't currently support ARM, but would be interested in providing it. If you wanted to issue a pull request, it'll get our attention. The only areas of concern (and there aren't many) are some vestigial assembly language for atomic and what are by now intrinsic compiler functions. As long as you are running in little-endian mode there won't be any surprises there (even though we support big-endian, we just have no more Federally authorized big-endian hardware to test on). We can be built in 32-bit mode, although many of the algorithms for big data operations just demand 64-bit, so we haven't created the alternate engineering branch to make them run slower in lower memory.

That said, it seems reasonable to do.

**Comment by luizirber** [comment]
This is an old issue, but I think it is increasingly relevant now that AWS has `A1` and `m6g` instances and would be a good options for working with SRA in the cloud.

**Comment by klymenko** [comment]
We added ARM support in 2.11.0. Please try.
