### ISSUE TITLE
fasterq-dump quit with error code 3

### ISSUE THREAD

**Issue by davidcheishvili** [ncbi/sra-tools#502]
I am using SRA-toolkit latest version 2.10.7 and this the command i am using: 
docker run -t --rm -v $PWD:/output:rw -w /output ncbi/sra-tools fasterq-dump -e 2 -p SRR******

getting the following error:
fasterq-dump quit with error code 3

**Comment by durbrow** [comment]
Is there a particular reason you are on an older version? The latest docker image has version 2.11 of the tools. See https://github.com/ncbi/sra-tools/issues/496#issuecomment-831314861

Could you try it again after updating the image? Or run:
`docker run -t --rm -v $PWD:/output:rw -w /output ncbi/sra-tools:latest fasterq-dump -e 2 -p SRR...`

**Comment by davidcheishvili** [comment]
getting the same error after running: docker run -t --rm -v $PWD:/output:rw -w /output ncbi/sra-tools:latest fasterq-dump -e 2 -p SRR... 
fasterq-dump quit with error code 3

**Comment by durbrow** [comment]
Does it quit immediately?

If so, can you try this: `docker run -t --rm -v $PWD:/output:rw -w /output ncbi/sra-tools:latest fasterq-dump -e 2 -p SRR000001`? Does it also quit immediately?

**Comment by davidcheishvili** [comment]
> Does it quit immediately?
> 
> If so, can you try this: `docker run -t --rm -v $PWD:/output:rw -w /output ncbi/sra-tools:latest fasterq-dump -e 2 -p SRR000001`? Does it also quit immediately?

Thanks! now it works. Thank you for your help!
