### ISSUE TITLE
Using sra-tools in my own Docker image

### ISSUE THREAD

**Issue by mdanb** [ncbi/sra-tools#511]
I know there's a Docker image for the sra-tools, but it is based on Alpine Linux, and I need Ubuntu. Is there a way for me to install the tools in my image through a Dockerfile command i.e RUN?

**Comment by durbrow** [comment]
You could try https://github.com/ncbi/sra-tools/blob/master/build/docker/Dockerfile.build-ubuntu
I haven't tested it lately, but we do Ubuntu builds internally all the time. Let me know if you have a problem building or using it.
