### ISSUE TITLE
use local Refseq files

### ISSUE THREAD

**Issue by woodyNsinbad** [ncbi/sra-tools#513]
Hello, I'm trying to convert sra files into fastqs locally which means I can't connect NCBI web. And I know I need **refseq files** to accomplish that. (https://ncbi.github.io/sra-tools/fastq-dump.html)

But how I deal it with this refseq datas? Or Can anyone tell me how to set vdb-config that I can use Refseq I had download ?

**Comment by klymenko** [comment]
You can download refseq files from ftp.
Email to sra@ncbi.nlm.nih.gov about how to do it..

**Comment by klymenko** [comment]
You can download refseq files from https://ftp.ncbi.nlm.nih.gov/sra/refseq/
or ftp://ftp.ncbi.nlm.nih.gov/sra/refseq/
