### ISSUE TITLE
Installing old version of the toolkit

### ISSUE THREAD

**Issue by mdanb** [ncbi/sra-tools#517]
How can I install an older version of the toolkit?

**Comment by klymenko** [comment]
Why? We don't recommend it.

**Comment by mdanb** [comment]
I need it for reproducibility

**Comment by durbrow** [comment]
Can you be more specific? What data sets, what tools, what version, what command line options?

Reproducibility is a tough subject. Any number of things can through it off. 

Have you tried it without success?

**Comment by mdanb** [comment]
I guess it's a whole pipeline. Is there any reason why there isn't an "archive" or something for older versions? Like you said, there's a lot of things, so I'd rather not have to think about it and just use the older version I used

**Comment by klymenko** [comment]
They are [here](https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/).
Use them at your own risk.
