### ISSUE TITLE
Different fastq output from sam-dump and fastq-dump

### ISSUE THREAD

**Issue by buddej** [ncbi/sra-tools#52]
sam-dump and fastq-dump can both be used to output a FASTQ formatted file. In trying to figure out the best way to process .sra files, I have been using both tools. I noticed an inconsistency in the quality strings printed out by the 2 tools for the same .sra file.

Example .sra is publicly accessible run [SRR3332402](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR3332402)

The following 2 command should produce nearly identical output, except for the sequence identifier:
```
SRR=SRR3332402
sam-dump -p ${SRR} -u -g --fastq ${SRR} > ${SRR}.sam-dump.p.u.g.fastq.fq
fastq-dump --split-3 --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+' -Z ${SRR} > ${SRR}.fastq-dump.split.defline.z.fq
```

The corresponding .sam file was created as well
```
sam-dump -p ${SRR} -u -g ${SRR} > ${SRR}.sam-dump.p.u.g.sam
```

Both output .fq files are 7805680 lines in length, representing 1951420 reads. fastq-dump reports that 975710 spots were read/written (975710 * 2 = 1951420). The .sam file has 1951420 alignments. So good so far.

However, the quality strings for reverse reads in the `${SRR}.sam-dump.p.u.g.fastq.fq` file appear reversed when compared to the quality strings in the `${SRR}.fastq-dump.split.defline.z.fq` file. The base sequences are not reversed.

```
head -8 ${SRR}.sam-dump.p.u.g.fastq.fq ${SRR}.fastq-dump.split.defline.z.fq
@SRR3332402.1.134261/1 primary ref=1 pos=107512 mapq=0
AGGGAAATTTGGACATAGAGAGAGGCACACAGGGAGGATGCCATATGAGAATTGACACTGTGCTGTCACAAGCCAAGGAACTACTGGAAGGAGAGAAAGA
+
CCCFFFFFHHHHHJJJJIJICFHHIJJIJJIIJIIIJJIHIJJIIIIEI@GGHIGEIIIE=DHIEGFFCHEB=?##########################
@SRR3332402.1.134261/2 primary ref=1 pos=107567 mapq=0
AGCTGGCAGGGCTAGGCTGCCTGAAAAGGTGCTAAGGAAGGAACTGTTCCAGTCCTCTTTCTCTCCTTCCAGTAGTACCTTGGCTTGAGACAGCACAGTG
+
#######################################@;=@>@=>FABHGADCCHEDHFIGGGBJIIHGIIJJIIJGIHJJFJJJHGHHHFFFFD?:+

==> SRR3332402.fastq-dump.split.defline.z.fq <==
@SRR3332402.1.134261/1
AGGGAAATTTGGACATAGAGAGAGGCACACAGGGAGGATGCCATATGAGAATTGACACTGTGCTGTCACAAGCCAAGGAACTACTGGAAGGAGAGAAAGA
+
CCCFFFFFHHHHHJJJJIJICFHHIJJIJJIIJIIIJJIHIJJIIIIEI@GGHIGEIIIE=DHIEGFFCHEB=?##########################
@SRR3332402.1.134261/2
AGCTGGCAGGGCTAGGCTGCCTGAAAAGGTGCTAAGGAAGGAACTGTTCCAGTCCTCTTTCTCTCCTTCCAGTAGTACCTTGGCTTGAGACAGCACAGTG
+
+:?DFFFFHHHGHJJJFJJHIGJIIJJIIGHIIJBGGGIFHDEHCCDAGHBAF>=@>@=;@#######################################
```

The relevant lines are the last ones for each file -- the qualities for read `SRR3332402.1.134261/2`. All other lines are the same, except for the naming difference.

The output from fastq-dump is more believable -- the quality should fall off at the end of the read. Or these might be masked illumina adapter sequences, since the insert size for this read pair is small (155) relative to the read length (100).

Comparing this with the same read pair in the .sam file:
```
samtools view ${SRR}.sam-dump.p.u.g.sam | head -2 | cut -f10,11 | tr "\t" "\n"
AGGGAAATTTGGACATAGAGAGAGGCACACAGGGAGGATGCCATATGAGAATTGACACTGTGCTGTCACAAGCCAAGGAACTACTGGAAGGAGAGAAAGA
CCCFFFFFHHHHHJJJJIJICFHHIJJIJJIIJIIIJJIHIJJIIIIEI@GGHIGEIIIE=DHIEGFFCHEB=?##########################
CACTGTGCTGTCTCAAGCCAAGGTACTACTGGAAGGAGAGAAAGAGGACTGGAACAGTTCCTTCCTTAGCACCTTTTCAGGCAGCCTAGCCCTGCCAGCT
#######################################@;=@>@=>FABHGADCCHEDHFIGGGBJIIHGIIJJIIJGIHJJFJJJHGHHHFFFFD?:+
```

Here the sequence of the reverse read is reverse-complemented relative to the .fq files above, as it should be. The quality string is also reversed, so the base-call and quality paring stays intact.

It seems like the `--fastq` option in sam-dump reverses the base sequence of the reverse reads, but fails to also reverse the quality sequence, resulting in an incorrect output.

I don't know how many people use sam-dump to create .fq output, but this would be a serious bug for those that do. Am I missing something in how these commands should be run?

**Comment by buddej** [comment]
2 additional notes:

The above testing was done with [sratoolkit.2.8.1-centos_linux64](https://github.com/ncbi/sra-tools/wiki/Downloads) running on CentOS Linux release 7.3.1611 (Core).

You can actually see this effect in the SRA run browser, without downloading the sratoolkit
1. Go to https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR3332402 (it should be the Reads tab)
2. Turn on quality scores using the checkbox
This shows the read in question. All of the qual=2 reads are at the end, and the sequences are oriented as shown in the .fq files in my initial comment
3. Open the Alignment tab (in a new brower tab)
4. Change the range to 1-133750, and the format to FASTQ
5. Output to screen. (This prints part of the next read, but there seems to be a bug in the output to screen where the last line is omitted from the output -- probably needs a fflush() somewhere. If you output to file, you can just use 1-110000 for the range).

This web app must use sam-dump, since the sequence names have the alignment location. You can see the sequence line for `@SRR3332402.1.134261/2` is oriented the same was as it is in the Reads tab, but the quality line is reversed.

**Comment by buddej** [comment]
Also, if one read of the pair is unaligned, this problem may or may not be seen.

From the same example SRR3332402, spots 5, 2053, 2081, 2226 OR 32, 120, 121, 172-- any spot with SAM FLAG 101 or 165 (the key bit set is mate reversed strand), the unaligned read will be reverse complemented, so it is in the same orientation as the aligned read. This is okay, since the quality string is reversed as well. However, the quality string of the aligned read is also reversed, but the read itself is not, which creates the problem. Sidenote, unaligned reads with these SAM FLAGs will be reversed by sam-dump if the --reverse option is used.

But for spots 35, 129, 320, 961 OR 533, 582, 586, 771 -- any spot with SAM FLAG 69 or 133 (basically any unaligned read where the mate is aligned to the forward strand), the unaligned read and the aligned read are left in the original orientation, and the output of sam-dump --fastq matches the output of fastq-dump.

Based on how the unaligned reads that don't need to be reversed are unaffected, maybe the issue is with the code that reverses sequences marked as "read reversed strand"?

I did check, and read pairs with SAM FLAGs 83/163 and 99/147 (the two most common where both reads align), all have the issue with the quality string, where the read with 83 or 147 is affected.

Code for a quick check of any SPOT below, comparing fastq-dump with sam-dump --fastq
```
SRR=SRR3332402; SPOT=5;
fastq-dump --split-3 --defline-seq '@$ac.$si.$sg/$ri' --defline-qual '+' -Z ${SRR} \
  | grep -m2 -A3 "^@${SRR}\.${SPOT}\."; \
  echo; \
  sam-dump -p ${SRR} -u -g --fastq ${SRR} | grep -m2 -A3 "^@${SRR}\.${SPOT}\."
```

**Comment by durbrow** [comment]
This was fixed. I don't know exactly when, but it was likely some years ago.

**Comment by klymenko** [comment]
@buddej, do you still see this issue?
