### ISSUE TITLE
vdb-config -i throws error

### ISSUE THREAD

**Issue by Pinkers** [ncbi/sra-tools#520]
I have been trying to install the SRA toolkit according to the documentation. I was able to download it with curl, but I did not succeed in appending the path. That said, it shouldn't affect the configuration, correct? When configuring, 'vdb-config -i'
 throws a 'command not found' error. I have been following all of the documentation, can someone point me in the right direction? Thank you very much!!

**Comment by durbrow** [comment]
It sounds like your shell doesn't know how to locate `vdb-config`. You mentioned "I did not succeed in appending the path"; this is likely the problem. You need something like
`export PATH=${PATH}:<path-to-where-i-installed-the-toolkit>`
