### ISSUE TITLE
update conda package

### ISSUE THREAD

**Issue by Josuerinho** [ncbi/sra-tools#521]
Hi all!

When I try to update or install the conda package sra-tools to its latest version (2.11.0 based on https://anaconda.org/bioconda/sra-tools) with the next command:

_conda install -c bioconda sra-tools_

I get only this option:

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jcurto/anaconda3/envs/bif2021

  added / updated specs:
    - sra-tools

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sra-tools-2.8.0            |                0       115.3 MB  bioconda
    ------------------------------------------------------------
                                           Total:       115.3 MB

The following NEW packages will be INSTALLED:

  sra-tools          bioconda/osx-64::sra-tools-2.8.0-0

Proceed ([y]/n)? n

If I try to specify the label to "main" with the next command:

_conda install -c bioconda/label/main sra-tools_

I get:

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jcurto/anaconda3/envs/bif2021

  added / updated specs:
    - sra-tools

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hdf5-1.10.5                |nompi_h3e39495_1104         3.0 MB  conda-forge
    sra-tools-2.10.1           |  pl526h9f37e31_0        48.1 MB  bioconda/label/main
    ------------------------------------------------------------
                                           Total:        51.2 MB

The following NEW packages will be INSTALLED:

  hdf5               conda-forge/osx-64::hdf5-1.10.5-nompi_h3e39495_1104
  sra-tools          bioconda/label/main/osx-64::sra-tools-2.10.1-pl526h9f37e31_0

Proceed ([y]/n)? n

So as you can see I can't install the latest version of sra-tools from bioconda. Is there any option I can try? Is anyone else having the same problem?

Thnks a lot!

Josu

**Comment by klymenko** [comment]
We don't support conda
Use [our build](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).
