### ISSUE TITLE
prefetch not working?

### ISSUE THREAD

**Issue by jmwhitha** [ncbi/sra-tools#524]
Good afternoon,

My script is giving me an error when I try to transfer some data into my working directory. I think something is wrong with prefetch.

Thank you for your help in advance,

###########################SCRIPT###############################
#!/bin/tcsh
#BSUB -n 1
#BSUB -x
#BSUB -W 600
#BSUB -J mycode
#BSUB -o stdout.%J
#BSUB -e stderr.%J

conda activate /usr/local/usrapps/metagenomics/env_sra-tools
#vdb-config --restore-defaults

#open the SRR folder you want
#these numbers are associated with samples saved at NCBI
#SRR13355283 is for a Tibetan kefir grain metagenome
prefetch SRR13355283

#retrieve the fastq file and leave the rest
#I is for paired-end reads
fastq-dump-orig.2.11.0 -I SRR13355283

conda deactivate /usr/local/usrapps/metagenomics/env_sra-toolkit.csh

########################SCRIPT##############################

########################RESULT#############################

2021-07-14T17:22:34 fastq-dump-orig.2.11.0 err: item not found while constructing within virtual database module - the path 'SRR13355283' cannot be opened as database or table
deactivate does not accept arguments
remainder_args: ['/usr/local/usrapps/metagenomics/env_sra-toolkit.csh']

########################RESULT###################################

**Comment by klymenko** [comment]
We already had [similar issues](https://github.com/ncbi/sra-tools/issues/497) with conda.
We don't support it.
Use [our build](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software).

**Comment by jmwhitha** [comment]
Okay thank you :)

**Comment by jmwhitha** [comment]
No, all set. Thank you.
