### ISSUE TITLE
Download SOLiD sequencing files in GEO

### ISSUE THREAD

**Issue by dahun73** [ncbi/sra-tools#527]
Hello :)

I have a question about downloading SOLiD data.
Actually,  I want to download old data in GEO. As you know, in 2010, most of data are SOLiD sequencing.

When I used 'fastq-dump', however, there is no quality score files. After downloading data, I want to convert these data to standard illumina fastq format. Is there any suggestion to download both color space fastq and quality score files?

Thank you in advance

Dahun

**Comment by osris** [comment]
Please send us an example accession number and command  line example.

-Chris


From: "dahun73" ***@***.******@***.***>>
Date: Friday, July 23, 2021 at 2:14:31 AM
To: "ncbi/sra-tools" ***@***.******@***.***>>
Cc: "Subscribed" ***@***.******@***.***>>
Subject: [ncbi/sra-tools] Download SOLiD sequencing files in GEO (#527)


Hello :)

I have a question about downloading SOLiD data.
Actually, I want to download old data in GEO. As you know, in 2010, most of data are SOLiD sequencing.

When I used 'fastq-dump', however, there is no quality score files. After downloading data, I want to convert these data to standard illumina fastq format. Is there any suggestion to download both color space fastq and quality score files?

Thank you in advance

Dahun

**Comment by dahun73** [comment]
Hello Chris,

thank you for reply.
SRA Run Number is here:
SRR039843
SRR039844
SRR039845
SRR039846
SRR039847
SRR039848
These are in GSE21161

Dahun

**Comment by osris** [comment]
Use “-B” option to get basespace. Without the “-B” option, you will see colorspace output.  The quality scores are in the ouput, but set to constant value.

>  fastq-dump -Z -X 2 -B SRR039843
Read 2 spots for SRR039843
Written 2 spots for SRR039843
@SRR039843.1 VAB_ChIP_SRF_SC_un_b11_41_1196 length=35
TTCTGACTGTGCCCTTCACTTTGCTTCGCCGCACG
+SRR039843.1 VAB_ChIP_SRF_SC_un_b11_41_1196 length=35
"""""""""""""""""""""""""""""""""""
@SRR039843.2 VAB_ChIP_SRF_SC_un_b11_43_905 length=35
CAATCATGTTGATGAGACTGTATGTGTGTAGGTTC
+SRR039843.2 VAB_ChIP_SRF_SC_un_b11_43_905 length=35
"""""""""""""""""""""""""""""""""""

*********************************
Christopher O’Sullivan PhD
Sequence Read Archive
NCBI/NLM/NIH
*********************************

**Comment by klymenko** [comment]
@dahun73, do you need more help?

**Comment by dahun73** [comment]
@klymenko 

It works well. Thanks!
