### ISSUE TITLE
connection failed while opening file within cryptographic module

### ISSUE THREAD

**Issue by RazaRaza** [ncbi/sra-tools#529]
Hello, I have been trying to download SRA files but I am getting following error 
fasterq-dump ERS3905552
2021-08-02T04:41:22 fasterq-dump.2.10.3 err: connection failed while opening file within cryptographic module - error with https open 'https://sra-pub-run-odp.s3.amazonaws.com/sra/ERS3905552/ERS3905552'
2021-08-02T04:41:22 fasterq-dump.2.10.3 err: invalid accession 'ERS3905552'

I have been using fasterq-dump for a long time and it was working fine until last week. I have tried with several SRA ids but it is giving me same error.

**Comment by durbrow** [comment]
You can't use SRA Toolkit tools directly with SRS, ERS, or DRS type accessions. They are valid accessions but they are containers not runs. The tools currently only know how to work directly with SRR, ERR, and DRR type accessions. Did you perhaps mean [ERR3905552](https://www.ncbi.nlm.nih.gov/sra/?term=ERR3905552)? Here is [ERS3905552](https://www.ncbi.nlm.nih.gov/sra/?term=ERS3905552)

**Comment by RazaRaza** [comment]
I have downloaded this ERS3905552 and ERS3905551 last week. But now i cannot download either and several other files. Previously, I have downloaded all the SRA types including SRS, SRR and ERS. I am not sure what is the real issue here. I am getting same error with each type including ERR3905552.

**Comment by durbrow** [comment]
Please run this command and reply with the result:
```
curl --head https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR3905552/ERR3905552
```

**Comment by klymenko** [comment]
What is the output of the following?
`curl -v --head https://sra-pub-run-odp.s3.amazonaws.com/sra/ERR3905552/ERR3905552`

**Comment by RazaRaza** [comment]
Hi Andrew, I got following error after this command.

*   Trying 52.217.105.36:443...
* TCP_NODELAY set
* Connected to sra-pub-run-odp.s3.amazonaws.com (52.217.105.36) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /home/abl/hiseq/miniconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by RazaRaza** [comment]
Hi, Andrew. 
I am still having the same issue. I can use the curl with EBI server to download the data but not with the NCBI.

**Comment by klymenko** [comment]
Did you ask your Systems for help?

Could you try to run this command on another computer in a different network?

**Comment by klymenko** [comment]
@RazaRaza, did you have success?
