### ISSUE TITLE
i have some problems in using aspera to download sra

### ISSUE THREAD

**Issue by nickxzshi** [ncbi/sra-tools#53]
Hello,dear everyone. I want to download some RNA-seq raw data from NCBI by using Aspera. i used the command
```
~/.aspera/connect/bin/ascp -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 0 -T -l200m  anonftp@ftp-private.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/SRR/SRR285/SRR2854733/SRR2854733.sra .
and terminal told me that

ascp: Source file list not specified, exiting

```i check the file in ncbi,the SRR2854733.sra in there . meanwhile, i try the SRR645370.sra

```
```
~/.aspera/connect/bin/ascp -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh -k 1 -T -l200m anonftp@ftp-private.ncbi.nlm.nih.gov:/sra/sra-instant/reads/ByRun/sra/SRR/SRR645/SRR645370/SRR645370.sra .SRR645370.sra 
0% 6161KB 9.5Mb/s 3:13:
```

it is working. can everybody tell me the reason？do the aspera have limit on some sra? I'd appreciate any advice & suggestions.thank you very much.

**Comment by kwrodarmer** [comment]
Please download or build the **latest** SRA Toolkit and use prefetch to access the data, or let the tools access the data remotely on demand (depending upon how you are using the data). The hand-crafted URL you are using is deprecated, as is direct use of `ascp`.

We have a Wiki page on how to access data - https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data . Please see that page, and if you are still having difficulties, write back and we'll help diagnose the problem.

**Comment by nickxzshi** [comment]
Thank you for your explanation ,but i meet a problem when i use `vdb-config -i ` to chang the import  path.the terminal told me 
`pre.location is not empty ,flush it?`

can i chang the import path ? 

Best Regards 
nick

**Comment by nickxzshi** [comment]
thank you for your enxplanation 👍 

Best Regards 
nick
