### ISSUE TITLE
std::exception on all operations

### ISSUE THREAD

**Issue by flamholz** [ncbi/sra-tools#530]
Hi there -- I am trying to get started with the SRA toolkit. I installed it via conda on OS X 10.15.6, the installed version is 2.11.0 (see link below). I configured the toolkit and tried both "prefetch" and "fasterq-dump" of various SRA runs, but all put out the same error:

$ fasterq-dump --split-files ERR1877972
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/ 

I read the documentation and can't figure out what I've done wrong. 
Best,
Avi Flamholz

Conda package https://anaconda.org/bioconda/sra-tools

**Comment by klymenko** [comment]
Could you download SRA toolkit from https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software ?

We already had [a similar issue](https://github.com/ncbi/sra-tools/issues/497) with conda.
