### ISSUE TITLE
MD5 for SRA files

### ISSUE THREAD

**Issue by saketkc** [ncbi/sra-tools#531]
Hi SRA tools team, This is more of a question than an issue, but I wanted to know if it is possible to obtain MD5 of SRA files hosted on the cloud (before downloading it). I would like to add checksum supports for [pysradb](https://github.com/saketkc/pysradb) for downloading `.sra` files. I found an updated list of accessions [here](https://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/) (file: SRA_Accesions.tab)  which does have an md5 column, but it does not appear to be the md5 of either the .sra or the corresponding .fastq. So I have two questions:

- Is it possible to have md5 of  all .sra files that one can check against if not using prefetch to download?
-  What is the md5 column in [this file](https://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/SRA_Accessions.tab)

Thanks,
Saket

**Comment by klymenko** [comment]
Here are examples how to get information about runs for AWS and GCP:
```
curl 'https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?filetype=run&location-type=forced&location=s3.us-east-1&accept-charges=aws&acc=SRR9886303'
curl 'https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?filetype=run&location-type=forced&location=gs.us&accept-charges=gcp&acc=SRR9886303'
```
Email questions about https://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/ to sra-tools@ncbi.nlm.nih.gov

**Comment by saketkc** [comment]
Many thanks!
