### ISSUE TITLE
Issues downloading fastq data using the parallel prefetch function

### ISSUE THREAD

**Issue by Christina1993** [ncbi/sra-tools#538]
I am going to download the all SRA files of a SRA study using the following command:
`prefetch --option-file sra.ids`
sra.ids is a file with id. The command works well however the download speed is too slow. So I used the parallel function. Here is the code I used.
`cat sra1.ids | parallel -j 4 "prefetch {}"`
However, the code is reporting an error. Here is the error message.
`prefetch.2.10.9 err: error unexpected while resolving query within virtual file system module`
Could somebody give me a hand with this.... many thanks in advance.

**Comment by Christina1993** [comment]
> What are the command line arguments that are passed to prefetch?

The argument is the 'sra1.ids' file including all SRA number I am going to download.
![image](https://user-images.githubusercontent.com/38967248/131201632-e2bb6f17-d6c9-44bf-94c2-90d28e0eb8f6.png)

**Comment by klymenko** [comment]
prefetching `SRR14321948` or `SRR14321949` should not cause any problem.

Could you run `prefetch SRR14321948` or prefetch `SRR14321949` without `parallel`?
