### ISSUE TITLE
How can i download all sra at once using the command Prefetch

### ISSUE THREAD

**Issue by nickxzshi** [ncbi/sra-tools#54]
Hello everyone
i use the sratools command `prefetch`,but it downloaded one sra sample at once ,can i use the command to download  several sra samples at once？
for exanple,i want to the sra samples in a experiment .it's SRR3621711,SRR3621712,SRR3621713,SRR3621714. How can i download the sra samples meanwhile using the` prefetch`?
thank you very much
nick

**Comment by klymenko** [comment]
You can run the following:
prefetch SRR3621711 SRR3621712 SRR3621713 SRR3621714

**Comment by nickxzshi** [comment]
ok，thank you，i should try to put them together，why i did not do it？
