### ISSUE TITLE
using ParaFly with prefetch

### ISSUE THREAD

**Issue by Hongpu-Chen** [ncbi/sra-tools#540]
Hi, there. 
I am using the ParaFly and prefetch to download the SRA data, the command line, for example, is `prefetch SRR_Number -O ./` (it is a line of the `download.commondlines` which contains about 40 tasks)

and then using ParaFly, `ParaFly -c download.commondlines -CPU 8`.

But it kept reporting the error `2021-09-05T11:36:52 prefetch.2.9.3 int: transfer incomplete while reading file within network system module - Cannot KStreamRead: https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos3/sra-pub-run-19/SRA_Number/SRA_Number.1`

Would you please give me some advice? Thank you.

**Comment by klymenko** [comment]
Please update your toolkit: we now have release 2.11.1:
https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software

**Comment by Hongpu-Chen** [comment]
It seems like to be working, thank you very much!
