### ISSUE TITLE
Underscore in input name gives error

### ISSUE THREAD

**Issue by michael-ford** [ncbi/sra-tools#544]
Discovered that a custom filename for an SRA archive works, but if it has an underscore it gives the following error and hangs:

```
$ fasterq-dump HG00512_2 -e 12
2021-09-28T18:16:59 fasterq-dump.2.11.0 err: extract_acc2( 'HG00512_2' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect) 
```

**Comment by klymenko** [comment]
What is `HG00512_2`?

**Comment by durbrow** [comment]
If "HG00512_2" is the name of a file, try using "./HG00512_2".

**Comment by klymenko** [comment]
@michael-ford, do you need more help? Where did you get HG00512_2?

**Comment by Caesar-666** [comment]
hello,have you sloved this?
