### ISSUE TITLE
Fasterq-dump failing consistently

### ISSUE THREAD

**Issue by cademirch** [ncbi/sra-tools#545]
I am trying to use fasterq-dump (2.11) as a part of my pipeline. In the near past I have used it without problem. However, recently, it has been failing consistently across different SRRs with some of these errors:

```
2021-09-30T05:42:34 fasterq-dump.2.11.0 err: cmn_iter.c cmn_read_uint8_array( #32354307 ).VCursorCellDataDirect() -> RC(rcXF,rcFunction,rcExecuting,rcBuffer,rcInsufficient) 
2021-09-30T05:42:34 fasterq-dump.2.11.0 err: row #32354307 : READ.len(300) != QUALITY.len(0) (F) 
```
```
2021-09-30T07:10:10 fasterq-dump.2.11.0 err: cmn_iter.c cmn_read_String( #59963213 ).VCursorCellDataDirect() -> RC(rcVDB,rcBlob,rcReading,rcBlob,rcCorrupt) 
```

I would appreciate any insight on to what these errors actually mean and how I can avoid them.

**Comment by durbrow** [comment]
Have you tried it will the current version, 2.11.1?

**Comment by cademirch** [comment]
Did not see that there was a newer version. I will try that, thank you. 

Is there any plan to have this newer version on Conda?

**Comment by durbrow** [comment]
We didn't make the Conda version, and we don't maintain it. We hope that some of the changes we are making to our build system will make it easier for them to stay up to date with us, but we have no control over it.

**Comment by klymenko** [comment]
We already had [similar issues](https://github.com/ncbi/sra-tools/issues/497) with conda.

**Comment by cademirch** [comment]
Unfortunately getting the same errors with the latest version.
```
2021-09-30T20:44:49 fasterq-dump.2.11.1 err: cmn_iter.c cmn_read_uint8_array( #93905732 ).VCursorCellDataDirect() -> RC(rcXF,rcFunction,rcExecuting,rcBuffer,rcInsufficient) 
2021-09-30T20:44:49 fasterq-dump.2.11.1 err: row #93905732 : READ.len(300) != QUALITY.len(0) (F) 
fasterq-dump quit with error code 3
```
Any ideas?

**Comment by klymenko** [comment]
What is your full command line?

**Comment by cademirch** [comment]
`sratoolkit.2.11.1-ubuntu64/bin/fasterq-dump.2.11.1 SRR5507194 -O data/fastq/Bos_taurus/SAMN06699052/SRR5507194 -t .tmp/ -e 6 &> logs/Bos_taurus/fasterq_dump/SAMN06699052/SRR5507194.log`

**Comment by klymenko** [comment]
Run `prefetch SRR5507194` first.
Then run your `fasterq-dump` command.
Execute it from the same current directory.
Make sure you have enough free space there - `SRR5507194` requires 15G.

**Comment by cademirch** [comment]
I will try this - but why use prefetch? What is going on with fasterq-dump that it can't process this SRR?

**Comment by klymenko** [comment]
If you don't prefetch - fasterq-dump fetches SRR5507194 on the fly via HTTP and there could be fatal errors during the transfer.
prefetch eliminates transfer problems.

**Comment by klymenko** [comment]
Add `-p` to `prefetch` and `fasterq-dump` commands to see progress.

**Comment by cademirch** [comment]
How do I point fasterq-dump to the prefetched .sra file?

**Comment by klymenko** [comment]
Run `fasterq-dump SRR5507194` from the same directory.
Directory `SRR5507194` with `.sra` file is expected to be there.

**Comment by cademirch** [comment]
Is there no other option? I'm trying to implement this as part of a Snakemake workflow in which all commands are executed from a top level directory.

**Comment by klymenko** [comment]
Use any option you want.
Just use the same accession as in prefetch and execute them in the same directory.
Make sure it has enough free space to prefetch.
By default prefetch will create a directory named by accession in the current directory.
All SRA tools will find it if you execute them from the same directory and use the same accession as argument.

**Comment by cademirch** [comment]
I think I am misunderstanding. For example, I ran `prefetch -O data/fastq/ -p SRR5507209` resulting in this directory structure:
```
.
└── data
    └── fastq
        └── SRR5507209
            └── SRR5507209.sra
```
When I run fasterq-dump from the top level directory. I get the same original error, which means its probably trying to download the sra file because it cannot find it. I cannot change to the SRR directory because all of the execution is being handled by Snakemake.

**Comment by klymenko** [comment]
In this case run use `data/fastq/SRR053325` as `fasterq-dump`'s argument.

**Comment by cademirch** [comment]
@klymenko, thank you for the help!
