### ISSUE TITLE
SRA ToolKit Arm Support?

### ISSUE THREAD

**Issue by mrburke00** [ncbi/sra-tools#547]
Hi there

I saw an old post mentioning support for ARM has been added, but I still have issues setting up the toolkit on a ubuntu 64 OS.

$ vdb-config -i 
$ cannot execute binary file: Exec format error 

Delving deeper the binary is in fact an x84-64 format, is there something special I need to do for the arm format or is arm still not supported?

**Comment by DenizOlgun** [comment]
Similarly, I am having the same issue with setting up the toolkit on Debian OS (aarch64). I receive the "Exec format error" upon executing any command in the toolkit.
