### ISSUE TITLE
Problem with prefetch

### ISSUE THREAD

**Issue by Enrico-biol** [ncbi/sra-tools#549]
Hi, 
i have some problem with several files from  PRJNA650245
my command 

`prefetch -p -X 200G SRRXXXXXXX` 

and the output is 

`2021-10-19T12:13:32 prefetch.2.11.0: 1) Downloading 'SRR12379499'...
2021-10-19T12:13:32 prefetch.2.11.0:  Downloading via HTTPS...
2021-10-19T12:14:28 prefetch.2.11.0:  HTTPS download succeed
2021-10-19T12:14:28 prefetch.2.11.0 int: no error - failed to verify
2021-10-19T12:14:28 prefetch.2.11.0: 1) failed to download 'SRR12379499': RC(rcFS,rcFile,rcReading,rcFile,rcCorrupt)
`
Thanks in Advance

**Comment by klymenko** [comment]
What is the output of the following:
```
srapath SRR12379499
md5sum -b `srapath SRR12379499`
```

**Comment by johnsnowgo** [comment]
Hi,
i have also met the same problem like that.
When i use the command srapath SRR16620446, the output is an URL which you can download sra file from it.
When i use the command md5sum -b `srapath SRR16620446`, the output is an error like the following:
md5sum: 'http://sra-pub-run-odp.s3.amazonaws.com/sra/SRR16620446/SRR16620446': No such file of directory.
what should I do next?

**Comment by durbrow** [comment]
`md5sum` (and most other Unix command line utilities) are designed to work on local file system objects, not URLs. A URL is not a file or directory in the local file system. You have to download it first. Use `prefetch` to download from the URL, then run `md5sum`.

(And please don't add comments to closed issues.)

**Comment by klymenko** [comment]
@johnsnowgo, by default `prefetch SRR16620446` will download run files into directory named `SRR16620446` and validate them.
This directory will contain `SRR16620446.sra` and possibly other files.
`prefetch` validates downloaded files by checking their size and md5sum with expected.
If there is a mismatch - it will issue a message `failed to verify` and `rcFile,rcCorrupt`.
We need more information to investigate why validation fails.
