### ISSUE TITLE
Name space conflict with kget download manager

### ISSUE THREAD

**Issue by tillea** [ncbi/sra-tools#55]
Hi,
I received a [bug report in Debian](https://bugs.debian.org/851219) that the executable kget conflicts with kget download manager.  For the moment I'll solve this by  renaming it to sra-kget but I think you should officially use a better name than conflicting with some frequently used KDE tool.
Kind regards
        Andreas.

**Comment by klymenko** [comment]
It will be addressed in our next release.

**Comment by tillea** [comment]
On Wed, Apr 07, 2021 at 07:59:32AM -0700, Andrew Klymenko wrote:
> It will be addressed in our next release.

Thank you, Andreas.

**Comment by klymenko** [comment]
It was fixed in SRA Toolkit 2.11.1.
