### ISSUE TITLE
fasterq-dump unrecognized option: '--seq-defline'

### ISSUE THREAD

**Issue by alpapan** [ncbi/sra-tools#552]
What I expected:

The help file to be accurate:

fasterq-dump version 2.11.3 from https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software 
https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.11.3/sratoolkit.2.11.3-ubuntu64.tar.gz

```
fasterq-dump
  --seq-defline                    custom defline for sequence:  $ac=accession,
                                   $sn=spot-name,  $sg=spot-group, $si=spot-id,
                                   $ri=read-id, $rl=read-length
  --qual-defline                   custom defline for qualities:  same as
                                   seq-defline
```

What I get

```
fasterq-dump --seq-defline '@$sn[_$rn]/$ri'
unrecognized option: '--seq-defline'
fasterq-dump --seq-defline "test"
unrecognized option: '--seq-defline'
fasterq-dump --seq-defline
unrecognized option: '--seq-defline'
```

Also I note in the help the fastq-dump option of read name ($rn) is missing.

Further I note that the `fasterq-dump -h` gives a different help and list of parameters than simply `fasterq-dump`.

hope it's an easy fix :-)
best,
alexie

**Comment by alpapan** [comment]
Further the help is unclear on whether you can provide one or more accessions:

```
fasterq-dump
  accessions(s)                    list of accessions to process

```

but https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump states
```
fasterq-dump does not take multiple accessions, just one.
```

**Comment by alpapan** [comment]
Oh and `--print-read-nr` has no effect

Without --print-read-nr
```
 head -1  ../a/SRR00000*.fastq
==> ../a/SRR000001_1.fastq <==
@SRR000001.2 EM7LVYS02GCAPL length=115

==> ../a/SRR000001_2.fastq <==
@SRR000001.2 EM7LVYS02GCAPL length=99

==> ../a/SRR000001.fastq <==
@SRR000001.1 EM7LVYS02FOYNU length=280
```

With --print-read-nr
```
head -1  SRR00000*.fastq
==> SRR000001_1.fastq <==
@SRR000001.2 EM7LVYS02GCAPL length=115

==> SRR000001_2.fastq <==
@SRR000001.2 EM7LVYS02GCAPL length=99

==> SRR000001.fastq <==
@SRR000001.1 EM7LVYS02FOYNU length=280
```

in other words, no difference.

**Comment by wraetz** [comment]
please give me the complete commandline you issued. I will inverstigate the --print-read-nr option.

**Comment by wraetz** [comment]
If fasterq-dump is used through the so called driver-tool, it takes multiple accessions. In fact the driver tool handles multiple accessions and calls the actual tool multiple times - each invocation producing its own output-file. But you are right: I will correct the text of the github-wiki. The fact that the custom defline is not recognized: I will investigate that one too. The read-name is the spot-name, just use $sn for the name. Most accession have a read-name stored, but it is very likely not the read-name the submitter did submit. If an accession does not have a read-name-column ( that is true for a minority of the accessions), the tools will automatically substitute the row-number for it.

**Comment by ghuls** [comment]
@wraetz 
fasterq-dump does not take multiple accesion number atm. It even segfaults:

```
$ fasterq-dump SRR930776 SRR930777 SRR930778 SRR930779 SRR930780
2021-11-23T15:05:03 fasterq-dump.2.11.3 int: string unexpected while executing query within virtual file system module - multiple response SRR URLs for the same service 's3'
Segmentation fault
```

**Comment by klymenko** [comment]
@ghuls, [download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit.
