### ISSUE TITLE
Installation has not been configured error with singularity and docker image 

### ISSUE THREAD

**Issue by NishiPhalke** [ncbi/sra-tools#554]
I am trying to run ncbi/sra-tools docker image with singularity. I am getting below error.
![image](https://user-images.githubusercontent.com/30417924/139946845-482f5cce-16dd-4afb-b42c-8017d160c3b5.png)

I also tried using another docker image which is built from ncbi/sra-tools docker image and I am copying /root/.ncbi/user-settings.mkfg to ${HOME}/.ncbi/user-settings.mkfg as mentioned [here](https://github.com/ncbi/sra-tools/wiki/SRA-tools-docker)

Can you please help me with this ?
Also,
How can I run **interactive** vdb-config in docker image ?

**Comment by durbrow** [comment]
I don't know anything about `singularity` and I don't have access to it. So I would need you help to try to understand the problem.

Try this and paste the output into the response:
```
singularity exec --containall docker://ncbi/sra-tools sh -c 'echo ${HOME}'
singularity exec --containall docker://ncbi/sra-tools sh -c 'echo ${PWD}'
singularity exec --containall docker://ncbi/sra-tools touch hello
singularity exec --containall docker://ncbi/sra-tools ls -l hello
```

**Comment by NishiPhalke** [comment]
This is the output:

**Comment by NishiPhalke** [comment]
This is the output: ![image](https://user-images.githubusercontent.com/30417924/139952460-eab6e4fc-5ede-4346-b70f-844011654c7f.png)
I understand that in ncbi/sra-tools  docker image user-settings.mkfg is in root. so I used another docker image where I am copying it in ${HOME}. but still same error.

**Comment by durbrow** [comment]
`touch hello` should have made a file `/home/niship/hello`
It didn't.
It appears that `${HOME}` is not writable from inside the container.

**Comment by durbrow** [comment]
Think that is what `--containall` does. https://sylabs.io/guides/3.1/user-guide/bind_paths_and_mounts.html#containall

**Comment by NishiPhalke** [comment]
You are right. command without --containall also gives same error
singularity exec docker://ncbi/sra-tools fasterq-dump -h also gives same error.

**Comment by durbrow** [comment]
```
mkdir .ncbi
singularity exec docker://ncbi/sra-tools cp /root/.ncbi/user-settings.mkfg .ncbi
ls -l .ncbi
singularity exec docker://ncbi/sra-tools fasterq-dump -h
```
What do you get?

**Comment by NishiPhalke** [comment]
cant copy 
![image](https://user-images.githubusercontent.com/30417924/139954423-a4d0031b-4303-4ea3-aef0-ff690b0b7c84.png)

**Comment by NishiPhalke** [comment]
Hi @durbrow, 

I built another docker image using below docker file. I am copying user-settings.mkfg from /root to ${HOME}. I have also changed /root permissions. Hence no longer getting above permission denied error while copy user-settings file. 

FROM ubuntu:latest
RUN chmod -R 777 /root
RUN chmod -R 777 "${HOME}"
ARG VERSION=current
RUN apt-get update && apt-get --quiet install --yes curl uuid-runtime && apt-get clean
RUN curl https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/${VERSION}/sratoolkit.${VERSION}-centos_linux64-cloud.tar.gz | tar xz -C /
ENV PATH=/usr/local/ncbi/sra-tools/bin:${PATH}

ARG NCBI_CONF_DIR="${HOME}/.ncbi"
RUN mkdir -p "${NCBI_CONF_DIR}"

RUN mkdir -p /root/.ncbi && \
    printf '/LIBS/IMAGE_GUID = "%s"\n' `uuidgen` > /root/.ncbi/user-settings.mkfg && \
    printf '/libs/cloud/report_instance_identity = "true"\n' >> /root/.ncbi/user-settings.mkfg && \
    cp /root/.ncbi/user-settings.mkfg "${NCBI_CONF_DIR}/user-settings.mkfg"

I am still getting same error, using above dockerfile image (singularity exec docker://testsradockerimage fasterq-dump -h)

This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

**Comment by durbrow** [comment]
If you pull the latest (or if `singularity` does that automagically), this should now work for you.
```
mkdir .ncbi
singularity exec docker://ncbi/sra-tools cp /root/.ncbi/user-settings.mkfg .ncbi
ls -l .ncbi
singularity exec docker://ncbi/sra-tools fasterq-dump -h
```

**Comment by NishiPhalke** [comment]
Thanks for fixing permission issue. 
mkdir .ncbi
singularity exec docker://ncbi/sra-tools cp /root/.ncbi/user-settings.mkfg .ncbi
ls -l .ncbi
works now 
But, 
singularity exec docker://ncbi/sra-tools fasterq-dump -h gives same error. as singularity messing with env variable. 

I am not sure how that can be resolved

**Comment by durbrow** [comment]
What do you get from `singularity exec docker://ncbi/sra-tools ls -l .ncbi`

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140101320-7e9c2ae6-0c32-4707-a1d4-2f4b12aed232.png)

**Comment by durbrow** [comment]
And?
```
singularity exec docker://ncbi/sra-tools sh -c 'echo ${HOME}'
singularity exec docker://ncbi/sra-tools sh -c 'echo ${PWD}'
```

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140101952-e7e39dde-96a9-4ef8-9e48-ea48e26a67d6.png)

**Comment by durbrow** [comment]
The toolkit expects to find `.ncbi` in `/home/niship`, but it looks like it is in `/home/niship/sratoolkit`? If you move `.ncbi` to `/home/niship`, it should work.

**Comment by NishiPhalke** [comment]
doesn't work

![image](https://user-images.githubusercontent.com/30417924/140102890-e6909972-add3-4f28-ad9d-d35487870cf9.png)

**Comment by durbrow** [comment]
I'm confused. In your previous reply `singularity exec docker://ncbi/sra-tools sh -c 'echo ${PWD}'` gave `/home/niship/sratoolkit`. But now it is giving you `/home/niship`?

**Comment by NishiPhalke** [comment]
sorry about confusion, 

In prev reply I was working sratoolkit directory and in last reply I switched to /home/niship and created .ncbi there. 
prev 
![image](https://user-images.githubusercontent.com/30417924/140104569-7e67fcb1-24ca-4660-a0e4-4b2e39aae163.png)

last 
![image](https://user-images.githubusercontent.com/30417924/140104694-7b933d38-c9eb-47e8-901e-5d15dbb9550e.png)

**Comment by durbrow** [comment]
Try
```
singularity exec docker://ncbi/sra-tools sh -c 'ls -l ${HOME}'
```

**Comment by NishiPhalke** [comment]
It lists all the files which I have in /home/niship/. If you are looking for .ncbi
![image](https://user-images.githubusercontent.com/30417924/140166413-4ed0b37b-9375-4b66-8ee1-e15823e8fd1a.png)

**Comment by durbrow** [comment]
Try
```
singularity exec docker://ncbi/sra-tools vdb-config -o n NCBI_SETTINGS
```

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140166854-33a7147b-751c-40a2-b2f1-351b2502c7c1.png)

**Comment by durbrow** [comment]
Good. Try
```
singularity exec docker://ncbi/sra-tools vdb-config -o n HOME LIBS/GUID
```

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140168194-7a8ea4de-3795-4302-818d-e62d103a15f5.png)

**Comment by durbrow** [comment]
Okay. Try
```
singularity exec docker://ncbi/sra-tools sh -c 'cat ${HOME}/.ncbi/user-settings.mkfg'
```

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140168515-365f4cb6-d444-4290-8d07-f8f1c6e98d08.png)

**Comment by durbrow** [comment]
Last thing for now. Try
```
singularity exec docker://ncbi/sra-tools vdb-config -o n HOME LIBS/IMAGE_GUID
```

**Comment by NishiPhalke** [comment]
![image](https://user-images.githubusercontent.com/30417924/140168822-f1aef161-ca22-41fc-9795-78be94290e1c.png)

**Comment by durbrow** [comment]
I don't know why it isn't working. I have my suspicions, but I will have to try some things on my end first.

As a workaround, open `~/.ncbi/user-settings.mkfg` in an editor and change `LIBS/IMAGE_GUID` to `LIBS/GUID`, save it, and try `fasterq-dump -h` again from inside the docker.

**Comment by NishiPhalke** [comment]
by changing LIBS/IMAGE_GUID to LIBS/GUID in ~/.ncbi/user-settings.mkfg 

singularity exec docker://ncbi/sra-tools fasterq-dump -h
works 

What's the issue exactly ?

**Comment by durbrow** [comment]
I suspect the toolkit can't update the configuration file. Normally, inside a docker image, it can update it.

**Comment by NishiPhalke** [comment]
ok. Thank you so much for the your help on this

**Comment by Lcornet** [comment]
Any update on this.
I have the same error using the Docker container from docker://ncbi/sra-tools

sudo singularity build SRA.sif docker://ncbi/sra-tools

singularity exec --bind /scratch/ulg/bioec/lcornet/GLOEO/Assembly:/mnt /scratch/ulg/GENERA/SRA.sif fastq-dump SRR7539891 --split-files /mnt/ --outdir /mnt/
Rejected 938 READS because READLEN < 1
Read 86204 spots for SRR7539891
Written 86204 spots for SRR7539891
2022-06-23T13:13:47 fastq-dump.3.0.0 err: item not found while constructing within virtual database module - the path '/mnt/' cannot be opened as database or table
fastq-dump quit with error code 3

**Comment by durbrow** [comment]
Remove `/mnt/` after `--split-files`

Also, fastq WAS successfully extracted from SRR7539891, so you shouldn't need to rerun the command after you fix it.
