### ISSUE TITLE
fastq-dump: an error occured: std::exception

### ISSUE THREAD

**Issue by ialbert** [ncbi/sra-tools#555]
After a bioconda installation of `sra-tools` the following error occurs when running `fastq-dump`:

```
$ fastq-dump
An error occured: std::exception
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
```

we've noticed that within the same installation the following tool works as expected:

```
$ fastq-dump-orig

Usage:
  fastq-dump-orig [options] <path> [<path>...]
  fastq-dump-orig [options] <accession>

Use option --help for more information

fastq-dump-orig : 2.11.0
```

This is when running on a Mac:

```
uname -a
Darwin foo.science.psu.edu 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

I run a class, many students have been reporting the same problem, not all were using Mac.

**Comment by klymenko** [comment]
Could you download SRA toolkit from https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software ?

We already had [a similar issue](https://github.com/ncbi/sra-tools/issues/497) with conda.

**Comment by ialbert** [comment]
The downloadable package does indeed work, but so does `fastq-dump-orig` that you have there. This new version of fastq-dump appears to be a symbolic link to `sratools.2.11.0`

But if I try to run `sratools.2.11.0` I get
```

$ sratools.2.11.0 
An error occured: unrecognized tool sratools
If this continues to happen, please contact the SRA Toolkit at https://trace.ncbi.nlm.nih.gov/Traces/sra/
```

At the same time I wonder, if you have a working binary for Mac why not distribute that as a binary with conda?

**Comment by ialbert** [comment]
The issue is not as much that I wouldn't be able to install it, I know of several workarounds to get FASTQ files, I know how to find fetch the files directly etc. 

This is about giving people with less command-line experience a way to install and run sratools. 

It is a lot simpler to instruct someone to type: `conda install sra-tools` than to describe how to install a downloadable command line tool package.

**Comment by durbrow** [comment]
We don't support conda. We are part of a large government institution, and have little say in the matter.

**Comment by durbrow** [comment]
You should continue to ask. You can also ask via email to sra@ncbi.nlm.nih.gov.

**Comment by ialbert** [comment]
Ok, I understand.  Thank you for the prompt replies.

I will restate the solution below to help people find it if they get here via a Google search. 

Install and use the binary packages from 

https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software
