### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by JieWu2012** [ncbi/sra-tools#558]
when I install sratoolkit, I use "vdb-config --interactive" and the configuration interface come out like this
![Screenshot16 40 17](https://user-images.githubusercontent.com/4727669/142448255-3387374b-2313-4f34-b0ec-7a4b12388b57.png)
What should I do to configure? There is no "Cache" tab as what is said in the tutorial "Quick Toolkit Configuration". It seems it is a completely different configuration interface. 
Besides, can I ask what is the advantage of having such configuration interface comparing to old version which ? It feels like windows dos. When I try to change the path, I can not even find a key to press "OK".

**Comment by durbrow** [comment]
You are using an old version of the toolkit. See [README](https://github.com/ncbi/sra-tools/blob/master/README.md) and follow the link to download the latest version.

**Comment by JieWu2012** [comment]
True. Thank you. The one I am installing is the new version. But I had old version installed before. And I forgot it also has "vdb-config" in the path.
