### ISSUE TITLE
Total files and file size in run selector

### ISSUE THREAD

**Issue by guodudou** [ncbi/sra-tools#562]
Hello,

I plan to download all runs from a project using sra-toolkit, but need to determine the required storage first.  Using RunSelector,  it displays "BAM,SRA" in "DATASTORE filetype", also total Bytes of all data. However, I am wondering:
1. Are the total Bytes the size of SRA files or BAM + SRA?
2. I understand NCBI hosts SRA files only, but AWS & GCP contain both SRA and original data files submitted such as bam or maf, then does the table returned by RunSelector contain duplicated entries for each run? For example, one for SRA, one for bam.

Thank you very much,
Wendy

**Comment by durbrow** [comment]
Please direct your question to sra@ncbi.nlm.nih.gov. We are the toolkit developers, the Run Selector is not something we know much about.

**Comment by guodudou** [comment]
Thank you very much!
