### ISSUE TITLE
Unable to decrypt data taken from cloud server

### ISSUE THREAD

**Issue by s-andrews** [ncbi/sra-tools#570]
I've been trying to retrieve data from dbGAP after going through the process of getting access to restricted data.

I was able to follow the instructions at https://www.ncbi.nlm.nih.gov/sra/docs/dbgap-cloud-access/#launch-cloud-compute-instance to set up an EC2 server to access the data using fusera.  From there I could see both SRR files and also encrypted tar.gz files which contain most of the data I need.

The problem is that I'm not able to decrypt the data using vdb-decrypt.

I picked one example file to test:

```
-r--r--r-- 1 ec2-user ec2-user 21G Jan 4 15:20 ./sra/SRR11142441/cll_wt_2.tar.gz
```

This appears to be an encrypted file:

```
file ./sra/SRR11142441/cll_wt_2.tar.gz
./sra/SRR11142441/cll_wt_2.tar.gz: data

$ strings ./sra/SRR11142441/cll_wt_2.tar.gz | head -1
NCBInenc 
```

The command I used to create the mount was:

```
$ fusera mount -t prj_30570.ngc -a SRR_Acc_List.txt /home/ec2-user/sra/ > output.log 2>&1 
```

I copied the test file to our local cluster, since the cloud image was running an older version of the toolkit, and we had the latest version.  I verified the data was identical on both ends.

```
[ec2-user@ip-172-31-91-34 ~]$ md5sum sra/*/cll_wt_2.tar.gz
12d9beae82c0947de6c0989d6031cd82 sra/SRR11142441/cll_wt_2.tar.gz 

[andrewss@headstone dbGAP]$ md5sum cll_wt_2.tar.gz
12d9beae82c0947de6c0989d6031cd82 cll_wt_2.tar.gz
```

I also verified that the ngc key file was identical:

```
[ec2-user@ip-172-31-91-34 ~]$ md5sum prj_30570.ngc
101310678b3c1dd74a2b9b9449c9443a prj_30570.ngc

[andrewss@headstone dbGAP]$ md5sum prj_30570.ngc
101310678b3c1dd74a2b9b9449c9443a prj_30570.ngc
```

However I wasn't able to decrypt the file:

```
$ vdb-decrypt --ngc prj_30570.ngc cll_wt_2.tar.gz decryted.tar.gz
2022-01-04T16:54:11 vdb-decrypt.2.11.2: Decrypting file cll_wt_2.tar.gz to decryted.tar.gz
2022-01-04T16:54:11 vdb-decrypt.2.11.2 err: size incorrect while constructing file within cryptographic module - error constructing decryptor
2022-01-04T16:54:11 vdb-decrypt.2.11.2: exiting: RC(rcKrypto,rcFile,rcConstructing,rcSize,rcIncorrect) (2183173836) 
```

This is using:

```
$ module list sratoolkit
  1) sratoolkit/2.11.3

[andrewss@headstone dbGAP]$ vdb-decrypt --version
vdb-decrypt : 2.11.2
```

So weirdly it reports as v2.11.2 even though it shipped in the 2.11.3 bundle.

The fusera version was the one which came with the AMI (ami-0d57e13fe62227b2e) you provide.

Any suggestions for how to get this working would be appreciated.

**Comment by durbrow** [comment]
The `fusera` tool is not part of the SRA toolkit. Please send your question to sra@ncbi.nlm.nih.gov.

**Comment by s-andrews** [comment]
The error I'm getting in the end comes from ```vdb-decrypt``` which is part of the toolkit.  As far as I can see the fuse mount is giving me data which has a suitable encryption header on the top of it, but I can't decrypt it afterwards.

Sure, the problem could come from ```fusera```  but given that in #565 this same data was failed to be retrieved by both ```prefetch``` and ```fastq-dump``` and this is the third route I've gone through to try to access it this I'm running out of options.

I appreciate that this type of data access involves multiple pieces of infrastructure, and that they have to play nicely to make things work, but having spent a long time going through lots of (often contradictory) documentation, dealing with different versions and options changes, and trying to construct informative and useful bug reports then getting short dismissive responses and closure of the report is a very frustrating experience.

**Comment by durbrow** [comment]
Please send your issue to sra@ncbi.nlm.nih.gov. Yes, we wrote `vdb-decrypt`, but we don't control the data, especially the protected human data, and your problem is with protected human data. We also don't control most of the documentation. The BEST way to get your problem fixed is to contact the SRA curators, not the devs.

I'm not being dismissive, I'm trying to direct you to the people who can fix your issue. We can't. We can't even see the data you are working with. It's not public data.
