### ISSUE TITLE
vdb-config failed

### ISSUE THREAD

**Issue by mlathara** [ncbi/sra-tools#579]
I'm trying to follow the basic guide [here](https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit) to install the SRA toolkit. I'm trying to install on a headless Centos 7 server (maybe that's the problem...? Though I've tried to x2go as well without success)

I tried both the yum install route and the tarball and with both options, I get hung up when trying to run `vdb-config`

```
$ vdb-config -i -vvvvvv
failed
```

Any pointers? A quick perusal of the issues/wiki seems to suggest that there is no way to non-interactively configure. I should also mention that running `vdb-config` with no options does spit out some sort of xml config.

**Comment by mlathara** [comment]
I had an older version of the toolkit installed on a different Centos server in my cluster (sratoolkit.2.9.6-1), and that seemed to still work. 

I went back to that, not really sure why more recent version isn't working 🤷 I'll leave it to the repository maintainers if they want to close the issue or not.

**Comment by durbrow** [comment]
One way to handle headless is to run `vdb-config -i` on a system that isn't headless and then copy `~/.ncbi/user-settings.mkfg` to the equivalent location (i.e. to `.ncbi/` in the home directory) on the headless system.

Long answer:

`vdb-config -i` needs a tty that supports a multiline display and ANSI formatting code. Your headless system probably does not.

One way to get around this is, you run `vdb-config` somewhere else and copy the file it creates. This file is `${HOME}/.ncbi/user-settings.mkfg`, and the SRA toolkit expects to find this file by that name/path on whatever system it is currently running on.
