### ISSUE TITLE
blastn_vdb:  "- Error opening the following db(s):"

### ISSUE THREAD

**Issue by musta1234** [ncbi/sra-tools#58]
Hello,
My blastn_vdb run exited with the error message pasted below and I am providing a description of my analysis if I can get any pointers as to what went wrong. Thanks in advance!
I attempted running blastn_vdb using a nucleotide fasta query (4 sequences, ~1kb each) on all gammaproteobacteria WGS sequences (24,507 wgs genomes). blastn_vdb downloaded 24040 genomes (XXX00N.cache) and 439 other XXX00N files without .cache extension before exiting with the following error messages. I have more than enough available disk space for wgs and blast output folders. 

Commands:
taxid2wgs.pl -title "Gammaprot" -alias_file Gammaprot 1236
blastn_vdb -query ../queries/queries.fna -db Gammaprot -outfmt '6 std qlen slen' -out Gammaprot_v_queries.txt

Error message:
NCBI C++ Exception:
    T0 "/export/home/tomcat/TeamCity/Agent3/work/9b0ff710cbae2b8c/blastn/c++/src/internal/blast/vdb/vdb2blast_util.cpp", line 266: Error: ncbi::CVDBBlastUtil::x_MakeSRASeqSrc() - Error opening the following db(s): MPCP01

**Comment by fbjornlund** [comment]
I had the same problem with downloaded E.coli sequences. The problem assembly was JMUY01, when I removed that one it worked.

**Comment by klymenko** [comment]
@musta1234, @fbjornlund, do you still need help?

**Comment by molbio7** [comment]
Hi, I'm having similar issue - have create a taxid list of oomycetes and when I run blastn_vdb I get the following error:

Error: (2108.2) VDB 2.11.2: 2022-04-21T03:09:11 . int: timeout exhausted while creating file within network system module - Error in VDBManagerOpenDBRead(QLOC01)
Error: NCBI C++ Exception:
    T1 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_660219_130.14.18.128_9008__PrepareRelease_Linux64-Centos_1643834072/c++/compilers/unix/../../src/algo/blast/vdb/vdb2blast_util.cpp", line 257: Error: (CException::eUnknown) ncbi::CVDBBlastUtil::x_MakeVDBSeqSrc() - Error opening the following db(s): SMMQ01 
NCBI C++ Exception:
    T4 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_660219_130.14.18.128_9008__PrepareRelease_Linux64-Centos_1643834072/c++/compilers/unix/../../src/algo/blast/vdb/vdb2blast_util.cpp", line 257: Error: (CException::eUnknown) ncbi::CVDBBlastUtil::x_MakeVDBSeqSrc() - Error opening the following db(s): NPIU01 
NCBI C++ Exception:
    T3 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_660219_130.14.18.128_9008__PrepareRelease_Linux64-Centos_1643834072/c++/compilers/unix/../../src/algo/blast/vdb/vdb2blast_util.cpp", line 257: Error: (CException::eUnknown) ncbi::CVDBBlastUtil::x_MakeVDBSeqSrc() - Error opening the following db(s): MBAC02 
NCBI C++ Exception:

There are many more lines, for all taxids.

Any help or advice please?

**Comment by klymenko** [comment]
blastn_vdb and tblastn_vdb binaries are now distributed and supported
by Blast team.
A new release is being prepared.

See https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
E-mail blast-help@ncbi.nlm.nih.gov with questions or comments.

**Comment by cduvallet** [comment]
Just [linking the same issue reported at Biostars](https://www.biostars.org/p/233182/) which I also ran into (while using the NCBI BLAST docker container, so it wasn't an issue of needing to update my binaries), and sharing NCBI's response when I emailed them about it:

> WGS datasets are numerous, they are stored within the same system as the SRA datasets with even larger number of volumes. Some lookup and retrieval for blast need will fail, which often is a reflection of the server status for that SRA retrieval system, there is nothing wrong with the db volume reported back. It is unfortunate that this will break the blast search. You may want to consider break up the alias into smaller subsets manually and search each separately.
