### ISSUE TITLE
TRIM OR UNTRIMMED READS

### ISSUE THREAD

**Issue by vappiah** [ncbi/sra-tools#582]
Hi All,

Are the reads downloaded using fasterq-dump already trimmed? Or trimming has to be done manually

**Comment by durbrow** [comment]
`fasterq-dump` does not trim bases from reads; it can only filter reads by read type. So, if your concern is about are things like primers, linkers, barcodes, or other non-biological reads, they are excluded by default from the output, but can be included. If you want biological bases trimmed, it would need to done after `fasterq-dump`. If you have questions concerning some particular dataset(s), you should ask the SRA curators at sra@ncbi.nlm.nih.gov.

**Comment by wraetz** [comment]
fasterq-dump/fastq-dump does not trim bases from reads; it does have options for filtering reads by read type. So, if your concern is about are things like primers, linkers, barcodes, or other non-biological reads, they are excluded by default from the output, but can be included. If you want biological bases trimmed, it would need to done after fasterq-dump. If you have questions concerning some particular dataset(s), you should ask the SRA curators at sra@ncbi.nlm.nih.gov
