### ISSUE TITLE
Running tar command to extract contents of the sratoolkit.tar.gz file produces error (Mac) 

### ISSUE THREAD

**Issue by Transmystical** [ncbi/sra-tools#583]
I am trying to install the SRA Took Kit using the instructions given for a Mac OS X, as is given here: [02. Installing SRA Toolkit](https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit). 

Here are the details of both computers I tried to do this on (I switched computers when it did not work on one). 
MacOS Monterey Version 12.0.1 & MacOS Big Sur Version 11.6. 

I have included a screenshot of one of these computers to note exactly what I am running on terminal. 
<img width="864" alt="SRAToolKit_TarError" src="https://user-images.githubusercontent.com/11700614/151881643-7b26b4e4-53ec-410e-9485-26ea6da88f58.png">

On both Mac OS's: 
I am able to fetch the tar file using the following command:
`curl --output sratoolkit.tar.gz http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-mac64.tar.gz`. 

This places the sratoolkit.tar.gz in my working directory, which in this case happens to be my desktop. 

Next, I try to run the `tar` command: `tar -vxzf sratoolkit.tar.gz` and it populates this error: 

> tar: Error opening archive: Unrecognized archive format

I have tried to use the following commands: `gunzip sratoolkit.tar.gz` and `unzip sratoolkit.tar.gz`, to no avail. They all say the same thing. I have tried double clicking the icon to have it expand and I get a pop up window from archive utility with the following error: 

> Unable to expand "sratoolkit.tar.gz". It is in an unsupported format. 

Am I missing something here? Why am I not able to open the sratoolkit.tar.gz file? Is there a work-around to this? 

Thank-you!

**Comment by durbrow** [comment]
Most likely your download command is getting an error. Try downloading it with a browser.
