### ISSUE TITLE
Getting Segmentation Fault when running fastq-dump

### ISSUE THREAD

**Issue by BFortunato1** [ncbi/sra-tools#584]
Trying to run a script to download a bunch of SRAs, below is said script

```
#!/bin/bash

accessions=(SRR9029178,SRR9029179,SRR9029180,SRR9029181,SRR11511042,SRR2035171,SRR3997230,SRR3997266,
SRR14459534,SRR14459535,SRR13825919,SRR13825917,SRR7505599,
SRR8404462,SRR5664468,SRR12576439,SRR12576438,SRR3997302,
SRR3997320,SRR3997284)

for i in ${accessions[@]}; do
	/mnt/cfce-stor1/home/bjf35/sratoolkit/bin/prefetch $i --force all
 	/mnt/cfce-stor1/home/bjf35/sratoolkit/bin/fastq-dump --gzip --skip-technical --readids --read-filter pass --dumpbase --split-3 --clip $i 
done
echo "Fastq-dump Complete"
```

But when run, prefetch works fine but fastq-dump outputs this error:

`/mnt/cfce-stor1/home/bjf35/sratoolkit/accession_dump.bash: line 6: 63919 Segmentation fault      "/mnt/cfce-stor1/home/bjf35/sratoolkit/bin/fastq-dump" --gzip --skip-technical --readids --read-filter pass --dumpbase --split-3 --clip $i
`

Any ideas?

**Comment by wraetz** [comment]
What version of fastq-dump are you using? ( call fastq-dump --version ).
Did the prefetch-step before fastq-dump return with an error-code 0? ( you are not testing this in your script )
What is your current directory when running this script? Do you have enough space there?
Did the error occur with the first accession in your set?

**Comment by BFortunato1** [comment]
- Version 2.11.2
- No it did not return with an error code. In other versions of the script that separated prefetch and fastq-dump into 2 for loops, prefetch went without a hitch. (Just to note, this other version of the script with separate for loops threw the same error).
- I'm running it in folder than contains the SRA files; /mnt/cfce-stor1/home/bjf35/tmp/SRA_deposit/sra/
- Yes the error occurs immediately during the first attempt of fastq-dump.

**Comment by wraetz** [comment]
That means in your folder '/mnt/cfce-stor1/home/bjf35/tmp/SRA/deposit/sra' is a subfolder named SRR9029178. In it is a file called SRR9029178.sra. How big is this file?

**Comment by BFortunato1** [comment]
The file is ~640,000 KB

**Comment by wraetz** [comment]
Please give me the exact byte-count.

**Comment by wraetz** [comment]
it should be 651,209,606 bytes.

**Comment by BFortunato1** [comment]
Yes 651,209,606 bytes

(Just a clarifying note; if I do each of the prefetch and fastq-dump steps manually, no error is thrown. It's purely when I try to run it in the aforementioned script. )

**Comment by wraetz** [comment]
the md5sum of it should be ae6521a8464148e6f8fb55a7cf33d746

**Comment by wraetz** [comment]
I also was able to run your command manually with success.

**Comment by BFortunato1** [comment]
Yes ae6521a8464148e6f8fb55a7cf33d746 is correct

**Comment by wraetz** [comment]
your script is not correct, it should be
accessions="SRR123456 SRR123457 SRR1234568"
for i in ${accessions}; do

The accessions have to be on one line, enclosed in quotation marks and separated by space.
The for loop needs just ${accessions} not ${accessions[@]}

Your version works for prefetch, because prefetch takes multiple accessions, but fastq-dump does not.

**Comment by BFortunato1** [comment]
This seems to have worked, thanks so much
