### ISSUE TITLE
Unable to separate files

### ISSUE THREAD

**Issue by ATVincent** [ncbi/sra-tools#585]
Hello,

I am trying to download from SRA the dataset ERR5083804 with fasterq-dump version 2.11.2. As usual, I do the simple command:
fasterq-dump ERR5083804

However, I get a single file fastq instead of two. I tried with the -S option, but I still get only one file.

Do you have an idea of the problem ?

Thank you,

Antony

**Comment by durbrow** [comment]
This run appears to only have one read per spot. https://www.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=run_browser&run=ERR5083804
If you know this is incorrect, would you email sra@ncbi.nlm.nih.gov and let the curators know. They should be able to get the run fixed.

**Comment by durbrow** [comment]
Given how the data was packaged in four separate files, it seems likely that the data was loaded incorrectly.

**Comment by ATVincent** [comment]
Thank you ! I will email SRA.
