### ISSUE TITLE
fastq-dump command?

### ISSUE THREAD

**Issue by anhmoss** [ncbi/sra-tools#59]
I have downloaded the latest version of SRA toolkit, 2.8.1 for the Ubuntu/Linux system. When I tried the fastq-dump command, I received the following error message: 

anh@anh-VirtualBox:~$ fastq-dump -X 5 -Z SRR1763777
2017-01-26T23:17:30 fastq-dump.2.3.5 err: error unexpected while resolving tree within virtual file system module - failed to resolve accession 'SRR1763777' - Obsolete software. See https://github.com/ncbi/sra-tools/wiki ( 406 )

Redirected!!!

2017-01-26T23:17:30 fastq-dump.2.3.5 err: name incorrect while evaluating path within network system module - Scheme is 'https'
2017-01-26T23:17:30 fastq-dump.2.3.5 err: item not found while constructing within virtual database module - the path 'SRR1763777' cannot be opened as database or table

When I typed in fastq-dump --help, it showed the fastq-dump as the 2.3.5 version still, despite having downloaded the 2.8.1 version of the entire toolkit:

anh@anh-VirtualBox:~$ fastq-dump

Usage:
  fastq-dump [options] <path> [<path>...]
  fastq-dump [options] <accession>

Use option --help for more information

fastq-dump : 2.3.5

Is there something I can do, or have missed in the download process? 

Thank you for all your help!

**Comment by kwrodarmer** [comment]
Check where you have the old installation by running `which fastq-dump` and delete everything related to 2.3.5.

I'm not entirely sure where Ubuntu was places things, but you should also ensure that the configuration for 2.3.5 is gone. One step at a time - first ensure that 2.8.1 is in your `$PATH` and that it runs, that you no longer have 2.3.5. From there, we can determine where the toolkit is picking up configuration files and remove them, too.

**Comment by anhmoss** [comment]
Thank you for your feedback! I went back to double check, just in case I had any copies of the installation. Although, I am fairly new to programming and this is the first time I have worked with the SRA toolkit, but I did clean it out and made sure that the only version I had on my computer was the 2.8.1. 

I also have the following script in my .bash_profile: export PATH="/sratoolkit.2.8.1-2-ubuntu64/bin:$PATH" 

And to follow your suggestion, I also ran the command: 
anh@anh-VirtualBox:~$ which fastq-dump
/usr/bin/fastq-dump

So I can essentially go into the bin folder and just delete that fastq-dump? 

Many thanks for your time and help!

**Comment by klymenko** [comment]
Are you sure that you extracted the toolkit to /sratoolkit.2.8.1-2-ubuntu64/bin ?
In the root directory?

**Comment by anhmoss** [comment]
I was fairly certain I did, but it doesn't hurt to double check....

I attached two screenshots to show where I have the file downloaded and extracted, as well as what path my terminal shows...If I do have it incorrect, please let me know!! I appreciate all the help and feedback!
![extracted file screenshot](https://cloud.githubusercontent.com/assets/22404372/22380604/01eab8f2-e48c-11e6-8fb2-207b4328541f.png)
![screenshot_of_terminal](https://cloud.githubusercontent.com/assets/22404372/22380605/01f3175e-e48c-11e6-89a6-a72c7f2dec9a.png)

**Comment by klymenko** [comment]
The correct location is most likely
~/sratoolkit.2.8.1-2-ubuntu64/bin

**Comment by klymenko** [comment]
You can do one of:

cd ~/sratoolkit.2.8.1-2-ubuntu64/bin; ./fastq-dump -X 5 -Z SRR1763777

or ~/sratoolkit.2.8.1-2-ubuntu64/bin/fastq-dump -X 5 -Z SRR1763777

If ~/sratoolkit.2.8.1-2-ubuntu64/bin is in your PATH - you can run fastq-dump -X 5 -Z SRR1763777
It this case
"which fastq-dump" should report "$HOME/sratoolkit.2.8.1-2-ubuntu64/bin/fastd-dump"

**Comment by anhmoss** [comment]
Awesome, that worked well! It read and produced 5 spots for the file. 

Thank you all so much for your time and feedback; I appreciate your dedication and willingness to help out!
