### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by VikArz02** [ncbi/sra-tools#591]
Hello!
I try to install files and get this error, but installation is continued and stop again without error. Can you explain this problem, please?

SRR8639142
lookup :|----  7.01%2022-02-15T12:13:14 fasterq-dump.2.11.3 err: make_lookup_writer().KDirectoryVCreateFile() -> RC(rcFS,rcDirectory,rcCreating,rcNoObj,rcUnknown)

**Comment by wraetz** [comment]
Please give us the complete commandline you entered and the complete error output of the tool.
Also where are you running it? Linux? MacOS? Windows? Cloud or local?

**Comment by VikArz02** [comment]
@wraetz , sorry for not a full answer!
I run the next code Ubuntu 20.04, server:
```
or i in ERR2355633 SRR8639142 SRR14841338 SRR14832553 SRR14832552 SRR14832808 SRR5296491 SRR5296494 SRR9861081; do echo $i; ~/Soft/sratoolkit.2.11.3-ubuntu64/bin/fasterq-dump -p --split-files $i  -O raw/ ; done
ERR2355633
lookup :|----  7.85%2022-02-15T08:48:39 fasterq-dump.2.11.3 err: make_lookup_writer().KDirectoryVCreateFile() -> RC(rcFS,rcDirectory,rcCreating,rcNoObj,rcUnknown)
 8.47%^Cfasterq-dump was killed (signal 2 SIGINT)
SRR8639142
lookup :|----  7.01%2022-02-15T12:13:14 fasterq-dump.2.11.3 err: make_lookup_writer().KDirectoryVCreateFile() -> RC(rcFS,rcDirectory,rcCreating,rcNoObj,rcUnknown)
 7.51%
```

**Comment by wraetz** [comment]
by the way:- there is a new version of the sra-toolkit just released ( version 3.0.0 ), you might have to ask your sys-admin to install it.
by the way: you do not have to specify --split-files ... it is the default.

It looks like you are running fasterq-dump in a bash-script, and want the output to be in 'raw/'.

Do you have enough space available there?
Also the tool will create temporary files while producing the output.
These temp. files will be created in the current directory ( unless you specify a different location via -t )
Do you have enough space for them?

If you are on a server, your sysadmin might have set a disk-quota for you. Is it large enough?

**Comment by wraetz** [comment]
also there is a lot about the disk space to be found in here:

https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump
and
https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump

**Comment by VikArz02** [comment]
Thank you, I updated soft.
Yes, I have enough space in my disk (2 TB). It's enough to install this data.

**Comment by wraetz** [comment]
Do you still have the 'KDirectoryVCreateFile()'-error?
What is the current directory when starting the script/line?
Have you tried to specify the output-dir like this: -O ./raw
However the error happens during production of the lookup-table. That happens in the temp. directory.
This temp. directory is a combination of user-name, machine-name, and process-id.
Does user-name/machine-name have any special characters ( unicode? ) in them?

**Comment by wraetz** [comment]
what happens if you specify the temp. directory explicitly like -t ./$i.temp_dir?

**Comment by wraetz** [comment]
That mean the update to the newest version fixed it? ( and we can close the issue ? )

**Comment by VikArz02** [comment]
Yup, thank you!

**Comment by VikArz02** [comment]
Hello!
I try to use -temp option, but I have a new error, that connects with disk space.
My bash code: SRR4235787; do echo $i; ~/Soft/sratoolkit.3.0.0-ubuntu64/bin/fasterq-dump -p -e 5 -t ./$i.temp_dir $i  -O raw/; done
Error:
`2022-02-22T17:57:15 fasterq-dump.3.0.0 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='8'`
Free space in disk 5.6 TB, but error connects with an overfill home directory. When i can correct temp output?

**Comment by DawnEve** [comment]
I have the same issue:

`2024-10-29T07:22:49 fasterq-dump.3.1.1 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
`

**Comment by VikArz02** [comment]
I solved my problem to use perfetch

 ~/Soft/sratoolkit.3.0.0-ubuntu64/bin/prefetch --max-size 100000000 "$i"

and next

~/Soft/sratoolkit.3.0.0-ubuntu64/bin/fasterq-dump -p -e 1 --outdir raw/
"$i".sra

**Comment by DawnEve** [comment]
Perhaps it's the `-e 1` parameter that works. 
I'll try now and give the answer tomorrow.

**Comment by DawnEve** [comment]
> Perhaps it's the `-e 1` parameter that works. I'll try now and give the answer tomorrow.

Still not working.

I will try the two step command abouve: prefetch, then faserq-dump

**Comment by DawnEve** [comment]
The two-step method works:
```
$ i=SRR2xxxxxx5
$ prefetch --max-size 500000000 $i

$ fasterq-dump -p -e 1 ${i}/${i}.sra
```

**Comment by durbrow** [comment]
Why `fasterq-dump -p -e 1 ${i}/${i}.sra` instead of `fasterq-dump -p -e 1 ${i}`?

If you have `prefetch`ed an accession, you are able to `fasterq-dump` it from the same directory using the same accession string, not the path to the accession data file inside the accession directory.

**Comment by DawnEve** [comment]
This is small issue about $i or $i/$i, 
the main problem is why can't I use the previous one-step command `fasterq-dump --split-files $i` now?

**Comment by DawnEve** [comment]
> Why `fasterq-dump -p -e 1 ${i}/${i}.sra` instead of `fasterq-dump -p -e 1 ${i}`?
> 
> If you have `prefetch`ed an accession, you are able to `fasterq-dump` it from the same directory using the same accession string, not the path to the accession data file inside the accession directory.

This is small issue about $i or $i/$i,
the main problem is why can't I use the previous one-step command `fasterq-dump --split-files $i` now?
