### ISSUE TITLE
Cannot get VDB column: ./SRRxxxxx.sra.SEQUENCE.ACC_PREFIX

### ISSUE THREAD

**Issue by bigben446** [ncbi/sra-tools#592]
I'm working locally with sra-toolkit. I have downloaded a sra files, and when I try to do a sra-tblastn search with  the following error occurs:

sra-tblastn -query yyy.fasta -db SRRxxx.sra -html -out SRRxxx.tblastn.html

Error: Cannot get VDB column: ./SRRxxx.sra.SEQUENCE.ACC_PREFIX

**Comment by bigben446** [comment]
similar questions:
https://www.biostars.org/p/9486828/

**Comment by klymenko** [comment]
sra-tblastn is now supported by Blast team, their email is [blast-help@ncbi.nlm.nih.gov](mailto:blast-help@ncbi.nlm.nih.gov)
