### ISSUE TITLE
Any differencies between in tblastn, sra-tblastn, tblastn_vdb?

### ISSUE THREAD

**Issue by bigben446** [ncbi/sra-tools#593]
I'm confused with these 3 tools in searching sra files? 

Another questions is, how to use the sra-tblastn/tblastn_vdb/tblastn tools for searching the local sra file which had been downloaded already ?

**Comment by klymenko** [comment]
1. sra-tblastn is an alias of tblastn_vdb.
2. To use the local sra file try to use path to `.sra` file as command line argument.
3. blastn_vdb and tblastn_vdb binaries are now distributed and supported by Blast team, their email is blast-help@ncbi.nlm.nih.gov
