### ISSUE TITLE
Fasterq-dump 2.11.3 err: row #321235139 : R[1].len(302) != Q[1].len(151) 

### ISSUE THREAD

**Issue by jasonbhn** [ncbi/sra-tools#594]
Hi, I'm trying to download a certain WGS fastq from accession id SRR3133265. after prefetch the sra file. fasterq-dump gave me these errors: 
`2022-02-19T15:48:54 fasterq-dump.2.11.3 err: row #321235139 : R[1].len(302) != Q[1].len(151) 
2022-02-19T15:48:54 fasterq-dump.2.11.3 err: terminated in loop_nr #5.733 for SEQ-ROWID #321235139
fasterq-dump quit with error code 3
`
Any insight into what this might mean?

**Comment by wraetz** [comment]
I can replicate this error, and our team is working on a solution. In the meantime you can use fastq-dump instead of fasterq-dump. Even if it will be slower.

**Comment by jasonbhn** [comment]
> I can replicate this error, and our team is working on a solution. In the meantime you can use fastq-dump instead of fasterq-dump. Even if it will be slower.

Hi is there any new development on this front? thanks

**Comment by wraetz** [comment]
I have located the problem, and there is a fix right now in our engineering build.
You can wait until our next official release of the toolkit.
Or you can build the toolkit yourself.
Or you can use fastq-dump ( it will be slower ) on this particular accession.

**Comment by jasonbhn** [comment]
Is this the same error as referenced in release 3.0.0? I have seen a patch that fixed this 
'fasterq-dump, fastq-dump, sratools: fixed a bug that caused multiple accession to cause the tool to exit with an error'

**Comment by jasonbhn** [comment]
> I have located the problem, and there is a fix right now in a feature branch ( VDB-4820 ). You can wait until our next official release of the toolkit. Or you can build the toolkit yourself. Or you can use fastq-dump ( it will be slower ) on this particular accession.

Would you mind provide a quick instruction for building the toolkit from scratch with the new cmake framework?

**Comment by durbrow** [comment]
This is the first iteration of our CMake build system. It's still very much a work in progress. So, the commands below are certain to change in upcoming releases.

This is based on the Dockerfile we use for building our Docker image (see build/docker/Dockerfile.build-alpine)

```
git clone -b engineering --depth 1 https://github.com/ncbi/ncbi-vdb.git

cmake -DCMAKE_BUILD_TYPE=Release \
          -S ncbi-vdb -B build/ncbi-vdb
cmake --build build/ncbi-vdb

git clone -b ${SRA_BRANCH} --depth 1 https://github.com/ncbi/sra-tools.git
cmake -DCMAKE_BUILD_TYPE=Release \
          -DVDB_INCDIR=${PWD}/ncbi-vdb/interfaces \
          -DVDB_LIBDIR=${PWD}/build/ncbi-vdb/lib \
          -S sra-tools -B build/sra-tools
cmake --build build/sra-tools
cmake -P build/sra-tools/cmake_install.cmake
```

**Comment by klymenko** [comment]
@jasonbhn, please try our 3.0.1 release.

**Comment by arpfennig** [comment]
Hi, 

I get a similar error with fasterq-dump 3.2.0 on multiple accessions, including ERR1305294. Any thoughts on this?

Thanks,
aaron

**Comment by durbrow** [comment]
Try running `prefetch ERR1305294` first. If the problem persists, please email sra@ncbi.nlm.nih.gov with your question.
