### ISSUE TITLE
Prefetch created only sra.lock, sra.prf, sra.temp, but no main folder downloaded

### ISSUE THREAD

**Issue by lorrainelim** [ncbi/sra-tools#595]
Version: sratoolkit.2.11.2-centos_linux64

I tried several times with different SRA ID, example below: 
`prefetch SRR5790106`

Return:
`2022-02-23T03:59:03 prefetch.2.11.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2022-02-23T03:59:04 prefetch.2.11.2: 1) Downloading 'SRR5790106'...
2022-02-23T03:59:04 prefetch.2.11.2: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2022-02-23T03:59:04 prefetch.2.11.2:  Downloading via HTTPS...`

Files created:
SRR5790106.sra.lock
SRR5790106.sra.prf
SRR5790106.sra.tmp

I could not find the main folder with sra file downloaded that I read online. Is it due to config settings?

**Comment by IHMTDaiy** [comment]
the same as me

**Comment by IHMTDaiy** [comment]
any solutions?

**Comment by JefferFoo** [comment]
the same as me, hoping the solutions come out

**Comment by labybaby** [comment]
you need to wait a moment, I have had the same problems before, and I put it in the background, and wait the network connect it will download successful.
