### ISSUE TITLE
sam-dump - Error 403 access denied when attempting to access public data

### ISSUE THREAD

**Issue by Calebros** [ncbi/sra-tools#597]
I am attempting to use sam-dump (version 2.11.0)  to access files within the SRA database using the following command:

`sam-dump --aligned-region chrA1:134261072-134581026 --output-file ERR6177051.sam ERR6177051`

I am receiving the following error:

```
sam-dump.2.11.0 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'ERR6177051' - Access denied - object has not been published. ( 403 )
Query ERR6177051: Error 403 Access denied - object has not been published.
```

When checking the SRA run browser website [SRA Run Browser ERR6177051](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR6177051), access to this information is listed as public, and the metadata for the run includes a release date.  I also appear to be able to download and access this information via the data access tab in the above link.

This issue is specific to a subset of SRA records:
ERR6177051
ERR6177054	
ERR6177055
ERR6177050
ERR5762361
ERR5762486

Does anyone know how I can begin troubleshooting whether this is an issue with database permissions or if this is a problem with the sam-dump function?

Thank you for your time.

**Comment by klymenko** [comment]
Please send this question to [sra-tools@ncbi.nlm.nih.gov](mailto:sra-tools@ncbi.nlm.nih.gov)

**Comment by Calebros** [comment]
Email sent, if this is the wrong avenue for this query feel free to close
