### ISSUE TITLE
Failed to call external services.

### ISSUE THREAD

**Issue by FredYu1990** [ncbi/sra-tools#598]
I installed the distribution of NCBI with the version 3.0.0. And I met this error after a few days when I use the common "fastq-dump". Before this week, everything worked well, but now it does not work at all. Is there anyone could help me with that? Many thanks in advance!

**Comment by klymenko** [comment]
What command do you execute?

**Comment by Jasoncbh** [comment]
> I also get this error ,
fasterq-dump -e 12 SRR12952858
Failed to call external services.

**Comment by klymenko** [comment]
What's the output of `srapath SRR12952858`?

**Comment by smoretti** [comment]
I have a similar error message in a Google cloud instance.
`srapath SRR12952858` returns nothing.

**Comment by klymenko** [comment]
@smoretti, what's the output of `srapath -V`?

**Comment by smoretti** [comment]
This command returns
```
$ srapath -V

"srapath" version 3.0.0

```

**Comment by klymenko** [comment]
@smoretti, what's the output of `curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR12952858` ?

**Comment by smoretti** [comment]
No it does not work:
`curl: (7) Failed to connect to locate.ncbi.nlm.nih.gov port 443: Connection timed out`

**Comment by klymenko** [comment]
@smoretti, what's the output of `curl -v https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR12952858` ?

**Comment by smoretti** [comment]
It returns
```
*   Trying 130.14.29.113:443...
* TCP_NODELAY set
*   Trying 2607:f220:41e:4290::113:443...
* TCP_NODELAY set
* Immediate connect fail for 2607:f220:41e:4290::113: Network is unreachable
*   Trying 2607:f220:41e:4290::113:443...
* TCP_NODELAY set
* Immediate connect fail for 2607:f220:41e:4290::113: Network is unreachable
*   Trying 2607:f220:41e:4290::113:443...
* TCP_NODELAY set
```

**Comment by klymenko** [comment]
@smoretti, it looks like your Google cloud instance is badly configured.
The same commands work for me.

**Comment by smoretti** [comment]
I will try to figure it out...

**Comment by smoretti** [comment]
It was an issue with external IPs which were denied for me.

Thanks
