### ISSUE TITLE
fasterq-dump only outputs one set of reads file (R1 or R2) for scRNA-seq paired end data

### ISSUE THREAD

**Issue by tbrunetti** [ncbi/sra-tools#599]
I am using the latest SRA toolkit release, 3.0.0, on a Ubuntu OS, and for some reason I cannot get the other end of the pair in a single-cell paired end data set.

These are the commands I am using:
`prefetch SRR9643701`
`fasterq-dump SRR9643701 --include-technical -S`

However, I only get the following data:
SRR9643701_1.fastq - cell ID file
SRR9643701_2.fastq - I think the UMI file?
SRR9643701_3.fastq - biological read

I am missing the other pair though...am I missing a command?

**Comment by klymenko** [comment]
This run has 2 technical reads and 1 biological:
```
$ vdb-dump -R1 SRR9643701
      READ_LEN: 8, 26, 98
     READ_TYPE: SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL
```

**Comment by tbrunetti** [comment]
Correct, I get all three of those files. However, the paper publication and the metadata file from SRA both indicate this is a paired-end data set. Isn't the 3 fastq files for just one read pair?

**Comment by tbrunetti** [comment]
I think I just figured this out -- Fastq1 and fastq2 are R1 that need horizontal concatenation and fastq3 is R2.

**Comment by durbrow** [comment]
Can you email sra@ncbi.nlm.nih.gov and inform them of this? The data should be fixed.

**Comment by stineaj** [comment]
This was a 3 file submission with an index fastq file as well as an r1 and r2 fastq file. You can see the submitted files on the Run Browser page using the Data Access tab. 
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR9643701

We try to do some detection of index files and mark them as technical reads but there can be errors in that process.
Other than the file names your 3 file output essentially match  what was submitted.

**Comment by tbrunetti** [comment]
Yes, I just found that out and I think the index file is already demultiplexed.  It would be nice if NCBI/SRA could provide documentation on how the reads for single cell are split across fastq files.  I think in this case, I don't need fastq1 since I checked that the sample barcodes are all the same for this particular case.  I will use fastq2 and fastq3 for alignment.  Thank you!!
