### ISSUE TITLE
Homebrew recipe for sra-tools

### ISSUE THREAD

**Issue by saketkc** [ncbi/sra-tools#6]
I opened a PR to get make sra-tools available as a `homebrew-science` recipe: https://github.com/Homebrew/homebrew-science/pull/1691

It builds fine on linux. Unfortunately, it looks like it does not get through on MacOS. For e.g. see: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/759/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_sratoolkit/

I do not have access to a Mac to look into this further. Would someone from the core team be interested in looking into this?

**Comment by kwrodarmer** [comment]
Is this a Mavericks issue?

**Comment by saketkc** [comment]
It fails on the rest too: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/759/

**Comment by kwrodarmer** [comment]
I've asked one of our engineers to look at the issue.

**Comment by klymenko** [comment]
May I see the output of configure in sra-tools?

**Comment by saketkc** [comment]
As I said, I do not have access to a Mac. unfortunately the logs are truncated too. 
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/759/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_sratoolkit/

```
ld: library not found for -lmagic-static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/usr/local/Cellar/sratoolkit/2.4.3/sra-tools/mac/clang/x86_64/rel/bin/copycat] Error 1
make[2]: *** [std] Error 2
make[1]: *** [copycat] Error 2
make: *** [tools] Error 2
==> Formula
```

**Comment by klymenko** [comment]
How do you run this build?
I there a way to run just "configure" in sra-tools without "make"?

**Comment by saketkc** [comment]
Does this help?
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/775/version=mavericks/testReport/brew-test-bot/mavericks/install_sratoolkit/

**Comment by klymenko** [comment]
Can you run "make" instead of "make CC=gcc-4.9" ?

**Comment by saketkc** [comment]
It still fails.
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/793/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_sratoolkit/

It would be good to replicate this locally rather than relying on the bot. I will try to see if I can get hold of a Mac machine.

**Comment by klymenko** [comment]
Yes, it is a good idea to run it locally.

While waiting: could you run "configure" in sra-tools but not run "make"?
I would like to see configure's output.

**Comment by iml** [comment]
FWIW, I built @saketkc's formula with Clang on Yosemite but the reference to `-lmagic-static` is problematic because most Macs will tend to build libmagic with shared linkage rather than statically. Here's the log output of the build, after patching `tools/copycat/Makefile` to invoke just `-lmagic`:

https://gist.github.com/anonymous/74fe285bbc3491465933

**Comment by klymenko** [comment]
Can we get an account on a Mac machine to check it locally?

**Comment by saketkc** [comment]
@klymenko I don't think that would be possible for the brew-bot machine.

**Comment by kwrodarmer** [comment]
The issue with static vs. dynamic libraries is somewhat involved...
When building from source, dynamic libraries are no problem. However, when building for binary distribution, they create a severe headache.
Patches the makefile to just use `-lmagic` is a perfect solution, but it doesn't create portable binaries.

**Comment by saketkc** [comment]
Any updates on this @kwrodarmer?

**Comment by kwrodarmer** [comment]
The best suggestion for now is to a) NOT configure for libmagic, and b) not configure for libhdf5. If the build is finding them anyway, then we can give you a temporary edit to the configuration files produced.

What we want is for those who check out and build from source, to use normal system libraries. But this build will not work for us, since we try to produce a portable binary. We will address this issue of build configuration as time permits.

In the meanwhile, we have released a new build that addresses a networking issue and are close to releasing a new NGS API with completed support for pileup.

**Comment by saketkc** [comment]
Thanks @kwrodarmer! It seems to be now building on both linux and Mac:
https://github.com/Homebrew/homebrew-science/pull/1811

Do you want to update your readme once that pull request is updated?

**Comment by kwrodarmer** [comment]
Yes, we'll do our best to update the readme, as well as some of the build-from-source instructions. Glad to hear you're able to build now!

**Comment by saketkc** [comment]
I am having issues getting `2.4.5` built on Mac again:
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/1118/version=mavericks/testReport/brew-test-bot/mavericks/install_sratoolkit/

```
vdb/mac/clang/x86_64/rel/lib/libncbi-vdb.2.4.5.dylib'
make[3]: *** [/usr/local/Cellar/sratoolkit/2.4.5/ncbi-vdb/mac/clang/x86_64/rel/lib/libncbi-vdb.dylib] Error 1
make[2]: *** [std] Error 2
make[1]: *** [ncbi-vdb] Error 2
make: *** [libs] Error 2
```

**Comment by kwrodarmer** [comment]
We're looking into it. I see that the failing link line generates  
```
clang -Wl,-arch,x86_64 -dynamiclib -DNDEBUG  -m64 -mmacosx-version-min=10.6 -L -o /Users/...
```
Notice the `-L -o` - the link path option is bad. We will produce a fix asap.

**Comment by kwrodarmer** [comment]
Please check out the new master branch.

There has been work being done on the side to support fat Mac binaries, which resulted in a quick linker path being inserted in `libs/ncbi-vdb/Makefile` which was only being defined internally to NCBI. This has been updated temporarily to alter its detection, and should now work.

**Comment by klymenko** [comment]
Saket,

We have a fix,
please check out the new master branch.

**Comment by saketkc** [comment]
Thanks, that seems to work!
