### ISSUE TITLE
Segmentation fault when downloading any data from GCP

### ISSUE THREAD

**Issue by efedo** [ncbi/sra-tools#608]
SRA-Tools 3.0.0 running on Ubuntu 20.04.4 LTS on Google Compute Engine

Occurs with all run accessions and all utilities tested (vdb-dump, prefetch, fasterq-dump, fastq-dump) 
![image](https://user-images.githubusercontent.com/70902412/158649841-a4ddc66a-baca-41fa-8f4d-c35d6fda5983.png)

Occurs whenever "Accept charges for GCP" is selected, even when "Enable remote access" and "Report cloud instance identity" are disabled.

**Comment by klymenko** [comment]
Disable `Accept charges for GCP`.

**Comment by efedo** [comment]
No segfault when it is unchecked. Do charges ever need to be accepted to receive public SRA data from GCP, or when must charges be accepted?

**Comment by klymenko** [comment]
`Accept charges` means that you are going to pay egress charges.

**Comment by klymenko** [comment]
Could you try it with the [latest](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) toolkit?
