### ISSUE TITLE
Issue with sam-dump and dbGaP protected project

### ISSUE THREAD

**Issue by emi80** [ncbi/sra-tools#61]
Hello,
I am getting the following error when I try to convert an SRA file to BAM:

```
2017-02-22T11:14:52 sam-dump.2.8.1 int: column invalid while reading cursor within virtual database module - VCursorCellDataDirect( row#8970235 . idx#9 . READ ) INSDC_dna_text (ptr) failed
```

The project is a dbGaP encrypted project. The SRA file is `prefetched` and converting to `fastq` with `fastq-dump` works as expected. Converting an SRA file from a public project gives no error. I use the following command for the conversion to BAM:

```
sam-dump -u ${accession} | samtools view -@4 -Sb - > ${accession}.bam
```

I also checked the row with `vdb-dump -IR 8970235  ${accession}` but I cannot see any error.

Any help would be very much appreciated.

Thanks a lot.

**Comment by osris** [comment]
can you send us an example SRR accession?
thanks,
-Chris
________________________________

**Comment by emi80** [comment]
Hello,
thanks for the quick reply.

Here is an example accession:
SRR4109101

Best,
Emilio

**Comment by osris** [comment]
Thanks,
I can reproduce the issue here. looking closer at it now.
-Chris


*********************************
Christopher O’Sullivan PhD
Sequence Read Archive
NCBI/NLM/NIH
osulliva@ncbi.nlm.nih.gov
*********************************

**Comment by bnelsj** [comment]
Has there been any progress on this issue? I get the same error with accession SRR3986881 and sam-dump.2.8.2.

**Comment by emi80** [comment]
Hi Chris,

did you get any chance to have a deeper look at the issue? We would need to download data for the affected dbGaP encrypted project for production use.

Many thanks.

Best,
Emilio

**Comment by osris** [comment]
apologies for losing track of this.
SRR4109101 was withdrawn by request of GTEX a couple weeks after you first reported the issue. SRR655076 is linked to the same GTEX sample and contains the same reads. i recall that GTEX re-aligned their data using STAR, but then they decided that the new alignments shouldn't be released so we suppressed them. i'm testing again regardless as the data will be re-released eventually.
i am looking at the public run example, SRR3986881 now. it is quite large. hope my test completes before a scheduled filesystem firmware update tomorrow morning. 

i think we have a fix in engineering branch, but i need to build sam-dump and test.

**Comment by cjyoon** [comment]
SRR4189083
SRR4189391
SRR4189089
SRR4189090.

**Comment by klymenko** [comment]
@emi80, @cjyoon, do you still need help?
