### ISSUE TITLE
fastq/sam-dump

### ISSUE THREAD

**Issue by dvbeek1** [ncbi/sra-tools#611]
Hi,

As far as I understood, genotype data does not need to be decrypted since sra-tools can read the files without decryption and fastq-dump and sam-dump can be used to translate the files into FASTA or BAM respectively. Both commands seem to run without errors and warnings (green check in MobaXterm) but I don't see any new or changed genotype files appearing. The vdb-validate function validates the file. The extension of the files is .tar.gz.ncbi_enc.

Any possible solutions?

Best regards,

Daan

**Comment by kwrodarmer** [comment]
dbGaP Genotype data are neither FASTQ nor SAM, so `fastq-dump` and `sam-dump` are not applicable tools. The genotype files are tar archives and can only be accessed using tools that are unaware of VDB encryption. These files need to be decrypted using `vdb-decrypt` to be accessed.

**Comment by dvbeek1** [comment]
But on the website it says SRA files don't need to be decrypted:

"The data files distributed through the dbGaP are all encrypted by NCBI’s data encryption algorithm. These files have a file suffix “.ncbi_enc”, indicating that they are NCBI encrypted files. Not all encrypted data however need to be decrypted.

The SRA (short-read-archive) data distributed through the dbGaP are encrypted but there is no need to decrypt them. The NCBI SRA toolkit can work directly on encrypted SRA data without decryption. Decrypted SRA data is in a binary format that is not human readable and can only be processed by the SRA toolkit anyway."

Does SRA data necessarily have an .sra suffix? 

Using vdb-decrypt I get the error "path excessive while resolving directory within file system module - unable to resolve". It works perfectly fine on the Phenotype Data that I have.

**Comment by kwrodarmer** [comment]
The SRA houses genomic data, and these do not need to be decrypted because the SRA Toolkit understands them natively. 

dbGaP stores its genomic data in the SRA, but its phenotype and genotype data are stored separately. They must be decrypted for access. The files are encrypted and have a `.ncbi_enc` extension, but they also have a `.tar.gz` extension before that.

The error you are receiving from `vdb-decrypt` would indicate there is something else going wrong with your decryption operation.

**Comment by klymenko** [comment]
@dvbeek1, what version of SRA toolkit do you use?

**Comment by dvbeek1** [comment]
@klymenko version 3.0.0 through MobaXterm on a Windows 10 environment. I have the key in the same folder as the genotype file, and the sra toolkit in a folder named sra.
So basically I'm running **sra/bin/vdb-decrypt --ngc GenotypeFiles/prj_xxxxx.ngc GenotypeFiles/genofilename.tar.gz.ncbi_enc**

And the error I get is
**path excessive while resolving directory within file system module - unable to resolve '.genofilename.tar.gz.ncbi_enc.vdb-decrypt-tmp'**

Also @klymenko @kwrodarmer thanks for the fast responses!
