### ISSUE TITLE
Extracting only unaligned/unmapped reads using sam-dump

### ISSUE THREAD

**Issue by ngs-seqer** [ncbi/sra-tools#619]
According to the sam-dump manual, 

"sam-dump --unaligned" retrieves (1) aligned AND (2) unaligned reads.

What is the option to retrieve unaligned reads only? 

I saw "--unaligned-spots-only", but its meaning is a bit confusing. 

Let me know. Thanks!

**Comment by wraetz** [comment]
You are right about the options being confusing.

sam-dump SRRXXXXXX produces only the aligned READS
sam-dump --unaligned SRRXXXXXX produces all aligned and unaligned READS
sam-dump --unaligned-spots-only produces only the READS of spots that are fully unaligned.

In the last case you will not get half-aligned READS ( one READ of a spot is aligned the other one is not ).
There is right now no option for sam-dump that produces all unaligned READS exclusively ( half- and fully-unaligned ).
Your best option to achieve this is to use 'sam-dump --unaligned SRRXXXXXX' and pipe the output into an AWK script to remove the aligned ones.

**Comment by ngs-seqer** [comment]
Well, when run sam-dump (3.0.0) with "--unaligned-spots-only", I get a very strange error message :

unrecognized option: '--unaligned-spots-only'

'sam-dump -h' lists this option.

**Comment by ngs-seqer** [comment]
OK, I checked several different sratoolkit versions and it seems that "--unaligned-spots-only" option is not supported since v2.10.xxx

v2.9.xxx looks recognizes it, but does not support "-ngc" option for dowinloading the protected data, so I cannot use it.

Was "--unaligned-spots-only" option deprecated? I may download WGS data using "sam-dump --unaligned", but the transfer speed is quite slow and the resulting SAM files are too big (I need hundreds of them). 

"--unaligned-spots-only" looks the perfect solution for me because I just need unaligned reads. Is there any good solution for this issue?

**Comment by ngs-seqer** [comment]
Do "fasterq-dump --only-unaligned" and "sam-dump --unaligned-spots-only" retrieve the same reads? BTW, "--unaligned-spots-only" is not recognized in > sratoolkit 2.9

**Comment by durbrow** [comment]
The problem with `sam-dump` and `--unaligned-spots-only` will be fixed in the next release. Thank you for the report.

**Comment by klymenko** [comment]
@ngs-seqer, please check our latest release.
