### ISSUE TITLE
Change default cache location

### ISSUE THREAD

**Issue by StijnT** [ncbi/sra-tools#62]
Hi,
I'm working on system with small home directories but a large SAN.
I changed the location of the workspace to a location on the SAN but it still creates cache files in /home/user/ncbi/Public
Does it fit that the cache is not part of the workspace?
Can you change the default cache location or can you only disable it?

**Comment by kwrodarmer** [comment]
If you update either the public workspace or a protected (dbGaP) workspace, the tools should be caching to the new workspace. It should be understood that some of the downloaded objects, specifically reference sequences, are considered public and will always be cached in the public workspace.

I suggest that you run the tool `test-sra` and capture the output, which you can send to sra-tools@ncbi.nlm.nih.gov for us to examine and see what we can figure out.

**Comment by DarioS** [comment]
Did you try to change it to a folder which already contains files? It's designed to reject the change, but doesn't emit an error message to inform you the change wasn't applied. In other words, every time you download a different set of SRR files, you need to run `mkdir` and `vdb-config` again to change the cache to an empty folder. `vdb-config -h` also provides no details about this constraint.

**Comment by kwrodarmer** [comment]
You don't change your "download" directory every time you use the sra toolkit. The directory that we create _for our use_. You do not confront SRA files directly - they are stored in our cache. When you work with them, all you need to do is to specify them by accession, regardless of your current directory, and we locate them _in our cache_. In the 10 years of the SRA, you are the first person I have heard of that has tried to reset their configuration for every set of files they download.

If you want to create subdirectories within the workspace, that is reasonable. But our cache area should be left alone for us to use as we have designed. Please see https://github.com/ncbi/ncbi-vdb/wiki/Name-Resolution-Process for more information about how we resolve names and use the cache. Also, this might shed some light on downloading, although it seems you're able to download without issue. https://github.com/ncbi/sra-tools/wiki/Download-On-Demand

**Comment by StijnT** [comment]
Changing the public workspace worked with  vdb-config.
The reason I thought it didn't work was because it is a user-based setting.
As soon as I set for every user it was ok.
