### ISSUE TITLE
Shared config file

### ISSUE THREAD

**Issue by pelacables** [ncbi/sra-tools#622]
We'd like to use a shared config file but we cannot find documentation on how to create that shared file and where to keep it. 

from [here ](https://github.com/ncbi/sra-tools/wiki/05.-Toolkit-Configuration) the only reference to that admin created config file is the next sentence:

> [Use Site Installation] ... this setting is only visible if your admin has configured a local site-repository

Could you please provide some docs on how to create and use a shared config file?

**Comment by klymenko** [comment]
System-wide configuration files can be created in `/etc/ncbi/` with extension `.kfg`.
What exactly do you want to share?

**Comment by pelacables** [comment]
In one research group the group lead would like to use the same config file with all his colleagues. 
Is there a way to use something not under /etc ? we do not have full access on the HPC compute nodes, which means that we have to put all our software and conf files under /apps/something .

**Comment by klymenko** [comment]
You can create a directory with configuration file[s].
Then export VDB_CONFIG environment variable that points to that directory.
