### ISSUE TITLE
Paired reads concatenated  - SRP270378

### ISSUE THREAD

**Issue by hjruscheweyh** [ncbi/sra-tools#623]
Dear SRA-Tools Team,

thank you for providing this fast and reliable tool. I have been downloading quite some number of sra files and your tool offers by far the availability and access to public read files. 

Im currently having an issue with a sequencing files from a project (https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP270378) ~1200 samples. I'm downloading the sra files (one listed as example):

```
$ sratoolkit.2.11.3-centos_linux64/bin/prefetch -o SRR12159142.sra --force yes --max-size 500G SRR12159142

2022-04-08T07:12:25 prefetch.2.11.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2022-04-08T07:12:26 prefetch.2.11.2: 1) Downloading 'SRR12159142'...
2022-04-08T07:12:26 prefetch.2.11.2: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2022-04-08T07:12:26 prefetch.2.11.2:  Downloading via HTTPS...
2022-04-08T07:16:04 prefetch.2.11.2:  HTTPS download succeed
2022-04-08T07:16:19 prefetch.2.11.2:  'SRR12159142' is valid
2022-04-08T07:16:19 prefetch.2.11.2: 1) 'SRR12159142' was downloaded successfully
2022-04-08T07:16:19 prefetch.2.11.2: 'SRR12159142' has 0 dependencies

```

 

And then I want to translate the sra files into fastq files (as it works for basically all other files that I have downloaded)

```
$ sratoolkit.2.11.3-centos_linux64/bin/fasterq-dump SRR12159142.sra -e 6 --outdir SRR12159142/ -b 100MB -c 100MB -m 10000MB
spots read      : 108,731,262
reads read      : 217,462,524
reads written   : 108,731,262
reads 0-length  : 108,731,262
```

For sra files in the project I get only one fastq file even though the data is labelled paired end and R1/R2 files are actually indicated at trace (and amazon/google downloads --> https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12159142) and https://db.cngb.org/search/project/CNP0000478/ which contains data from the same project.

It looks like R1 and R2 reads are just concatenated (not interleaved). How do I need to change the command so that I will get R1 and R2 read files? Note: I have also tried with V3.0.0 but the result was the same.

Thank you a lot,
Hans

**Comment by wraetz** [comment]
Dear Hans,

unfortunately there is no command-line option that can split this accession into 2 reads. Despite the fact that they are labeled as paired end, that is not what is in the actual archive. You can see for yourself with this command: 'vdb-dump SRR12159142.sra -R1'. It shows all stored data for the first spot. The layout of the spot looks like that: 2 reads, but the first read is technical and of length zero, the second read is biological and has bases ( as shown in READ_SEG and READ_TYPE ). This second biological read is the data you see produced by fasterq-dump. Please contact sra@ncbi.nlm.nih.gov, if you have need this data to be reprocessed.

**Comment by hjruscheweyh** [comment]
Dear @wraetz 

Thank you for the quick feedback. It's just strange as the google/amazon cloud has links to the forward/reverse reads.

I will contact the mail address you have provided and hope that the issue will get fixed in time.

best,
hans
