### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by MjelleLab** [ncbi/sra-tools#627]
I downloaded the ubuntu 3.0 version, but not sure how to config the toolkit before using it. 

~/software/sra3.0/sratoolkit.3.0.0-ubuntu64/bin$ ./fastq-dump
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

**Comment by klymenko** [comment]
run: vdb-config --interactive

**Comment by MjelleLab** [comment]
I know how to open it, but what kind of changes is needed in the config?

**Comment by klymenko** [comment]
Run vdb-config --interactive.
Exit it.

Then run your fastq-dump command again.
