### ISSUE TITLE
KDirectoryGetDiskFreeSpace

### ISSUE THREAD

**Issue by cecombs** [ncbi/sra-tools#63]
I can not find what package this is referring to. Ubuntu 14.04

Tried with gcc 4.8.4 and 4.9.3

./configure --prefix=/share/apps/sra-toolkit-2.8.2 --with-ngs-sdk-prefix=/share/apps/ngs-sdk-1.3.0 --with-ncbi-vdb-sources=/share/apps/src/ncbi-vdb-2.8.2/ncbi-vdb-2.8.2rc && make

test-sra.c:(.text+0x1654): undefined reference to `KDirectoryGetDiskFreeSpace_v1'

Have a suspicion that it's related to KDE - this node does not run KDE or Gnome. I hope that is helpful. Let me know if you need any more information.

Thank you

**Comment by kwrodarmer** [comment]
Did you also get the latest `ncbi-vdb` package? They're related.

**Comment by cecombs** [comment]
I tried with the latest master from the github page and it gave me the same
error except without the "_v1". Rolling back to 2.8.2rc gave me the one I
posted.

What API does KDirectoryGet.... come from? Our environment is, admittedly,
extremely complex.

**Comment by kwrodarmer** [comment]
KDirectoryGetDiskFreeSpace_v1 is a function within the kfs module of ncbi-vdb.  See:

https://github.com/ncbi/ncbi-vdb/blob/master/libs/kfs/unix/sysdir.c

line 2417. If you are not seeing it, then there is a linking issue and you are possibly linking against an older library. This function was introduced exactly for this release, and wouldn't be found in 2.8.1 or before.

**Comment by kwrodarmer** [comment]
Please reopen this ticket if you are still having issues.
