### ISSUE TITLE
fasterq-dump give an error 3 when using for loop 

### ISSUE THREAD

**Issue by JW-Huh** [ncbi/sra-tools#636]
I downloaded 330 SRA files by prefetch and tried to extract fastq files using for loop + fasterq-dump 

When I run this very simple bash script, error messages pop up

----------------
#!/bin/bash

for i in $(cat accession.txt) # It contains SRA accession 

do

 fasterq-dump ./$i/{$i}.sra -S -e 10 -O ./SRA-all
	
done
-----------------

But, the command worked for an individual SRA file 
($ fasterq-dump ./directory/SRA.sra -S -e 10 -O ./SRA-all  --> it worked)

Error message is like below

fasterq-dump.2.11.0 err: name not found while resolving query within virtual file system module - failed to resolve accession './SRR15051303/{SRR15051303}.sra' - Cannot resolve accession ( 404 )
2022-05-02T02:30:23 fasterq-dump.2.11.0 err: extract_acc2( './SRR15051303/{SRR15051303}.sra' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect)
2022-05-02T02:30:23 fasterq-dump.2.11.0 err: invalid accession './SRR15051303/{SRR15051303}.sra'

**Comment by kwrodarmer** [comment]
> fasterq-dump ./$i/{$i}.sra -S -e 10 -O ./SRA-all

You don't need the curly braces, but if you want to use them you have to move `$` outside:
`fasterq-dump ./$i/$i.sra -S -e 10 -O ./SRA-all`

**Comment by JW-Huh** [comment]
Now It works! feel embarrassing a bit =_= 
(it still gave this kind of message)

spots read      : 18,307,534
reads read      : 36,615,068
reads written   : 36,615,068
2022-05-02T02:47:54 fasterq-dump.2.11.0 err: fasterq-dump.c fastdump_csra() checking ouput-file './SRA-all/SRR15051413.fastq' -> RC(rcExe,rcFile,rcPacking,rcName,rcExists)

but, output fastq files are extracted well. 

Thank you for fast response :)

**Comment by kwrodarmer** [comment]
Glad to hear!
