### ISSUE TITLE
cmake: allow disable building `test` when unused

### ISSUE THREAD

**Issue by cho-m** [ncbi/sra-tools#638]
Currently, tests are built whether they are used or not:

https://github.com/ncbi/sra-tools/blob/02ddc5743da8b13c75e86f5c3b01248ab119f036/CMakeLists.txt#L54

---

It would be nice to offer option to disable building tests. This could be either common CTest `BUILD_TESTING` option or a repo-dedicated option, e.g.
```cmake
if (BUILD_TESTING)
	add_subdirectory( test )
endif()
```

**Comment by durbrow** [comment]
It is planned for the next release.

**Comment by klymenko** [comment]
@cho-m, it was done it 3.0.1 release.
Please check.
