### ISSUE TITLE
cmake: allow changing installation library directory

### ISSUE THREAD

**Issue by cho-m** [ncbi/sra-tools#639]
Currently, libraries are hardcoded to install into `lib64`

https://github.com/ncbi/sra-tools/blob/02ddc5743da8b13c75e86f5c3b01248ab119f036/build/env.cmake#L365

In Homebrew (https://github.com/Homebrew/homebrew-core/pull/98654) we don't use that directory and instead want to install into `lib`.

Can there be a way to override directory? For example, using standard `${CMAKE_INSTALL_LIBDIR}` or using a CMake option that can be overridden.

**Comment by klymenko** [comment]
@cho-m, it was done it 3.0.1 release.
Please check.

**Comment by cho-m** [comment]
There is a Homebrew PR to update to 3.0.1 where we can check that it works (https://github.com/Homebrew/homebrew-core/pull/115909).
