### ISSUE TITLE
Timeout Error While Downloading

### ISSUE THREAD

**Issue by DarioS** [ncbi/sra-tools#64]
I saw the error `2017-03-14T01:57:55 fastq-dump.2.8.2 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )` but the downloading file continues to increase in size. How can it be?

**Comment by kwrodarmer** [comment]
It's impossible to say in this case what is happening without more information. But I can say that the VDB library *(which performs the network operations)* works very hard at maintaining a connection and download. It will reconnect as necessary and retry an operation many times before giving up. It is entirely possible that a single error occurred at the **TLS** level that was retried and continued.

**Comment by kwrodarmer** [comment]
If you are still having network issues, please reopen this ticket or write to us at sra-tools@ncbi.nlm.nih.gov to pursue it further.
