### ISSUE TITLE
sam-dump - "file insufficient while reading binary large object within database module - VCursorCellDataDirect( row#2566 . idx#5 . SAM_QUALITY ) char_ptr failed"

### ISSUE THREAD

**Issue by lfearnley** [ncbi/sra-tools#641]
I'm running sam-dump on SRR files hosted in Google Cloud Storage, and I've encountered the following:

```
fearnley_l@instance-1:sam-dump -u -r /home/fearnley_l/lbd_mount_test/SRR15473301/SRR15473301 | samtools view -bS - > ~/bl_202205_lbd/tmp/SRR15473338.bam
2022-05-19T13:37:30 sam-dump.3.0.0 int: file insufficient while reading binary large object within database module - VCursorCellDataDirect( row#2566 . idx#5 . SAM_QUALITY ) char_ptr failed
sam-dump quit with error code 3
[E::read_ncigar] No CIGAR operations
[W::sam_read1_sam] Parse error at line 232558
samtools view: error reading file "-"
```

There's only one other mention of that error that I can find, and that was in a log where that sample was discarded - what does this error message mean?

user-repository, local SRR file (obtained through the Cloud Delivery Service), and the output file location are all on Google Cloud Storage - if I can pinpoint which of these is likely to be the issue then I'll start trying to debug this further.

**Comment by klymenko** [comment]
What is the output of `vdb-validate /home/fearnley_l/lbd_mount_test/SRR15473301/SRR15473301` ?

**Comment by kiranchari** [comment]
@klymenko I am getting the same error:

**Comment by kiranchari** [comment]
@klymenko I am getting a similar error. vdb-validate returned that the database is consistent. Would appreciate any help in debugging this!
```
2024-11-17T01:01:09 sam-dump.3.1.1 int: incomplete while reading within network system module - failed to read HTTP file
2024-11-17T01:10:48 sam-dump.3.1.1 warn: database incorrect while opening manager within database module - can't open NT_187483.1 as a RefSeq or as a WGS
2024-11-17T01:14:23 sam-dump.3.1.1 int: database incorrect while opening manager within database module - VCursorCellDataDirect( row#427703662 . idx#3 . READ ) read_char_ptr

=============================================================
An error occurred during processing.
A report was generated into the file '/home/users/ncbi_error_report.txt'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================

sam-dump quit with error code 3
[E::read_ncigar] No CIGAR operations
[W::sam_read1_sam] Parse error at line 428037137
samtools view: error reading file "-": No such file or directory
```

**Comment by klymenko** [comment]
@kiranchari , the same question about `vdb-validate`

**Comment by kiranchari** [comment]
@klymenko I have emailed the file to sra-tools@ncbi.nlm.nih.gov. Thanks!

**Comment by klymenko** [comment]
@kiranchari , did you get ticket/issue number?

**Comment by kiranchari** [comment]
-rw-rw-r--+ 1 user user 37229561251 Nov 19 06:19 SRR15675790

**Comment by klymenko** [comment]
How did you get this file?

We need to do create a directory, move this file and run `prefetch` in order to make sam-dump succeed.

**Comment by kiranchari** [comment]
So I should run `prefetch /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples/SRR15675790` followed by 
`sam-dump /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples/SRR15675790` ?

**Comment by klymenko** [comment]
No, run:
```
cd /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples
mv SRR15675790 SRR15675790.sra
mkdir SRR15675790
mv SRR15675790.sra SRR15675790
prefetch /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples/SRR15675790
```

**Comment by kiranchari** [comment]
ok, will try sam-dump again after prefetch. Will update again. Thanks!

**Comment by kiranchari** [comment]
I am getting this error with prefetch..

`$ prefetch --max-size 99999999999999 /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples/SRR15675790`

`2024-11-19T15:03:01 prefetch.3.1.1 err: name not found while resolving query within virtual file system module - failed to resolve accession '/scratch/users/astar/gis/krishnak/mosaic_benchmark_samples/SRR15675790' - Cannot resolve accession ( 404 ); ncbi_phid=322C421DE0050CA500004C06EDE2EF6B.1.m_2
`

**Comment by klymenko** [comment]
Run:
```
cd /scratch/users/astar/gis/krishnak/mosaic_benchmark_samples
prefetch SRR15675790
```

**Comment by klymenko** [comment]
@kiranchari, did you have success?

**Comment by kiranchari** [comment]
@klymenko yes, prefetch made sam-dump work, thanks for your help! I am now running the sam-dump binary directly (https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit) rather than using sra-tools from conda. It seems to work without requiring prefetch first. This makes me think the issue might be with sra-tools available on conda.

**Comment by kiranchari** [comment]
Noted and thanks @klymenko  and @durbrow. Perhaps I missed it in the wiki/docs, but it would be good to include the recommended workflow (prefetch + sam-dump) for new users of sra-tools.
