### ISSUE TITLE
10X Genomics tags

### ISSUE THREAD

**Issue by blaserlab** [ncbi/sra-tools#642]
Hi,

I am trying to convert SRA bam files from a 10X genomics project (controlled access) into fastqs to run through cellranger.  

After converting with sam-dump, I pipe to samtools and convert to bam.  Then when I try to run cellranger bamtofastq I get the following message:

bamtofastq error:  BAM record missing tag: "CR" on read "1". You do not appear to have an original 10x BAM file. If you downloaded this BAM file from SRA, you likely need to download the "Original Format" version of the BAM available for most 10x datasets.

How do I download original format with sra-tools?

**Comment by durbrow** [comment]
Please email sra@ncbi.nlm.nih.gov The SRA curators can help you access the originals. (We are the toolkit devs.)
