### ISSUE TITLE
fastq-dump/fasterq-dump Error on M1 Mac

### ISSUE THREAD

**Issue by jjp55** [ncbi/sra-tools#645]
Hello, 

I have recently run into an issue when trying to download files using fastq-dump/fastq-dump on my M1 laptop. SRA-tools was complied using Conda. I receive the following error when using accessions with SRR; fastq-dump SRR2926782:

fasterq-dump.2.11.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
Failed to call external services.

When I try to download files with SRX accessions I get the following error: 
SRX1412889 is not a run accession. For more information, see https://www.ncbi.nlm.nih.gov/sra/?term=SRX1412889

In regards to the second error, I was able to use this accession on my old laptop (Mac with Intel Chip) and successfully download the files. Additionally, I am not able to download the files directly from the SRA website, but I am able to download them from the ENA website. Any suggestions to try would be greatly appreciated.

**Comment by klymenko** [comment]
[Download the latest toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).
Conda version is out of date and does not work correctly.

**Comment by taylorreiter** [comment]
Are there any plans to update the conda package?

**Comment by durbrow** [comment]
The conda package was not created by us and isn't maintained by us.
