### ISSUE TITLE
error for using fastq-dump

### ISSUE THREAD

**Issue by dahun73** [ncbi/sra-tools#647]
Hello :) 

I have one problem for using fastq-dump.

When I tried to download multiple files, this error came out.
```
fastq-dump --gzip --split-files SRR14301924 SRR14301925
2022-05-30T07:40:02 fastq-dump.2.11.2 int: string unexpected while executing query within virtual file system module - multiple response SRR URLs for the same service 's3'
Segmentation fault (core dumped)
```

Funny things, it is working well separately like this.
```
fastq-dump --gzip --split-files SRR14301924
fastq-dump --gzip --split-files SRR14301925
```

I remember it worked well before.... Or is there any wrong parameter?

Thank you  in advance!!! :)

**Comment by klymenko** [comment]
[Download the latest toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).

**Comment by dahun73** [comment]
> [Download the latest toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).

Thank you for reply :)
