### ISSUE TITLE
Allow Runs in Projects For Download To Be Specified

### ISSUE THREAD

**Issue by DarioS** [ncbi/sra-tools#65]
If there's a dataset with two kinds of samples (e.g. tissue and cell line) and only runs of one type of sample need to be downloaded, there doesn't seem to be a way to do this. The help pages of the sofware [aren't particularly useful](https://edwards.sdsu.edu/research/fastq-dump/), so maybe it's possible and just not documented. Either way, the user experience could be improved.

**Comment by kwrodarmer** [comment]
You're welcome to offer suggestions!

**Comment by DarioS** [comment]
It would be convenient if an invocation such as `$ fastq-dump SRR1768821:SRR1768953` worked by getting all of the runs in the range of IDs specified or if `$ fastq-dump /home/dario/sequencing/SRA_ACC_List.txt` got all the runs in the single-column table downloaded from [SRA Run Selector](https://www.ncbi.nlm.nih.gov/Traces/study/?go=home) by clicking on the Accession List button.

**Comment by seandavi** [comment]
I have tended to rely on linux-like tooling for this kind of automation
because of its inherent flexibility. Perhaps that approach is a viable
alternative?

**Comment by kwrodarmer** [comment]
perhaps
`fastq-dump $(cat /home/dario/sequencing/SRA_ACC_List.txt)`

Many of our other tools support an option `--option-file xyz` but fastq-dump is among the oldest and does not share the same command line processing code. Still, the Unix command `cat` works fine.

**Comment by DarioS** [comment]
sra-tools is available from Linux, MacOS and Windows. It'd be nice if sra-tools didn't depend on the operating system's shell commands in this case.
