### ISSUE TITLE
"fasterq-dump" version 3.0.0 exit code 3

### ISSUE THREAD

**Issue by RichardCorbett** [ncbi/sra-tools#650]
Hi there.

I used prefetch to first download my sra files"
`cat ../SRR_Acc_List.txt | xargs -i echo "prefetch -p -v  -X 2000000000 -O . {}" | parallel -j 8 --eta`

Some of these SRA files can be converted to .fastq without error or warning, for example:
```
fasterq-dump -v --split-files SRR18145555.sra 
Preference setting is: Prefer SRA Normalized Format files with full base quality scores if available.
spots read      : 127,942,138
reads read      : 127,942,138
reads written   : 127,942,138
```

But others get this report:
```
fasterq-dump -v --split-files SRR18145539.sra
Preference setting is: Prefer SRA Normalized Format files with full base quality scores if available.
2022-06-08T22:30:54 fasterq-dump.3.0.0 err: fasterq-dump.c fastdump_csra() checking ouput-file '/projects/vendor_data/Ultima/fastqs_downloaded/manual_download/SRR18145539/SRR18145539.fastq' -> RC(rcExe,rcFile,rcPacking,rcName,rcExists)
fasterq-dump quit with error code 3
```

Is there something I can check or modify with my commands to convert the latter sample to .fastq?

thanks,
Richard

**Comment by durbrow** [comment]
Is your list of accessions unique? If there are duplicates, they would both try to create the same output files.

**Comment by RichardCorbett** [comment]
Yes, Here is my list of you are interested:
```
SRR18145538
SRR18145539
SRR18145540
SRR18145541
SRR18145542
SRR18145543
SRR18145544
SRR18145545
SRR18145546
SRR18145547
SRR18145548
SRR18145549
SRR18145550
SRR18145551
SRR18145552
SRR18145553
SRR18145554
SRR1814555
```

**Comment by RichardCorbett** [comment]
Could my error be showing up because there are already fastq files in the folder and it doesn't want to overwrite them?

**Comment by wraetz** [comment]
Another problem: 'fasterq-dump -v --split-files SRR18145555.sra'.
You specify the SRRXXXXXX.sra -file. That leads to problems. The prefetch-tool created a directory for the accession. You should copy/use that directory not a file inside it:

$fasterq-dump /path/to/prefetched/SRRXXXXXX ... good
$fasterq-dump /path/to/prefetched/SRRXXXXXX/SRRXXXXXX.sra ... bad
