### ISSUE TITLE
only one fastq produced

### ISSUE THREAD

**Issue by Biofarmer** [ncbi/sra-tools#651]
Hi, 
1. I am using sra-tools version 2.11.0 to download sra file from one study and then transfer to fastq (command: fasterq-dump SRRXXX). The majority of samples worked well, however, there were 16 samples (out of 228) that failed to transfer from sra to fastq, i.e. only one fastq produced. The samples are "
SRR14306867
SRR14306874
SRR14306889
SRR14306895
SRR14306903
SRR14306907
SRR14306912
SRR14306927
SRR14306928
SRR14306934
SRR14306935
SRR14306940
SRR14306942
SRR14306931
SRR14321957
SRR14368362"
May I ask whether this is due to the files itself or the software? Thanks

2. In addition, may I ask the position of SRR file affects the fasterq-dump results? For example, whether command "fasterq-dump **SRRXXX** --threads 10 --split-3 --skip-technical --print-read-nr --mem 1G --outdir xxx" and "fasterq-dump --threads 10 --split-3 --skip-technical --print-read-nr --mem 1G --outdir xxx **SRRXXX**" will produce the exact same fastq files?
Thanks

**Comment by Biofarmer** [comment]
> 1. `--split-3` does not guarentee that 3 files **will** be produced, you may get 1 (`*.fastq` with unpaired reads), 2 (`*_1.fastq` and `*_2.fastq` with paired reads), or 3 (`*_1.fastq` and `*_2.fastq` with paired reads, and `*.fastq` with unpaired reads) depending on the data. The data may have only one read per spot, in which case you would only get 1 file. For example, SRR14306867 has only one read per spot. See https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR14306867 If you have reason to believe that SRR14306867 should have more reads per spot, please email [sra@ncbi.nlm.nih.gov](mailto:sra@ncbi.nlm.nih.gov) and let the SRA curators know. They can get it fixed.
> 2. The parameters are not positionally processed. Our command line processing operates on the entire command line as a unit. All parameters (and their arguments) are acted on and then the accession(s) are processed in the order they were given. For example, you can type out a command and put `--help` at the end, and all the tool will do is print out the help text.

Hi, thanks for your reply. I think the sra I mentioned should have forward and reverse fastq, and I will ask SRA curators. As for question 2, can I understand simply that there is no difference in fastq files from the two commands I mentioned? 
Thanks

**Comment by Biofarmer** [comment]
Sorry, may I know whether I understand correctly?

**Comment by durbrow** [comment]
There should be no difference. If you see a difference (and it is reproducible), then it is a bug.

**Comment by xutongran** [comment]
HI, I met the same problems , i would like to know how did you solve this problems?
