### ISSUE TITLE
error certificates 

### ISSUE THREAD

**Issue by wk1267** [ncbi/sra-tools#660]
I was following the manual to install sratoolkit on mac as in https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit.
I have passed step 4 which gave me:
/Users/User1/opt/anaconda3/envs/sratool/bin/fastq-dump
I have configured as in step 5, but when testing in step 6, I faced the following error:
running `fasterq-dump --stdout SRR390728 | head -n 8` gives 
`fastq-dump.2.11.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  ) Failed to call external services.
`
Apologies if this is a very trivial problem; I am quite new to this framework. Thanks!

**Comment by pingguoilove** [comment]
Have you solved this problem？ @wk1267
