### ISSUE TITLE
prefetch error: "path invalid while opening directory within file system module - could not build vfs-resolver"

### ISSUE THREAD

**Issue by afowler56** [ncbi/sra-tools#666]
Hello,

I am attempting to download RNA-seq read files from an approved access request through dbGaP using SRA Toolkit.  I followed the install instructions for SRA Toolkit found here (https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit) and the download instructions found here (https://www.ncbi.nlm.nih.gov/books/NBK570248/#Dwnld_DownloadData.Download_Procedure) and here (https://www.ncbi.nlm.nih.gov/sra/docs/sra-dbgap-download/). 

After downloading the dbGaP repository key and the cart file from SRA, I used the following code in Command Prompt on my desktop computer, which runs MS Windows 10 (file names have been modified for confidentiality reasons):
`C:\Users\afowler\Desktop\sratoolkit.3.0.0-win64\bin>prefetch --ngc /Users/afowler/Desktop/ngc_file.ngc /Users/afowler/Desktop/cart_file.krt `

And received the following output:
```
2022-06-28T20:50:41 prefetch.3.0.0 warn: libs/kfs/win/sysdir.c:842:KSysDirMakeSimulatedFSPath: path invalid while opening directory within file system module - could not build vfs-resolver
2022-06-28T20:50:41 prefetch.3.0.0 int: libs/vfs/manager.c:3218:VFSManagerGetResolver: tree NULL while accessing manager within virtual file system module – VFSManagerGetResolver
```

I would appreciate any advice you may have.

Thank you!

**Comment by afowler56** [comment]
Already did! They didn't really know how to help me, so I just wanted to cover all my bases by asking here as well. 

Thanks!

**Comment by afowler56** [comment]
case #CAS-915667-Y4G1Q7

**Comment by cmatKhan** [comment]
Getting the same error -- was there any useful resolution to this?

**Comment by klymenko** [comment]
@cmatKhan, email to [sra-tools@ncbi.nlm.nih.gov](mailto:sra-tools@ncbi.nlm.nih.gov).

**Comment by klymenko** [comment]
Could you try our latest release?
Do you still have this problem?

**Comment by cmatKhan** [comment]
I emailed the helpdesk back in February and somehow this was resolved, I believe on the server end. My submission cmd remained the same, but it started working after emailing.

I think I have the data that I have been asked to gather at this point, but the next time I need to pull data I'll make sure to update
