### ISSUE TITLE
Typo in Taxomony analysis page

### ISSUE THREAD

**Issue by CatChenal** [ncbi/sra-tools#668]
This page https://www.ncbi.nlm.nih.gov/sra/docs/sra-taxonomy-analysis-tool/ has a typo under its "Frequently Asked questions" section.

This question:
```
Are all SRA Runs analyzed using the course and fine databases?
```
should be:
```
Are all SRA Runs analyzed using the coarse and fine databases?
```
PS: I could not find who is responsible for producing the page, hence this issue.

**Comment by klymenko** [comment]
Send a message to sra@ncbi.nlm.nih.gov.
