### ISSUE TITLE
Naming conflict with glibc 2.25 "canonicalize"

### ISSUE THREAD

**Issue by rekado** [ncbi/sra-tools#67]
Building sra-tools 2.8.2-1 on a system with glibc 2.25 fails because of a naming conflict.  `tools/bam-loader/bam.c` contains a definition of `canonicalize` that does not match the definition of `canonicalize` in the file `include/bits/mathcalls.h` provided by glibc 2.25.

A simple work-around is to rename `canonicalize` in `tools/bam-loader/bam.c` to something else, e.g. `sra_tools_canonicalize`.

**Comment by kwrodarmer** [comment]
We will rename it, thanks for the alert!

**Comment by rekado** [comment]
I believe this is still a problem (https://github.com/ncbi/sra-tools/blob/1fd466169f64ed9249fb827c8b374a56ba41dd30/tools/bam-loader/bam.c#L4000), or am I overlooking the fix?

**Comment by kwrodarmer** [comment]
The fix is in our engineering branch - will be released to master soon. My apologies for the trigger finger.

**Comment by klymenko** [comment]
@rekado , was your issue fixed?
