### ISSUE TITLE
SRA archived only R2 reads in bam from a scRNA dataset

### ISSUE THREAD

**Issue by zyh4482** [ncbi/sra-tools#670]
https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR7586091&display=data-access

According to the record, the original data is a bam file. In metadata, it only contains one 98bp read. Where is the I1 and R1? The length is quite similar to the read length of R2 in a 10x 3' library. It seems SRA only provide R2 read in the bam instead of all reads. Is there a workaround?

**Comment by durbrow** [comment]
Please email sra@ncbi.nlm.nih.gov with questions regarding the SRA data.
