### ISSUE TITLE
vdb-decrypt: storage exhausted while writing file within file system module

### ISSUE THREAD

**Issue by daniel-hui** [ncbi/sra-tools#673]
I am trying to use vdb-decrypt to access a file that is 810G. I've able to use vdb-decrypt to access all files needed with suffix "ncbi_enc" except for this one. When I try to use vdb-decrypt for this file I get the messages:

```
#2022-07-06T22:33:07 vdb-decrypt.3.0.0: Decrypting file in place phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc
#2022-07-06T22:33:07 vdb-decrypt.3.0.0: copying phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc to .phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc.vdb-decrypt-tmp
#2022-07-06T23:34:16 vdb-decrypt.3.0.0 err: storage exhausted while writing file within file system module - system bad file descriptor error fd='4'
#2022-07-06T23:34:16 vdb-decrypt.3.0.0 err: storage exhausted while writing file within file system module - Failed to write to file .phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc.vdb-decrypt-tmp at 595722502144
#2022-07-06T23:34:16 vdb-decrypt.3.0.0: exiting: RC(rcFS,rcFile,rcWriting,rcStorage,rcExhausted) (841353875)
```

where "phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc" is the file I'm trying to access. I run vdb-decrypt like:

`~/sratoolkit.3.0.0-centos_linux64/bin/vdb-decrypt.3.0.0 --ngc prj_27904_D29838.ngc phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc
`

I just downloaded sratoolkit yesterday. I tried multiple file locations for "phg001013.GERA.genotype-imputed-data.c1.HMB-IRB-NPU.tar.gz.ncbi_enc", where there is ample disk space. Any help is appreciated, thanks.

**Comment by klymenko** [comment]
You are out of disk space.
