### ISSUE TITLE
One single file only from Fasterq-dump from pair end sequencing

### ISSUE THREAD

**Issue by Fdm8610** [ncbi/sra-tools#675]
Hi 
I download SRR9604257.sra and all the other sra files (up to n266) of the same project which should be pair end sequencing using prefetch 3.0.0.

I then used fasterq-dump 3.0.0: I alway obtain one single fastq file from each .sra. 
Shouldn't I get at list 2 or 3 file since split 3 is in fasters-dump?  I tried to also use --include-technical but I always get ONE single fastq file.

Is this correct? Anyone knows what's happening and if I could proceed with cellranger with these single fastq generated?

Thank you

**Comment by howtofindme** [comment]
> Hi I download SRR9604257.sra and all the other sra files (up to n266) of the same project which should be pair end sequencing using prefetch 3.0.0.
> 
> I then used fasterq-dump 3.0.0: I alway obtain one single fastq file from each .sra. Shouldn't I get at list 2 or 3 file since split 3 is in fasters-dump? I tried to also use --include-technical but I always get ONE single fastq file.
> 
> Is this correct? Anyone knows what's happening and if I could proceed with cellranger with these single fastq generated?
> 
> Thank you

hi， have you solved it? the same problems
