### ISSUE TITLE
download on demand doesn't use minSpotId and maxSpotId?

### ISSUE THREAD

**Issue by rec3141** [ncbi/sra-tools#68]
using the example provided

```
fastq-dump --stdout -X 2 SRR390728
```

should do download-on-demand, which I would expect to be very small. however it appears to fetch the entire fastq and then only output the first two sequences because I see a 194Mb file in the cache. Is this how it is supposed to work?

```
ls -l ~/ncbi/public/sra/SRR390728.sra.cache
-rw-rw-r-- 1 manager manager 193615662 Apr  5 18:50 /home/manager/ncbi/public/sra/SRR390728.sra.cache
```

**Comment by kwrodarmer** [comment]
Please see https://github.com/ncbi/sra-tools/wiki/Download-On-Demand, which explains how download on-demand works.

The cache files are sparse, and appear to take up the entire size when only occupying the necessary blocks. Note that at this time the Mac is not supporting sparse files, and we are going to supply a workaround, but Linux and even Windows does support them.

**Comment by rec3141** [comment]
I'm afraid I'm still confused, because the cache files "appear to" have filled up my hard disk on Linux, so are you saying it generates a 194Mb file that is totally empty except for 2 sequences? (hexdump suggests otherwise). How much actually goes across the network in a case like the example given? thanks

**Comment by osris** [comment]
the cache file contains only the content necessary to produce the 2 sequences and only this data is transferred across network. if you later run fastq-dump -X 5 SRR390728, the first 2 sequences would be read from the cache and the next 3 pulled from NCBI servers and added to the cache. if you run ls -lsa, the first column shows the actual byte size of the file. du or stat can also show the 'real' size.
________________________________

**Comment by kwrodarmer** [comment]
The system would not work well if it only retrieved the exact bytes needed for two sequences and nothing more. It retrieves 128K pages of the original file, only the necessary pages, but these pages may contain a few more sequences than were originally requested.

If you run `cache-mgr -r` it will tell you how many bytes are actually used.

**Comment by rec3141** [comment]
Great, thank you, I see that it pulls down
