### ISSUE TITLE
Cannot decrypt .ncbi_enc

### ISSUE THREAD

**Issue by ded1112** [ncbi/sra-tools#686]
Hi, I am running into issues for decrypting a dbGap dataset downloaded via Aspera connect. I have the project and also my repository key:

![image](https://user-images.githubusercontent.com/110183294/181568126-a801e5fe-1264-42ea-8182-2ba9c0be4181.png)

OS: Windows 64
SRA Toolkit Version: Latest 3.0.0

**Comment by klymenko** [comment]
Please post the output of the following commands:
```
dir prj_25042.ngc
certutil -hashfile prj_25042.ngc MD5
```

**Comment by ded1112** [comment]
Here's the output:

![image](https://user-images.githubusercontent.com/110183294/181584903-3e2cda69-418c-48cf-bafb-95382e7e5e96.png)


I had to shift the project key into the bin folder. Does the data downloaded need to be in the bin folder too?

**Comment by klymenko** [comment]
It is not recommended.
Better add bin folder to your PATH: `set PATH=M:\PROJECTS\...\sratoolkit.3.0.0-win63\bin;%PATH%`
Then `cd` to directory with data and run `vdb-decrypt --ngc <PATH TO NGS> <FILES TO DECRYPT>`

**Comment by ded1112** [comment]
Added the two commands:
![image](https://user-images.githubusercontent.com/110183294/181589733-aa900f5d-2c1a-4f9e-b17f-1e74163f7589.png)

On running, it gives me this error:
![image](https://user-images.githubusercontent.com/110183294/181590025-b1872b9e-d743-49f9-bdc8-25c3f50d8821.png)

**Comment by klymenko** [comment]
Don't use `<` and `>` in your commands.

**Comment by ded1112** [comment]
Can you see the edited version of the comment:
![image](https://user-images.githubusercontent.com/110183294/181590695-dd72c0db-907e-428e-a01a-5dc638faeed2.png)

**Comment by klymenko** [comment]
Run `echo %PATH%`

**Comment by ded1112** [comment]
![image](https://user-images.githubusercontent.com/110183294/181591393-c400343d-99b2-4a85-99fb-c50a7dab5229.png)

**Comment by klymenko** [comment]
Can you execute vdb-decrypt without arguments from data directory?

**Comment by ded1112** [comment]
The vdb-decrypt is in the sratoolkit which is in  %PATH% and the directory is set in the folder with the downloaded data 

![image](https://user-images.githubusercontent.com/110183294/181592574-e8569b2d-3dcd-424d-abb3-7f98152a4711.png)

**Comment by klymenko** [comment]
Not `dir vdb-decrypt`; just `vdb-decrypt`

**Comment by klymenko** [comment]
Sorry, I typed `sratoolkit.3.0.0-win63` in set PATH command.
It's `sratoolkit.3.0.0-win64`.

**Comment by ded1112** [comment]
Okay, fixed that and reran:

`M:\PROJECTS\DIKHA\AREDS2\AREDS2 ERD 2022\88494\PhenoGenotypeFiles\ChildStudyConsentSet_phs000429.AREDS.v1.p1.c1.EDO\PhenotypeFiles>set PATH=M:\PROJECTS\DIKHA\AREDS2\sratoolkit.3.0.0-win64\bin;%PATH%

M:\PROJECTS\DIKHA\AREDS2\AREDS2 ERD 2022\88494\PhenoGenotypeFiles\ChildStudyConsentSet_phs000429.AREDS.v1.p1.c1.EDO\PhenotypeFiles>vdb-decrypt

Usage:
  vdb-decrypt [options] <source-file>
  vdb-decrypt [options] <source-file> <destination-file>
  vdb-decrypt [options] <source-file> <destination-directory>
  vdb-decrypt [options] <directory>

Summary:
  Decrypt a file or all the files (recursively) in a directory


Use option --help for more information.

2022-07-28T16:54:34 vdb-decrypt.3.0.0: exiting: success

M:\PROJECTS\DIKHA\AREDS2\AREDS2 ERD 2022\88494\PhenoGenotypeFiles\ChildStudyConsentSet_phs000429.AREDS.v1.p1.c1.EDO\PhenotypeFiles>vdb-decrypt --ngc %PATH% phs000429.v1.pht002481.v1.p1.c1.areds_data_final_11.EDO.txt.gz.ncbi_enc
2022-07-28T16:54:56 vdb-decrypt.3.0.0 err: no error - too many parameters

Usage:
  vdb-decrypt [options] <source-file>
  vdb-decrypt [options] <source-file> <destination-file>
  vdb-decrypt [options] <source-file> <destination-directory>
  vdb-decrypt [options] <directory>

Summary:
  Decrypt a file or all the files (recursively) in a directory


Use option --help for more information.

2022-07-28T16:54:56 vdb-decrypt.3.0.0: exiting: success`

**Comment by klymenko** [comment]
Replace `%PATH%` in your command with the real path to your ngc file.

**Comment by ded1112** [comment]
It worked! Thank you so much :)
![image](https://user-images.githubusercontent.com/110183294/181595852-8a72bec8-ad36-4371-992b-0161dedae8de.png)

Do I now change directory for all the datasets and decrypt them one by one?

**Comment by klymenko** [comment]
You can specify `vdb-decrypt *` to decrypt all files in your current directory.
Or `vdb-decrypt DIRECTORY` to decrypt all the files recursively in DIRECTORY.

**Comment by ded1112** [comment]
Thank you so much for all your help
