### ISSUE TITLE
How should I run tests in the source code: sra-tools / tools/

### ISSUE THREAD

**Issue by HuangseYuanli** [ncbi/sra-tools#687]
I tried to execute the script in the file, but all failed，Can I think that if the scripts in the bin file can be executed, it proves that the SRA tool installation is successful.

**Comment by klymenko** [comment]
How did you install the toolkit?

**Comment by HuangseYuanli** [comment]
I successfully installed sra-tools on the arm architecture, and the files in the sra-tools /linux/gcc/arm64/rel/bin directory can be executed, but I execute the file in the test directory in the source code: sra-tools-3.0.0/test/copycat/test-copy.sh, which appears:

testing copycat copy
test-copy.sh: line 10: /copycat: No such file or directory
copycat copy failed, res=127 output=

Therefore, I am not sure whether I have successfully installed this tool. I don't know how to test all the functions of the tool.

**Comment by klymenko** [comment]
This test is meant to run by make.

In your case, run the following command:
`fastq-dump --stdout -X 2 SRR390728`
It is expected to produce 2 spots for SRR390728.

**Comment by HuangseYuanli** [comment]
Thanks！
