### ISSUE TITLE
Documentation of "kart" file

### ISSUE THREAD

**Issue by chkcole** [ncbi/sra-tools#69]
Hello, this isn't a software issue per se.
However, I can't seem to find documentation on the kart format either here or on NCBI.
I'm currently in the process of downloading some single cell mRNA data and I would like to be able to pass prefetch a manifest instead of calling the program once per SRR.

Any guidance would be appreciated.

**Comment by klymenko** [comment]
@chkcole , you can proved multiple SRR-s or use "--option-file <file>" option
