### ISSUE TITLE
prefetch SRR files failed

### ISSUE THREAD

**Issue by Seraph-009** [ncbi/sra-tools#693]
Hi, recently, I prefetch(version 3.0.0 ) SRR8956151 from ncbi, however, there is the hint " Current preference is set to retrieve SRA Normalized Format files with full base quality scores." 
what dose this mean? how can I download files?

**Comment by klymenko** [comment]
See announcement for `October 7, 2021. SRA Toolkit 2.11.2` in https://github.com/ncbi/sra-tools/blob/master/README.md
