### ISSUE TITLE
fasterq-dump is sometimes not deleting fastq fiels after compressing

### ISSUE THREAD

**Issue by gernophil** [ncbi/sra-tools#699]
Hey,
I downloaded some .fastq.gz files (using the fasterq-dump snakemake wrapper) and I realized that sometimes the original .fastq files are deleted and sometimes they remain in the download folder after gz compression. How can I be sure that my compressed gz files are complete though?

**Comment by durbrow** [comment]
`snakemake` is not ours and we don't maintain it. You could ask the people who made it.

> How can I be sure that my compressed gz files are complete though?
At a minimum, you will need to decompress, parse, and analyze. You can probably get by with using `gzcat` to decompress to stdout, but the parse and analyze is up to you. I would suggest at least counting the bases and comparing it to what the [SRA run browser](https://www.ncbi.nlm.nih.gov/Traces/sra/?view=run_browser) gives. (FWIW, the FASTQ from `fasterq-dump` is very regular, each read has exactly 4 lines, and the sequence is always the second line of each read.)
