### ISSUE TITLE
10x SRA files not correctly converted to fastq

### ISSUE THREAD

**Issue by royfrancis** [ncbi/sra-tools#701]
As an example; SRR17102621 creates 3 files (which is correct) with this code

```
fastq-dump -F --split-files SRR17102621
```

while all these variations of `fasterq-dump` produces just 1 file

```
fasterq-dump -O . --threads 6 --mem 24G --split-3 --skip-technical --print-read-nr --progress SRR17102621
fasterq-dump -O . --threads 6 --mem 24G --split-files SRR17102621
fasterq-dump --split-files SRR17102621
```

Now this example; SRR10419617, both tools produce 2 fastq files while I should get 3 (I think).

Perhaps, I could be doing something wrong.

`sratools/2.10.9`

**Comment by durbrow** [comment]
Unlike `fastq-dump`, `--skip-technical` is the default for `fasterq-dump`. What you are seeing is most likely caused by that. For example, SRR17102621 has two technical reads and one biological read, so `fasterq-dump` will produce only one file by default, and `fastq-dump` will also produce only one file if you were to run it with `--skip-technical`.

**Comment by durbrow** [comment]
In general, if you want to see what is in the SRA, there is a data browser on NCBI's website, e.g. for [SRR10419617](https://www.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&page_size=10&acc=SRR10419617&display=reads) it shows two reads. If you know this is in error, you should contact the data curation team at sra@ncbi.nlm.nih.gov, this repo is just the software.

**Comment by royfrancis** [comment]
So, is it possible to skip `--skip-technical` and get the 3 separate files using `fasterq-dump`?

**Comment by durbrow** [comment]
Yes, try `--include-technical`

**Comment by royfrancis** [comment]
Ok. Finally, it works! Thanks @durbrow 

To add, it only works when `--split-files` is used. It doesn't work if `--split-3` is used.

For those who are lost and found their way here, this seems to work for the "good" 10x SRA files.

`fasterq-dump --threads 10 --mem 24G --split-files --include-technical --print-read-nr --progress SRR17102621`

_sratools/2.10.9_

**Comment by durbrow** [comment]
You should upgrade, that version has a typo.
