### ISSUE TITLE
fastq-dump.3.0.0 sys: connection unexpected ERR

### ISSUE THREAD

**Issue by Dhohadh** [ncbi/sra-tools#709]
I'm trying to download some SRA files but when I run the following command 
 
fastq-dump --stdout -X 2 SRR390728

to verify that the toolkit is functional, I still get the same message:

connection unexpected while executing query within virtual file system module - can't open NC_000010.9 as a RefSeq or as a WGS
2022-08-27T06:14:57 fastq-dump.3.0.0 err: connection unexpected while executing query within virtual file system module - failed SRR390728

Does someone have any suggestions or solutions? Thank you.

**Comment by klymenko** [comment]
What is the output of the following?
`curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=NC_000010.9`

**Comment by jawi005** [comment]
I get a similar error: .3.0.0 err: item not found while constructing within virtual database module - the path 'SRR390728' cannot be opened as database or table

if I run the output of: curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=NC_000010.9 

it gives me back:
{
    "version": "2",
    "result": [
        {
            "bundle": "NC_000010.9",
            "status": 200,
            "msg": "ok",
            "files": [
                {
                    "object": "refseq|NC_000010.9",
                    "accession": "NC_000010.9",
                    "type": "sra",
                    "name": "NC_000010.9",
                    "size": 33081323,
                    "md5": "428e52dd4722c73f8bd1f5c2948303bb",
                    "modificationDate": "2018-02-22T18:21:29Z",
                    "locations": [
                        {
                            "service": "sra-ncbi",
                            "region": "public",
                            "link": "https://sra-download.ncbi.nlm.nih.gov/traces/refseq/NC_000010.9"
                        }
                    ]
                }
            ]
        }
    ]
}
