### ISSUE TITLE
randomly missing SAM UB and CB tags and incorrect SAM FLAG field in SRA file SRR19653202

### ISSUE THREAD

**Issue by dariomel** [ncbi/sra-tools#711]
I have been examining the data deposited to SRA with accession number [SRR19653202](https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR19653202&display=data-access). In particular, I have compared the SRA file to the original BAM file. I was expecting the SAM alignment records in the SRA file to match consistently the corresponding records in the BAM file. Instead, I found that the UB and CB SAM tags are missing from many SAM records in the SRA file, while those tags are present in the original BAM file. This omission of UB and CB tags seems to occur randomly. Because the BAM file was produced from a single-cell transcriptomic library, the consistent presence of UB and CB SAM tags in the SRA file is essential for meaningful downstream analysis of the read alignments. Because the particular SRA file examined is part of a large set associated with project [PRJNA831566](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA831566), it is possible that other SRA files in that project contain similar defects. The following are specific details about the discrepancies found between the SRA file in question and the original BAM file.

The SRA file was downloaded using the SRA Toolkit prefetch command, version 2.10.8. The corresponding BAM file was downloaded using wget with URL https://sra-pub-src-1.s3.amazonaws.com/SRR19653202/KD8_p1_36_possorted_genome_bam.bam.1. Both files were downloaded on 8/24/2022. The files were examined using samtools view, version 1.15.1, and the SRA Tooklit sam-dump command, version 3.0.0.
The BAM file was found to contain 801636577 SAM records, of which 739474211 are aligned segments:
```bash
samtools view -c KD8_p1_36_possorted_genome_bam.bam.1
801636577
```
```bash
samtools view -F4 -c KD8_p1_36_possorted_genome_bam.bam.1 # omit unaligned
739474211
```
The number of SAM records in the SRA file was found to match the number of records for aligned segments in the BAM file:
```bash
sam-dump -n SRR19653202.sra | wc -l
739474211
```
Corresponding SAM records in the two files were compared using a [custom Perl script](https://github.com/ncbi/sra-tools/files/9448337/cmpsrabam.zip). For each SAM record in the SRA file, the SAM fields 2 (FLAG) through 11 (QUAL) were found to be identical to the corresponding fields in the corresponding record in the BAM file, with the exception that the FLAG field was found to differ in 444310 records in the SRA file. The following is an example of such a discrepancy, where the FLAG field is 1536 in the BAM file, but is 1024 in the SRA file:
```bash
sam-dump -n SRR19653202.sra|grep -m1 '^1168590'
1168590    1024    chr1    778950    255    29S69M    *    0    0    CCAGTGGAATCAACGCAGAGTACATGGGGAGACTCTGCGCTAGCAGGCGCTGCGCGCCAACCGGCCGGCACCTGTCGCAGAAGGAGCAACCGATCGCA    ,FFF,,F,F,F:,,:,F:F,FFFFF:,,,FFF:F::,:F,,FFFF,,,,FFFFF,F:F:F:F,::FF,FF::FF:,,FF,FF,F,FFF:F,FF,F,F:    RG:Z:p1_36:0:1:HLKKGDSXY:2    CB:Z:GACAGCCGTCGTATTG-1    UB:Z:CCGAGGGCTCAA    NH:i:1    NM:i:1
```
```bash
samtools view KD8_p1_36_possorted_genome_bam.bam.1|head -n1168590|tail -n1
A00351:398:HLKKGDSXY:2:2425:30707:9079    1536    chr1    778950    255    29S69M    *0    0    CCAGTGGAATCAACGCAGAGTACATGGGGAGACTCTGCGCTAGCAGGCGCTGCGCGCCAACCGGCCGGCACCTGTCGCAGAAGGAGCAACCGATCGCA    ,FFF,,F,F,F:,,:,F:F,FFFFF:,,,FFF:F::,:F,,FFFF,,,,FFFFF,F:F:F:F,::FF,FF::FF:,,FF,FF,F,FFF:F,FF,F,F:    NH:i:4    HI:i:2    AS:i:65    nM:i:1    ts:i:28    RG:Z:p1_36:0:1:HLKKGDSXY:2    TX:Z:ENST00000412115,+203,29S69M;ENST00000429505,+190,29S69M;ENST00000434264,+180,29S69M;ENST00000457084,+168,29S69M;ENST00000589899,+20,29S69M;ENST00000609830,+13,29S69M;ENST00000651411,+101,29S69M;ENST00000655765,+203,29S69M;ENST00000656571,+148,29S69M;ENST00000657896,+190,29S69M;ENST00000658648,+154,29S69M;ENST00000665719,+138,29S69M;ENST00000665867,+141,29S69M;ENST00000666217,+138,29S69M;ENST00000669749,+141,29S69M;ENST00000670700,+192,29S69M    GX:Z:ENSG00000237491    GN:Z:LINC01409    fx:Z:ENSG00000237491    RE:A:E    MM:i:1    xf:i:17    CR:Z:GACAGCCGTCGTATTG    CY:Z:F,FFFFFFFFFFF::F    CB:Z:GACAGCCGTCGTATTG-1    UR:Z:CCGAGGGCTCAA    UY:Z:FFFFFF:FFFFF    UB:Z:CCGAGGGCTCAA
```
The BAM file was found to contain 735732168 SAM records that include the UB tag. Of the corresponding records in the SRA file, 17277801 were found to lack the UB tag. The following is an example of such discrepancy:
```bash
samtools view KD8_p1_36_possorted_genome_bam.bam.1|head -n4|tail -n1
A00351:397:HLKJCDSXY:1:1508:11894:30859    0    chr1    10016    1    91M7S    *0    0    CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAAATGAC    FFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFF:FF:FFF:FFFF,:FFFF::FFFF,FF:FF,:,,,,:,    NH:i:3    HI:i:1    AS:i:89    nM:i:0    RG:Z:p1_36:0:1:HLKJCDSXY:1    RE:A:I    xf:i:0    CR:Z:TAGGGTTAGGGTTAGG    CY:Z:,F,,FFFF,FF:,F,F    UR:Z:GTTAGGGTTAGG    UY:Z::FFFFF:FFF,F    UB:Z:GTTAGGGTTAGG
```
```bash
sam-dump -n /opt/archive/ref/sra/SRR/SRR196/SRR19653202.sra|head -n4|tail -n1
4    0    chr1    10016    1    91M7S    *    0    0    CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAAATGAC    FFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFF:FF:FFF:FFFF,:FFFF::FFFF,FF:FF,:,,,,:,    RG:Z:p1_36:0:1:HLKJCDSXY:1    NH:i:1    NM:i:0
```
Similarly, the BAM file was found to contain 721837594 records that include the CB tag. Of the corresponding records in the SRA file, 3383227 were found to lack the CB tag. The following is an example of such discrepancy:
```bash
sam-dump -n SRR19653202.sra|head -n22|tail -n1
22    16    chr1    10543    3    67M31S    *    0    0    GAAATCCGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACCCCCATGTACTCTGCGTTGATACCACTGCTT    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF    RG:Z:p1_36:0:1:HLKJCDSXY:3    NH:i:1    NM:i:2
```
```bash
samtools view KD8_p1_36_possorted_genome_bam.bam.1|head -n22|tail -n1
A00351:397:HLKJCDSXY:3:2650:27588:22717    16    chr1    10543    3    67M31S    *0    0    GAAATCCGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACCCCCATGTACTCTGCGTTGATACCACTGCTT    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF    NH:i:2    HI:i:1    AS:i:61    nM:i:2    ts:i:30    RG:Z:p1_36:0:1:HLKJCDSXY:3    RE:A:I    xf:i:0    CR:Z:TGCGACGTCCATGAGT    CY:Z:FFFFFFFFFFFFFFFF    CB:Z:TGCGACGTCCATGAGT-1    UR:Z:GATTTANATTAT    UY:Z:FFFFFF#FFFFF
```
The main questions here are: why are the SAM UB and CB tags randomly missing from the SRA file, and why is the FLAG field not always equal to the value in the original BAM file? 
I initially submitted the foregoing problem description to the [NLM Support Center](https://support.ncbi.nlm.nih.gov/ics/support/default.asp), and it was promptly dismissed with the response: "SRA does not save all custom bam fields and the fields of interest for 10X change over time". But if the policy of SRA is really not to "save all custom bam fields", then why is it that the vast majority of records in the SRA file do include the UB and CB tags? Wouldn't it make more sense, and be less misleading, to omit those tags from all records in the SRA file? Also, the NLM Support response did not address the discrepancies found in the FLAG field. If I had to guess, I'd say there is some bug in the tool (perhaps bam-load?) that was used to generate the SRA file from the BAM file. Or perhaps the bug is in sam-dump?

**Comment by durbrow** [comment]
As far as SAM FLAG bits is concerned, SRA considers considers some of the bits to be redundant. In your example, the SAM file has 1536 and the SRA file 1024. These correspond respectively to 512+1024 (bit 9 + bit 10) and 1024 (bit 10). From SAM spec, bit 9 is:

> not passing filters, such as platform/vendor quality controls

and bit 10 is:

> PCR or optical duplicate

The SRA data model (which must apply equally to ALL the run data in the SRA) considers these two states to mean the same thing: The read (and its mate) should be filtered out.

As far as CB/UB tags, SRA expects both or it stores neither.
