### ISSUE TITLE
prefetch: cannot open remote file: https://https://sra-download.be-md.ncbi.nlm.nih.gov/vast/sra01/SRR/020880/SRR21381251

### ISSUE THREAD

**Issue by enricorox** [ncbi/sra-tools#713]
Hi! I'm trying to download SRR21381251 with the command `prefetch --progress SRR21381251` and got this:
> 2022-09-06T21:23:37 prefetch.3.0.0 err: incorrect while parsing path within network system module - Port is '0'
> 2022-09-06T21:23:37 prefetch.3.0.0 int: incorrect while parsing path within network system module - cannot open remote file: https://https://sra-download.be-md.ncbi.nlm.nih.gov/vast/sra01/SRR/020880/SRR21381251

It seems a bug because `https://` is repeated twice but the url is correct. I don't have any custom configuration.

**Comment by klymenko** [comment]
What is the output of the following?
`curl "https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?filetype=run&acc=SRR21381251"`

**Comment by enricorox** [comment]
> What is the output of the following? `curl "https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?filetype=run&acc=SRR21381251"`

This

```
{
    "version": "2",
    "result": [
        {
            "bundle": "SRR21381251",
            "status": 200,
            "msg": "ok",
            "files": [
                {
                    "object": "srapub|SRR21381251",
                    "accession": "SRR21381251",
                    "type": "sra",
                    "name": "SRR21381251",
                    "size": 317372847,
                    "md5": "5970f3ea5be660b6c53ded9fb2f8b775",
                    "modificationDate": "2022-08-31T22:50:33Z",
                    "locations": [
                        {
                            "service": "s3",
                            "region": "us-east-1",
                            "link": "https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR21381251/SRR21381251"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by klymenko** [comment]
Please try your `prefetch` command again.

**Comment by enricorox** [comment]
Now it's working! But why? Server side problem?

**Comment by klymenko** [comment]
Where was a problem in SRA Data Locator that was fixed.
