### ISSUE TITLE
error about Cloning into 'RE2'...

### ISSUE THREAD

**Issue by HuangseYuanli** [ncbi/sra-tools#716]
When compiling, I encountered a problem:
fatal: unable to access 'https://github.com/google/re2.git/': Failed to connect to github.com port 443: Connection timed out
Cloning into 'RE2_'...
fatal: unable to access 'https://github.com/google/re2.git/': Empty reply from server
Cloning into 'RE2'...
-- Had to git clone more than once:
          2 times.
Note: switching to '2021-09-01'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 8e08f47 thread_local support in MinGW seems to be buggy.

How can I solve it，thanks

**Comment by aboshkin** [comment]
One of the components of sra-toolkit (namely, SharQ loader) has a CMake generation-time dependency on an external github project (google/re2) which you do not seem to have access to. We are opening an internal ticket to handle this situation without breaking the build, and the fix should go into the next release. In the meantime, you can try modifying CMake files to suppress building SharQ. Assuming you are on version 3.0.0, edit 2 files: sra-tools/tools/CMakeLists.txt and sra-tools/test/CMakeLists.txt by commenting out the line ''add_subdirectory( sharq )".
Hope this helps.

**Comment by HuangseYuanli** [comment]
Thank you very much for your help，The problem has been solved.
