### ISSUE TITLE
latest sratoolkit m1 mac

### ISSUE THREAD

**Issue by parkjooyoung99** [ncbi/sra-tools#717]
hello, i am trying to download the latest sratoolkit in my imac. 
i have tried setup-yum,sh and setup-apt.sh but they did not work. 
So, i tried tar.gz for mac but m1's architecture is not arm 64, where i could not use it. 

is there any other way to install it in m1 mac?

Thank you!

**Comment by shreyaslabh** [comment]
Their MacOS 64bit Arch toolkit is working on my M1 MBP

**Comment by durbrow** [comment]
We do not have official macOS M1 builds (our build machines are all x86_64). The x86_64 binaries work fine with Rosetta 2. If you **REALLY** need native code, our docker images are multi-architecture.
