### ISSUE TITLE
MD5 does not match in decryption

### ISSUE THREAD

**Issue by bwspitzer-bwh** [ncbi/sra-tools#718]
Hello,

I've made multiple attempts to download and decrypt a set of files from dbGaP using IBM Aspera. On the first attempt, the connection was interrupted and the download was incomplete. On the second attempt, the download appeared to be complete, but when I used sra-tools to decrypt the files ("vdb-decrypt {directory}"), I received the following message for each file:

"err: constraint corrupt while reading file within file system module - MD5 does not match in decryption"

I deleted the directory, downloaded the files again, and attempted to decrypt them again. I got the same error message. In addition, I'm only seeing encrypted data files for two chromosomes, rather than for the full genome.

I have used IBM Aspera and sra-tools to successfully download and decrypt numerous dbGaP files in the past, and I'm using the same procedure that I usually employ. The only difference I'm aware of is the first, failed download. 

If you could explain how I can successfully download and decrypt these files, I would appreciate it very much. Thank you.

Brian Spitzer

**Comment by klymenko** [comment]
@bwspitzer-bwh, send an email to sra@ncbi.nlm.nih.gov

**Comment by klymenko** [comment]
@bwspitzer-bwh , do you need more help?
