### ISSUE TITLE
installation for a multi-user cluster

### ISSUE THREAD

**Issue by nreid** [ncbi/sra-tools#723]
Perhaps this isn't the best place to ask, but I'd like to install an sratools module for users of a large computer cluster, but I don't want to force each user to run vdb-config the first time they use it. We have lots of new users and it's one more hurdle for them to deal with. I'd rather point it to a generic config file with variables set up to write temp files in their home directories. Is this possible? I can't figure this out from the documentation I've read. Thanks.

**Comment by durbrow** [comment]
What you are asking to do is possible. The toolkit looks in `/etc/ncbi` in addition to users' home for configuration. You could use `vdb-config` to set up your configuration file `~/.ncbi/user-settings.mkfg` and then copy (probably want to edit it first, it is text, lines of name=value) that file to `/etc/ncbi/settings.kfg`. When your users run something from the toolkit, it will load that file in addition to any settings users have in their home.

**Comment by klymenko** [comment]
@nreid, do you need more help?

**Comment by nreid** [comment]
No, thank you. This issue can be closed.
