### ISSUE TITLE
fasterq-dump error code 3

### ISSUE THREAD

**Issue by koalabear23** [ncbi/sra-tools#729]
Hi all,

I keep getting error code 3 when running fasterq-dump (I've also tried fastq-dump and get the same error).

I'm running the latest version (3.0.0) and this is the output I get:
spots read      : 326,736,822
reads read      : 326,736,822
reads written   : 326,736,821
reads invalid   : 1
fasterq-dump quit with error code 3

It'll run for several hours and then quit. Any thoughts on what might be the issue?

**Comment by wraetz** [comment]
The one invalid read is probably the reason why the return-code is not 0. What accession are you converting to FASTQ? ( Let me see if I get the same result... ) Did you "prefetch" the accession?

**Comment by koalabear23** [comment]
It's SRR11920851 and yes I prefetched. Thank you!

**Comment by wraetz** [comment]
I just examined the accession: there is a problem with the data itself. There is nothing you can do right now on your side. The problem is this: The reference-data is missing the canonical name. As a result the tools ( prefetch as well as fastq-dump/fasterq-dump ) cannot find the reference. That is also the reason why it runs for such a long time. It tries to resolve the reference-name, fails at that and times out for each single alignment.

**Comment by wraetz** [comment]
just to make sure, the file is correct - can you run md5sum and compare:

**Comment by wraetz** [comment]
I have to take my previous comment about the problem being in the data back. I just run fasterq-dump on the accession you mentioned - and it succeeds without an error!
spots read      : 803,706,955
reads read      : 803,706,955
reads written   : 803,706,955

**Comment by koalabear23** [comment]
Interesting! I wonder why it failed the first time? I've tried running several times

**Comment by dongyiyi** [comment]
Hi,

I got the same error code. I prefetched SPR5088465, and then I got a file in the current directory: SPR5088465/SPR5088465.sra. I tried: fastq-dump --split-3 ./SPR5088465/SPR5088465.sra, and the error code showed up.

No idea.

**Comment by durbrow** [comment]
Our tools use exit code 3 to indicate the lack of success. You need to look at the error messages to see what the cause might be.
