### ISSUE TITLE
fasterq-dump error

### ISSUE THREAD

**Issue by DelongZHOU** [ncbi/sra-tools#737]
Hello,

I'm working with bioproject PRJNA507872 including runs SRR8270301 through SRR8270338 on a hpc and fasterq-dump gives the same error with all samples.

> fasterq-dump.3.0.0 err: string_printf( output-filename ) -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
fasterq-dump quit with error code 3

I've used prefetch to get the data (side note: prefetch stuck during the verification process, has to disable to proceed)

I always have the same error with the following commands, with or without "-3" option or file extension (because I saw the issue with the extension in a previous build)

`fastq-dump -o fastq -e 32 --mem 120G --split-files $sample/$sample.sralite`
`fastq-dump -o fastq -e 32 --mem 120G --split-files $sample/$sample`
`fastq-dump -o fastq -3 -e 32 --mem 120G --split-files $sample/$sample`

Let me know if there's anything else I can provide to fix this issue!
Thanks,

**Comment by klymenko** [comment]
What is your full command line of fasterq-dump?

**Comment by DelongZHOU** [comment]
That was it. I had a SRR run selection assession list and did
`prefetch -C no -v --option-file acclist.txt`
then followed by one of the above commands

**Comment by wraetz** [comment]
I tried this:
$prefetch SRR8270301 -p
$fasterq-dump ./SRR8270301
I did succeed without an error. The files SRR8270301_1.fastq and SRR8270301_2.fastq were produced.

You can omit some of the options:
"-e 32" ... that is a lot of threads! In my experience on a machine with 96 cores - I did not get a faster result past "-e 8".
"--mem 120G" ... that is just the memory used in a sorting step for cSRA accession. The accessions you are using are not of the cSRA-kind! This option is ignored.
"-3" ... that is the default option
"-3" and "--split-files" are mutually exclusive. "-3" is used and is identical to the default.
"-o fastq" means produce output-files that have "fastq" as the basename. ( It does not mean produce fastq-format )

Where do you assign a value to $sample? Just replace the fastq-command with "echo $sample" to see what accession fastq-dump is trying to operate on.

Just in case: fastq-dump can only transform one accession at a time. It cannot operate on a list of accessions per se. You have to write a loop in a bash-file to iterate over the accessions in a list.

**Comment by DelongZHOU** [comment]
I just realized what went wrong.. I should have used -O (CAPITAL) to indicate the folder instead of -o.
Since there's a folder with the name "fastq" it causes a name conflit which in turn gives this error.
Thanks for your time!
