### ISSUE TITLE
fasterq-dump fails to download dbgap data with --perm parameter (AWS us-east-1, docker image)

### ISSUE THREAD

**Issue by rankovicmiona** [ncbi/sra-tools#740]
Hi,

I'm trying to run `fasterq-dump` in order to download dbgap data. Based on the available documentation and the fact that I'm running `fasterq-dump` on AWS (us-east-1) and inside a docker container, I ran the following command:
`fasterq-dump --perm <path-to-jwt-file> SRR****`

I'm getting the following error message:
`Currently, --perm can only be used from inside a cloud computing environment.
Please run inside of a supported cloud computing environment, or get an ngc file from dbGaP and reissue the command with --ngc <ngc file> instead of --perm <perm file>.`

Can you please help me to understand following:
1. What method is used by `fasterq-dump` to determine if it runs inside a cloud computing environment? Can you please point me to that part of the code?
2. Is there any known issue with `fasterq-dump` with `--perm` inside the docker container? If so, is there a way to solve this issue? 

Thanks!
Miona

**Comment by klymenko** [comment]
What is the output of `fasterq-dump -V` ?

**Comment by durbrow** [comment]
From the host, run:
```
printf "%s\n" `wget -qO - http://169.254.169.254/latest/meta-data/placement/availability-zone`
```
You should get something like:
```
us-east-1d
```
Then run the same command from inside the docker container. You should get the same result. This is exercising the same mechanism the toolkit uses to get cloud instance metadata. If you don't get the same result from inside the container as from the host, the problem is not in the toolkit.

**Comment by durbrow** [comment]
Also beware that by default, your files on the host are not visible inside the docker container. If your perm file is on the host, the toolkit will not be able to use it. The simplest way to "fix" this is to mount your home directory into the docker container, like so:
```
docker run -it -v ${HOME}:/work:rw -w /work --rm ncbi/sra-tools
```
This will mount read-write your `$HOME` as `/work` inside the container and set the current working directory to it.

**Comment by rankovicmiona** [comment]
Hi All,

This was definitely the problem at my end.
Thanks for the instructions and the detailed explanation and sorry for the false alarm.
