### ISSUE TITLE
sra-tools-3.0.1/build/Makefile.config is missing

### ISSUE THREAD

**Issue by lifan18** [ncbi/sra-tools#743]
Sorry, I just install the latest version of this great tool, but I cannot `make` the file as usual.

The detailed info like this,
`
/sra-tools-3.0.1/build/Makefile.env:44: *** "*** File '/sra-tools-3.0.1/build/Makefile.config' is missing. Please run /sra-tools-3.0.1/build/configure".  Stop.
`

Could you fix it?

Thank you!

**Comment by aboshkin** [comment]
@lifan18 before you can run `make`, the toolkit needs to be configured. Please `cd `into `/sra-tools-3.0.1/` and run `./configure`, as the error message suggests. Please let us know if that does not solve the problem.

**Comment by lifan18** [comment]
Thank you for your quick response! Yes, I ran `configure` under the dir "/sra-tools-3.0.1" and got this error `[sra-tools-3.0.1](configure: error: required ncbi-vdb package not found.)`.

Hope you can help me to fix it.

Thank you!

**Comment by aboshkin** [comment]
@lifan18 to build from source, please follow the instructions at https://github.com/ncbi/sra-tools/wiki/Building-and-Installing-from-Source. It appears that the step 0 (checkout and build the SDK, i.e. `ncbi-vdb`) was not completed

**Comment by aboshkin** [comment]
@lifan18 alternatively and if that suits you, you can simply download the binaries instead of building them from source. Follow https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit.

**Comment by lifan18** [comment]
> @lifan18 alternatively and if that suits you, you can simply download the binaries instead of building them from source. Follow https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit, https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit etc. as needed.

Thank you very much! Very user-friendly! Yes, it solved my issue. Great work!
