### ISSUE TITLE
fasterq-dump: "disk-limit exeeded!"

### ISSUE THREAD

**Issue by jlongo62** [ncbi/sra-tools#750]
I am running the following command using a container:

```
ID=SRR10571659
fasterq-dump /aci/mnt/$ID --outdir /aci/mnt/$ID -t /aci/mnt/$ID -v -x
```
I am getting the error: **disk-limit exeeded!**

How do I fix this ?

bash-5.1# fasterq-dump /aci/mnt/$ID --outdir /aci/mnt/$ID -t /aci/mnt/$ID -v -x
Preference setting is: Prefer SRA Normalized Format files with full base quality scores if available.
/aci/mnt/SRR10571659 is an SRA Normalized Format file with full base quality scores.
2022-12-12T17:23:05 fasterq-dump.3.0.1 err: inspector.c get_file_size( '/aci/mnt/SRR10571659', remotely = NO ) -> RC(rcFS,rcDirectory,rcAccessing,rcPath,rcIncorrect)
cursor-cache : 5,242,880 bytes
buf-size     : 1,048,576 bytes
mem-limit    : 52,428,800 bytes
threads      : 6
scratch-path : '/aci/mnt/SRR10571659/fasterq.tmp.SandboxHost-638064579707097561.8428/'
total ram    : 10,454,175,744 bytes
output-format: FASTQ split 3
check-mode   : on
output-file  : '/aci/mnt/SRR10571659/SRR10571659.fastq'
output-dir   : '/aci/mnt/SRR10571659'
output       : '/aci/mnt/SRR10571659/SRR10571659.fastq'
append-mode  : 'NO'
stdout-mode  : 'NO'
seq-defline  : '@$ac.$si $sn length=$rl'
qual-defline  : '+$ac.$si $sn length=$rl'
only-unaligned : 'NO'
only-aligned   : 'NO'
accession     : 'SRR10571659'
accession-path: '/aci/mnt/SRR10571659'
est. output          : 21,369,187,212 bytes
disk-limit (OS)      : 22,330,540,032 bytes
disk-limit-tmp (OS)  : 22,330,540,032 bytes
out/tmp on same fs   : 'NO'

SRR10571659 is local
... has a size of 0 bytes
... is cSRA without alignments
... SEQ has NAME column = YES
... SEQ has SPOT_GROUP column = YES
... uses 'SEQUENCE' as sequence-table
SEQ.first_row = 1
SEQ.row_count = 61,417,949
SEQ.spot_count = 61,417,949
SEQ.total_base_count = 6,262,501,278
SEQ.bio_base_count = 6,262,501,278
SEQ.avg_name_len = 1
SEQ.avg_spot_group_len = 8
SEQ.avg_bio_reads_per_spot = 2
SEQ.avg_tech_reads_per_spot = 0
ALIGN.first_row = 0
ALIGN.row_count = 0
ALIGN.spot_count = 0
ALIGN.total_base_count = 0
ALIGN.bio_base_count = 0

disk-limit exeeded!
fasterq-dump quit with error code 3
bash-5.1# 

This is my disk system
```
bash-5.1# df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               51606304  13401484  35566996  27% /
tmpfs                    65536         0     65536   0% /dev
shm                      65536         0     65536   0% /dev/shm
\134\134passaciaumyb.file.core.windows.net\134acishare
                     131072000 109264832  21807168  83% /aci/mnt
/dev/sdc              51606304  13401484  35566996  27% /etc/resolv.conf
tmpfs                  5104576         0   5104576   0% /sys/fs/cgroup
/dev/sdc              51606304  13401484  35566996  27% /etc/hostname
/dev/sdc              51606304  13401484  35566996  27% /etc/hosts
tmpfs                  5104576         0   5104576   0% /proc/acpi
tmpfs                    65536         0     65536   0% /proc/kcore
tmpfs                    65536         0     65536   0% /proc/keys
tmpfs                    65536         0     65536   0% /proc/timer_list
tmpfs                  5104576         0   5104576   0% /sys/firmware
```

**Comment by durbrow** [comment]
You don't have enough free space on /aci/mnt. You are telling `fasterq-dump` to use /aci/mnt for both output and scratch space, so you would need at least 25 GB (~12.5 GB for the output + about the same for scratch space) on /aci/mnt for both. You only have ~21 GB.

You could try to set `-t` to a location that is not on /aci/mnt. You could try `fastq-dump`; it's slower but doesn't use as much resources as `fasterq-dump`.
