### ISSUE TITLE
Fastq-dump can’t transform SRA file into fastq format file and vdb-dump didn’t work

### ISSUE THREAD

**Issue by ligaojian96** [ncbi/sra-tools#751]
The SRA file was downloaded by prefetch, and when I got trouble when transforming the SRA file into fastq format file.
![Screenshot_2022-12-14_23-08-35_看图王](https://user-images.githubusercontent.com/61624003/207764855-f11b425c-9121-4846-b987-72405dfdc5b5.png)
![Screenshot_2022-12-14_23-23-13_看图王](https://user-images.githubusercontent.com/61624003/207764858-4f962805-14fd-4e7f-ab3e-922b2937ec9c.png)
![windows1](https://user-images.githubusercontent.com/61624003/207764860-2dcb2bd7-f5bb-4653-8152-15d99814e802.png)
![windows2](https://user-images.githubusercontent.com/61624003/207764862-9a86b917-2dca-4953-8734-606446ab5f2e.png)

**Comment by ligaojian96** [comment]
Here is my e-mail address, ljian0216@126.com, many thanks for valuable suggestions.

**Comment by klymenko** [comment]
[Download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit.
