### ISSUE TITLE
Building SRA-tools in Arch linux [File 'Makefile.config.linux.x86_64' is missing] error

### ISSUE THREAD

**Issue by kbipinkumar** [ncbi/sra-tools#756]
i am trying to build and package sra-tools for arch linux. 

[from your wiki,](https://github.com/ncbi/sra-tools/wiki/Building-and-Installing-from-Source) my understanding is that i need to download and extract source tarballs for `ncbi-vdb` and `sra-tools` to same folder and then run `./configure` and `make` in folder of `ncbi-vdb` and `sra-tools` in the aforementioned order followed by make install

in archlinux this process can be automated in `PKGBUILD' script which is essentially a bash script like this
```bash
build(){
  cd "ncbi-vdb-3.0.2"
  ./configure \
	--prefix="$pkgdir/usr/" 
  
  make
  cd ..

  cd "sra-tools-3.0.2"
   /configure \
	--prefix="$pkgdir/usr/"
  
  make
  cd ..
}
```
the script creates aforementioned `ncbi-vdb` and `sra-tools` folders in the `/build/sra-tools/src` location

now the script runs fine and builds ncbi-vdb as shown in output below

```terminal
[ 99%] Built target ncbi-vdb
[ 99%] Linking C shared library /build/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib/libncbi-vdb.so
[ 99%] Built target ncbi-vdb-shared
[ 99%] Linking C static library /build/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib/libncbi-wvdb.a
[ 99%] Built target ncbi-wvdb
[100%] Linking C shared library /build/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/lib/libncbi-wvdb.so
[100%] Built target ncbi-wvdb-shared
```
but when is start running `./configure` in `sra-tools-3.0.2' tools directory i am getting following error
```
CONFIGURING ngs-sdk
Unknown option: with-hdf5
configure: error at konfigure.perl line 109.

CONFIGURING ngs-java
Unknown option: with-hdf5
configure: error at konfigure.perl line 109.

CONFIGURING ngs-python
Unknown option: with-hdf5
configure: error at konfigure.perl line 109.

make[1]: Entering directory '/build/sra-tools/src/ngs-3.0.1/ngs-sdk'
*** File 'Makefile.config.linux.x86_64' is missing. Please run ./configure
make[1]: *** [/build/sra-tools/src/ngs-3.0.1/ngs-sdk/Makefile.rules:72: Makefile.config.linux.x86_64] Error 1
make[1]: Leaving directory '/build/sra-tools/src/ngs-3.0.1/ngs-sdk'
make: *** [Makefile:54: ngs-sdk] Error 2
```
any idea regarding what am i doing wrong? i dont remember even passing this `Unknown option: with-hdf5` option as well

**Comment by klymenko** [comment]
`ngs` repository was moved into `sra-tools`.
Please retry with the latest code.
