### ISSUE TITLE
fastq-dump not running

### ISSUE THREAD

**Issue by Sharmishtha-7** [ncbi/sra-tools#757]
I followed ncbi steps to install sra kit and run the fastq files to analyze. But even after a smooth configuration I am unable to run the fastq-dump successfully, with an error : 
fastq-dump.3.0.2. err: item not found while constructing the virtual database module - the path 'SRR390728' cannot be opened as a database or a table. The fastq-dump quit with error code 3. I need an urgent solution to the same to progress further soon!!

Thanks,
Sharmistha

**Comment by klymenko** [comment]
What is the output of `srapath SRR390728`?

**Comment by Sharmishtha-7** [comment]
Ideally, it should be 

Read 2 spots for SRR390728
Written 2 spots for SRR390728
@SRR390728.1 1 length=72
CATTCTTCACGTAGTTCTCGAGCCTTGGTTTTCAGCGATGGAGAATGACTTTGACAAGCTGAGAGAAGNTNC
+SRR390728.1 1 length=72
;;;;;;;;;;;;;;;;;;;;;;;;;;;9;;665142;;;;;;;;;;;;;;;;;;;;;;;;;;;;;96&&&&(
@SRR390728.2 2 length=72
AAGTAGGTCTCGTCTGTGTTTTCTACGAGCTTGTGTTCCAGCTGACCCACTCCCTGGGTGGGGGGACTGGGT
+SRR390728.2 2 length=72
;;;;;;;;;;;;;;;;;4;;;;3;393.1+4&&5&&;;;;;;;;;;;;;;;;;;;;;<9;<;;;;;464262
