### ISSUE TITLE
Buffer insufficient while executing function within transform module

### ISSUE THREAD

**Issue by apredeus** [ncbi/sra-tools#759]
Hi, 

I have a somewhat strange issue with `SRR13997822` - while other 104 SRA files from the same dataset have processed normally. Here's the full error:

> 2023-01-07T12:38:56 fastq-dump.2.11.0 err: buffer insufficient while executing function within transform module - failed SRR13997822
> An error occurred during processing.
> A report was generated into the file '/nfs/users/nfs_c/cellgeni-su/ncbi_error_report.txt'.
> If the problem persists, you may consider sending the file
> to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
> fastq-dump quit with error code 3

The `vdb-validate` output seems to be OK: 

> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Database 'SRR13997822' metadata: md5 ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Table 'SEQUENCE' metadata: md5 ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'ALTREAD': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'NAME_FMT': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'QUALITY': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'READ': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'SPOT_GROUP': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'X': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Column 'Y': checksums ok
> 2023-01-07T12:38:22 vdb-validate.2.11.0 warn: type unrecognized while validating database - Database 'SRR13997822' has unrecognized type 'NCBI:SRA:Illumina:db'
> 2023-01-07T12:38:22 vdb-validate.2.11.0 info: Database 'SRR13997822' is consistent

Pretty much any way I try to get these, I get the same error. 

Any suggestions are appreciated!

**Comment by klymenko** [comment]
Use [the latest toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).

**Comment by apredeus** [comment]
Thank you, it worked!
