### ISSUE TITLE
latf-load 3.0.2 outputs "KQueuePop failed" errors

### ISSUE THREAD

**Issue by komstat** [ncbi/sra-tools#764]
We tested the latf-load in https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.2/sratoolkit.3.0.2-ubuntu64.tar.gz

This is a test fastq file we loaded.
https://www-dev.ddbj.nig.ac.jp/test-single.fq

Here is the latf-load 3.0.2 command we used.
```
sratoolkit.3.0.2-ubuntu64/bin/latf-load --quality PHRED_33 -o test-single.sra test-single.fq 
2023-01-18T00:44:15 latf-load.3.0.2 err: data done while removing queue within container module - KQueuePop failed
```

The latf-load 3.0.2 generated "data done while removing queue within container module - KQueuePop failed" errors for most of test fastq files. However, sra files were successfully loaded and generated from the test fastq file, and we could generate fastq files from the sra files by using fastq-dump.

What is "data done while removing queue within container module - KQueuePop failed" error? And how can we avoid this error?

**Comment by aboshkin** [comment]
The message is benign and can be safely ignored, as long as the exit code of the tool is 0. In some cases it may indicate a problem, but then it would always be accompanied by additional error messages and a non-0 exit code. We will open an internal ticket to fix the code to not report this error without a good reason. Thank you for reporting!

**Comment by komstat** [comment]
Thank you very much. We will ignore this error.
