### ISSUE TITLE
prefetch stuck at certain SRR

### ISSUE THREAD

**Issue by hukai916** [ncbi/sra-tools#766]
Hi there,

On an Ubuntu machine, the following scripts stuck forever:
```
prefetch -f yes --max-size 100GB -o SRR14729158.sra SRR14729158
prefetch -f yes --max-size 100GB -o SRR14729159.sra SRR14729159
prefetch -f yes --max-size 100GB -o SRR14729160.sra SRR14729160
```
While the following 3 are okay (all 6 samples are from the same GEO)
```
prefetch -f yes --max-size 100GB -o SRR14729155.sra SRR14729155
prefetch -f yes --max-size 100GB -o SRR14729156.sra SRR14729156
prefetch -f yes --max-size 100GB -o SRR14729157.sra SRR14729157
```

Could it be a data crash problem?

Thanks,

**Comment by klymenko** [comment]
What is the version of `prefetch`?
Add `-p` to `prefetch` arguments to see progress.
It's not recommended to use `-o` option - `prefetch` will not download reference sequences.
