### ISSUE TITLE
Command line changing vdb-config

### ISSUE THREAD

**Issue by linsalrob** [ncbi/sra-tools#77]
Is there an explanation somewhere of how to change vdb-config using the command line? It appears possible. e.g.

```
vdb-config -h

...
-s|--set <name=value>            set configuration node value
...
```

So one might assume that 

```
vdb-config -s cache-disabled=true 
```
might disable local caching, but this does not appear to do so.

How does one interact with vdb-config via the command line, and specifically, how do I disable local caching?

**Comment by ageier4** [comment]
My configuration file, user-settings.mkfg, has:
/repository/user/protected/'project'/cache-enabled = "true"
I believe you would have to switch 'cache-enabled' to 'false' instead of 'cache-disabled' to 'true'. Using the set option should work. I used it to set the root directory of my project.

**Comment by kwrodarmer** [comment]
The vdb configuration files are free-form text, and much like XML, will happily ignore anything unrecognized. For this reason, we don't encourage people to edit the file directly.

You can run vdb-config in interactive mode and check the lines that change, and these can be set from the command line as was previously commented.

**Comment by linsalrob** [comment]
But how do I do that if I am using a bunch of servers in the cloud where manipulating each one is not an option?

**Comment by kwrodarmer** [comment]
My comment was not that you shouldn't use vdb-config to update configuration, just that there is no documentation *(other than the code)* to describe what nodes and values you need to access. But if you use `vdb-config -I` to guide you on what to modify, it will tell you what you need to do on the command line.

That said, cloud usage creates some challenges, cluster computing presents others. By all means, write to us to explain the problem you need to solve and if we have already dealt with it or can help, we will be happy to pass it along.

**Comment by amizeranschi** [comment]
Hello,

I'm facing a similar issue. I would like to enable and set up sra-tools caching non-interactively (i.e. without using `vdb-config -i` to a custom directory. How could I do this?

**Comment by klymenko** [comment]
@amizeranschi , what do you need to do?
Change caching location to a custom directory non-interactively?

**Comment by amizeranschi** [comment]
Yes, exactly. I'd like local caching to be done in the same directory where the files are being downloaded with `prefetch` and `fasterq-dump`. I believe I achieved this with the following commands, but it would be great if you could confirm if this is the right way to do things.

```
rm -rf ~/.ncbi
vdb-config --restore-defaults
vdb-config -s "/repository/user/main/public/root=."
vdb-config -s "cache-enabled=true"
```

**Comment by klymenko** [comment]
@amizeranschi, we changed default behavior of prefetch.
Now by default it downloads to the current directory.

To use it, just remove ~/.ncbi.

Then run "vdb-config -i" once.

Then the sequence is following, e.g. to fastq-dump SRR000001:
`prefetch SRR000001 && fasterq-dump SRR000001`
If you are done with processing of SRR000001 - you can remove directory SRR000001 located in the current directory.

Make sure to use the latest toolkit (2.10.7).

**Comment by amizeranschi** [comment]
Alright, I will test the latest version 2.10.7.

Is there really no way to avoid having to run `vdb-config -i` and to set things up using `vdb-config -s`? I'd like to include sra-tools into a pipeline where things are as automated as possible and as little user input is required. From what I've seen so far, asking (some) users to deal with stuff like `vdb-config -i` is just asking for trouble. 

If it's not possible to avoid `vdb-config -i` for sra-tools, then could you suggest some other way (besides wget) for downloading data from SRA in an unattended way?

**Comment by amizeranschi** [comment]
OK, it seems like the latest version simply refuses to run unless I run `vdb-config -i`, even though I tried running the `vdb-config -s` commands mentioned in https://github.com/ncbi/sra-tools/issues/77#issuecomment-635090007. I was using version `2.10.3` before and `vdb-config -s` seemed to do the trick, but for some reason that stopped working in the newest version. 

```
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
[a.mizeranschi@fep7-1 fastq]$ 
[a.mizeranschi@fep7-1 fastq]$ fasterq-dump --split-files -O . -t . SRR6784354
This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
For more information, see https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/
```

Out of curiosity, what is the reason for forcing every user to run the interactive setup and to not allow this to be done via `vdb-config -s`? This seems like quite an odd design choice to me and it's just going to prevent the automated and unattended set-up and use of sra-tools in pipelines like I've described in my previous post.

**Comment by kwrodarmer** [comment]
> Out of curiosity, what is the reason for forcing every user to run the interactive setup and to not allow this to be done via vdb-config -s?

The reason is exactly because of what you said:

> to prevent the automated and unattended set-up and use of sra-tools in pipelines 

Your use case would give rise to a race condition. We are using human intervention as a type of semaphore. This is a result of us supplying directly usable binaries rather than running an installer, such that just turning the binaries loose can cause a problem. We are going to switch to providing normal installer packages in the future, which will remove this limitation, and you may not be aware that with release 2.10.7, we now have a docker file in the sources that also gets around the race condition.

**Comment by amizeranschi** [comment]
Sorry, but I still don't get it. What kind of race condition would my use case give rise to, and why is there a need for such type of a semaphore?

I was previously using v. 2.10.3 installed from Bioconda (this is still the latest version available there) and it went perfectly fine and was able to be configured in an automated fashion via `vdb-config -s`. What kind of trouble was this causing, that you felt the need to enforce user intervention while installing? I'm honestly curious why you guys felt you had to kill that functionality within the span of a couple of months.

If you are now going against automated configuration of sra-tools, does this also mean that stuff like Bioconda packages are going to get blocked in the future? Docker is a good compromise for some users, but not for others (such as those running on clusters).

**Comment by linsalrob** [comment]
Its also not really that useful as an approach to force user interaction. 

A simple solution that I use is to set up `vdb-config -i` on a machine somewhere and turn off caching and set the directories as appropriate, then tar `~/.ncbi` and copy it to any new machine when installing the sra tools. Its an extra step but it avoids completely having to deal with `vdb-config` during machine set up.

**Comment by durbrow** [comment]
You appear to have used the mechanism as it was intended. **You created a configuration** and then cloned it to the set of machines that you were running. The intention is for **you** to create a configuration, to examine the options, to give thought to it, so that the toolkit does not go off and do things you were not expecting.

**Comment by amizeranschi** [comment]
Sounds like this is more of a legal issue, and not a technical issue, after all. Is enforcing users to run `vdb-config -i` and then to press `X` meant to be interpreted as some form of expressing consent? 

If so, then why can't that be implied from the fact that the user installs a pipeline that relies on sra-tools to download the FASTQ files correpsonding to a list of SRA run IDs into some directory that the user chooses?

**Comment by blajoie** [comment]
> Its also not really that useful as an approach to force user interaction.
> 
> A simple solution that I use is to set up `vdb-config -i` on a machine somewhere and turn off caching and set the directories as appropriate, then tar `~/.ncbi` and copy it to any new machine when installing the sra tools. Its an extra step but it avoids completely having to deal with `vdb-config` during machine set up.

Thank you for the tip - running into the same issue trying to deploy/run SRA automatically without human intervention.  We will take the same non-optimal approach.  Manually configure once, and the deploy/mount the .ncbi/user-settings.mkfg to the image.  

@sra - please reconsider your design, software should not require any interactive/manual steps.
