### ISSUE TITLE
Access denied - please request permission / using ngc file

### ISSUE THREAD

**Issue by jdime** [ncbi/sra-tools#775]
Hello,

I'm having issues using download data from a controlled study (phs001988) using my prj_XXXXX.ngc file. Note that I was granted access to this study (I can see it "Approved" in my dbGaP account).

This is what I did:

1. Installed SRA toolkit v3.0.1
2. Downloaded my prj_XXXXX.ngc file from my dbGaP account.
3. Tested `prefetch` and `fasterq-dump` with a public (uncontrolled) dataset:
`prefetch SRR11192680`
`fasterq-dump --split-files SRR11192680/SRR11192680.sra`
Both steps were successful, I could get the fastq sequences of this dataset.
4. Tried to `prefetch` one dataset from the phs001988 controlled study:
`prefetch --ngc /path_to/prj_XXXXX.ngc SRR13681931`
```
2023-02-10T19:17:16 prefetch.3.0.0 err: query unauthorized while resolving query within virtual file system module - failed to resolve accession 'SRR13681931' - Access denied - please request permission to access phs001988 / DS-PC-MDS in dbGaP. ( 403 )
2023-02-10T19:17:16 prefetch.3.0.0: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
```

Could you please advise?

Thanks.

Javier

**Comment by klymenko** [comment]
Email to sra@ncbi.nlm.nih.gov.

**Comment by klymenko** [comment]
@jdime  , do you need more help?

**Comment by jdime** [comment]
Hello @klymenko ,

I worked with the SRA rep to solve the issue. I don't need more help. Thanks.

**Comment by mousepixels** [comment]
> Hello @klymenko ,
> 
> I worked with the SRA rep to solve the issue. I don't need more help. Thanks.

So what was the solution? Having the same issue for a specific project

**Comment by klymenko** [comment]
@mousepixels, the solution is to contact [sra@ncbi.nlm.nih.gov](mailto:sra@ncbi.nlm.nih.gov).
