### ISSUE TITLE
prefetch fails downloading

### ISSUE THREAD

**Issue by ebrigos** [ncbi/sra-tools#778]
I am trying to download genotype imputed data from an accepted project from dbGaP. Once the access has been granted, I've followed the [download guidelines](https://www.ncbi.nlm.nih.gov/books/NBK570248/#Dwnld_DownloadData.what_is_aspera_softwa) with the recommended configuration.

To download the files, I've used the combination of the kart file and my fresh dbGaP repository key:

```{shell}
$ prefetch --ngc prj_XXXXX.ngc cart_DAR116945_202212151302.krt
````

Even if it connects with the server and is able to find the correct file, this error rises:

```{shell}
Downloading kart file 'cart_DAR116945_202212151302.krt'
Checking sizes of kart files...
2023-01-16T13:24:42 prefetch.3.0.1: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
Downloading the files...
2023-01-16T13:24:43 prefetch.3.0.1: 1) Downloading 'phg000130.v1.GENEVA_VenousThrombosis_imputed.genotype-imputed-data.chr21.c1.GRU.tar'...
2023-01-16T13:24:43 prefetch.3.0.1:  Downloading via HTTPS...
2023-01-16T13:25:35 prefetch.3.0.1 err: data unexpected while reading file within network system module - Cannot KStblHttpFileRead
```

**Comment by klymenko** [comment]
email to sra@ncbi.nlm.nih.gov

**Comment by ebrigos** [comment]
Dear Andrew,

I have already emailed them and I have been waiting for an answer for more
than two months...
I would really need some help with this error because it is delaying an
important step of the research project.
I don't know what else to do to find any kind of assistance from SRA/NCBI.

Thanks,

Eva



Missatge de Andrew Klymenko ***@***.***> del dia dc., 8 de
març 2023 a les 16:36:

**Comment by klymenko** [comment]
@ebrigos , send them your kart file and the number of dbGaP project.
@stineaj , please ask curators to notify me when they receive this.
