### ISSUE TITLE
fast-dump error: column not found while opening table within short read archive module

### ISSUE THREAD

**Issue by sable2** [ncbi/sra-tools#779]
Hi,
I downloaded sra files with download . files () using file paths from SraRunInfo.csv in RStudio(linux),
When I run fast-dump for srr files I get the error: column not found while opening table within short read archive module column not found while opening table within short read archive module.
Previously everything worked for the same set of files and a download method.

#Read SRA file infos
`sri<-read.csv("SraRunTable.txt", stringsAsFactors=FALSE)
files<-basename(sri$download_path)
for(i in 1:length(files)) download.file(sri$download_path[i], files[i])`

#Convert SRA to FASTQ format
`stopifnot( all(file.exists(files)) ) 
for(f in files) {
  cmd = paste("fastq-dump --split-3", f)
  cat(cmd,"\n")#print the current command
  system(cmd) # invoke command
}
`
fastq-dump --split-3 SRR1919015.sralite.1 
2023-02-13T17:53:25 fastq-dump.2.5.7 err: column not found while opening table within short read archive module - failed SRR1919015.sralite.1

fastq-dump --split-3 SRR1919016.sralite.1 
2023-02-13T17:53:25 fastq-dump.2.5.7 err: column not found while opening table within short read archive module - failed SRR1919016.sralite.1
[SraRunInfo.csv](https://github.com/ncbi/sra-tools/files/10725857/SraRunInfo.csv)

**Comment by sable2** [comment]
solved

**Comment by ZhongmiaoLiu** [comment]
Hello, I would like to ask you how to solve this problem.

**Comment by sable2** [comment]
I updated the version of the software
________________________________
From: ZhongmiaoLiu ***@***.***>
Sent: Saturday, July 1, 2023 12:26 AM
To: ncbi/sra-tools ***@***.***>
Cc: Safronova, Alexandra ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [ncbi/sra-tools] fast-dump error: column not found while opening table within short read archive module (Issue #779)


Hello, I would like to ask you how to solve this problem.

**Comment by ZhongmiaoLiu** [comment]
Thank you very much. I succeeded in the same way.
| |
liuzhongmiao0224
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/02/2023 00:49 |
| To | ncbi/sra-tools ***@***.***> |
| Cc | ZhongmiaoLiu ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [ncbi/sra-tools] fast-dump error: column not found while opening table within short read archive module (Issue #779) |

I updated the version of the software
________________________________
From: ZhongmiaoLiu ***@***.***>
Sent: Saturday, July 1, 2023 12:26 AM
To: ncbi/sra-tools ***@***.***>
Cc: Safronova, Alexandra ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [ncbi/sra-tools] fast-dump error: column not found while opening table within short read archive module (Issue #779)


Hello, I would like to ask you how to solve this problem.
