### ISSUE TITLE
err: extract_acc2

### ISSUE THREAD

**Issue by zhangqc723** [ncbi/sra-tools#780]
When I split SRA files to FASTQ files using this code, I meet this error as follow image.But it still output result.
**Code**: for i in *sra; do path/to/fasterq-dump -p -e 30 --split-3 ${i}; done
![image](https://user-images.githubusercontent.com/86176443/218707205-72a4851a-6f39-44fa-a022-ba949cc4598a.png)

**Comment by klymenko** [comment]
[Download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit.
