### ISSUE TITLE
fastq-dump not extracting pacbio sra

### ISSUE THREAD

**Issue by JonEilers** [ncbi/sra-tools#781]
I am trying to extract some pacbio SRA using the recommended fastq-dump and it is throwing this error. sra-tools was installed using conda and sratoolkit version 3.0.3 package h87f3376_0. 

```bash
fastq-dump SRR10130136.sra
2023-02-14T20:46:42 fastq-dump.3.0.1 err: accession 'SRR10130136' is PACBIO, please use fastq-dump instead
```
I later installed sra-toolkit version 2.11.3 using apt-get and fastq-dump is working fine for extracting pacbio sra.

**Comment by klymenko** [comment]
It's incorrect message.
Use `fasterq-dump`.

**Comment by klymenko** [comment]
We don't support conda.
Download toolkit from [here](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit).
