### ISSUE TITLE
Is it possible to only dump technical reads?

### ISSUE THREAD

**Issue by xexpanderx** [ncbi/sra-tools#785]

**Comment by wraetz** [comment]
It is not possible to dump only technical reads. But you can use fasterq-dump to dump all reads (including the technical ones). The commandline for this would be: fasterq-dump SRRXXXXXX --split-files --include-technical. This will result in multiple files. How many of these files it creates depends on the spot-layout of the accession in question - and this spot-layout depends on what data the submitter has been sending to us. You have to manually inspect the files to determine which files contain the technical reads. You can use vdb-dump to get a hint with: vdb-dump SRRXXXXXX -R1 -C READ_TYPE. If the answer is for instance READ_TYPE: SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL, SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL - then the first and the third file have the technical reads in them. This spot-layout can vary between accessions, including having no technical reads and having hundreds of reads - depending on the platform. It can also happen that the read-layout is different for each row. A safer way to do it would be to use vdb-dump to extract the READ, READ_START, READ_LEN, and READ_TYPE columns - and pipe this data into a script which filters for technical reads.

**Comment by xexpanderx** [comment]
Thank you, I am a bit concerned regarding your "It can also happen that the read-layout is different for". What do you mean by this, that I cannot trust the:
`READ_TYPE: SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL, SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL
`

I.e. the "positions" in the spot is not ALWAYS the same order, you mean vdb-dump SRRXXXXXX -R2 -C READ_TYPE can give:
`READ_TYPE: SRA_READ_TYPE_BIOLOGICAL, SRA_READ_TYPE_BIOLOGICAL, SRA_READ_TYPE_TECHNICAL, SRA_READ_TYPE_BIOLOGICAL
`
e.t.c?

**Comment by wraetz** [comment]
Yes, indeed - the spot-layout can be different for each row. However this is rare ( below 1% of all accessions ). If it happens it is mostly that the first maybe 10000 rows have the same layout - then it switches to something else etc. Because of this - if you want to be correct in all cases - you have to pipe the output of vdb-dump SRRXXXXXX -C READ, READ_START, READ_LEN, READ_TYPE into a script and handle each row in isolation. To make it easier for your script you can use '-f tab' or '-f csv' or '-f json'.

**Comment by wraetz** [comment]
To check if an accession is actually this rare case, you can run vdb-dump SRRXXXXXXX -C READ_TYPE -f tab into the uniq-tool. If you have only one output-line - all rows have the same layout.

**Comment by xexpanderx** [comment]
Ok, thank you. How would this affect the --split-files which split files based on the reads in the spot?

**Comment by xexpanderx** [comment]
Ok, thank you!
