### ISSUE TITLE
Trouble with SRA toolkit sra-blastn

### ISSUE THREAD

**Issue by ytliuSVN** [ncbi/sra-tools#79]
I'm trying to use `sra-blastn` to search WGS projects and keep getting below error messages: 

```
VDB: 2017-06-07T12:18:22 . sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
VDB: 2017-06-07T12:18:28 . err: file not found while opening file within network system module - error with https open 'https://ftp-trace.ncbi.nlm.nih.gov/sra/wgs/AA/OU/AAOU01.6'
VDB: 2017-06-07T12:18:28 . int: file not found while opening file within network system module - Error in VDBManagerOpenDBRead(AAOU01)
```

I have built alias file "**bacteria-wgs.nvl**" via `taxid2wgs.pl` using following command:
`taxid2wgs.pl -title "Bacteria WGS" -alias_file bacteria-wgs 2`

What I do next is execute `sra-blastn` search.
`sra-blastn -query ZYUP_submission.assembly.fasta -db bacteria-wgs -num_threads 20 -outfmt 7 -out bacteria-results.out`

Could it be a configure issue? Thank you!

**Comment by kwrodarmer** [comment]
It is highly unlikely that this would be related to configuration or your software. We have been experiencing sporadic network issues that we are working to resolve, and over the weekend we had a hardware failure that brought down an entire data center.

**Comment by vincebaby6** [comment]
How did you resolve this issue? did you simply execute the command again?
