### ISSUE TITLE
SRR*_pass.fastq.gz

### ISSUE THREAD

**Issue by malonzm1** [ncbi/sra-tools#792]
Hi,

Using fastq-dump generates SRR*_pass.fastq.gz files like SRR7420405_pass.fastq.gz instead of the usual SRR*.fastq.gz (without the "pass" in the filename). Is this because I use the flag `--read-filter pass`? I use the following command:

`--gzip --skip-technical  --readids --read-filter pass --dumpbase --split-3 --clip`

Thanks and good day.

**Comment by klymenko** [comment]
What is the complete output?

**Comment by klymenko** [comment]
Yes, `_pass` suffix was added because you used `--read-filter pass`.

**Comment by malonzm1** [comment]
Thanks!
