### ISSUE TITLE
error with prefetch --type fastq

### ISSUE THREAD

**Issue by SaraValpione** [ncbi/sra-tools#799]
Good evening, I have been trying to download the original files for GSE222078 for now three weeks. The original files are necessary as the SRA Normalized Format files are useless for downstream analyses with cellranger (these are Chromium 10X scRNA-Seq FASTQ files and need their original name etc). I have been following the instructions from 

prefetch --type fastq SRR22957171 
2023-03-28T17:54:55 prefetch.3.0.1 err: name not found while resolving query within virtual file system module - failed to resolve accession 'SRR22957171' - no data ( 404 )
2023-03-28T17:54:55 prefetch.3.0.1: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.

[xxx@login01 sc]$ ml list 

Currently Loaded Modules:
  1) apps/sratoolkit/3.0.1

[xxx@login01 sc]$ ls
[xxx@login01 sc]$ 

SRA tutorial includes setting up an AWS or a GCS account, but these are options unavailable in my institution.

I really could do with some help please.

SV

**Comment by klymenko** [comment]
What is the output of `srapath SRR22957171` ?

**Comment by SaraValpione** [comment]
Hi,

Thanks for your reply.

***@***.*** sc]$ srapath SRR22957171
https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR22957171/SRR22957171

I know that the tutorial indicates the option to use AWS or GCS as an alternative to prefetch --type fastq but neither AWS nor GCS are supported by my institution so the only option I have is to rely on SRAToolkit (and I really need those data).
BW

Sara Valpione

**Comment by klymenko** [comment]
Fastq files are located in cold store.
Contact sra@ncbi.nlm.nih.gov .

**Comment by klymenko** [comment]
@SaraValpione, do you need more help?
