### ISSUE TITLE
recipe for target 'adapter' failed

### ISSUE THREAD

**Issue by blaiseli** [ncbi/sra-tools#8]
My script for installing sra-tools from the github repository used to work (last month on the same computer it worked). Now it fails as follows (`<username>` is for anonymization):

    make[1]: *** No rule to make target '/home/<username>/src/ngs/ngs-sdk/adapter/unix/x86_64/atomic32.h', needed by '/home/<username>/ncbi-outdir/ngs-sdk/linux/gcc/x86_64/rel/obj/adapter/Refcount.pic.o'.  Stop.
    make[1]: Leaving directory '/home/<username>/src/ngs/ngs-sdk/adapter'
    /home/<username>/src/ngs/ngs-sdk/Makefile.rules:31: recipe for target 'adapter' failed
    make: *** [adapter] Error 2
    get_sra-tools.sh: ngs-sdk build failed

(I was trying to update after noticing strange error messages using fastq-dump (reporting being version 2.4.3), that did not seem to prevent the fastq data from being dumped from a pre-downloaded .sra archive)

**Comment by kwrodarmer** [comment]
Please try `make clean` before running your build.

**Comment by blaiseli** [comment]
Thanks. Inserting a `make clean` between `configure` and `make` seemed to solve the problem.
