### ISSUE TITLE
Tool kit is not functional and no error is showing. 

### ISSUE THREAD

**Issue by Codding-for-life** [ncbi/sra-tools#802]
I just started with coding. I am using my MacBook air. 

I was able to verify that the binaries are found by the shell

However, when I ran "fastq-dump --stdout -X 2 SRR390728" to test the tool kit, nothing happened. 

I checked for a file, but did not find one. Would really love some help on this.

Thank you

**Comment by durbrow** [comment]
You may need to allow the command to execute:

> Apple menu  > System Settings, click Privacy & Security  in the sidebar, then go to Security
