### ISSUE TITLE
Question - Downloading SRA from dbGaP with AWS user credentials

### ISSUE THREAD

**Issue by tudor-turcu** [ncbi/sra-tools#803]
Hi,
I am trying to determine the correct way to download SRA from the dbGaP repository, based on what is documented at https://www.ncbi.nlm.nih.gov/sra/docs/sra-dbGAP-cloud-download/ , https://www.ncbi.nlm.nih.gov/sra/docs/sra-dbgap-download/, or https://github.com/ncbi/sra-tools/wiki/First-help-on-decryption-dbGaP-data

I am using SRA Toolkit 3.0.2 on my local laptop, on Windows 10, and I'm trying to use the test key  ( [prj_phs710EA_test.ngc](https://ftp.ncbi.nlm.nih.gov/sra/examples/decrypt_examples/prj_phs710EA_test.ngc) ) as mentioned at https://www.ncbi.nlm.nih.gov/sra/docs/sra-dbgap-download/#prerequisites  : 
`C:\Tests\SraToolkit\3.0.2\bin\prefetch.exe p -v -t http -O "C:\Users\turcut\SraTest\" -L debug --max-size 10g --verify yes  --ngc "C:\Tests\NCBI_SRA\DbGaP\prj_phs710EA_test.ngc" SRR23043274 `

If I first configure the toolkit by calling vdb-config  (non-interactive), without any additional parameters, all works ok.

However, if I try to set the AWS credentials (from a valid AWS user):
`vdb-config  --set-aws-credentials C:\Tests\SraToolkit\aws-access-key.csv --report-cloud-identity yes --accept-aws-charges yes `
and run the same prefetch command, the download fails:

> 2023-04-03T10:55:45 prefetch.3.0.2 info: HTTP read failure: URL=\"https://sra-ca-run-odp.s3.amazonaws.com/sra/phs000710.c99/SRR23043274/SRR23043274\" status=403; tried 6/6 times for 120 milliseconds total
>2023-04-03T10:55:46 prefetch.3.0.2 int: file unauthorized while opening file within network system module - cannot open remote file: https://sra-ca-run-odp.s3.amazonaws.com/sra/phs000710.c99/SRR23043274/SRR23043274"

I tried also from an AWS EC2 instance (running Windows Server 2019), using a .cart file this time:
`C:\SraToolkit\3.0.2\bin\prefetch  -p -v -t http -O "C:\Users\Administrator\AppData\Local\Temp\2\SraDownloadsTests\" -L debug --max-size 10g --verify yes  --perm "C:\Users\Administrator\SraDbGapTests\cart.jwt\" SRR23043274`

but I get a similar error:
> 2023-04-03T11:35:13 prefetch.3.0.2 info: HTTP read failure: URL=\"https://sra-ca-run-odp.s3.amazonaws.com/sra/phs000710.c99/SRR23043274/SRR23043274\" status=403; tried 6/6 times for 120 milliseconds total
>2023-04-03T11:35:13 prefetch.3.0.2:  HTTPS download failed
>2023-04-03T11:35:13 prefetch.3.0.2: 1) failed to download 'SRR23043274': RC(rcNS,rcFile,rcOpening,rcFile,rcUnauthorized) 

The user-settings.mkfg file contains just this:
`/LIBS/GUID = "0c177128-72d7-4ade-8572-055929ff602b"

/aws/credential_file = "C:TestsSraToolkit\x07ws-access-key.csv"

/libs/cloud/accept_aws_charges = "true"

/libs/cloud/report_instance_identity = "true"

/repository/user/ad/public/apps/file/volumes/flatAd = "."

/repository/user/ad/public/apps/refseq/volumes/refseqAd = "."

/repository/user/ad/public/apps/sra/volumes/sraAd = "."

/repository/user/ad/public/apps/sraPileup/volumes/ad = "."

/repository/user/ad/public/apps/sraRealign/volumes/ad = "."

/repository/user/ad/public/apps/wgs/volumes/wgsAd = "."

/repository/user/ad/public/root = "."`

Is there some .. incompatibility between having AWS credentials configured in user-settings.mkfg (https://github.com/ncbi/sra-tools/wiki/04.-Cloud-Credentials ) and downloading dbGaP data using the --ngc parameter?

**Comment by klymenko** [comment]
Do not accept-aws-charges.

**Comment by tudor-turcu** [comment]
done

**Comment by klymenko** [comment]
@tudor-turcu  , do you need more help?

**Comment by tudor-turcu** [comment]
Thanks @klymenko - not for now - most of the questions were clarified.

I include below the answer I received, in case somebody else has the same question:


> From: NLM Support 
> Sent: 05 April 2023 23:01
> To: Tudor Turcu 
> Subject: RE: [EXTERNAL] RE: case #CAS-1089329-V2X3W1: Question - Downloading SRA from dbGaP with AWS us... TRACKING:000393000014855
> You can specify the file types when downloading with the cloud data delivery service (SRA format or original format).
> Best,
> Rick_
> 
 
> 
> _From: Tudor Turcu ;
> Received: Tue Apr 04 2023 02:32:22 GMT-0400 (Eastern Daylight Time)
> To: nlm-support@...;
> Subject: [EXTERNAL] RE: case #CAS-1089329-V2X3W1: Question - Downloading SRA from dbGaP with AWS us... TRACKING:000393000014855
> 

> Thanks for clarifying this!
> All I wanted is to make sure that, if possible, the actual SRA download is done from the S3 bucket instead of the old NCBI server, regardless of where we run the SRA Toolkit .
>  
> This will complicate a bit our implementation, since we will have to modify at runtime the toolkit config file, by including or not the AWS credentials, if the SRA is public/unrestricted, or restricted/dbGaP, and to download separately the SRAs for each case.. ☹
> (ex.: the user could specify 50 SRA accession Ids, out of which 23 are dbGaP, and the rest are not)
>  
> About SRA's cloud data delivery service – I thought that this is possible only for the original files submitted to SRA, not for the ‘processed’ SRAs.
>  
> Best regards,
> Tudor_
> 
> _From: NLM Support 
> Sent: 03 April 2023 23:05
> To: Tudor Turcu 
> Subject: Re: case #CAS-1089329-V2X3W1: Question - Downloading SRA from dbGaP with AWS us... TRACKING:000393000014855
>  
> You cannot configure the toolkit to use AWS credentials and use the ngc key. If you are using the toolkit on your local laptop, do not configure the AWS tab in vdb-config. 
>  
> Please use the SRA's cloud data delivery service ([https://www.ncbi.nlm.nih.gov/sra/docs/data-delivery/] if you would like to transfer files directly to an AWS bucket.
>  
> Best,
> Rick Lapoint
> SRA Curator_
