### ISSUE TITLE
SSL Connection Error with Fastq-dump

### ISSUE THREAD

**Issue by seanjedi** [ncbi/sra-tools#808]
Hello, I am new to sra-tools and getting data in general, and I seem to be facing an SSL connection error when trying to use fastq-dump.

I am getting error messages when trying to access data from NCBI, specifically this dataset here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE226315 

This is the error message I get:
`
2023-04-09T21:59:30 test-sra.2.8.0 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )
2023-04-09T21:59:30 test-sra.2.8.0 sys: mbedtls_ssl_get_verify_result returned 0x8 (  !! The certificate is not correctly signed by the trusted CA  )
`

![image](https://user-images.githubusercontent.com/18587013/230798354-08ad4f39-1769-427c-b62b-266a52b985e9.png)

This seems similar to this issue here: 
https://github.com/ncbi/sra-tools/issues/137

I have tried the steps outlined in the issue above, but it doesn't seem to work for me (IE I tried redownloading Conda, and installing the most recent versions of SRA-tools with no luck)

Any suggestions would be highly appreciated, thank you and have a great day!

**Comment by klymenko** [comment]
The solution is [mentioned](https://github.com/ncbi/sra-tools/issues/137#issuecomment-1315876141).
We don't support Conda.

**Comment by klymenko** [comment]
It looks like you don't run the most recent version of SRA tools after downloading it.

**Comment by SteffanChristiansen** [comment]
Had the exact same issue. Installed outside conda as suggested and now I can run the test without any issues. You may find this tutorial useful:
https://www.youtube.com/watch?v=zE851fWCYQg
