### ISSUE TITLE
Failure downloading SRR521450 from S3

### ISSUE THREAD

**Issue by peter-sandor-1992** [ncbi/sra-tools#823]
I'm trying to download the SRA mentioned in the title using the prefetch tool on an AWS EC2 instance from S3:

> $ ./prefetch -p -v -t http -O "./output" -L info --max-size 300g --verify yes SRR521450
> 2023-06-21T15:05:31 prefetch.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
> 2023-06-21T15:05:31 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-21T15:05:31 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-21T15:05:31 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 int: self NULL while reading file within network system module - cannot open remote file: https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-21T15:05:32 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2: 1) Downloading 'SRR521450.sralite'...
> 2023-06-21T15:05:33 prefetch.3.0.2: SRA Lite file is being retrieved, if this is different from your preference, it may be due to current file availability.
> 2023-06-21T15:05:33 prefetch.3.0.2:  Downloading via HTTPS...
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-21T15:05:33 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-21T15:05:34 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-21T15:05:35 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-zq-2.s3.amazonaws.com/SRR521450/SRR521450.sralite.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-21T15:05:35 prefetch.3.0.2:  HTTPS download failed
> 2023-06-21T15:05:35 prefetch.3.0.2: 1) failed to download 'SRR521450.sralite': RC(rcNS,rcFile,rcReading,rcSelf,rcNull)

We configured the toolkit with the following options:
> $ ./vdb-config --set-aws-credentials ./awsCredentials.csv --report-cloud-identity yes --accept-aws-charges yes

The operating system on the EC2 instance is **Ubuntu 20.04.2 LTS**

Disabling the *--accept-aws-charges* option seems to be a workaround for now because that way the download URL falls back to a different one (https://sra-downloadb.st-va.ncbi.nlm.nih.gov/sos5/sra-pub-zq-12/SRR000/521/SRR521450/SRR521450.sralite.1) which retrieves the file successfully.

Every other SRA ID I've tried up to this point is downloaded from the `https://sra-pub-run-odp.s3.amazonaws.com/sra/` bucket without issues.
Is there a specific reason why this one is stored in a different bucket? Are there any other SRA files stored there that I could try to see whether I can reproduce this issue with all of them?

I've also attached the output of the `./test-sra SRR521450` command, hopefully the error message from it will help in figuring out the issue: [test-sra SRR521450.txt](https://github.com/ncbi/sra-tools/files/11819519/test-sra.SRR521450.txt)

Please let me know if you need other details to investigate the issue.

**Comment by peter-sandor-1992** [comment]
Our QA team was able to reproduce this issue with another SRA ID:

> prefetch -p -v -t http -O "./temp" -L info --max-size 300g --verify yes ERX120625
> 2023-06-22T11:41:36 prefetch.3.0.2: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
> 2023-06-22T11:41:36 prefetch.3.0.2: 1) Downloading 'ERR144697'...
> 2023-06-22T11:41:36 prefetch.3.0.2: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
> 2023-06-22T11:41:36 prefetch.3.0.2:  Downloading via HTTPS...
> |-------------------------------------------------- 100%
> 2023-06-22T11:41:42 prefetch.3.0.2:  HTTPS download succeed
> 2023-06-22T11:41:42 prefetch.3.0.2:  'ERR144697' is valid
> 2023-06-22T11:41:42 prefetch.3.0.2: 1) 'ERR144697' was downloaded successfully
> 2023-06-22T11:41:42 prefetch.3.0.2 info: KConfig(repository) found: using VResolver
> 2023-06-22T11:41:43 prefetch.3.0.2: 'ERX120625' has 1 unresolved dependency
> 2023-06-22T11:41:43 prefetch.3.0.2: 2) Downloading 'ncbi-acc:NC_009332.1?vdb-ctx=refseq'...
> 2023-06-22T11:41:43 prefetch.3.0.2:  Downloading via HTTPS...
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-22T11:41:43 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 1/6 times for 0 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 2/6 times for 5 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 3/6 times for 15 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 4/6 times for 30 milliseconds total
> 2023-06-22T11:41:44 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 5/6 times for 60 milliseconds total
> 2023-06-22T11:41:45 prefetch.3.0.2 info: HTTP read failure: URL="https://sra-pub-refseq.s3.amazonaws.com/NC_009332.1/NC_009332.1.1" status=403; tried 6/6 times for 120 milliseconds total
> 2023-06-22T11:41:45 prefetch.3.0.2:  HTTPS download failed
> 2023-06-22T11:41:45 prefetch.3.0.2: 2) failed to download 'ncbi-acc:NC_009332.1?vdb-ctx=refseq': RC(rcNS,rcFile,rcReading,rcSelf,rcNull)

I've also attached the `./test-sra ERX120625` command's output: [test-sra ERX120625.txt](https://github.com/ncbi/sra-tools/files/11833543/test-sra.ERX120625.txt)

It seems that this time the download attempt is from `https://sra-pub-refseq.s3.amazonaws.com/` which also doesn't seem to work (just like `https://sra-pub-zq-2.s3.amazonaws.com` in the original post).
Is there a migration plan to move all these files under `https://sra-pub-run-odp.s3.amazonaws.com/sra/`? That one works without any issues.

**Comment by peter-sandor-1992** [comment]
Attaching the [user-settings.mkfg](https://github.com/ncbi/sra-tools/files/11915631/user-settings.mkfg.txt) configuration file, hopefully this will help with the investigation.

**Comment by klymenko** [comment]
There is a bug in SRA tools that will be fixed in the next release.
aws-credentials that is set by vdb-config is ignored.
The quick workaround is to copy awsCredentials.csv to ~/.aws as credentials.

**Comment by peter-sandor-1992** [comment]
Thanks for letting me know @klymenko!
I'll make sure to test the new version after it's released and close the issue if it's fixed.

**Comment by klymenko** [comment]
Please [try](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) our new release.

**Comment by peter-sandor-1992** [comment]
@klymenko Thanks for getting back to me! I cannot reproduce this issue anymore with the 3.0.2 version either. There was probably some fix on the data/repo layer too because the older version can also correctly find the place where to download the SRA files from. Closing issue.

**Comment by peter-sandor-1992** [comment]
@klymenko sorry I spoke too soon, I did manage to reproduce it today unfortunately. We had the _--accept-aws-charges no_ workaround in place that's why it didn't fail anymore for these IDs.

Even if I use the 3.0.7 (latest) version of the toolkit I get similar errors as before, with a third ID **SRX254364** we've found recently. We also get a new error message here which seems to be unique for this one:

> int: string unexpected while executing query within virtual file system module - multiple response SRR URLs for the same service 's3'

Maybe this will help with the investigation.

I've also attached the outputs of the following commands using the 3.0.7 version, on the same EC2 instance running Ubuntu 20.04:
- `./vdb-config`: [vdb-config-output.txt](https://github.com/ncbi/sra-tools/files/12547885/vdb-config-output.txt)
- `./test-sra SRX254364 > test-sra-output_SRX254364.txt 2> test-sra-output_SRX254364.txt`: [test-sra-output_SRX254364.txt](https://github.com/ncbi/sra-tools/files/12547884/test-sra-output_SRX254364.txt)
- `./prefetch -p -vv -t http -O ./results -L info --max-size 300g --verify yes SRX254364 > prefetch-output_SRX254364.txt 2> prefetch-output_SRX254364.txt`: [prefetch-output_SRX254364.txt](https://github.com/ncbi/sra-tools/files/12547883/prefetch-output_SRX254364.txt)

I've also attached the latest version of the [user-settings.mkfg](https://github.com/ncbi/sra-tools/files/12547861/user-settings.mkfg.txt) file.

As I said above, setting the _--accept-aws-charges_ option to **no** still works, but we'd like to enable it to reduce load on the gov URLs which serves the file without any issues.

**Comment by klymenko** [comment]
Currently we don't support AWS credential file in csv format.
We support just INI files:
```
[default]
aws_access_key_id=foo
aws_secret_access_key=bar
```

**Comment by klymenko** [comment]
2. Error messages ` - multiple response SRR URLs for the same service 's3` appear because you are using experiment accessions, not runs.
The use of SRX accessions is not fully implemented and may or may not work.

**Comment by tudor-turcu** [comment]
Hi @klymenko ,
We discovered the set-aws-credentials parameter and the CSV format by running:

> ...\SraToolkit\3.0.2\bin>vdb-config.exe --help
> ...
> Options:
> ...
>  --report-cloud-identity <yes | no>  Give permission to report cloud instance
>                                    identity.
>   --accept-aws-charges <yes | no>  Agree to accept charges for AWS usage.
>   --set-aws-credentials <path>     Select file with AWS credentials.
>   --set-aws-profile <profile>      Set AWS profile.
>   ...
> 
and the information from https://github.com/ncbi/sra-tools/wiki/04.-Cloud-Credentials 
('_Save the CSV file to your computer and copy it to the location you'll specify to vdb-config in next page_')

Is there another supported way to specify the AWS credentials from the commandline?

**Comment by klymenko** [comment]
Thank you for pointing to these problems in out documentation.

I updated https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump and we are going to add support of csv files in our next release.

**Comment by peter-sandor-1992** [comment]
@klymenko thanks to the details you've provided I was able to get this working on Linux on all our instances! Changing the AWS credentials to the INI format you've suggested made everything work, including the download of SRX experiments - I'm pretty sure it failed before because the experiment contained some runs that downloaded alone would have thrown the same error, due to the AWS credential issue.

However, I have a different issue now, and I'm not sure if I should close this and open a new one or continue the discussion here. We also have Windows Server 2019 instances, where we get the same error as before, regardless of the AWS credential format - both .INI and .CSV throw the same error. Should we configure the AWS credentials differently on Windows? I couldn't find any platform differences in the documentation: https://github.com/ncbi/sra-tools/wiki/04.-Cloud-Credentials

**Comment by klymenko** [comment]
@peter-sandor-1992, do you still need help?

**Comment by peter-sandor-1992** [comment]
@klymenko I believe we still have issues on Windows but it's not a big deal, the Linux was a blocker one. I think it's ok to close this ticket now and I'll open another one if we can't make it work on Windows. Thanks for the help and happy holidays!

**Comment by klymenko** [comment]
@peter-sandor-1992, please try our latest release.
We fixed an issue that could be causing your problem on Windows.
