### ISSUE TITLE
Unable to download SRA files

### ISSUE THREAD

**Issue by arupgsh** [ncbi/sra-tools#83]
fastq-dump -X 5 -Z SRP058229
2017-06-16T12:41:13 fastq-dump.2.8.2 err: item not found while constructing within virtual database module - the path 'SRP058229' cannot be opened as database or table

**Comment by klymenko** [comment]
Please configure the toolkit according to https://github.com/ncbi/sra-tools/wiki/Toolkit-Configuration

**Comment by kwrodarmer** [comment]
Version 2.8.2 of the SRA Toolkit does not operate on projects, but only on runs. There are 14 runs you can supply to fastq-dump to examine data in SRP058229: 

SRR2016724
SRR2016725
SRR2016726
SRR2016727
SRR2016728
SRR2016729
SRR2016730
SRR2016731
SRR2016732
SRR2016733
SRR2016734
SRR2016735
SRR2016736
SRR2016737
