### ISSUE TITLE
vdb-config: option "Prefer SRA Lite files..." has no effect

### ISSUE THREAD

**Issue by nikyk** [ncbi/sra-tools#837]
sra-tools version 3.0.6, binary release.
vdb-config: option "Prefer SRA Lite files..." has no effect. sralite file is downloaded irrelevantly of option selected.
Of course, fasterq-dump produces FASTQ with no read quality (which is not saved in sralite)
Expected behavior: sralite when option set, sra when option unset

**Comment by klymenko** [comment]
Preferred file type is given when it is available.
E.g., when you specify "Prefer SRA Lite files..." and light files are not available from your location - you will get full-quality-files.
