### ISSUE TITLE
prefetch fails for all SRAs:   sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )

### ISSUE THREAD

**Issue by map2085** [ncbi/sra-tools#84]
Lots of errors with prefetch since Friday, June 16.
Sounds a lot like [this other issue](https://github.com/ncbi/sra-tools/issues/74) from this github repo.

$ prefetch  SRR3161834

> 2017-06-17T20:41:53 prefetch.2.8.2 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )
> 2017-06-17T20:41:53 prefetch.2.8.2: 1) Downloading 'SRR3161834'...
> 2017-06-17T20:41:53 prefetch.2.8.2:  Downloading via https...
> 2017-06-17T20:42:23 prefetch.2.8.2 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )
> 2017-06-17T20:42:23 prefetch.2.8.2 int: connection failed while opening file within cryptographic module - failed to open file for https://sra-download.ncbi.nlm.nih.gov/srapub/SRR3161834
> 2017-06-17T20:42:53 prefetch.2.8.2 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -76 ( NET - Reading information from the socket failed )
> 2017-06-17T20:42:53 prefetch.2.8.2 int: connection failed while opening file within cryptographic module - Xp�: Cannot KNSManagerMakeClientRequ
> 2017-06-17T20:42:53 prefetch.2.8.2: 1) failed to download SRR3161834

Another error message from the same command:

> 2017-06-17T20:46:54 prefetch.2.8.2 err: query unauthorized while resolving tree within virtual file system module - failed to resolve accession 'SRR3161834' - Access denied - object has been removed from distribution ( 403 )
> 2017-06-17T20:46:54 prefetch.2.8.2 err: path not found while resolving tree within virtual file system module - 'SRR3161834' cannot be found.

Same error no matter which SRA accession I attempt.

**Comment by kwrodarmer** [comment]
It does not matter which command you use - the error does not occur within the SRA Toolkit tools. The error is external and network related.

Since we switched to using https for all communications, all network errors end up being reported as coming from mbedtls, but this is only where the error is reported. Versions 2.8.2 and before had lighter error REPORTING in release mode, because we were not seeing problems. But we have seen a spike recently and are doing what we can to diagnose them.

Please note that we are not part of an IT support group, so some of our visibility into the problem can be less than straightforward. We're working on it though.

**Comment by map2085** [comment]
OK, thank you.

**Comment by kwrodarmer** [comment]
NIH had some issues with a water cooler last night, and the extent of damage will not be clear until the start of the week.

**Comment by kwrodarmer** [comment]
Please try again now and let us know if it still fails. We had network failures over the weekend that were not repaired until this morning.
SRA Toolkit Team.

**Comment by kwrodarmer** [comment]
On Friday, June 16, 2017, the National Library of Medicine experienced a hardware problem that resulted in the shutdown of the SRA's primary data center. Although the hardware problem was addressed within hours and most services were restored, a few servers continued to experience network issues until this morning, June 19th.

Service was restored as of 9:20 AM EDT.

If you experience any problems accessing the SRA, please write to us at sra@ncbi.nlm.nih.gov.

**Comment by map2085** [comment]
Yes, I confirm that it works again now.
Thank you for the information even though it was not necessarily in your department/responsibility.  Those of us on the outside are unaware of the division of resources and labor with the NIH.

**Comment by kwrodarmer** [comment]
I have tried to address some of the issues we encounter with network errors on this Wiki page:
https://github.com/ncbi/sra-tools/wiki/Network-and-Connection-Errors .

The errors you report are very generic. People will tend to run very reasonable tests such as curl or wget to see if they get the same behavior - sometimes they do, sometimes it appears different. All of the tools use TCP to connect, but as far as we're aware only the SRA uses _partial reads_ to enable random access. `prefetch` is our only tool that does not.

I _will_ say or repeat that in an effort to help us to diagnose network problems, our network code is too chatty and will report errors as soon as they are observed, even while we are repeating each failed attempt a number of times until we eventually succeed or give up. The only time an error will affect results is when we never succeed. I recognize that this behavior is confusing to end users - it was made intentionally chatty to help us give information to our network engineers.

**Comment by SKarr07** [comment]
hello, I have the same issue as in the original comment:

prefetch.2.9.1 sys: connection failed while opening file within cryptographic module - mbedtls_ssl_handshake returned -9984 ( X509 - Certificate verification failed, e.g. CRL, CA or signature check failed )

can this still be a problem of network connection?

**Comment by klymenko** [comment]
@SKarr07, see question # 1 in https://github.com/ncbi/sra-tools/wiki/FAQ
