### ISSUE TITLE
how can I export to PATH

### ISSUE THREAD

**Issue by mick42-star** [ncbi/sra-tools#847]
**When I ran fastq-dump without './ ' ,it will not find the command. and it will run when I use ./fastq-dump.**

~ % cd /Users/sratoolkit.3.0.7-mac64/bin
bin % fastq-dump
zsh: command not found: fastq-dump
bin % ./fastq-dump
Usage:
  ./fastq-dump [options] <path> [<path>...]
  ./fastq-dump [options] <accession>

Use option --help for more information

./fastq-dump : 3.0.7

**Then I tried to add PATH to .bash_profile with these commands**
export PATH=$PATH:'/Users/sratoolkit.3.0.7-mac64/bin'
export PATH=$PATH:./ 
~ % fastq-dump
zsh: command not found: fastq-dump

It still cannot find fastq-dump in home directory.

I wonder how should I export PATH correctly

**Comment by klymenko** [comment]
.bash_profile is bash specific, you are running zsh.

**Comment by williamtbarker** [comment]
nano ~/.zshrc is what you're searching for
