### ISSUE TITLE
fasterq-dump --split-files SRR1718500 paired reads have different names

### ISSUE THREAD

**Issue by achristofferson-bbi** [ncbi/sra-tools#848]
Hello,

With the following command two fastq files are created but at the end of the fastqs the paired reads start to have different names which causes bwa-mem2 mem to fail with:
[mem_sam_pe] paired reads have different names: "SRR1718500.530041463", "SRR1718500.530041445"

fasterq-dump --split-files SRR1718500

tail -n8 SRR1718500_1.fastq
@SRR1718500.532255342 532255342 length=101
CTCCTGACCTCAGGTAATCCACCTGCCTTGGCCCCCCAAAGTGCTGTGATTACAGGTGTGAACCACCACACCGGCCTTAACTGTTCAGATCGGAAGAGCAC
+SRR1718500.532255342 532255342 length=101
?????????????????????????????????????????????????????????????????????????????????????????????????????
@SRR1718500.532255345 532255345 length=101
TATCAGTTGGGAGACTGATGTAGTGGCATAGTAAGAAACAACAAAGCTCAGAATATAGGCAGTGGTAGCAGAAATAGAGAGGACAGGAGATTAAGATTTAA
+SRR1718500.532255345 532255345 length=101
?????????????????????????????????????????????????????????????????????????????????????????????????????

tail -n8 SRR1718500_2.fastq
@SRR1718500.532255343 532255343 length=101
ATCTTGAATGGTAGGGAATCAGCAAAGATTCCCTTCCATCAACCCAACCTTCGATACTGTTGTAAAGACTTCTGTTTTAAAGATCGGAAGAGCGTCGTGTA
+SRR1718500.532255343 532255343 length=101
?????????????????????????????????????????????????????????????????????????????????????????????????????
@SRR1718500.532255344 532255344 length=101
AAGTGCCGCAAATGTCCAACGGCAGATTCTACAAAAAGAGTGTTTCAAAGCTGCTAAATCAAAAGAAATGTTCAACTCTGTGAGATGAAAGCACACATCAC
+SRR1718500.532255344 532255344 length=101
?????????????????????????????????????????????????????????????????????????????????????????????????????

Is there an option to include the missing paired reads or exclude these that do not have a proper pair?

**Comment by achristofferson-bbi** [comment]
Using the default options with 
fasterq-dump SRR1718500

results in the expected three files of 
SRR1718500_1.fastq
SRR1718500_2.fastq
SRR1718500.fastq

However, there is no information in the SRR1718500.fastq file that says what read (1|2) it belongs too.
Maybe there is a tool that can combine the extra reads in the SRR1718500.fastq back into the correct location in the SRR1718500_1.fastq or SRR1718500_2.fastq based on wither or not the read name it missing?

**Comment by jesswiley-PBio** [comment]
This issue also make using the paired reads with Trimmomatic crash as it cannot read the quality score as Phred+33. Does anyone have a fix for this issue?

**Comment by durbrow** [comment]
This is what `--split-files` does. You want `--split-3`.
`--split-files` puts each read in its own file, read 1 in _1, read 2 in _2, and so on, without regard to pairing things up.
`--split-3` puts read 1 in _1 and read 2 in _2 if there are both reads, everything else (e.g. unpaired reads) goes into another file.
