### ISSUE TITLE
fastq-dump --offset documentation is ambiguous

### ISSUE THREAD

**Issue by rrohwer** [ncbi/sra-tools#85]
Hi, this is an issue about ambiguous documentation, not a code bug.

It is not clear to me from the documentation if the `--offset` specifies the original submitted format or the output format you would like. The phrasing you use is: 
```
  -Q|--offset <integer>            Offset to use for quality conversion,
                                   default is 33
```
So for example, if the data I want to download was created using Illumina 1.3, but I want to view the quality scores as standard phred scores: 
* should I specify `--offset 33` because I want SRA to convert it to offset 33 
* or `--offset 64` because I want SRA to convert it to fastq correctly from an offset 64 sequencing platform's raw data. 

Thanks,
Robin

**Comment by kwrodarmer** [comment]
FASTQ is defined as bases plus Phred scores, not log-odds or anything else. `fastq-dump` reads the quality values from an SRA object as phred in all cases, where the purpose of the `--offset` parameter is to specify the character encoding to use.

The SRA has over the years preserved qualities in log-odds, 4-channel log-odds, and phred, but always provides a conversion to phred upon read. The only way to retrieve original scores (if they were even submitted) is to read them using a tool that requests them specifically.

For several years now, the community has converged on phred scores. SAM and BAM require them, so the original values tend to get lost.

So you don't need to do anything special to get phred scores, ASCII-encoded by default with offset 33.

**Comment by kwrodarmer** [comment]
Hi @rrohwer, should I close this or is there something else?

**Comment by rrohwer** [comment]
Thank you @kwrodarmer ! Your explanation made it really clear to me.  Now I Understand that the "quality conversion" means from log odds to the fastq value, which by default is offset 33. Thanks so much!

Robin
