### ISSUE TITLE
Prefetch finished with no error

### ISSUE THREAD

**Issue by Wang0293** [ncbi/sra-tools#855]
“Current preference is set to retrieve SRA Normalized Format files with full base quality scores.” displayed and then prefetch finished directly.
Who knows what's the wrong?

**Comment by bvaldebenitom** [comment]
Hi,

are you running this through a job scheduling system? I was getting the same message, but running `prefetch` on a clean terminal worked.

**Comment by Wang0293** [comment]
> Hi,
> 
> are you running this through a job scheduling system? I was getting the same message, but running `prefetch` on a clean terminal worked.

I have tried it but failed, may be different question.

**Comment by klymenko** [comment]
@Wang0293, what is your `prefetch` command line?

**Comment by Wang0293** [comment]
> @Wang0293, what is your `prefetch` command line?

I used the simplest command:
`prefetch SRR1173821`
but failed too.

**Comment by klymenko** [comment]
What is the output of the following?
`curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR1173821`

**Comment by Wang0293** [comment]
> What is the output of the following? `curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR1173821`

`{
    "version": "2",
    "result": [
        {
            "bundle": "SRR1173821",
            "status": 200,
            "msg": "ok",
            "files": [
                {
                    "object": "srapub|SRR1173821",
                    "accession": "SRR1173821",
                    "type": "sra",
                    "name": "SRR1173821",
                    "size": 13227449800,
                    "md5": "a58577a516c12c6e1cfb50ca1259e291",
                    "modificationDate": "2014-02-20T20:24:27Z",
                    "locations": [
                        {
                            "service": "s3",
                            "region": "us-east-1",
                            "link": "https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR1173821/SRR1173821"
                        }
                    ]
                }
            ]
        }
    ]
}`
That's the result.

**Comment by klymenko** [comment]
What is the output of the following?
`srapath SRR1173821`

**Comment by Wang0293** [comment]
> What is the output of the following? `srapath SRR1173821`

Surprisingly, it works well now, and `prefetch` also works well.
However, in my memory, this command outputted nothing when I tried it after failed download some days ago. And the same commands (`prefetch` and `srapath`) were tried on a clean terminal and I got the same output.
In fact, I downloaded 132 samples by accession number using `--option-file` that day, and got 11 *.sra files successfully. Others finished just showed `Current preference is set to retrieve SRA Normalized Format files with full base quality scores.`.
I can't understand what happened but I can use it normally now. I didn't do anything after opened this issue !!!
Do you have some possible explanation?
Very thanks for your time.

**Comment by klymenko** [comment]
Now it is difficult to say what was the exact reason of failure.
Most likely you had problems in network connections to NCBI resources.

**Comment by Wang0293** [comment]
> Now it is difficult to say what was the exact reason of failure. Most likely you had problems in network connections to NCBI resources.

Probably, yes. Network of our server is unstable.
I'll try `curl` in the first place if I repeated it again.
Truly appreciate for your help.
