### ISSUE TITLE
Can not use Aspera in perfetch command

### ISSUE THREAD

**Issue by HowcanIwriteCode** [ncbi/sra-tools#864]
`-a|--ascp-path <ascp-binary|private-key-file>  Path to ascp program and private key file (asperaweb_id_dsa.putty) 
 --ascp-options <value> Arbitrary options to pass to ascp command line. `

I want to use Aspera to speed up downloads, but I can not find 'private-key-file' in Aspera directory 
![image](https://github.com/ncbi/sra-tools/assets/47035765/0008c32a-f78f-45c5-ae12-4032807e0f34)

Is this command disabled? If not what command should be changed to?

**Comment by klymenko** [comment]
Aspera download is not available anymore,
