### ISSUE TITLE
Where's The Documentation on SRA Tools Commands?

### ISSUE THREAD

**Issue by felixm3** [ncbi/sra-tools#867]
I'm reading a pipeline on variant calling whose first step is pulling data from the SRA.

The first command is sam-dump.

I did a web search and it looks like this is an SRA Tools command.

Where can I find documentation on the use of this and other SRA Tools commands please?

It's not mentioned in the Wiki here.

**Comment by klymenko** [comment]
Run `sam-dump -h`
