### ISSUE TITLE
prefetch not downloading phenotype files with SRA toolkit v3.0.7

### ISSUE THREAD

**Issue by kevin198930** [ncbi/sra-tools#873]
Hi, I'm trying to download phenotype data files from dbGap using the prefetch tool but haven't had any success.

Command:
/Users/ks/sratoolkit.3.0.7-win64/bin/prefetch --ngc my_ngc_file.ngc my_cart_file.krt

Checking sizes of kart files...
Output:
2023-11-03T01:45:29 prefetch.3.0.7: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.

Nothing is downloaded and I'm using the latest SRA toolkit version 3.0.7. It's only about 1.5 MB of data. I've seen the same problem in other posts but no solution was presented, only to try an earlier version of SRA toolkit. However, that hasn't worked for me and I noticed another user in post #744 also had no success with the earlier version. I was wondering if there are any new solutions to solve this issue. Thanks.

**Comment by stineaj** [comment]
Are you using a windows operating system? The paths being given use slashes that suggest this is a unix environment instead. If you are using a ubuntu or similar virtual machine within your windows computer you should attempt using the version of the toolkit that most closely matches the unix version you are using.

**Comment by kevin198930** [comment]
I am using Windows Powershell. The command part has the C: syntax left out in my post, but the actual command that led to no files being downloaded does include the C: syntax. The correct syntax that I used in power shell is below:

Command:
C:\Users\ks\sratoolkit.3.0.7-win64\bin\prefetch --ngc my_ngc_file.ngc my_cart_file.krt

Checking sizes of kart files...
Output:
2023-11-03T01:45:29 prefetch.3.0.7: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.

**Comment by akhilpampana** [comment]
I just want to followup to see if this issue has been resolved. I am also facing the same issue and am not sure how to fix it. I have been using Linux version of the dataset and still having issues with the download.

**Comment by klymenko** [comment]
What is the output of the following:
`curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR000001`

**Comment by akhilpampana** [comment]
Hello, The issue was resolved with the updated version of prefetch and Ascp. Thank you so much for the help.

**Comment by kevin198930** [comment]
Do you mean an updated version of prefetch and Ascp within SRA toolkit v3.0.7? Or is a different version of SRA toolkit required? I am using SRA toolkit v3.0.7 and prefetch is not downloading the files.

**Comment by akhilpampana** [comment]
An updated version of ascp resolved the issue with the SRA toolkit v3.0.7

**Comment by kevin198930** [comment]
Thanks, could you share a link to where to download ascp as a standalone file because I already have SRA toolkit v3.0.7 downloaded. Also, according to this post by SRA-Toolkit, only prefetch should be used to download kart files and not ascp. Since I am trying to download the contents of a kart file, I don't know if ascp would be applicable?

https://github.com/ncbi/sra-tools/wiki/HowTo:-Access-SRA-Data

**Comment by klymenko** [comment]
@kevin198930, ascp download is not supported anymore.

**Comment by kevin198930** [comment]
I wanted to follow up to see if anyone has a working solution to this issue?

**Comment by klymenko** [comment]
What is the output of the following:
curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR000001

**Comment by kevin198930** [comment]
Thanks, the output is the following:

PS C:\Users\ks> curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR000001
curl : <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_ACCESS_DENIED>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>
<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a
href="https://locate.ncbi.nlm.nih.gov/*">https://locate.ncbi.nlm.nih.gov/*</a></p>
<blockquote id="error">
<p><b>Access Denied.</b></p>
</blockquote>
<p>Access control configuration prevents your request from being allowed at this time. Please contact your service
provider if you feel this is incorrect.</p>
<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3
A%20prdn-proxy-01.oit.duke.edu%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Wed,%20
10%20Jan%202024%2020%3A22%3A18%20GMT%0D%0A%0D%0AClientIP%3A%2010.136.206.128%0D%0A%0D%0AHTTP%20Request%3A%0D%0ACONNECT%
20%2F%20HTTP%2F1.1%0AUser-Agent%3A%20Mozilla%2F5.0%20(Windows%20NT%3B%20Windows%20NT%2010.0%3B%20en-US)%20WindowsPowerS
hell%2F5.1.20348.2110%0D%0AProxy-Connection%3A%20Keep-Alive%0D%0AHost%3A%20locate.ncbi.nlm.nih.gov%3A443%0D%0A%0D%0A%0D
%0A">root</a>.</p>
<br>
</div>
<hr>
<div id="footer">
<p>Generated Wed, 10 Jan 2024 20:22:18 GMT by prdn-proxy-01.oit.duke.edu (squid/3.5.20)</p>

</div>
</body></html>
At line:1 char:1
+ curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR000001
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by klymenko** [comment]
See https://github.com/ncbi/sra-tools/wiki/Firewall-and-Routing-Information

**Comment by lxzzzzzzzzzzzzzzzzzzzz** [comment]
I also encountered the same problem, may I ask whether it was finally solved.
