### ISSUE TITLE
vdb-config, not working  sratoolkit

### ISSUE THREAD

**Issue by gungil07** [ncbi/sra-tools#880]
I just started learning how to download FASTQ. So, I installed sratoolkit.3.0.7, and to do config, I run ./vdb-config, but I got an error message, Abort trap: 6.
my mac is old system, version 10.15.7
What should I do?

**Comment by gungil07** [comment]
Is it true that sratoolkit needs Mac OS X 12.6...
I got these messages as well - which was built for Mac OS X 12.6

**Comment by klymenko** [comment]
Try to build the toolkit yourself.
