### ISSUE TITLE
Failed to call external services.

### ISSUE THREAD

**Issue by jestlin15** [ncbi/sra-tools#882]
Hi, I am facing this "Failed to call external services. " issue when I run`./fasterq-dump –-split-files -O /Volumes/LaCie SRR3140235`. Can I please get some help? I am on a MacOS with sea version 3.0.7. 

When I run `srapath SRR3140235` , I get: 
`https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR3140235/SRR3140235`

**Comment by durbrow** [comment]
Are you still having this problem? This is usually a temporary problem with the SRA Data Locator service at NCBI.

**Comment by jestlin15** [comment]
Hi, I re-tried it there and it works now! Thank you~
