### ISSUE TITLE
prefetch not working, no error message 

### ISSUE THREAD

**Issue by m-neuhoff** [ncbi/sra-tools#884]
Hi, I have installed the sratoolkit sticking to this instructions https://github.com/ncbi/sra-tools/wiki but it is <br>1. not downloading any files <br>2. nor creating any directories <br> 3. and unfortunately also not giving me error messages to work on. <br> I am working on a cluster with slurm as workload manager. If anyone could point me into a direction, whether it is the internet connection or something else, share a helpful link or a tip what I forgot to check or do, everything is welcome. =) 

I used this commands:
1) /path/to/prefetch --max-size 10g --option-file /path/to/SRR_test_list.txt
2) /path/to/prefetch --max-size 10g SRR11963181

I got this in my errorfile for 1) (list contains two SRR_IDs):
2023-11-23T05:40:30 prefetch.3.0.7: Current preference is set to retrieve SRA Lite files with simplified base quality scores.
2023-11-23T05:41:30 prefetch.3.0.7: Current preference is set to retrieve SRA Lite files with simplified base quality scores.
this for 2):
2023-11-23T10:11:57 prefetch.3.0.7: Current preference is set to retrieve SRA Lite files with simplified base quality scores.
(accordingly for normal quality)

I tried using srapath in the script to check wether it can find a path too, but it does not produce any output nor error message.  If I use the same command directly in the terminal, it does print the correct link, though.

What I did or checked to get prefetch working:
In the sratoolkit configuration remote access and local file caching is enabled.
I set the user repository and ticked the box that it saves downloaded files in the user repository.
I defined the error and output files to be created in a different directory than the one I defined as the user repository.
I checked the available space.
I set the --max-size so that it is enough for my test run (with only one to two files to download).
I tried with lite and with normal quality.
I tried different SRR-IDs.
I scaled up the memory request for the slurm job.

**Comment by klymenko** [comment]
Most likely you do not have access to NCBI servers.
