### ISSUE TITLE
why sra file is much large then decompressed fastq file?

### ISSUE THREAD

**Issue by yhg926** [ncbi/sra-tools#892]
I have fastq-dump this run ERR4575751, and the fastq file is much smaller then .sra file ,why? do i miss some data?
And, could I trust the fastq file decompressed?

<img width="521" alt="Screen Shot 2023-12-21 at 11 32 27 AM" src="https://github.com/ncbi/sra-tools/assets/16019807/38b55a39-cb7f-4ce0-beb3-bf220de2047e">

**Comment by durbrow** [comment]
[ERR4575751](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=ERR4575751&display=alignment) also contains alignments, the fastq file only contains the reads and not the alignments.

**Comment by durbrow** [comment]
File size is a poor estimator of the size of the fastq. Use the number of bases and the number of spots.
