### ISSUE TITLE
original format fastq files

### ISSUE THREAD

**Issue by sherinesaber** [ncbi/sra-tools#895]
Hello, is it possible to use fasterq-dump to download original format fastq files?

prefetch and fastq-dump are too slow. 

I tried to prefetch SRR21834810 but it did not work at all. I wanted to prefetch the accession first then use fastq-dump for original fasta format.

**Comment by wraetz** [comment]
I just checked SRR21834810, it has also only 1 biological read per spot, but 3 technical ones...
I you think there is something wrong with this layout, please contact: sra-tools@ncbi.nlm.nih.gov
