### ISSUE TITLE
how to download only SRA Normalized Format files with full base quality scores using Prefetch

### ISSUE THREAD

**Issue by Balu-Anupoju-Vt** [ncbi/sra-tools#897]
I require SRA Normalized Format files containing complete base quality scores for my analysis. However, the "prefetch" command downloads only the lite version for certain #SRR numbers, despite using prefetch with default parameters. Does this imply that the Normalized Format is unavailable for some #SRR numbers?

Note: I assume that the default parameters in prefetch always download SRA Normalized Format, or is it necessary to provide additional parameters to ensure that prefetch exclusively downloads the Normalized format?

<img width="942" alt="image" src="https://github.com/ncbi/sra-tools/assets/131491378/c5eeea7d-cc30-487e-b971-638626ee9241">

**Comment by klymenko** [comment]
export NCBI_VDB_QUALITY=R
It will enforce use just files with full quality scores.
SRA tools will fail if such files are not available.

**Comment by Balu-Anupoju-Vt** [comment]
Thanks. The Prefetch is now throwing an error when there are no files with full quality scores. Is there a method to obtain the files with full quality score from an alternative location?

Note: Additionally, could you provide instructions on how to revert (export NCBI_VDB_QUALITY=R) if I need to work with Sralite files?
