### ISSUE TITLE
Read names not normal

### ISSUE THREAD

**Issue by vappiah** [ncbi/sra-tools#898]
Hi Developers,

I used fasterq-dump to download reads from SRA 
_fasterq-dump --split-files -e 8 ERR024816_ 
And output files were named as ERR024816_1 and ERR024816_3 
I was expecting _1 and _2 since the data was paired-end. Are the names okay?

Vincent

**Comment by wraetz** [comment]
Yes the filenames are as expected in the '--split-files' mode. What you actually want is the '--split-3' mode. That is also the default mode. That means 'fasterq-dump -e 8 ERR024816' is the right commandline for you.
You can see the details at: [https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump]
