### ISSUE TITLE
Prefetch stuck for hours

### ISSUE THREAD

**Issue by ATpoint** [ncbi/sra-tools#90]
Hello, I am using prefetch (ascp) to load multiple SRRs. Most of them are loaded without problem, but some, such as SRR316001 appear to be stuck at the end of the download. The ~6.5GB of the mentioned file are downloaded in like 1min, but then for hours, no reaction. The tmp-file is not converted to sra, and the aspera-key and lock are not removed. I tested it on two different machines, but no success. Could you please check if this is a files-specific issue?

Thanks!
-ATPoint

**Comment by kwrodarmer** [comment]
SRR316001 is under authorized access, which involves quite a few more moving parts than public SRA. Please send a detailed description to sra-tools@ncbi.nlm.nih.gov including time stamps and an exact transcript of commands and responses and we will work with our systems team to match events with logs.
