### ISSUE TITLE
err: insp_get_file_size

### ISSUE THREAD

**Issue by VikArz02** [ncbi/sra-tools#906]
Hello! Thank you for this great programm. Unfortunatly, i have the error:

My input: ~/Soft/sratoolkit.3.0.10-ubuntu64/bin/fasterq-dump -p -e 1 --outdir raw_sra/ SRR13997107

And the error is 2024-02-01T13:33:58 fasterq-dump.3.0.10 err: insp_get_file_size( 'https://sra-downloadb.be-md.ncbi.nlm.nih.gov/sos3/sra-pub-zq-22/SRR013/13997/SRR13997107/SRR13997107.lite.1', remotely = YES ) -> RC(rcNS,rcFile,rcCreating,rcTimeout,rcExhausted)

How i can solve it?

**Comment by durbrow** [comment]
There isn't really anything that you can do to fix it other than to try again later. The problem is on the remote side, i.e. the servers at NCBI.

You could try `prefetch SRR13997107` followed by `fasterq-dump ... SRR13997107`. `prefetch` might still timeout, but it is resumable.
