### ISSUE TITLE
fasterq-dump error

### ISSUE THREAD

**Issue by linsson** [ncbi/sra-tools#909]
Hi. I'm having problems recovering fastq files from 11 accessions: 

SRR8640104
SRR8640113
SRR8640126
SRR8640135
SRR8640138
SRR8640142
SRR8640152
SRR8640160
SRR8640164
SRR8640166
SRR8640178

Apparently the error occurs after prefetch-ing when I try to use fastq-dump to recover fastq files.

> $ vdb-validate SRR8640178
> 2024-02-19T08:25:59 vdb-validate.3.0.10 info: Database 'SRR8640178.sra' metadata: md5 ok
> 2024-02-19T08:25:59 vdb-validate.3.0.10 info: Table 'SEQUENCE' metadata: md5 ok
> 2024-02-19T08:26:00 vdb-validate.3.0.10 info: Column 'ALTREAD': checksums ok
> 2024-02-19T08:26:00 vdb-validate.3.0.10 info: Column 'QUALITY': checksums ok
> 2024-02-19T08:26:01 vdb-validate.3.0.10 info: Column 'READ': checksums ok
> 2024-02-19T08:26:33 vdb-validate.3.0.10 info: Database 'SRR8640178.sra' is consistent

> $ fasterq-dump SRR8640178
> 2024-02-19T08:26:57 fasterq-dump.3.0.10 err: insp_read_len().VCursorCellDataDirect( NAME ) -> RC(rcSRA,rcColumn,rcReading,rcRow,rcNull)
> 
> An error occurred during processing.
> A report was generated into the file '/home/aprea/ncbi_error_report.txt'.
> If the problem persists, you may consider sending the file
> to 'sra-tools@ncbi.nlm.nih.gov' for assistance.

> fasterq-dump quit with error code 3

[ncbi_error_report.txt](https://github.com/ncbi/sra-tools/files/14328593/ncbi_error_report.txt)

Am I missing something?

Thank you.

**Comment by durbrow** [comment]
There are problems with the data. We have requested that they get reloaded. You can email [sra@ncbi.nlm.nih.gov](mailto:sra@ncbi.nlm.nih.gov) with this issue. They may be able to keep you up-to-date on the reload process.
