### ISSUE TITLE
prefetch could not download data

### ISSUE THREAD

**Issue by lxzzzzzzzzzzzzzzzzzzzz** [ncbi/sra-tools#911]
When I use prefetch to download SRA data, The result only shows 
"Current preference is set to retrieve SRA Normalized Format files with full base quality scores. "
There was no result, but I successfully downloaded the data before, and suddenly this happened. I tried to reinstall different versions of sra-tool, but I still couldn't download it. Has anyone encountered the same problem.

**Comment by klymenko** [comment]
What is the output of the following:
`curl https://locate.ncbi.nlm.nih.gov/sdl/2/retrieve?acc=SRR000001`

**Comment by lxzzzzzzzzzzzzzzzzzzzz** [comment]
When I run this line of code, the result shows
"curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to locate.ncbi.nlm.nih.gov:443"

**Comment by klymenko** [comment]
See [my response to issues/873](https://github.com/ncbi/sra-tools/issues/873#issuecomment-1887601819).
