### ISSUE TITLE
Issues downloading with fasterq-dump

### ISSUE THREAD

**Issue by bnovak32** [ncbi/sra-tools#916]
We ran into issues downloading samples from project DRP009700. All run accessions for this project were affected. The run downloads correctly with prefetch, but fasterq-dump quits with "error code 3" and no further information.

The error message is:
```
fasterq-dump quit with error code 3
```

Initial attempt was with sra-tools 3.0.0. I updated to 3.1.0 and had the same issue.

We were able to download the files successfully using the fastq-dump tool instead.

**Comment by klymenko** [comment]
What is your `fasterq-dump` command line?

**Comment by bnovak32** [comment]
I used prefetch first:
`prefetch --max-size 500G --progress -O DRS284030-tmp/ DRR384607`
followed by fasterq-dump:
`fasterq-dump --progress -O DRS284030-tmp/ --seq-defline '@$ac.$si $sn $ri' --qual-defline '+' DRR384607 `

Switching to this fastq-dump command instead works successfully:
`fastq-dump -O DRS284030-tmp/ --defline-seq '@.  ' --defline-qual '+' DRS284030-tmp/DRR384607 --split-3 --skip-technical`

**Comment by klymenko** [comment]
Correct your `fasterq` command:
fasterq-dump --progress -O DRS284030-tmp/ --seq-defline '@$ac.$si $sn $ri' --qual-defline '+' `DRS284030-tmp/DRR384607`

`prefetch` downloaded `DRR384607` to `DRS284030-tmp/`

**Comment by bnovak32** [comment]
I tried the suggested modification and got the same error:

```
% prefetch --progress -O DRS284050-tmp/ DRR384627

2024-03-22T15:11:32 prefetch.3.1.0: Current preference is set to retrieve SRA Normalized Format files with full base quality scores.
2024-03-22T15:11:33 prefetch.3.1.0: 1) Downloading 'DRR384627'...
2024-03-22T15:11:33 prefetch.3.1.0: SRA Normalized Format file is being retrieved, if this is different from your preference, it may be due to current file availability.
2024-03-22T15:11:33 prefetch.3.1.0:  Downloading via HTTPS...
|-------------------------------------------------- 100%
2024-03-22T15:14:13 prefetch.3.1.0:  HTTPS download succeed
2024-03-22T15:14:14 prefetch.3.1.0:  'DRR384627' is valid
2024-03-22T15:14:14 prefetch.3.1.0: 1) 'DRR384627' was downloaded successfully
2024-03-22T15:14:14 prefetch.3.1.0: 'DRR384627' has 0 unresolved dependencies
% fasterq-dump --progress -O DRS284030-tmp/ --seq-defline '@$ac.$si $sn $ri' --qual-defline '+' DRS284030-tmp/DRR384607


fasterq-dump quit with error code 3
```

**Comment by bnovak32** [comment]
That worked. Thanks!

**Comment by klymenko** [comment]
It's not a glitch.
It's incorrect command line arguments.
`fasterq-dump DRR384607` after download to `DRS284030-tmp/` will work.
If will not use downloaded files but refetch them directly from NCBI.

**Comment by klymenko** [comment]
Suggestion if you want to use a work directory:

Don't specify `-O DRS284030-tmp/`.

Do the following instead:
```
mkdir DRS284030-tmp
cd DRS284030-tmp
prefetch DRR384607
fasterq-dump DRR384607
```
Don't add `-O DRS284030-tmp/` to `prefetch` and `fasterq-dump` commands.

You can remove `DRS284030-tmp/DRR384607/` after you finished conversion to save space.
