### ISSUE TITLE
make_joined_filename() with fasterq-dump

### ISSUE THREAD

**Issue by rchikhi** [ncbi/sra-tools#917]
This accession seems unreadable:

SRR6279421

```
$ s5cmd cp s3://sra-pub-run-odp/sra/SRR6279421/SRR6279421 SRR6279421.sra
$ fasterq-dump --fasta-unsorted --stdout SRR6279421.sra |tail
2024-03-20T13:21:11 fasterq-dump.3.1.0 err: temp_dir.c make_joined_filename() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
spots read      : 0
reads read      : 0
reads written   : 0
```

Tested on a March 10 2024 build of sra-tools

**Comment by rchikhi** [comment]
Oh! But, this is appears unrelated to `--stdout`:

```
$ fasterq-dump --fasta-unsorted  SRR6279421.sra
2024-03-20T14:34:58 fasterq-dump.3.1.0 err: temp_dir.c make_joined_filename() -> RC(rcVDB,rcNoTarg,rcConstructing,rcParam,rcInvalid)
spots read      : 0
reads read      : 0
reads written   : 0
```

But, removing `--fasta-unsorted` makes it output a FASTQ indeed.

**Comment by wraetz** [comment]
I have to investigate this one...

**Comment by wraetz** [comment]
There seems to be a problem combining a Pacbio accession loaded via HDF5 (pacbio-load) and the --fasta-unsorted mode. Fixing this will take a little bit longer... ( in this case just use --fasta instead of --fasta-unsorted )

**Comment by rchikhi** [comment]
Thanks! good to know that `--fasta` fixes it for now
