### ISSUE TITLE
Proxy error after setting up DNS server in tool configuration

### ISSUE THREAD

**Issue by CHANayechan** [ncbi/sra-tools#919]
I installed and set up all setting in configuration (vdd-config -i) and I set up my DNS server. After this, I prefetch dataset and there is an error occurred (err: my proxy number). I restart and re-installed it, but error still remain. How should I change the proxy setting of SRA Toolkit. This is error comment in terminal <no error - Proxy ' 133.11.124.164:0' was ignored>

**Comment by klymenko** [comment]
What is the output of the following?
`vdb-config http`
