### ISSUE TITLE
fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 

### ISSUE THREAD

**Issue by oscarpuig** [ncbi/sra-tools#92]
Not sure if I am doing something wrong. Trying to convert .sra into fastq and it is taking days, with this error

fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

The .sra file is local in my computer, fastq-dump is also local, so why is it trying to connect to NCBI server? and why is the connection failing?

**Comment by kwrodarmer** [comment]
Please give your exact command line and response.

**Comment by oscarpuig** [comment]
path-to-sratoolkit/sratoolkit.2.8.2-1-ubuntu64/bin/fastq-dump --split-files --readids --read-filter pass --clip --skip-technical --gzip SRR3398721.sra

It seems it is working, but very very slow, and I get this error

2017-08-09T18:21:52 fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2017-08-09T18:22:36 fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2017-08-09T18:25:19 fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )
2017-08-09T18:25:40 fastq-dump.2.8.2 sys: error unknown while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

**Comment by kwrodarmer** [comment]
When it runs very slow, either the network itself is slow, or the networking errors that occur will cause the SRA Toolkit to retry according to a configured schedule, which is what would make a process take a very long time.

Questions:
1. How did you download the SRA file?
2. Do you have local file caching enabled?
3. Do you have sufficient cache space on the drive that is downloading references?

**Comment by oscarpuig** [comment]
1) Download was by using this command
path-to-sratoolkit/sratoolkit.2.8.2-1-ubuntu64/bin/prefetch -X 200G path-to-sradata/sradata/dbGAP-14923/cart_file.krt
It downloaded SRR3138930.sra and SRR3398721.sra.vdbcache files
2) I don't believe we have local file caching enabled. Is that a configuration option within ncbi/fastq-dump? Or did you mean at a system level? If caching is built-in to fastq-dump, where is the location of the cache specified? 
3) We have plenty of storage, although we have multiple drives on our machine. Is it possible that fastq-dump automatically defaults to a local cache on the root volume (which does not have as much available space as the current volume with which we are working)? More importantly, why would fastq-dump be attempting to download files at all — we should only be operating on local (already downloaded) SRA files, so our understanding was that no additional downloads should be necessary. If this is not the case, it would be helpful to understand what fastq-dump is doing.

**Comment by oscarpuig** [comment]
Sorry, made a mistake with files, it downloaded SRR3398721.sra and SRR3398721.sra.vdbcache files

**Comment by kwrodarmer** [comment]
If you have the .sra file and the .sra.vdbcache, the only reason to be having any networking is if the external reference files are missing. They would be missing if they were not cached to the reference cache area for whatever reason - either caching is turned off, or you were unaware that the reference cache area may be on a partition with a quota, etc.

Given that we are talking about protected data, I think that to investigate further this should be taken off of the public issue. Please write to us at sra-tools@ncbi.nlm.nih.gov and we can try debugging from there.

**Comment by oscarpuig** [comment]
Ok, thanks. Done.
