### ISSUE TITLE
`fastq-dump` `split-3` cannot generate index file correctly

### ISSUE THREAD

**Issue by jiangpuxuan** [ncbi/sra-tools#927]
Hi,
Here is a scATAC-seq library `.sra` file:

<img width="473" alt="1712120144644" src="https://github.com/ncbi/sra-tools/assets/81287604/bf44e3d4-94ec-4e06-922b-df6dd1dd00f0">

 I used `fasterq-dump --split-files` but only got 2 files (both 50 bp reads) so I did not  get the index file.
 
I knew the parameter `split-file` worked as this chart showed  so it could not work on my  `.sra` file:

![image](https://github.com/ncbi/sra-tools/assets/81287604/7f776f1e-41af-4860-82c0-f81eecf4846b)

 So How could I choose right parameter to dump such library structure?
 
Thank you for your help!

**Comment by wraetz** [comment]
The 2 shorter READS ( L=8 and L=16 ) are considered technical READS by SRA. They are ignored by default. You can ask the tool to extract them by adding "--include technical" to your command-line.

**Comment by jiangpuxuan** [comment]
> The 2 shorter READS ( L=8 and L=16 ) are considered technical READS by SRA. They are ignored by default. You can ask the tool to extract them by adding "--include technical" to your command-line.

Thank you for your advice.
I had tried `--include technical` but nothing happened, still two files.
The log:
```
spots read      : 47,097,428
reads read      : 188,389,712
reads written   : 94,194,856
technical reads : 94,194,856
2024-04-03T14:48:03 fasterq-dump.2.11.0 err: fasterq-dump.c fastdump_csra() checking ouput-file 'SRR21944910.fastq' -> RC(rcExe,rcFile,rcPacking,rcName,rcExists)
fasterq-dump quit with error code 3
```

**Comment by wraetz** [comment]
You need the combination of "--split-files" and "--include technical".
Your command above failed because the output-file(s) do already exist (from your previous attemp). Delete them.

**Comment by jiangpuxuan** [comment]
> You need the combination of "--split-files" and "--include technical". Your command above failed because the output-file(s) do already exist (from your previous attemp). Delete them.

Oh I did not concern the exist output. Now it ran properly.
Thank you for your help!

**Comment by wraetz** [comment]
you are welcome...
