### ISSUE TITLE
fasterq-dump unable to convert sra file to fasta

### ISSUE THREAD

**Issue by krisma2002** [ncbi/sra-tools#929]
Hi All,

I am trying to use fasterq-dump to extract fasta files for this accession ERR260142, but failed.
Whether I re-download the sra file or update the sra-tools version, it doesn't work!
The error shows as follows:

2024-04-19T07:52:47 fasterq-dump.3.1.0 err: cmn_iter.c cmn_read_uint8_array( #10452993 ).VCursorCellDataDirect() -> RC(rcXF,rcFunction,rcExecuting,rcBuffer,rcInsufficient)
2024-04-19T07:52:47 fasterq-dump.3.1.0 err: row #10452993 : READ.len(202) != QUALITY.len(0) (F)
spots read      : 2,022,351
reads read      : 4,044,702
reads invalid   : 1
=============================================================
An error occurred during processing.
A report was generated into the file 'C:\Users\Kris Ma/ncbi_error_report.txt'.
If the problem persists, you may consider sending the file
to 'sra-tools@ncbi.nlm.nih.gov' for assistance.
=============================================================
fasterq-dump quit with error code 3

[ncbi_error_report.txt](https://github.com/ncbi/sra-tools/files/15037881/ncbi_error_report.txt)

Any advice would be appreciated!

**Comment by durbrow** [comment]
Try it again.
```
prefetch ERR260142
fasterq-dump --split-3 ERR260142
```
Don't remove `ERR260142.sra` from the `ERR260142` directory. Don't use the path to the `.sra` file. Just `prefetch` and dump. That is how it is intended to work. Or, because this is a small unaligned accession, you could use `fastq-dump --skip-technical` with negligible loss of performance:
```
fastq-dump --skip-technical --split-3 ERR260142
```

**Comment by krisma2002** [comment]
@durbrow  Well received. This problem was solved perfectly. Thanks!
