### ISSUE TITLE
failed to download ncbi-acc

### ISSUE THREAD

**Issue by tzhu-bio** [ncbi/sra-tools#939]
![image](https://github.com/ncbi/sra-tools/assets/54537420/668b178c-9b51-48ef-a106-268384aa1b0a)

Hello, I'm having this problem when I'm using prefetch to download SRR6240775, SRR6240776.

**Comment by klymenko** [comment]
[Download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit.
