### ISSUE TITLE
Issue with `--max-size u` Argument in Prefetch

### ISSUE THREAD

**Issue by ChongLC** [ncbi/sra-tools#942]
Dear developer,

According to the "Check the maximum-size limit of the 'prefetch' tool" section of the [GitHub wiki page](https://github.com/ncbi/sra-tools/wiki/08.-prefetch-and-fasterq-dump), it appears possible to provide an unlimited maximum size argument using `--max-size u`. However, I encountered an issue when running the following command:
```
prefetch SRR15887667 --max-size U -o test_run
```

The error message received was:
```
2024-06-22T14:08:09 prefetch.2.10.0 err: param invalid while parsing argument list - Maximum requested file size is zero
```

Could you please assist me in resolving this issue? Thank you.

Best regards, 
Chong

**Comment by durbrow** [comment]
> `prefetch SRR15887667 --max-size U -o test_run`

The command line options and parameters are case sensitive. The expected value in this case is 'u' (lower case).

**Comment by ChongLC** [comment]
I tried with the lower case too. It also gives the same error. 

prefetch SRR15887667 --max-size u -o test_run
2024-06-24T14:28:06 prefetch.2.10.0 err: param invalid while parsing argument list - Maximum requested file size is zero

**Comment by klymenko** [comment]
[download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit

**Comment by ChongLC** [comment]
Thank you. It works well with the latest toolkit.
