### ISSUE TITLE
incorrect SAM format when using blastn_vdb and blast_formatter_vdb

### ISSUE THREAD

**Issue by djleite** [ncbi/sra-tools#949]
Hi,

I have an issue with SAM file header formatting. The input FASTA contains two queries, and the blastn_vdb search is against one SRA accession.

After running (example)...
```
blastn_vdb -db SRR23038822 -query input.fasta -out ASN.asn -outfmt 11
```

and...
```
blast_formatter_vdb -archive ASN.asn -outfmt "17 SQ" -out bad_formatted.sam
```

The SAM has the header split, with query 1 and 2 headers and alignments appearing concatenated, rather than correctly combined headers.

I cannot identify why this example causes this issue, and I would appreciate some guidance on how to resolve it or if there are some issues with the tools/commands.

Many thanks

[ASN.asn.gz](https://github.com/user-attachments/files/16284161/ASN.asn.gz)
[bad_formatted.sam.gz](https://github.com/user-attachments/files/16284162/bad_formatted.sam.gz)
[input.fasta.gz](https://github.com/user-attachments/files/16284163/input.fasta.gz)

**Comment by klymenko** [comment]
blastn_vdb and tblastn_vdb binaries are now distributed and supported
by Blast team.

E-mail blast-help@ncbi.nlm.nih.gov with questions or comments.
