### ISSUE TITLE
Obtaining Cloud credentials for Google cloud

### ISSUE THREAD

**Issue by JeffRobson** [ncbi/sra-tools#950]
![Screenshot 2024-07-18 233208](https://github.com/user-attachments/assets/7d66ae4a-3f64-4c6c-b82e-9e2cafd032cf)
I am not able to find where I can enable the access key for GCP in the console for role definitions. Do I need to create an API key first? Attached are the steps and marked in red where I am having issues. Thanks

**Comment by vartanianmh** [comment]
Should look something like this:
![image](https://github.com/user-attachments/assets/dad4cafc-4111-468e-b5e8-4a8d73967ebb)

Are you seeing any GCP permission errors (usually in a gray box) between steps 4 and 5, after hitting Create and Continue?
Were you able to download the service account's JSON key?

![image](https://github.com/user-attachments/assets/c6698704-d5e1-47d5-ab68-1167e32867ab)

**Comment by JeffRobson** [comment]
Thanks, I was able to download the json key and have copied it to the /bin folder in the sra folder location. Still struggling with define the cloud location on the the SRA Toolkit correctly so that large RNA-Seq FASTQ files are deposted directly. I will keep pushing on my own but will reach out to forum when I can't proceed
