### ISSUE TITLE
download original fastq files or split one fastq file into multiple fastq files

### ISSUE THREAD

**Issue by Seungjin1234** [ncbi/sra-tools#951]
I'm trying to download fastq files for PRJNA777966 which consists of from SRR16784064 to SRR16784071.

In each SRR run, there are 6 fastq files. 3 of them are scRNA-seq data(I1, R1, R2), and the others are BCR-seq data(I1, R1, R2). 

When I used 'prefetch' for SRR16784064, for example, I got SRR16784064,sra file. And I used 'fastq-dump', I got 3 fastq files, which are 'SRR16784064_1.fastq', 'SRR16784064_2.fastq', and 'SRR16784064_3.fastq'.

However, there are 6 fastq files in there.

My question is,

1. Is there any method to download 6 original fastq files from the begining?

2. If first is impossible, is there any method to split 3 fastq files which are downloaded from fastq-dump into 6 original fastq files?
If possible by sra-toolkit, could you advise me how to do it?

Thanks

**Comment by durbrow** [comment]
Please send your question to sra@ncbi.nlm.nih.gov. This is primarily a question concerning a complicated set of data (which may have been submitted incorrectly); it isn't a question about the toolkit itself (which is what this repository is for).
