### ISSUE TITLE
File download with sam-dump

### ISSUE THREAD

**Issue by SBaluszek** [ncbi/sra-tools#955]
There's a `Failed to call external services.` error on two independent machines I've tried. I have attempted to modify the vdb-config and still get the error. Is the server up?

I get this error, while executing
`fastq-dump --stdout -X 2 SRR390728`
From this repo _vignette_.

**Comment by klymenko** [comment]
What is the output of `fastq-dump -V` ?

**Comment by klymenko** [comment]
See https://github.com/ncbi/sra-tools/wiki/FAQ#faq1
