### ISSUE TITLE
Google file path not found

### ISSUE THREAD

**Issue by cachris1** [ncbi/sra-tools#957]
I am attempting to fasterq-dump files on google cloud.  I am using a google cloud virtual compute instance, in US-EAST.  I setup my google cloud credentials using vdb-config.  However, when I try to fasterq-dump, or prefetch, I consistently get this error:
```

prefetch SRR29652354
2024-08-14T21:49:01 prefetch.3.1.1: 1) Resolving 'SRR29652354'...
2024-08-14T21:49:01 prefetch.3.1.1: Current preference is set to retrieve SRA Lite files with simplified base quality scores
2024-08-14T21:49:02 prefetch.3.1.1 int: self NULL while reading file within network system module - cannot open remote file: https://storage.googleapis.com/sra-pub-zq-100/SRR29652354/SRR29652354.lite.1
2024-08-14T21:49:03 prefetch.3.1.1: 1) Downloading 'SRR29652354.lite'...
2024-08-14T21:49:03 prefetch.3.1.1:  SRA Lite file is being retrieved
2024-08-14T21:49:03 prefetch.3.1.1:  Downloading via HTTPS...
2024-08-14T21:49:05 prefetch.3.1.1:  HTTPS download failed
2024-08-14T21:49:05 prefetch.3.1.1 int: self NULL while reading file within network system module - 1) failed to download 'SRR29652354.lite'


```
I can use gsutil to copy the file on the path gs://sra-pub-zq-100/SRR29652354/SRR29652354.lite.1, and then get the fastq from there, but this doesn't seem ideal.  

Here is my config:

```
~/.ncbi/user-settings.mkfg 
 auto-generated configuration file - DO NOT EDIT

/LIBS/GUID = "**"
/config/default = "false"
/gcp/credential_file = "/home/cachris/**.json"
/libs/cloud/accept_gcp_charges = "true"
/libs/cloud/report_instance_identity = "true"
/libs/vdb/quality = "ZR"
/repository/user/ad/public/apps/file/volumes/flatAd = "."
/repository/user/ad/public/apps/refseq/volumes/refseqAd = "."
/repository/user/ad/public/apps/sra/volumes/sraAd = "."
/repository/user/ad/public/apps/sraPileup/volumes/ad = "."
/repository/user/ad/public/apps/sraRealign/volumes/ad = "."
/repository/user/ad/public/apps/wgs/volumes/wgsAd = "."
/repository/user/ad/public/root = "."
/repository/user/default-path = "/home/cachris/ncbi"

```

**Comment by klymenko** [comment]
> /gcp/credential_file = "/home/cachris/**.json"

Why do you use star? So you have multiple configuration files?

**Comment by cachris1** [comment]
no its because I did not want to share my google cloud project ID and GUID, I just replaced the values with **.  That was probably just being paranoid though.

**Comment by cachris1** [comment]
Thank you for helping, the commands work now to download the files, but when I `vdb-dump --info`, it gives a path to the NCBI database, not google cloud.  For my project, I need to be able to concurrently download many files at once, and I am worried I will not be able to do this if I am downloading from the ncbi database instead of Google Cloud.  

`vdb-dump --info SRR29652354
acc    : SRR29652354
path   : https://trace.ncbi.nlm.nih.gov/Traces/sdlr/sdlr.fcgi?jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6InNkbHJraWQxIiwidHlwIjoiSldUIn0.eyJhY2MiOiJTUlIyOTY1MjM1NCIsImV4cCI6MTcyNDE5MDQyMSwiZmlsZVNpemUiOiIxODgwODgzIiwiaWF0IjoxNzI0MTc2MDIxLCJsaW5rIjoiaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3NyYS1wdWItenEtMTAwL1NSUjI5NjUyMzU0L1NSUjI5NjUyMzU0LmxpdGUuMSIsInJlZ2lvbiI6InVzLWVhc3QxLWMiLCJzZXJ2aWNlIjoiZ3MiLCJzaWduaW5nQWNjb3VudCI6InNyYV9ncyIsInRpbWVvdXQiOjE0NDAwfQ.pWOxSX2EARtDZt1TGoILepYMYzFpsekc_XK66o7gfDvwVSQhsRClH55-_aQHa9pBfkU406gA_Kh_Z4Gtl1uBAyE1J9JF3noHt7nRYx_Jway76mpet6iAfdliS3TdzD3d9AdgQBYmJx9o73cmWh7P5-KDmNj8P3GCAKKQmW6JreZELaSXF-NTZVkolmAZqeOp-ltm-_UpGi1Ueev6e7MvxpJssAq6EQ9iaoMGTSROajDw_EohMg_t7p8EQb1zpsoiATEWkmBK6AAFVr_tdeOV_iC5D3z6gi7Noi57YSERmNAPIWNkZcUqh8RUw71cM6t35CckOk_dzBAomP1FV6ujPQ&ncbi_phid=322C8FC0FF4F9E9500002DB27D26DFEB.1.1`

**Comment by klymenko** [comment]
`gives a path to the NCBI database, not google cloud`
This path goes to google cloud (https://storage.googleapis.com/...")
But you will not pay egress charges.

`I need to be able to concurrently download many files at once`
You can concurrently launch multiple `prefetch`es, jusr make sure that by accident you don't use the same accession.

**Comment by cachris1** [comment]
Thank you for your help, I will try doing it that way.  Just to clarify, the path `https://trace.ncbi.nlm.nih.gov/Traces/sdlr/` ultimately points to the google cloud bucket and not an external NCBI server?

**Comment by klymenko** [comment]
In your case, when you run on GCP and agree to report cloud instance identity - yes.

**Comment by durbrow** [comment]
FYI, the SDLR URL is to a redirector service that handles dbGaP permissions. That is, it doesn't have the data, but can redirect to it if you have been granted permission to it.

**Comment by cachris1** [comment]
Thank you so much!
