### ISSUE TITLE
fastq-dump 'item not found while constructing within virtual database module'

### ISSUE THREAD

**Issue by stolpeo** [ncbi/sra-tools#96]
Hello,

I get an error when I try to convert an .sra to .fastq file using `fastq-dump`.

```terminal
$ fastq-dump --split-files --gzip --outdir fastq data/sra/SRR3184198.sra
2017-09-18T14:36:04 fastq-dump.2.8.2 err: item not found while constructing within virtual database module - the path 'data/sra/SRR3184198.sra' cannot be opened as database or table
```

I tried it for different files in my folder in case one is corrupted, but it is the same for all tested ones. I saw solutions while googling for this error but none of them applied to me. The file exists and is a data file:

```terminal
$ file data/sra/SRR3184198.sra
data/sra/SRR3184198.sra: data
```

I also tried the following, but no change:

```terminal
$ vdb-config --restore-defaults
Fixed default configuration
```

What could be the reason, how can I fix this?

Thanks,
  Oliver

**Comment by kwrodarmer** [comment]
You are working with restricted access files. Please write to us at sra-tools@ncbi.nlm.nih.gov for more assistance.

**Comment by stolpeo** [comment]
The problem was that my project folder was not inside the ncbi root folder. This allowed for the download but not for the unpacking. Moving the folder to the ncbi root folder solved the problem.
