### ISSUE TITLE
fasterq-dump ERROR: - asterq-dump.3.0.0 err: extract_acc2( 'SRR18323606.lite.1' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect)

### ISSUE THREAD

**Issue by ManuelSokolov** [ncbi/sra-tools#961]
Dear SRA creators, 

I trying to dowload data from https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=769413 , here is the process I am doing:

`esearch -db bioproject -query PRJNA769413 | elink -target sra | efetch -format runinfo > results.csv`

Then keep only the samples where LibraryStrategy == "RNA-seq" and finally using download_path to wget each link. This provides a ".lite.1" file per sample. 

Then I want to convert this .lite.1 to fastq. I started by using ` fastq-dump --split-files --gzip  SRR18323xxx.lite.1`, here got no errors but it was very slow, then tried with ` fasterq-dump --split-files  SRR18323xxx.lite.1` (removed the gzip because fasterq-dump does not support gzip conversion).

When running that line, the code is running but have this log:

`fasterq-dump.3.0.0 err: extract_acc2( 'SRR18323606.lite.1' ).VFSManagerExtractAccessionOrOID() -> RC(rcVFS,rcPath,rcConstructing,rcParam,rcIncorrect)`

What can be this issue?

Best Regards,

**Comment by durbrow** [comment]
The toolkit's own `prefetch` tool is the recommended way to get the data.

Try something like:
```
for i in `esearch -db bioproject -query PRJNA769413 | elink -target sra | efetch -format runinfo | tail -n +2 | cut -d, -f1`
do 
    prefetch $i
    fasterq-dump --split-files $i
    rm -rf $i
    gzip *.fastq 
done
```
