### ISSUE TITLE
Unsuccessful installation

### ISSUE THREAD

**Issue by rtasakis** [ncbi/sra-tools#97]
Hi guys, 
I'm new to bioinformatics, trying to install sra-toolkit on my mac. I think I'm not doing something correct at point 3. I'm really typing in the terminal export 
`PATH=$PATH:$PWD/sratoolkit.2.4.0-1.mac64/bin`
I doubt that it works for me, because when I search the fastq-dump with 
`which fastq-dump` 
I get no message in return and subsequently the download example fails. 

Can you help me? 

Thanks in advance!

**Comment by kwrodarmer** [comment]
I think you must have followed our Wiki page about installing binaries that was written a couple of years ago. The version numbers need to be updated if things are going to work.

So if you download the latest code, it should be
`export PATH=$PATH:$PWD/sratoolkit.2.8.2-1.mac64/bin`
