### ISSUE TITLE
2.8.2.1: CentOS6: fastq-dump: -v and --verbose not interchangeable

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [ncbi/sra-tools#98]
Hi there, 

```
SRA version: 2.8.2.1
OS version: centos_linux64
```

just came to use `fastq-dump` for the first time (I'm an implementer
of tools, not a practitioner in the science domain itself) and, because 
I'm the inquisitive type, thought to put a `verbose` into the example 
given at 

https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump

and so typed

`$ fastq-dump --verbose -I --split-files SRR519926`

at which point I was told,

`2017-10-03T00:05:46 fastq-dump.2.8.2 err: param incorrect while reading argument list within application support module - --verbose`

however, because I'm the persistent type, I decided to try

`$ fastq-dump -v -I --split-files SRR519926`

instead, and that appears to have "done the right thing",
in that I see a few messages about CA certs and, eventually,
get some data written.

```
...
Read 400596 spots for SRR519926
Written 400596 spots for SRR519926
Read 400596 spots total
Written 400596 spots total
```

Is it likely that your option handling code isn't doing the right thing
with respect to handlng GNU-style long options, or have I missed 
something obvious?

Kevin M. Buckley

eScience Consultant
School of Engineering and Computer Science
Victoria University of Wellington
New Zealand

**Comment by kwrodarmer** [comment]
The option handling code in `fastq-dump` is not correct with respect to our own standards, you are right. However, it is a very old tool, and changing/correcting behaviors can break scripts - so we haven't touched it.

We are releasing a new tool for dumping fastq, and it will have more correct processing. Incidentally, that is not by necessity GNU-style, but it tends to be quite similar.

**Comment by vuw-ecs-kevin** [comment]
> The option handling code in fastq-dump is not correct with respect to our own standards,
> you are right. However, it is a very old tool, and changing/correcting behaviors can break
> scripts - so we haven't touched it.

Hear you on the old", indeed I had to update the copy here from something so 
old that it didn't have the "swap to HTTPS" stuff in it, however, I can't see that 
anyone will have a script that is relying on a behaviour that results in an error 
when asking for verbose output, though, having said that

> We are releasing a new tool for dumping fastq

I'll happily withdraw my issue with the behaviour in the "old" code: feel free to close.

**Comment by kwrodarmer** [comment]
You may be right that changes (such as verbose, etc.) might not affect any scripts, but to play it safe we've left it alone. Thanks for your input.
