### ISSUE TITLE
Will the fastq-dump download the sra repetitively?

### ISSUE THREAD

**Issue by mckf111** [ncbi/sra-tools#99]
I wonder if the fastq-dump would download the sra cache file every time even if I have that in my */sra* directory. Like overwrighting the existed file~~

If not, I don't understand why I run the same command it still takes a relatively long time. If yes, I think that would be a huge waste of time.

Would anyone know this? Thanks in advance!

**Comment by kwrodarmer** [comment]
If your cache is properly set up, `fastq-dump` will not re-download anything it has already retrieved.

The performance of `fastq-dump` is related more to the content of the runs being converted. Some of what we have in the SRA is quite hostile to fastq formatting and can take a long time.

That said, we will be releasing an alternative tool for dumping fastq with our next release. This tool makes use of temporary memory and multiple threads to perform conversions of whole runs.
