### ISSUE TITLE
SRA to FASTQ error ：can't obtain technical reads files

### ISSUE THREAD

**Issue by Mollyx06** [ncbi/sra-tools#990]
Hello, I'm having some problems with the latest sratools (==3.1.1), 
the raw data was downloaded directly from NCBI via prefetch, and the data is labeled as double-ended sequencing data from illumina, but when I try to convert the format I always can't get the appropriate file, and when using fastq-dump
![image](https://github.com/user-attachments/assets/61a8c7b0-503a-44ed-ae2f-f75678e89b82)
Only a fastq.gz ending in “1” is generated.
Then I tried another tool, fasterq-dump, and followed the advice to add the --include-technical parameter, but it reported the error
![image](https://github.com/user-attachments/assets/433eb950-d9f2-45a5-869a-2d5915c8aadd)
Having used the --split-3 parameter before this I can only get one file, any other suitable suggestions?
Here's a screenshot of the raw data
![image](https://github.com/user-attachments/assets/4b0a6d4b-9492-4597-9b39-f7ea7a5e06ea)

**Comment by wraetz** [comment]
When you run fasterq-dump to include technical reads - it reacted with 'disk-limit exeeded'. The tool does a check if the expected size of the output will fit onto your HDD/SSD. It asked you to re-run the same command with the '-x' option ( aka print details ) - that will tell you why it rejected to do it. You can then lift the disk-limit with the '--disk-limit' option ( if you think you have enough space ) or turn the size-check off with '--size-check off'.

**Comment by wraetz** [comment]
The run-browser listed the number of bases as 26.3 GB. The expected output ( FASTQ ) is approximately 7 times that number.

**Comment by durbrow** [comment]
As you can see from your screenshot, the run has only one read. This is why you are getting only one file from `fastq-dump`. Please contact the SRA curators at sra@ncbi.nlm.nih.gov, and let them know that there's a problem with the data file.

**Comment by Mollyx06** [comment]
I understand, I'll ask about the data, and thanks for the answer about disk memory.
