### ISSUE TITLE
Interest in recovering linked-read information in fastq data

### ISSUE THREAD

**Issue by dhooper1** [ncbi/sra-tools#992]
I was wondering if there might be a way to recover linked-read information present in the read headers of fastq files submitted to SRA. I recently submitted linked-read sequence data (BioProject PRJNA1147746) generated using the ‘haplotagging’ method of linked-read sequencing. In this method, molecular barcode information is stored as BX, RX, and QX values for each read. Unfortunately, it seems that even with the “--origfmt” option of fastq-dump, the associated linked-read information is not recovered. Could you advise on a way to recover this information, should one exist, or comment on the potential of including this ability in a subsequent update? Many thanks for your help and advice!

An example of a submitted fastq file is shared below:
<img width="1074" alt="Screenshot 2024-11-20 at 10 56 14 AM" src="https://github.com/user-attachments/assets/86e86823-7be4-417a-8454-2f7fd377420d">

**Comment by durbrow** [comment]
Please send your request to the data curators at sra@ncbi.nlm.nih.gov. They can explain and/or initiate the process of getting the submitted files. This is not something that the developers of the toolkit can help with.
