### ISSUE TITLE
Minor Update Issue - Revision to path references of version in (02. Installing SRAtoolkit)

### ISSUE THREAD

**Issue by rebeclem** [ncbi/sra-tools#994]
Current version of sratookit is 3.1.1 when downloaded via curl provided in the install guide - https://github.com/ncbi/sra-tools/wiki/02.-Installing-SRA-Toolkit

references such as export PATH=$PATH:$PWD/sratoolkit.3.0.0-mac64/bin should be export PATH=$PATH:$PWD/sratoolkit.3.1.1-mac-x86_64/bin

**Comment by klymenko** [comment]
It is better to use
`export PATH=$PWD/sratoolkit.3.1.1-mac-x86_64/bin:$PATH`

**Comment by durbrow** [comment]
Immediately above the command from the wiki that you referenced is:

> Note the name of the directory that tar created. The name of this directory changes with each release and varies by platform, i.e. it follows the pattern sratoolkit.<release>-<platform> e.g. sratoolkit.3.0.0-mac64 for the 3.0.0 release for Mac OS X.

The name of this directory varies by platform and changes with each release. The command from the wiki is an example.
