### ISSUE TITLE
fastq-dump - unable to download fastq

### ISSUE THREAD

**Issue by SM1420** [ncbi/sra-tools#999]
Hi, 

I am trying to download fastq files given the SRR access number using SRA-toolkit. 

I first get the SRR file by this command which works, 

wget --no-check-certificate --no-proxy https://sra-pub-run-odp.s3.amazonaws.com/sra/$SRR_ACCESSION/$SRR_ACCESSION
and then try to download using this command, but it provides this error (Screenshot provided).

fastq-dump --origfmt --gzip $SRR_ACCESSION
Could you please help me with this issue? Thank you! 

<img width="996" alt="Screenshot 2024-12-20 at 11 21 44 AM" src="https://github.com/user-attachments/assets/9b18243d-7eba-472f-840a-c60ca7f413ac" />

**Comment by klymenko** [comment]
[Download](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit) the latest toolkit.
